### ISSUE TITLE
Open worlds via ftp

### ISSUE THREAD

**Issue by Monkey0x9** [Khroki/MCEdit-Unified#181]
There should be a function so you can open and edit worlds via ftp/sftp.
This is pretty handy for people that have a (big) world on a server and just need to do a little change, if it's added you don't need to download the world and upload it again.

**Comment by Podshot** [comment]
I have been running into some issues with this, so I have decided to passively work on this, but it will no longer be my top most priority. If anyone else wants to try to take a crack at it, all of my code related to this is on the FTP-Addition branch.

**Comment by Podshot** [comment]
This has been added and will present in the next release.
