### ISSUE TITLE
Bo2/Bo3 Support integration for MCEdit

### ISSUE THREAD

**Issue by someonepic** [Khroki/MCEdit-Unified#201]
The old issue can be found here: https://github.com/mcedit/mcedit/issues/170#issuecomment-10314528

Essentially this is a Feature request for the ability to create, edit, save and adjust Bo2 and Bo3 formats. Bo2/Bo3's are biome objects that are used by a variety of plugins and programs to populate worlds with everything from trees to custom buildings. The formats originally made for the old phoenix mod have been ported to implement new functionality and more customisation.

This is a Data Structure layout for the bo2: http://pastebin.com/FVr9f52y
Here is one for the newer bo3 format: https://github.com/MCTCP/TerrainControl/wiki/BO3-objects

the ability to import and export from a world, convert from schematic or to schematic, add or customise the fields, change options would be very nice indeed. There is currently no unified way to do this that i know of, you need to manually create a schematic, and then covert using ruby libs to a bo2, and then manually convert up to bo3 format changing the options as you go.

**Comment by Podshot** [comment]
Bo2 support has been completed, however, since Bo3 does not seem to be in completely valid YAML format, I will hold off support for both until I can get a parser for the Bo3 format.

**Comment by someonepic** [comment]
thanks so much :)

**Comment by Podshot** [comment]
I am almost done with support for BO3's, but I ran into a problem, the BO3 you linked is too big for my parser to handle and I need a smaller one to test the parser with first. Do you have a smaller one available?

**Comment by someonepic** [comment]
Here is one, if its still to big ill create one with only one or two blocks.
http://pastebin.com/DpFDbiRS
https://www.dropbox.com/s/b1qajtit75wixio/Nether-Tower-Bridge.bo3?dl=0

**Comment by Podshot** [comment]
Just merged support for BO2 formats, BO3's were having some bugs with coordinates, so I merged it without support for BO3, since this request was getting old.
