### ISSUE TITLE
v1.2.1 Crash on start up Win7x64

### ISSUE THREAD

**Issue by MagboneD** [Khroki/MCEdit-Unified#202]
Console window just pops up and immediately disappears. Running mcedit.exe from command window results in the following error:

Traceback (most recent call last):
  File "<string>", line 35, in <module>
AttributeError: 'module' object has no attribute '_MEIPASS'

**Comment by Khroki** [comment]
If anyone who had this issue previously could test this build for me it would be appreciated, we are trying to upgrade our build software but don't want to break this again. https://www.dropbox.com/s/diblg860juepoil/mcedit%201.5.x.x%20test.exe?dl=0
