### ISSUE TITLE
Mcedit.exe Won't Start

### ISSUE THREAD

**Issue by Sandro-Halpo** [Khroki/MCEdit-Unified#210]
Hello. I'm using version 1.2.2.0 on a Windows 64bit system. When I try and open mcedit.exe either by double clicking or using the command prompt, the command prompt flashes for a brief instant then crashes. Nothing else happens, and running as an administrator does not help. I examined previous reported issues with the program not opening, which were apparently solved, but I am confident my problem is not the same one they had. Moving the location of the mcedit folder does not seem to make any difference, and before anyone asks yes I did unzip the downloaded .zip files prior to running mcedit.exe.

When attempting to run the program, from any location/admin or not/etc, it gives me the following lines:

![mcedit error message](https://cloud.githubusercontent.com/assets/10088785/5318051/bc854cb8-7c6a-11e4-9cc2-2f6ba7690ae8.JPG)

Advice? I mean, I don't need any help using the program, and I really appreciate you guys keeping this thing alive and compatible with current Minecraft versions, but it would be nice if I could get it to turn on.

**Comment by GeDrepVedrp** [comment]
Is it still the same procedure as McEdit2-2.0.0a1?

**Comment by Minecraftguy1972** [comment]
Having the same problem. I get an error dialog upon double-clicking to open it.
![mcedit_error](https://cloud.githubusercontent.com/assets/11745511/6931693/183de302-d7de-11e4-8fd0-47e06baa52a3.jpg)

**Comment by TrazLander** [comment]
@GeDrepVedrp @Minecraftguy1972 Sorry but the mcedit2 issue tracker is that way -> https://github.com/mcedit/mcedit2/issues

**Comment by JohnHector03** [comment]
Hi. Does anybody know how to solve this problem? My mcedit just won't start.
![error](https://cloud.githubusercontent.com/assets/20939325/17540198/e10e6c30-5ee6-11e6-9533-edf966b6537a.PNG)
Does anybody knows how to fix this?
Thank you.

**Comment by OGChriss** [comment]
arrrrgh. i got this error
