### ISSUE TITLE
Nudge Green Brightness

### ISSUE THREAD

**Issue by Azounstone** [Khroki/MCEdit-Unified#229]
I might be wrong but this seems to be less transparent than previous version.
I have uninstalled this latest version and gone back to using older one from 23 days ago.

**Comment by naor2013** [comment]
Seems like I change the nudge green to be brighter without noticing it..
I changed it to be exactly like the old green so it should be fine for next version

**Comment by TrazLander** [comment]
Fixed with https://github.com/Khroki/MCEdit-Unified/commit/ec2bc210a15b87ab7f27c969b2a9f68ab74b37d0

**Comment by TrazLander** [comment]
So now, the only thing we did was add the selection tool green nudge button glow to the clone tool and import tool green nudge buttons: http://imgur.com/a/KRq7B

You may have to read that sentence a few times...

**Comment by naor2013** [comment]
I actually added it and it took me 3 times to read this sentence to understand it! :P
