### ISSUE TITLE
Windows SmartScreen prevented unknown program from running.

### ISSUE THREAD

**Issue by ShawnsSpace** [Khroki/MCEdit-Unified#238]
Just installed 1.2.3.1 with out issue, recieved update notification in app about 1.2.4 update.  Downloaded and attempted to install update but windows is blocking install from all profiles.  
Error:  Windows SmartScreen prevented unknown app from starting.  Running this app might put your  PC at risk.

Attempted from:
Normal Profile.
Admin Profile
Admin Profile run as Admin.
Windows 8.1 "Fully updated."
Avast security professional detects no issues.

**Comment by Khroki** [comment]
Closing, since there's not much we can do :P.
