### ISSUE TITLE
Can't export mod blocks to schematic

### ISSUE THREAD

**Issue by Frontrider** [Khroki/MCEdit-Unified#241]
We have a 1.7 modded server, and i messed up my base. I wanted to import it from an older save, but i could not export it into a schematic.

Possibly has to do things with chicken chunks.

I tried deleting some blocks, with no succes, the first is the exeption when deleting, the second is when exporting.

http://pastebin.com/D9CuzA9C

**Comment by Rubisk** [comment]
Yeah just select it and press the DELETE key.

**Comment by Frontrider** [comment]
Thats exactly what i did. But there are more.

**Comment by Frontrider** [comment]
I can not remove that block.

Still error at 0x000000000AD4AK48 Key Error('Key x not found',)

**Comment by Rubisk** [comment]
You should delete the NBT entry of the block, and then load in mcedit without loading in minecraft.

**Comment by OniOniOn-** [comment]
Is there no block data type outside of NBT limit?

**Comment by Rubisk** [comment]
Yes, but we're talking about a missing X coordinate. NBT can probably handle up to 16^4 I think, but we're not talking about a missing block. The block is there, yet the tile entity that is stored with the block is corrupted.

**Comment by Frontrider** [comment]
I did not loaded in minecraft. 
I see tile boxes in mcedit, but i can not click on them.

**Comment by Rubisk** [comment]
Of course you can't click on them. You should look up those tile boxes in the chunk.tileEntities of the chunk they're in with an external NBT editor.

**Comment by Khroki** [comment]
This is outside of the current MCEdit scope, so closing it for now.
