### ISSUE TITLE
Translation Update (Request to translators)

### ISSUE THREAD

**Issue by LaChal** [Khroki/MCEdit-Unified#242]
Hello,

it appears that the translations haven't been updated before the last release.
It will be good to provide them in a short lap of time.

So, can you check the file(s) you're interested in, and make the changes?

The strings to translate are allready in the files, and they are 15.

In advance, thank you.
Regards,

-- D.C.-G. (LaChal)

P.S.: please, report here when the changes are done. A package for end users will be done then.

**Comment by MobileCrafter** [comment]
I will also update the german language in the next weeks.
I still have todo 50% of the strings.
