### ISSUE TITLE
Cannot open MCEdit for OSX

### ISSUE THREAD

**Issue by jduartemiller** [Khroki/MCEdit-Unified#243]
I recently downloaded MCEdit 1.2.4 for Mac OSX (i am running OS 10.9.5, and it fully meets all system requirements), and it failed to open, bringing up a prompting window saying "mcedit error" and prompting me to click either "open console" or Terminate the program. I then downloaded previous versions, and got the same results for 1.2.3.1, 1.2.3.0, 1.2.2.0, 1.2.1.0, and 1.2.0.0. By that point my frustration reached the point that i contacted you. The last edition i used prior to this was 0.8.1, and understandably wanted to update it .

**Comment by Khroki** [comment]
Any news as to if this worked? We'd still like to see those packs.

**Comment by naor2013** [comment]
Maybe fixed for next release (Not sure) but the program won't crash if one of your resource packs is broken so I'll count that as fixed..
Please open a new issue if it would warn you because of broken pack and tell us the error (It won't crash)
