### ISSUE TITLE
MCEdit Linux trouble

### ISSUE THREAD

**Issue by DEADLYCOW2** [Khroki/MCEdit-Unified#248]
I am a Minecrafter running on the software Linux Mint. I have attempted to install MCEdit and all have gone perfectly, until it said that mcedit.sh was missing. I have no idea what this means, maybe it isn't added by the makers or something, but if not, i need help. Thank you

**Comment by TrazLander** [comment]
Calling @LaChal

**Comment by DEADLYCOW2** [comment]
I am confused as of what you are implying.....

**Comment by TrazLander** [comment]
he made the linux build

**Comment by DEADLYCOW2** [comment]
oh, ok

**Comment by LaChal** [comment]
When it was said to you that mcedit.sh was missing?
During installation?

**Comment by DEADLYCOW2** [comment]
Um.....I kinda gave up on it a few hours ago, then I redownloaded a few seconds ago to find it working.....sorta. The mcedit.sh was fixed, but now a new problem. It now says this exactly when I try to open the launcher:

Starting MCEdit...
Running in fixed mode. Support files are in your Documents folder.
Traceback (most recent call last):
  File "../bin3/mcedit/mcedit.py", line 13, in <module>
ImportError: No module named OpenGL
Press any key to close.

**Comment by LaChal** [comment]
The issue you first had is what I suspected: a file corruption on download. We can not do anything for this...

To help fixing your second problem I need some information.
Did you install the dependencies?
If, yes, did you installed them system wide or only for the user?

**Comment by DEADLYCOW2** [comment]
um......i'm sorry, i must seem like a total noob, but i didnt. I think I tried the commands in the read.me, but the commands didn't work, so I thought I could get by without it. Can you send me the commands? btw I'm running on a linux mint debian package.

**Comment by LaChal** [comment]
You may need to install some dependencies yourself, using your package manager. If they aren't found on your system, the installer will warn you.
See LINUX_INSTALL.txt in the 'mcedit' folder the installer creates.

Once the system binary dependencies are satisfied, run again the installer or the 'install.sh' script.
Be sure to answer 'yes' to the dependencies installation question.

**Comment by DEADLYCOW2** [comment]
you know what guys, im sorry for wasting your time, but im giving up. Again i apologize for wasting ur time, but it's not working

**Comment by LaChal** [comment]
You don't need to apologize ;)
And we're interested in the feedback that users give us!

I won't be available for some hours. But if you mind to post screenshots or error texts (or anything you think it will help), I'll look at when I return.

**Comment by DEADLYCOW2** [comment]
sure :) although I don't think i'll be much help since the only error is the lack of dependancies. the error messages were the ones i have posted above, thank you for helping.
