### ISSUE TITLE
Install Error - Shortcut/Link Creation

### ISSUE THREAD

**Issue by gpmidi** [Khroki/MCEdit-Unified#254]
When I attempt to run an install I get the error below: 

Start step 4 (create launchers) [y/n]? y
Traceback (most recent call last):
  File "../bin3/mcedit/install.py", line 542, in <module>
  File "../bin3/mcedit/install.py", line 528, in OOO
IOError: [Errno 2] No such file or directory: 'MCEdit-Unified.desktop'

**Comment by gpmidi** [comment]
The error was when trying to install mcedit on a Ubuntu 14.04 based system. It was run as root from /home/gpmidi/Downloads. More output can be found here: https://www.dropbox.com/s/i9w5jqgdo5hpdrs/error2.txt?dl=0

**Comment by LaChal** [comment]
To avoid having this issue, answer 'no' to 'Start step 2 (dependencies installation) [y/n]?'
MCEdit will be moved in the right folder, and the launchers will be created.
This issue will be fixed in the next release.

Thus, without the dependencies, MCEdit won't run.

**Comment by LaChal** [comment]
Fixed in release 1.2.5.0.
