### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by Monster301** [Khroki/MCEdit-Unified#256]
Mcedit was running untill today. It opens a cmd window and close what i can do?

**Comment by Podshot** [comment]
Can you post a screenshot of the command prompt?

**Comment by Monster301** [comment]
it automatly close

**Comment by Monster301** [comment]
i can not see it before it close

**Comment by Monster301** [comment]
i taka a screenshot
![mcedit problem](https://cloud.githubusercontent.com/assets/10322611/5606420/8aab3984-9437-11e4-928d-02ea01846d77.png)

**Comment by Monster301** [comment]
now it puts me another text
![mcedit problem 2](https://cloud.githubusercontent.com/assets/10322611/5606443/b4d3f902-9438-11e4-9b44-cef76247ffd6.png)

**Comment by naor2013** [comment]
It seems like one of your resource packs is broken..
For now, you can just remove your resource packs to use MCEdit but we'll try to fix it for next release..
If you'll find the resource pack that cause this crash, please send it to us

**Comment by Monster301** [comment]
ok thanks

**Comment by Monster301** [comment]
i find the resource pack that cause the problem it is the village sound pack from a map which name is The Abandoned Village V1.0

**Comment by naor2013** [comment]
I think I solved this specific bug (Not sure) but for next release, the program would ignore broken packs and won't crash if it's broken
