### ISSUE TITLE
Cannot open world from minecraft 1.8.1 (or any world) on OSX 10.9.5

### ISSUE THREAD

**Issue by eyau77** [Khroki/MCEdit-Unified#257]
Cannot "OPEN" world.  Quick Load does load though.  Is there a workaround for now, or a way to add to the quick load list?

Console log as follows:

1/4/15 1:40:27.589 PM mcedit[3557]: [   ERROR][                   root.py:724]:MCEdit version Unified v1.2.4.0 for Minecraft 1.8
1/4/15 1:40:27.594 PM mcedit[3557]: Traceback (most recent call last):
1/4/15 1:40:27.594 PM mcedit[3557]:   File "/Users/edwardyau/Downloads/mcedit.app/Contents/Resources/__boot__.py", line 399, in <module>
1/4/15 1:40:27.595 PM mcedit[3557]:     _run()
1/4/15 1:40:27.595 PM mcedit[3557]:   File "/Users/edwardyau/Downloads/mcedit.app/Contents/Resources/__boot__.py", line 336, in _run
1/4/15 1:40:27.595 PM mcedit[3557]:     exec(compile(source, path, 'exec'), globals(), globals())
1/4/15 1:40:27.595 PM mcedit[3557]:   File "/Users/edwardyau/Downloads/mcedit.app/Contents/Resources/mcedit.py", line 762, in <module>
1/4/15 1:40:27.595 PM mcedit[3557]:     sys.exit(main(sys.argv))
1/4/15 1:40:27.595 PM mcedit[3557]:   File "/Users/edwardyau/Downloads/mcedit.app/Contents/Resources/mcedit.py", line 722, in main
1/4/15 1:40:27.595 PM mcedit[3557]:     MCEdit.main()
1/4/15 1:40:27.596 PM mcedit[3557]:   File "/Users/edwardyau/Downloads/mcedit.app/Contents/Resources/mcedit.py", line 557, in main
1/4/15 1:40:27.596 PM mcedit[3557]:     rootwidget.run()
1/4/15 1:40:27.596 PM mcedit[3557]:   File "albow/root.pyc", line 134, in run
1/4/15 1:40:27.596 PM mcedit[3557]:   File "albow/root.pyc", line 200, in run_modal
1/4/15 1:40:27.596 PM mcedit[3557]:   File "albow/root.pyc", line 615, in gl_clear
1/4/15 1:40:27.596 PM mcedit[3557]:   File "/Users/edwardyau/Downloads/mcedit.app/Contents/Resources/lib/python2.7/OpenGL/error.py", line 232, in glCheckError
1/4/15 1:40:27.596 PM mcedit[3557]:     baseOperation = baseOperation,
1/4/15 1:40:27.596 PM mcedit[3557]: OpenGL.error.GLError: GLError(
1/4/15 1:40:27.597 PM mcedit[3557]: 	err = 1286,
1/4/15 1:40:27.597 PM mcedit[3557]: 	description = 'invalid framebuffer operation',
1/4/15 1:40:27.597 PM mcedit[3557]: 	baseOperation = glClear,
1/4/15 1:40:27.597 PM mcedit[3557]: 	cArguments = (16640,)
1/4/15 1:40:27.597 PM mcedit[3557]: )
1/4/15 1:40:27.604 PM mcedit[3557]: mcedit Error
1/4/15 1:40:27.604 PM mcedit[3557]: 2015-01-04 13:40:27.603 mcedit[3557:707] mcedit Error

![screen shot 2015-01-04 at 1 41 50 pm](https://cloud.githubusercontent.com/assets/802394/5607038/79cda59a-9417-11e4-9678-635dfd37e8c5.png)

**Comment by naor2013** [comment]
You can just copy your worlds to the "saves" folder in Minecraft
What happens when you click "Open..."?
Does it show it or just crash immediately?

**Comment by eyau77** [comment]
Tried adding a world to the saves folder but it didnt appear on quickload.  Though i've been trying to open a minecraft pe 0.10.4 world and just learned it isnt supported!  

Nevertheless, i've been trying to open the demo world from minecraft 1.8.1 and experience the same error.  I click on open, browse to the level.dat file, then the error in the screenshot appears.  Pasted the logs in the original post as well.. hope this is enough info for you. Let me know if you need additional information.  Thanks!  God bless open source.

**Comment by naor2013** [comment]
We don't have support for MCPE 0.9+ yet but I hope we'll have it next release

A 1.8.1 minecraft map should work from the "saves" folder using quick load.

So the problem happens when you choose a file and not when clicking "Open..."?
Can you try clicking "Open..." and then "cancel" and tell me if it's crashing too?
And can you take a screenshot of your "Open..." menu where it shows the files?

Thanks for the help!

**Comment by eyau77** [comment]
Here are a series of screenshots that show what happens.  In the end i just have to terminate..

![screen shot 2015-01-04 at 4 36 14 pm](https://cloud.githubusercontent.com/assets/802394/5607612/f680c352-942f-11e4-962f-ad52752fc382.png)
![screen shot 2015-01-04 at 4 36 29 pm](https://cloud.githubusercontent.com/assets/802394/5607613/fc2883e4-942f-11e4-9a1d-7f03e92a7d89.png)
![screen shot 2015-01-04 at 4 36 36 pm](https://cloud.githubusercontent.com/assets/802394/5607614/0144d6b6-9430-11e4-98ac-121b07fa8d0b.png)

**Comment by naor2013** [comment]
It seems like it's got problems with the Views of the selection window
In the top left side of the selection window, change your view to the second one from the left..
It will crash in the first time but then it would work correctly
![finder-window-view-buttons](https://cloud.githubusercontent.com/assets/5496913/5609793/1b4981c0-94b1-11e4-9015-a9699497e73d.jpg)

That's an old picture I found but those are the ones I mean.. Use only the second one from the left

**Comment by Gallion** [comment]
I have the same issue. Putting the world in the saves folder solved the issue.

**Comment by Khroki** [comment]
See #259 for more info, they seem to be the same issue.

**Comment by yrsegal** [comment]
Another dupe issue: #278

**Comment by naor2013** [comment]
There are a lot of copies of this issue so I'll keep just one open
