### ISSUE TITLE
File chooser Issues

### ISSUE THREAD

**Issue by IntensePlatypus** [Khroki/MCEdit-Unified#259]
Schematics will save but when I try to open them up with McEdit the program crashes. I click import then select a schematic and it says mcedit Error
For: MCEdit v1.2.4.0
Minecraft 1.8.1 
Mac Version 10.9.5

**Comment by Podshot** [comment]
Can you post a screenshot of the console window and attach the schematic you are trying to import?

**Comment by IntensePlatypus** [comment]
![screen shot 2015-01-05 at 8 00 20 pm](https://cloud.githubusercontent.com/assets/10408300/5622717/ba7baa7a-9515-11e4-8a11-05fa7b8d3ada.png)
and how should i attach the schematic

**Comment by IntensePlatypus** [comment]
Also I found out if I don't select a schematic and just cancel out of the schematic folder it crashes as well.

**Comment by Podshot** [comment]
You can post the schematic to dropbox or mediafire and then give us the link to download it.

**Comment by naor2013** [comment]
It's a problem with the Mac file chooser.. In the top left side of it you have 4 possible views, only the second one from the left works so use only this one..
I'll try to figure out a way to fix it

**Comment by Khroki** [comment]
See http://knowledge.autodesk.com/support/autocad-for-mac/troubleshooting/caas/sfdcarticles/sfdcarticles/Select-File-dialog-in-Yosemite-crashes-AutoCAD-for-Mac.html for the cause of this.

**Comment by yrsegal** [comment]
Similar problems for 10.10.
#278

**Comment by naor2013** [comment]
Fixed by removing the Mac file chooser, so now Mac uses the old Albow one..
It's not the ideal solution but that's our only fix for now

**Comment by yrsegal** [comment]
Hey, hey, hey. TexelElf somehow does filechoosers without mcedit crashing, in the Multiplatform NBT filter. Use his method, perhaps?

**Comment by Khroki** [comment]
His method uses TK, but unfortunately that method doesn't work properly on both Mac and Windows when compiled.
