### ISSUE TITLE
Updated german localization

### ISSUE THREAD

**Issue by Neui** [Khroki/MCEdit-Unified#260]
Since git seems just not downloading the fork (for making an pull request), i decided to upload the updated german localization to pastebin and post an "issue".
Find it there: http://pastebin.com/raw.php?i=rCNYjiMU
Includes some fixes to the old one (like Strg instead of Ctrl) and i translate almost all of the new strings.

**Comment by naor2013** [comment]
Thanks! Updated for next release

**Comment by MobileCrafter** [comment]
Danke dir Neui! :)
