### ISSUE TITLE
Title not resetting on world closing

### ISSUE THREAD

**Issue by MobileCrafter** [Khroki/MCEdit-Unified#264]
When you close a world the title does not reset to:
MCEditUnified v1.2.5.0 for Minecraft 1.8
![1](https://cloud.githubusercontent.com/assets/5413827/5659897/16b0b1ea-971a-11e4-9137-c0dd93a5e98f.png)
![2](https://cloud.githubusercontent.com/assets/5413827/5659898/16b7507c-971a-11e4-817e-f2c68d472f43.png)
The levelname is still there.

**Comment by OniOniOn-** [comment]
I think I could easily fix this

**Comment by MobileCrafter** [comment]
:+1: :+1: :+1: :+1: :+1:
