### ISSUE TITLE
MCEdit saving elswhere? Can't see any changes in minecraft that I made in MCEdit.

### ISSUE THREAD

**Issue by Crare** [Khroki/MCEdit-Unified#268]
Thats pretty much it. I'm using minecraft launcher 1.6.5 and minecraft 1.8.1. MCEdit version is v1.2.5.0 64bit.
I see changes though in mcedit when I go back there, but not in minecraft, it's like it did another copy of the world elswhere.

**Comment by naor2013** [comment]
What did you change?

**Comment by Crare** [comment]
I used brush tool size 30 - 100 using fill with air in a world that's made of 1 layer of bedrock and 254 layers of stained clay. also used soil tool to make grass in some places and filled some parts of air with water with replace tool. Using PC. Does this help?

**Comment by naor2013** [comment]
When in the map in MCEdit, open the menu (Esc/Click the MCEdit button on the top left) and then click the "World Info" button.
From there, you can click on the "Open Folder" button and get to the map folder you're editing
Check if it's the same map folder you're opening in Minecraft

**Comment by Crare** [comment]
yes it goes to the /appdata/.minecraft/saves/WORLDNAME directory. There's 3 level.dat files. level.dat, level.dat_mcr and level.dat_old also MCEdit has made a folder "##MCEDIT.TEMP## which has empty folder named region.
![worldfolder](https://cloud.githubusercontent.com/assets/10487241/5695931/8a8e071c-99c1-11e4-88f6-376e76889d77.jpg)

**Comment by naor2013** [comment]
That's fine but check if this is the world you open in MInecraft or not..
You can change the name of the directory and if it's changing the name of the world you open too, that means it's the same world

**Comment by Crare** [comment]
oh they actually seems to be different destination, but very similar all the way to the user folder. Odd.. why is it doing so?

**Comment by Crare** [comment]
Also there's a green border around the mcedit window, something about firewall?

**Comment by naor2013** [comment]
I don't know why you didn't open the same world..
Can you take a screenshot of the green border? Not sure what it is..

**Comment by Crare** [comment]
![mcedit stuff](https://cloud.githubusercontent.com/assets/10487241/5696037/66a66196-99c6-11e4-993d-7f6c590dc43f.jpg)

**Comment by naor2013** [comment]
No idea what that means..
Did I solve your world saving problem? Can I close the issue now?
I don't think the green border is a problem

**Comment by Crare** [comment]
Oh wow.. my firewall thingie COMODO had it in sandbox mode, I added the program to the trusted files and now it works fine I think. All the destinations were I guess "virtualized" for the program. But now I need to start over, because it didn't save because of it. Unless it's in there "virtual folder" somewhere, because I could load it back then..

**Comment by Crare** [comment]
OK, yeah now it works just fine. It was firewall doing it putting it in sandbox mode. Oddly they don't inform about it, just put it inside a green border like I ever would know :D
