### ISSUE TITLE
After deleting chunks, surrounding chunk borders aren't being render updated.

### ISSUE THREAD

**Issue by TrazLander** [Khroki/MCEdit-Unified#271]
1. Have a large area full of just solid block (Quartz in my example)
![2015-01-12 03-25-05-am](https://cloud.githubusercontent.com/assets/4455904/5700359/fb96c694-9a0a-11e4-9d79-cbf7aea0dde9.png)
2. Delete the Chunk, it doesn't fix the borders of the chunks surrounding it.
![2015-01-12 03-28-32-am](https://cloud.githubusercontent.com/assets/4455904/5700363/183db9e2-9a0b-11e4-898c-357c6df430ff.png)
3. A quick world reload does show that the chunk was properly removed
![2015-01-12 03-29-43-am](https://cloud.githubusercontent.com/assets/4455904/5700376/535cbaaa-9a0b-11e4-9f20-ffb1ba9b338e.png)

Another example, just deleted a chunk in a survival world I created:
![2015-01-12 03-35-09-am](https://cloud.githubusercontent.com/assets/4455904/5700425/0f29e4c4-9a0c-11e4-9c28-324eda94d38f.png)

**Comment by naor2013** [comment]
Now, deleting chunk will cause a reload of the world (Just chunks reload, not actually reload of the map)
