### ISSUE TITLE
Support Filters In Subdirectories

### ISSUE THREAD

**Issue by infogulch** [Khroki/MCEdit-Unified#274]
MCEdit should load filters from subdirectories of the main Filters dir. This would allow custom filters to be maintained with their own separate version control.

This could be changed by using [`os.walk()`](https://docs.python.org/2/library/os.html#os.walk) instead of [`os.listdir`](https://docs.python.org/2/library/os.html#os.listdir) in [`filters.py`](https://github.com/Khroki/MCEdit-Unified/blob/master/editortools/filter.py#L587) (the semantics are slightly different so the change won't be trivial).

**Comment by LaChal** [comment]
Such a thing will need more than changing from `listdir` to `walk`, like specific rules to name the version folders and some tweaks in the translation system for the custom filters (and a lot of vaudou).
But we'll study this ;)

**Comment by infogulch** [comment]
Thanks for looking into it!

**Comment by TrazLander** [comment]
Closing this as "revist later" to keep the issue tracker clean, and added it to our main ToDo list.

**Comment by infogulch** [comment]
Hi, I'm just wondering if there is there any news on this. Also, is the ToDo list you mentioned public somewhere? I didn't see it glancing through the repo, issues, and wiki.

**Comment by naor2013** [comment]
Actually, Podshot added it for next release (1.3.1.0) and it will be used as filters-grouping.
The ToDo list is: https://docs.google.com/document/d/1YpX-ORVrUSf3L1sutn5nuSeOLbaQZJYYrza4fBsw8Y8/edit#

I don't think you can edit anything but if you have a suggestion, bug, or an idea - we are available in here (The Github issue tracker), reddit and the Minecraft Forums.

**Comment by infogulch** [comment]
That's good to hear! Of course there's no need for me to be able to edit your todo list, I just like having a view into how the project is progressing. Thanks! :smile:
