### ISSUE TITLE
MCedit 1.2.5.0 Win64 WONT START... 

### ISSUE THREAD

**Issue by Randomguy31** [Khroki/MCEdit-Unified#275]
When I run it, it opens cmd that obliges me to press enter, when I press enter, another cmd window opens and it closes.
when i open mcedit.exe :
![error1](https://cloud.githubusercontent.com/assets/10567910/5786188/a40f6806-9e13-11e4-9bcd-53ce641ff70e.png)

after pressing enter:
![error2](https://cloud.githubusercontent.com/assets/10567910/5786192/b5928194-9e13-11e4-9159-1ba83e26671f.png)

**Comment by Randomguy31** [comment]
please help

**Comment by Khroki** [comment]
Could you give us your system specs?

**Comment by LaChal** [comment]
I suspect a wrong OpengGL version, or a wrong path for MCEdit installation.
`AppData` folder is generally not a good place to install programs. Even administrators can't read/write files easely in there.
In addition of sending your system specs, can you copy mcedit folder elsewhere (eg. `C:\Users\James`) and reopen the program?

**Comment by martinhanzik** [comment]
According to http://newsgroups.derkeiler.com/Archive/Comp/comp.graphics.api.opengl/2007-03/msg00109.html it seems to have been introduced in OpenGL 1.4.

**Comment by Khroki** [comment]
Since there's been no response for 12 days, going to assume either solved or attempted to run below system requirements.
