### ISSUE TITLE
Crashes on Startup (Mac Mini 2010 OSX 10.9.2)

### ISSUE THREAD

**Issue by theravensrequiem** [Khroki/MCEdit-Unified#276]
Hey just getting a crash at the new splash screen with the latest build and the following crash report:

1/18/15 4:51:03.697 PM mcedit[2592]: Splash load...
1/18/15 4:51:09.432 PM mcedit[2592]: Error loading /Library/Audio/Plug-Ins/HAL/DVCPROHDAudio.plugin/Contents/MacOS/DVCPROHDAudio:  dlopen(/Library/Audio/Plug-Ins/HAL/DVCPROHDAudio.plugin/Contents/MacOS/DVCPROHDAudio, 262): no suitable image found.  Did find:
	/Library/Audio/Plug-Ins/HAL/DVCPROHDAudio.plugin/Contents/MacOS/DVCPROHDAudio: no matching architecture in universal wrapper
1/18/15 4:51:09.432 PM mcedit[2592]: 2015-01-18 16:51:09.431 mcedit[2592:707] Error loading /Library/Audio/Plug-Ins/HAL/DVCPROHDAudio.plugin/Contents/MacOS/DVCPROHDAudio:  dlopen(/Library/Audio/Plug-Ins/HAL/DVCPROHDAudio.plugin/Contents/MacOS/DVCPROHDAudio, 262): no suitable image found.  Did find:
1/18/15 4:51:09.432 PM mcedit[2592]: Cannot find function pointer NewPlugIn for factory C5A4CE5B-0BB8-11D8-9D75-0003939615B6 in CFBundle/CFPlugIn 0x1001618f0 </Library/Audio/Plug-Ins/HAL/DVCPROHDAudio.plugin> (bundle, not loaded)
1/18/15 4:51:09.432 PM mcedit[2592]: 	/Library/Audio/Plug-Ins/HAL/DVCPROHDAudio.plugin/Contents/MacOS/DVCPROHDAudio: no matching architecture in universal wrapper
1/18/15 4:51:09.432 PM mcedit[2592]: 2015-01-18 16:51:09.431 mcedit[2592:707] Cannot find function pointer NewPlugIn for factory C5A4CE5B-0BB8-11D8-9D75-0003939615B6 in CFBundle/CFPlugIn 0x1001618f0 </Library/Audio/Plug-Ins/HAL/DVCPROHDAudio.plugin> (bundle, not loaded)
1/18/15 4:51:09.457 PM mcedit[2592]: Running in fixed mode. Support files are in your App Support Folder (Available from the main menu of MCEdit)
1/18/15 4:51:10.659 PM mcedit[2592]: Error while trying to load one of the resource packs: [Errno 24] Too many open files: u"/Applications/MCEdit.app/Contents/textures/Frenden's Meringued Cartoon Pack 1.8/assets/minecraft/textures/blocks/random/planks_birch2.png"
1/18/15 4:51:10.683 PM mcedit[2592]: Error while trying to load one of the resource packs: [Errno 24] Too many open files: u'/Users/Deep_Thought/Library/Application Support/minecraft/resourcepacks/Girlcraft.zip'
1/18/15 4:51:10.685 PM mcedit[2592]: Error while trying to load one of the resource packs: [Errno 24] Too many open files: u'/Users/Deep_Thought/Library/Application Support/minecraft/resourcepacks/Hollywood Blocks.zip'
1/18/15 4:51:10.685 PM mcedit[2592]: Traceback (most recent call last):
1/18/15 4:51:10.685 PM mcedit[2592]:   File "/Applications/MCEdit.app/Contents/Resources/__boot__.py", line 399, in <module>
1/18/15 4:51:10.685 PM mcedit[2592]:   File "/Applications/MCEdit.app/Contents/Resources/__boot__.py", line 336, in _run
1/18/15 4:51:10.685 PM mcedit[2592]:   File "/Applications/MCEdit.app/Contents/Resources/mcedit.py", line 14, in <module>
1/18/15 4:51:10.685 PM mcedit[2592]:   File "resource_packs.pyc", line 816, in <module>
1/18/15 4:51:10.685 PM mcedit[2592]:   File "resource_packs.pyc", line 791, in __init__
1/18/15 4:51:10.686 PM mcedit[2592]:   File "resource_packs.pyc", line 763, in setup_resource_packs
1/18/15 4:51:10.686 PM mcedit[2592]:   File "resource_packs.pyc", line 611, in __init__
1/18/15 4:51:10.686 PM mcedit[2592]:   File "resource_packs.pyc", line 524, in __init__
1/18/15 4:51:10.686 PM mcedit[2592]:   File "PIL/Image.pyc", line 1950, in open
1/18/15 4:51:10.686 PM mcedit[2592]: IOError: [Errno 24] Too many open files: 'terrain.png'
1/18/15 4:51:10.728 PM mcedit[2592]: An uncaught exception was raised during execution of the main script.

This may mean that an unexpected error has occurred, or that you do not have all of the dependencies for this application.

See the Console for a detailed traceback.
1/18/15 4:51:10.728 PM mcedit[2592]: 2015-01-18 16:51:10.727 mcedit[2592:707] An uncaught exception was raised during execution of the main script.

This may mean that an unexpected error has occurred, or that you do not have all of the dependencies for this application.

See the Console for a detailed traceback.
1/18/15 4:51:16.933 PM com.apple.launchd.peruser.501[164]: (org.pythonmac.unspecified.mcedit.95248[2592]) Exited with code: 255

**Comment by Khroki** [comment]
This is likely an error with resource packs, removing them should allow mcedit to start, if that works could you send us your packs?

**Comment by Khroki** [comment]
No response, assumed solved. Packs would be nice if that fixed it.
