### ISSUE TITLE
Add Delete Key

### ISSUE THREAD

**Issue by MobileCrafter** [Khroki/MCEdit-Unified#281]
Right now you cannot use Delete to delete Text.
It would be cool if someone can add this.

**Comment by naor2013** [comment]
What Delete key?
To delete what text?
I don't understand..

**Comment by MobileCrafter** [comment]
Yes you can not delete text with the Delete Key.
To delete every kind of text were you can edit the text.

**Comment by naor2013** [comment]
What text? Do you mean those text fields used by filters?
What do you think the Delete key should do? Delete the whole text or just 1 char?

**Comment by MobileCrafter** [comment]
Just 1 char like you use it in a word file or simple text editor.
I mean text fields where you can search, change Levelname etc.

**Comment by Rubisk** [comment]
Text in textfields. Backspace works but delete just delets w/e is in your selection, quite odd.

**Comment by LaChal** [comment]
I've found where the bug is.
I'll commit a correction asap :)

**Comment by LaChal** [comment]
Fixed in commit [f015a](https://github.com/Khroki/MCEdit-Unified/commit/f015a84e0e67f31ab9c0811c581dd45c2c2ad8da)
