### ISSUE TITLE
Updated german localization

### ISSUE THREAD

**Issue by Neui** [Khroki/MCEdit-Unified#282]
I know the localization is already updated but i checked though the file and fixed some things like rewording or even adding missing translations.

Because my internet is so bad it would take a long time to download and send it as a pull request, i uploaded it to pastebin: http://pastebin.com/raw.php?i=Fh6gqx95

**Comment by TrazLander** [comment]
I believe github has a feature to do basic edits by directly going to the file (https://github.com/Khroki/MCEdit-Unified/tree/master/lang), hitting the little edit icon, and using that to submit a pull request, so you don't even have to download the whole repo. Am not positive on that.

**Comment by Khroki** [comment]
Merged :D
