### ISSUE TITLE
Issues in OS X 10.10.1? MCEdit won't run.

### ISSUE THREAD

**Issue by murtaugh** [Khroki/MCEdit-Unified#287]
I've run MCEdit before, but after downloading and attempting to run it this morning, it immediately becomes non-responsive and has to be killed.

**Comment by naor2013** [comment]
What MCEdit version? Is there an error?

**Comment by murtaugh** [comment]
The most recent version, as well as the couple before I tested out.

No error, just no window, fans eventually spin up, and you have to kill it manually.

**Comment by TrazLander** [comment]
> The most recent version, as well as the couple before I tested out.

Did the others work before you tried the latest one? I wonder if something got corrupted with your config files... Try moving those and let mcedit refresh them and see if that does anything. I'm actually not sure where they're stored for Mac...but it should be a folder named "MCEdit" with stuff like "mcedit.ini" in it.

Also, do you have any resource packs in your resource packs folder? We've had some bugs with those I'm not sure if we've gotten all the kinks out of. You could try removing them from the folder and seeing if mcedit loads up.

**Comment by Khroki** [comment]
No response, assuming fixed, reopen if you're still having the issue.

**Comment by murtaugh** [comment]
Sorry for going silent — I've deleted the config files and re-downloaded mcedit a couple of times, and I get the same results. The app seems to start loading, but then it seems to hang, and no window ever appears.

**Comment by LaChal** [comment]
We need more information to help with this.

Please, run MCEdit and kill him when it's hanged. Then, open the Console app and paste all what happend since you started MCEdit somewhere (i't not a good place here because you may have a lot of text; pastebin is fine).

By the way, Yosemite is a strange thing...

**Comment by murtaugh** [comment]
do you want me to filter the log to only show mcedit's entries?

**Comment by murtaugh** [comment]
do you want me to filter the log to only show mcedit's entries?

**Comment by murtaugh** [comment]
do you want me to filter the log to only show mcedit's entries?

**Comment by murtaugh** [comment]
It doesn't matter — here's a gist with just the entries from just before opening it to just after killing it:

https://gist.github.com/murtaugh/78a24e5e00ac1b1745e1

**Comment by LaChal** [comment]
Thank you for the log.

I can't see anything related to the issue.
In the Console app, there's a `User Diagnostic Reports` item. It shall contain at least one entry begening with `mcedit` followed by a timestamp. Can you paste the last one?

**Comment by murtaugh** [comment]
There aren't any mcedit reports in there, unfortunately.

**Comment by murtaugh** [comment]
I don't know if this means anything, but the Finder reports the app as not having a version number.

**Comment by murtaugh** [comment]
I used the get info window to force it to open in 32 bit mode, and that prompted a crash, but I have no idea if that's expected or not.
