### ISSUE TITLE
Mcedit crashing on startup with missing module

### ISSUE THREAD

**Issue by NoahNMorton** [Khroki/MCEdit-Unified#291]
Using Ubuntu Linux 14.04 LTS running from source in fixed mode, using the command 
`python mcedit.py` 
in the folder, mcedit crashes with the error message:

>Splash load...
>Running in fixed mode. Support files are in your Documents folder.
>Traceback (most recent call last):
>  File "mcedit.py", line 94, in <module>
>    import leveleditor
>  File "/home/noah/MCEdit-Unified/leveleditor.py", line 27, in <module>
>    from ftp_client import FTPClient
>  File "/home/noah/MCEdit-Unified/ftp_client.py", line 1, in <module>
>    import ftputil
>ImportError: No module named ftputil

**Comment by LaChal** [comment]
ftputil is a Python library.

Just install it like you installed the other MCEdit dependecies, and it'll be allright!

**Comment by TrazLander** [comment]
Ya sorry ftputil was a new dependency added to allow Loading worlds from an FTP Server (feature added by @Podshot, available in the QuickLoad menu).

Closing dis!
