### ISSUE TITLE
Note to translators

### ISSUE THREAD

**Issue by LaChal** [Khroki/MCEdit-Unified#293]
Please consider to retranslate the strings 114, 124, 125, 130, 133, 134, 135, 137, 150, 151, 152, 153, 154, 155 (commit e0cd99b86).
The original ones has already been changed. Just update the translated ones.

**Comment by OniOniOn-** [comment]
Yosi!

**Comment by MobileCrafter** [comment]
Im a bit late here but german language is updatetd with that.
