### ISSUE TITLE
Hat layer doesn't render

### ISSUE THREAD

**Issue by yrsegal** [Khroki/MCEdit-Unified#296]
On player markers, only the head layer renders. The hat layer doesn't.

**Comment by Khroki** [comment]
It's a known issue, the renderer doesn't support it, however it might be possible to merge the hat layer into the face layer. Marking as enhancement.

**Comment by yrsegal** [comment]
See, I know it's theoretically possible to make it a seperate layer, insofar as I know OpenGL. Pod said he would look at it, so we'll see.

**Comment by Khroki** [comment]
Fair enough, it's not so much opengl limitations so much as the renderer, but pod has fixed other difficult things before.

**Comment by yrsegal** [comment]
I remember I jokingly asked him to fix all the render bugs and he fixed about 75% of them :P so we'll see

**Comment by Podshot** [comment]
Completed as of commit 5027d4b
