### ISSUE TITLE
what is the problem please

### ISSUE THREAD

**Issue by pierce2010** [Khroki/MCEdit-Unified#298]
![screenshot 1](https://cloud.githubusercontent.com/assets/10912458/6103885/676c2954-b040-11e4-9323-3be8a7c5f7b8.png)

**Comment by Khroki** [comment]
What are your system specs? And have you downloaded your manufacturer's video drivers?

**Comment by Khroki** [comment]
No response, assumed fixed. Reopen if you have more info/still have the issue.

**Comment by pierce2010** [comment]
it still wont work

**Comment by Rubisk** [comment]
What are your system specs? And have you downloaded your manufacturer's video drivers?
