### ISSUE TITLE
A source app: Auto-updating MCE-U

### ISSUE THREAD

**Issue by yrsegal** [Khroki/MCEdit-Unified#300]
So, I just set up (possibly the hackiest thing ever) a way to run MCEdit Unified from source, at latest commit, from a .app file.

It's essentially an applescript app with this code:
do shell script "cd ~/Library/Application\\ Support/MCEdit\\ Unified/MCEdit-Unified
git pull
python mcedit.py"

Surely you could package something, perhaps within an app, to do this? 
It would contain some release's source, installs all dependencies on first run, and then git pull for updates.

I mean, this seems like a good enough idea that *maybe* it could work. I can create an example one if you wish.

Edit: Python appears to be the way we're going. I've made a little python script that *in theory* works on any OS and runs MCE-U.

**Comment by yrsegal** [comment]
Well, this is cool. It seems to 100% work. http://www.mediafire.com/download/3cvxzsq33cy8yyr/MCEdit_Unified_Source.app.zip

**Comment by yrsegal** [comment]
Here's my fairly hacky version, courtesy of applescript. :l at least it works https://www.mediafire.com/?3cvxzsq33cy8yyr
applescript code for Pod:
```
to replace(input, x, y)
	set text item delimiters to x
	set ti to text items of input
	set text item delimiters to y
	ti as text
end replace
set the app_path to (POSIX path of (path to me) as string)
set the app_path to my replace(app_path, " ", "\\ ")

tell application "Finder"
	if not (exists POSIX file (app_path & "Contents/Resources/MCEdit-Unified")) then
		do shell script "cd " & app_path & "Contents/Resources
git clone https://github.com/Khroki/MCEdit-Unified.git
cd MCEdit-Unified
easy_install --user -d . PyOpenGL 
easy_install --user -d . numpy 
easy_install --user -d . pygame 
easy_install --user -d . pyyaml 
easy_install --user -d . Pillow
easy_install --user -d . ftputil"
	end if
end tell

do shell script "cd " & app_path & "Contents/Resources/MCEdit-Unified
git pull
python mcedit.py"
```

**Comment by yrsegal** [comment]
new code with auto updating of dependencies
```
to replace(input, x, y)
    set text item delimiters to x
    set ti to text items of input
    set text item delimiters to y
    ti as text
end replace
set the app_path to (POSIX path of (path to me) as string)
set the app_path to my replace(app_path, " ", "\\ ")

tell application "Finder"
    if not (exists POSIX file (app_path & "Contents/Resources/MCEdit-Unified")) then
        do shell script "cd " & app_path & "Contents/Resources
git clone https://github.com/Khroki/MCEdit-Unified.git
cd MCEdit-Unified
easy_install --user -d . PyOpenGL 
easy_install --user -d . numpy 
easy_install --user -d . pygame 
easy_install --user -d . pyyaml 
easy_install --user -d . Pillow
easy_install --user -d . ftputil"
    end if
end tell

do shell script "cd " & app_path & "Contents/Resources/MCEdit-Unified
git pull
easy_install --user --update -d . PyOpenGL 
easy_install --user --update -d . numpy 
easy_install --user --update -d . pygame 
easy_install --user --update -d . pyyaml 
easy_install --user --update -d . Pillow
easy_install --user --update -d . ftputil
python mcedit.py"
```

**Comment by yrsegal** [comment]
python install script (maybe)
too tired to check
```
import os

def ensure_dir(path):
        directory = os.path.dirname(path)
        if not os.path.exists(directory):
                os.makedirs(directory)

current_path = ""
if os.name == "posix":
	current_path = os.path.join(os.path.expanduser("~"), "Library", "Application\\ Support", "MCEdit\\ Unified")
elif os.name == "nt":
	current_path = os.path.join(os.path.expanduser("~"), "AppData", "Roaming", "MCEdit\\ Unified")
else:
	current_path = os.path.join(os.path.expanduser("~"), "MCEdit\\ Unified")

setup_script = "\
cd "+current_path+"""
git clone https://github.com/Khroki/MCEdit-Unified.git
cd MCEdit-Unified
easy_install --user -d . PyOpenGL 
easy_install --user -d . numpy 
easy_install --user -d . pygame 
easy_install --user -d . pyyaml 
easy_install --user -d . Pillow
easy_install --user -d . ftputil"""
load_script = "\
cd " +os.path.join(current_path,"MCEdit-Unified")+ """
git pull
easy_install --user -U -d . PyOpenGL 
easy_install --user -U -d . numpy 
easy_install --user -U -d . pygame 
easy_install --user -U -d . pyyaml 
easy_install --user -U -d . Pillow
easy_install --user -U -d . ftputil
python mcedit.py"""
if os.name == "nt":
	load_script = load_script.replace("python ","")


if not os.exists(os.path.join(current_path, "MCEdit-Unified")):
	ensure_dir(current_path)
	os.system(setup_script)

os.system(load_script)
```

**Comment by LaChal** [comment]
What exactly fails on Linux, and on which Linux?

**Comment by yrsegal** [comment]
On linux, after apt-get on git, python-setuptools (dependencies):
nothing installs by easy_install right, and ensure_dir doesnt make the directories.
you need to apt-get the libraries still.

**Comment by LaChal** [comment]
Elementary OS Freyja does not look to be a very used OS...

This is a system specific issue. The tests I've made on Ubuntu, Mint and openSuse went well.
Did you try the release Linux installer?

In my opinion, to update automatically from development version is not a very good idea (you can break a lot of things on your system)...
Bu if you have somthing working for Elementary OS Freyja, it's somthing you shall share with this OS users :)

By the way, I think the definition of your `setup_script` variable is messy. You shall rework it using only triple quotes and/or string formating.

**Comment by yrsegal** [comment]
Do you have a retina display? This problem is only occurring with Apple
screens.

**Comment by yrsegal** [comment]
EOS ends up being like Ubuntu for all compatibility.
Also I can't be bothered to write good code when i'm tired.

**Comment by TrazLander** [comment]
oh didnt even realize this was here. Ya we probably could really use something like this. Though system-specific issues always arise :/

I'm going to close this as it's not an active issue report and PM you @yrsegal
