### ISSUE TITLE
(1.2.5.0) Clone tool no longer scales below a factor of 1.0

### ISSUE THREAD

**Issue by threetwo** [Khroki/MCEdit-Unified#302]
In the Cloning tool, using the "Scale Factor" option on a selection only works if the factor is 1.0 or higher. This option used to accept and clone any factor below 1.0 to the first decimal place (0.1 - 0.9) and was a handy feature (for me at least.)

Here it is working as it should:
![ss 2015-02-10 at 11 20 02](https://cloud.githubusercontent.com/assets/7419056/6132611/394c6afa-b119-11e4-8282-80ff86c72452.jpg)

Here it is with the scale factor set below 1.0:
![ss 2015-02-10 at 11 20 50](https://cloud.githubusercontent.com/assets/7419056/6132632/6e4a00b4-b119-11e4-96ea-1c30720040cd.jpg)
As you can see the clone target selection turns into a plane instead of a box. When cloned and saved the area is empty.

And again:
![ss 2015-02-10 at 11 21 32](https://cloud.githubusercontent.com/assets/7419056/6132676/c38c3466-b119-11e4-845e-7ebe6fa060fd.jpg)

**Comment by naor2013** [comment]
I don't understand the problem
It does let you scale down and it seems like it's scaling down in the right way for me
What's exactly the problem?

**Comment by threetwo** [comment]
I just realized the issue seems to be that the selection I have (in the above images) is only 1 block in height. So, when it tries to scale down the y, it's cloning less than one block which, in minecraft is no blocks.

It's been a while but, I seem to remember the clone tool was able to scale a flat surface. Like in the above scenario, the since the y is 1, only the x and z should be scaled.

Hope that explains it better.

**Comment by naor2013** [comment]
So what you're is that if any sides would become 0, they should be 1 instead?

**Comment by threetwo** [comment]
Yes, if that's possible. Like I said, it's been a while since i've used the clone tool for 2D (or flat) objects but, it seems like it worked like that at one time. For now I'm just doubling and tripling the height of the object before I scale it down and seems to work fine.

**Comment by OniOniOn-** [comment]
Yeah. If anything is 1 block long(like height width blahblah) clone tool will make it smaller than 1 block which means nothing! I also had same issue and just ended up making it 2 blocks long by selecting air with it.

**Comment by TrazLander** [comment]
Another bug with this is that mousewheel scroll down in a float box goes from 1.0 to .5, and no lower. instead of 1.0 -> .9 -> .8 -> etc

**Comment by TrazLander** [comment]
Err nevermind it goes 1.0 -> .5 -> .25 -> .125
I guess that's how it is supposed to be? or would 1.0 -> .9 -> .8 -> etc, be better?

**Comment by TrazLander** [comment]
I think I see the main issue with this report.

Scaling should never scale a side to 0.
It's scaling y to 0, which just makes it a flat nothing:
![u6nc24s](https://cloud.githubusercontent.com/assets/4455904/6158631/4e6050f8-b21a-11e4-8f3e-93c8b8a2d863.png)

The minimum it should be able to scale a side to is 1
