### ISSUE TITLE
MCEdit with new blocks.

### ISSUE THREAD

**Issue by Nubebuster** [Khroki/MCEdit-Unified#303]
Blocks added after some Minecraft version are not being exported correctly in MCEdit to schematics.

I want to paste schematics into the game, but for example a beacon has the id -113 while the actual id is 138.
This problem occurs with any block added after 1.5 (I think).

WorldEdit somehow doesn't have this issue, but I don't get why. But I can't use WorldEdit to paste the schematics for unimportant reasons.

This is my code to parse a schematic: http://pastebin.com/HqSC2N6d
This is my code to paste a schematic: http://pastebin.com/gpYunVQQ

**Comment by Podshot** [comment]
Are you using MCEdit to export the schematic and then using your code to import it?

**Comment by Nubebuster** [comment]
yes

**Comment by Podshot** [comment]
Do schematics  that were exported by WorldEdit work?

**Comment by Nubebuster** [comment]
Yes

**Comment by Nubebuster** [comment]
but if I export a schematic from MCEdit and paste it with WorldEdit it does work.

**Comment by Podshot** [comment]
Then it is a problem that we can't fix. If mcedit can export it and WorldEdit can import it, then you may have to debug/modify your code.

**Comment by Nubebuster** [comment]
Yes, but I have no idea how thats possible...
the beacons are exported with the id -113

**Comment by Podshot** [comment]
Our block definitions have the id at 138, what version of mcedit are you using?

**Comment by Nubebuster** [comment]
I dont know, im running windows 10 so I let someone else export them, I'll ask him tomorrow.

**Comment by Nubebuster** [comment]
May this be because Beacons have an inventory? I think so, I didnt think about that yet.
but then there is also something up with stained clay. Maybe too high data?

**Comment by TrazLander** [comment]
Are you running 1.2.5.0 from the download here http://www.mcedit-unified.net/

**Comment by Nubebuster** [comment]
I tried exporting on that vesion but the problem stayed. Beacons somehow still have the id -118 and i found out that exporting with worldedit gives the same problem

**Comment by OniOniOn-** [comment]
So... WorldEdit is problem!

**Comment by Nubebuster** [comment]
No, " i found out that exporting with worldedit gives the same problem".

**Comment by yrsegal** [comment]
not necessarily true, the problem could solely lie in WE's exporting

**Comment by Nubebuster** [comment]
Well, that doesn't change the fact that I have the same problem with MCEdit.

But I am not saying the problem is either of those problems, I am saying that the problem lies in the MCEdit schematic format.

And I thought this was also the right place to ask about the format. Isn't it?

**Comment by martinhanzik** [comment]
Binary representation of the unsigned number 138 is 10001010, but 10001010 as a signed number is -118, there's your problem.
