### ISSUE TITLE
Retina display Mac Laptop on Elementary OS Freyja shows obvious hate for Retina

### ISSUE THREAD

**Issue by yrsegal** [Khroki/MCEdit-Unified#306]
The image says it all
![linuxpic](https://cloud.githubusercontent.com/assets/6596492/6198357/194df68e-b3ca-11e4-8cee-129f2e726422.png)

**Comment by TrazLander** [comment]
> tags should be [Linux] [Annoying] [Bug]

[Pun]

**Comment by Khroki** [comment]
Ah yeah, MCEdit doesn't have display scaling, so super-HD is pretty small.

**Comment by yrsegal** [comment]
Luckily i only use my linux side for testing things :3
but I have a friend who uses EOS as his main OS, so this is an annoying bug

**Comment by LaChal** [comment]
Two questions.

What is this screen resolution?

Do you use release or dev version?

**Comment by yrsegal** [comment]
Screen resolution is, I believe, is 4x 1080p, but spoofed as 1080p.
Always latest commit.

**Comment by LaChal** [comment]
A new option has been implemented in the `Options` panel: `Fonts Proportions`.
Use it to change the text sizes in MCEdit!

**Comment by yrsegal** [comment]
Woo, will this change button size with it? I want my Linux test environ to
be as easy to use as possible :P

**Comment by LaChal** [comment]
Yes. The buttons sizes are changed too ;)

**Comment by yrsegal** [comment]
I'll check it now :D *boots into EOS*

**Comment by yrsegal** [comment]
So, it works. however, I'm getting some barf in the terminal when I quit...
```
[   ERROR][                   root.py:728]:MCEdit version Unified v1.3.0.0 for Minecraft 1.8
Traceback (most recent call last):
  File "mcedit.py", line 767, in <module>
    main(sys.argv)
  File "mcedit.py", line 726, in main
    MCEdit.main()
  File "mcedit.py", line 560, in main
    rootwidget.run()
  File "/home/wire/MCEdit Unified/MCEdit-Unified/albow/root.py", line 158, in run
    self.run_modal(None)
  File "/home/wire/MCEdit Unified/MCEdit-Unified/albow/root.py", line 238, in run_modal
    self.quit()
  File "/home/wire/MCEdit Unified/MCEdit-Unified/albow/root.py", line 538, in quit
    if self.confirm_quit():
  File "mcedit.py", line 396, in confirm_quit
    self.saveWindowPosition()
  File "mcedit.py", line 609, in saveWindowPosition
    if wParent:
UnboundLocalError: local variable 'wParent' referenced before assignment

==================================
			  MCEdit has crashed
==================================
Press the Enter key to close this window 
```

**Comment by yrsegal** [comment]
More barf, when trying to generate a new world. However, I've not created a minecraft instance on this partition.
```
Splash load...
Running in fixed mode. Support files are in your Documents folder.

(mcedit.py:2452): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(mcedit.py:2452): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(mcedit.py:2452): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(mcedit.py:2452): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(mcedit.py:2452): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
Gtk-Message: Failed to load module "canberra-gtk-module"
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of /home/wire/.mcedit/MCEdit/ServerJarStorage named with the server's version number
Cached servers:  []
<class 'Xlib.protocol.request.QueryExtension'>
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of /home/wire/.mcedit/MCEdit/ServerJarStorage named with the server's version number
Cached servers:  []
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of /home/wire/.mcedit/MCEdit/ServerJarStorage named with the server's version number
Cached servers:  []
[ WARNING][                  root.py:1138]:Re-acquired session lock
No servers found in cache.
Downloading the latest Minecraft Server...
Version: 1.8.3
Found version  Release 1.8.3

[ WARNING][                  root.py:1138]:Re-acquired session lock
[ WARNING][                  root.py:1138]:Re-acquired session lock

[ WARNING][                  root.py:1138]:Re-acquired session lock
[ WARNING][                  root.py:1138]:Re-acquired session lock
[ WARNING][                  root.py:1138]:Re-acquired session lock
[   ERROR][                  root.py:2360]:Error while creating world. {world => /home/wire/Documents/mcedit testworld}
Traceback (most recent call last):
  File "/home/wire/MCEdit Unified/MCEdit-Unified/leveleditor.py", line 2355, in createNewLevel
    newlevel.saveInPlace()
  File "/home/wire/MCEdit Unified/MCEdit-Unified/pymclevel/level.py", line 407, in saveInPlace
    for _ in gen:
  File "/home/wire/MCEdit Unified/MCEdit-Unified/pymclevel/infiniteworld.py", line 1195, in saveInPlaceGen
    for cx, cz in self.unsavedWorkFolder.listChunks():
  File "/home/wire/MCEdit Unified/MCEdit-Unified/pymclevel/infiniteworld.py", line 965, in listChunks
    for filepath in self.findRegionFiles():
  File "/home/wire/MCEdit Unified/MCEdit-Unified/pymclevel/infiniteworld.py", line 956, in findRegionFiles
    regionDir = self.getFolderPath("region")
  File "/home/wire/MCEdit Unified/MCEdit-Unified/pymclevel/infiniteworld.py", line 908, in getFolderPath
    raise IOError("The file does not exist")
IOError: The file does not exist
```

**Comment by yrsegal** [comment]
Here's the picture, though. Not quite as good quality as Mac, but good enough. 
![screenshot from 2015-03-04 22 11 17](https://cloud.githubusercontent.com/assets/6596492/6498571/77f3905e-c2bb-11e4-92ca-0ec146407b51.png)

**Comment by yrsegal** [comment]
Perhaps the button scaling could be adjusted, so it looks clean, like this: 
![screen shot 2015-03-04 at 10 14 53 pm](https://cloud.githubusercontent.com/assets/6596492/6498610/f8c8912a-c2bb-11e4-9287-ee9e982f12de.png)

**Comment by LaChal** [comment]
*ysergal*: 
> So, it works. however, I'm getting some barf in the terminal when I quit... [...]

Do you have Xlib python module installed? Which version? (MCEdit uses 0.14.)

*ysergal*:
> So, it works. however, I'm getting some barf in the terminal when I quit... [...]

Not the first time I see this error. However, the world should be created.

*ysergal*:
> Here's the picture, though. Not quite as good quality as Mac, but good enough. [...]
>Perhaps the button scaling could be adjusted, so it looks clean, like this: [...]

Try to use a greater font proportion in Linux.
By the way, OSX and Linux does not handle the same things the same way...

**Comment by yrsegal** [comment]
I tried using a greater font proportion, but the buttons didn't have any buffer between the letters and the edge of the button at any scaled size. This is ALSO a problem when I'm using OSX scaling.

**Comment by LaChal** [comment]
Some parameters hass been changed in the GUI behaviour.
The gap between the widgets borders and content are now 'poportionalized'.
