### ISSUE TITLE
Crash when opening level.dat or *.schematic

### ISSUE THREAD

**Issue by Balthizar** [Khroki/MCEdit-Unified#307]
I am having an issue with the latest release of MCedit unified where the program crashes whenever I use any portion of the openfile dialog or save file dialog. I am unable to open any file type through the GUI or save anything to .schematics files.

System Specs:
Hardware Overview:

  Model Name:	iMac
  Model Identifier:	iMac11,2
  Processor Name:	Intel Core i3
  Processor Speed:	3.06 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Memory:	6 GB
  Processor Interconnect Speed:	5.86 GT/s
  Boot ROM Version:	IM112.0057.B01
  SMC Version (system):	1.64f5

The latest crash spit this error log out:
2/16/15 1:13:03.962 PM mcedit[9480]: [   ERROR][                   root.py:710]:MCEdit version Unified v1.2.5.0 for Minecraft 1.8
2/16/15 1:13:03.965 PM mcedit[9480]: Traceback (most recent call last):
2/16/15 1:13:03.965 PM mcedit[9480]:   File "/Users/Balthizar/Desktop/mcedit.app/Contents/Resources/__boot__.py", line 399, in <module>
2/16/15 1:13:03.965 PM mcedit[9480]:     _run()
2/16/15 1:13:03.965 PM mcedit[9480]:   File "/Users/Balthizar/Desktop/mcedit.app/Contents/Resources/__boot__.py", line 336, in _run
2/16/15 1:13:03.965 PM mcedit[9480]:     exec(compile(source, path, 'exec'), globals(), globals())
2/16/15 1:13:03.966 PM mcedit[9480]:   File "/Users/Balthizar/Desktop/mcedit.app/Contents/Resources/mcedit.py", line 748, in <module>
2/16/15 1:13:03.966 PM mcedit[9480]:     sys.exit(main(sys.argv))
2/16/15 1:13:03.966 PM mcedit[9480]:   File "/Users/Balthizar/Desktop/mcedit.app/Contents/Resources/mcedit.py", line 708, in main
2/16/15 1:13:03.966 PM mcedit[9480]:     MCEdit.main()
2/16/15 1:13:03.966 PM mcedit[9480]:   File "/Users/Balthizar/Desktop/mcedit.app/Contents/Resources/mcedit.py", line 544, in main
2/16/15 1:13:03.966 PM mcedit[9480]:     rootwidget.run()
2/16/15 1:13:03.966 PM mcedit[9480]:   File "albow/root.pyc", line 125, in run
2/16/15 1:13:03.966 PM mcedit[9480]:   File "albow/root.pyc", line 261, in run_modal
2/16/15 1:13:03.967 PM mcedit[9480]:   File "albow/widget.pyc", line 356, in handle_mouse
2/16/15 1:13:03.967 PM mcedit[9480]:   File "albow/widget.pyc", line 438, in call_handler
2/16/15 1:13:03.967 PM mcedit[9480]:   File "albow/controls.pyc", line 216, in mouse_up
2/16/15 1:13:03.967 PM mcedit[9480]:   File "albow/widget.pyc", line 438, in call_handler
2/16/15 1:13:03.967 PM mcedit[9480]:   File "leveleditor.pyc", line 2544, in showControls
2/16/15 1:13:03.967 PM mcedit[9480]:   File "albow/widget.pyc", line 500, in present
2/16/15 1:13:03.967 PM mcedit[9480]:   File "albow/root.pyc", line 190, in run_modal
2/16/15 1:13:03.967 PM mcedit[9480]:   File "albow/root.pyc", line 522, in gl_clear
2/16/15 1:13:03.967 PM mcedit[9480]:   File "/Users/Balthizar/Desktop/mcedit.app/Contents/Resources/lib/python2.7/OpenGL/error.py", line 232, in glCheckError
2/16/15 1:13:03.968 PM mcedit[9480]:     baseOperation = baseOperation,
2/16/15 1:13:03.976 PM mcedit[9480]: OpenGL.error.GLError: GLError(
2/16/15 1:13:03.976 PM mcedit[9480]: 	err = 1286,
2/16/15 1:13:03.977 PM mcedit[9480]: 	description = 'invalid framebuffer operation',
2/16/15 1:13:03.977 PM mcedit[9480]: 	baseOperation = glClear,
2/16/15 1:13:03.977 PM mcedit[9480]: 	cArguments = (16640,)
2/16/15 1:13:03.977 PM mcedit[9480]: )
2/16/15 1:13:04.142 PM mcedit[9480]: mcedit Error
2/16/15 1:13:04.142 PM mcedit[9480]: 2015-02-16 13:13:04.142 mcedit[9480:2629759] mcedit Error

**Comment by naor2013** [comment]
In the dialog that opens where you choose a file, you have 4 views at the top of the dialog
Only the second one from the left works and I have no idea why..
Change it to the second one, then  restart MCEdit and it should work
Since we can't seem to fix it, just tell me if it works and I'll close the issue

**Comment by yrsegal** [comment]
It's stopped working for me. I can no longer open files by mcedit; I can only use the Quick Load.
However, TexelElf's Multiplatform NBT filter loads files quite well; maybe use Tkinter as a fix?

**Comment by naor2013** [comment]
We're trying to fix it..
There's another bug reported about it so we'll keep that one open and I'll close this one
