### ISSUE TITLE
datetime.datetime object has no attribute 'dismiss'

### ISSUE THREAD

**Issue by Estevo-Aleixo** [Khroki/MCEdit-Unified#309]
http://imgur.com/9S3HBrO

This was from the win64 binary and running mcedit.exe & loading a flatworld (skyblock with air generation)

**Comment by yrsegal** [comment]
Happens on 10.10 loading an air generation world as well.

**Comment by naor2013** [comment]
It's a bug with double clicking in Quick-Load.
For now you can click the "load" button
Fixed for next release

**Comment by Estevo-Aleixo** [comment]
What commit fixed this?
