### ISSUE TITLE
ImportError: No module named ftputil

### ISSUE THREAD

**Issue by Aidoboy** [Khroki/MCEdit-Unified#310]
aidan@cinnabar:~/GameData/Minecraft/Tools/MCEdit-Unified$ python mcedit.py 
Splash load...
Running in fixed mode. Support files are in your Documents folder.
Traceback (most recent call last):
  File "mcedit.py", line 94, in <module>
    import leveleditor
  File "/home/aidan/GameData/Minecraft/Tools/MCEdit-Unified/leveleditor.py", line 27, in <module>
    import ftp_client
  File "/home/aidan/GameData/Minecraft/Tools/MCEdit-Unified/ftp_client.py", line 1, in <module>
    import ftputil
ImportError: No module named ftputil

Does anyone know where I can get ftputil.py, or why I don't have it?

**Comment by Podshot** [comment]
Use your package manager to install ftputil like you do with regular modules. I am not experienced with Linux to know anything else about the process.

**Comment by Aidoboy** [comment]
Thank you! Pip didn't install it by defualt for some reason, I had to run "sudo pip install ftputil".

**Comment by xiaoas** [comment]
the ftputil should be included in MCedit I think... it's hard to install by a user...it's extremely user-hostile

**Comment by Podshot** [comment]
I'll look into it's license, but due to the repository being under a code freeze for our next release, I won't be able to possibly add it in until the release is public.

**Comment by Khroki** [comment]
Hmm, shouldn't the linux installer taken care of it? We don't include any of the dependencies with the linux release. They're all installed via the installer.

**Comment by xiaoas** [comment]
YEP I'm using Ubuntu 14.04 and the complaint is for MCedit 1.4.0.1, the new version is much better...but I still suggest to make a configure file & then make throgh terminal like other softwares do  (instead of a installer)

**Comment by RossComputerGuy** [comment]
Same issue except on Pop!_OS and `python-ftputil` isn't available and pip for python2 isn't available as well.
