### ISSUE TITLE
Documentation for INI settings and in-editor option Flags

### ISSUE THREAD

**Issue by CleanerOrc** [Khroki/MCEdit-Unified#312]
Is there a plan to create user documentation for INI options and in-editor options and flags.

For example, on the fill dialogue, option "Choose Block Immediately".  There are lots of options like this that just aren't intuitive to new or maybe even seasoned users.

**Comment by Khroki** [comment]
The UI could definitely use some rewording in places, although all INI options should all be somewhere in the program. Marking as enhancement.

**Comment by CleanerOrc** [comment]
Thanks.  Some of the UI controls show comments when you hover over, some don't.   Could add verification of control comments to enhancement.

**Comment by TrazLander** [comment]
I am trying to clean up and remove/improving confusing things for newer users. The power of hovertext is very useful for this. I am going to close this issue as it's a rather broad request and not very specific, but I will add that "Choose Block Immediately" one to my TODO list. I'm not very sure what that does either, and I'm a long time user of the program :P

But trust me, UI clarity and improvement is steadily a WIP, and I hope to address it all. I'm pretty much the one that's in charge of this issue.

**Comment by CleanerOrc** [comment]
If you come up with a list of things that need done that would help the project along, that someone outside the team could help with, let me know.  Ie, as simple as cross checking the documented control list with controls that actually have a help text…

I suspect it would cause a lot more work than it would leaving it to a developer down the road though.  Just asking.
