### ISSUE TITLE
Exception loading  xxxx.png :  FormatError('PNG file has invali d signature.',)

### ISSUE THREAD

**Issue by ShawnsSpace** [Khroki/MCEdit-Unified#322]
`Exception loading  xxxx.png :  FormatError('PNG file has invali d signature.',)
Couldn't find Image file (xxxx.png) or the file may be corrupted
Trying to re-download skin....`

Seems when loading server worlds with a lot of users i have this error for almost every single user on the server.  Current world is erroring around 1200 times, takes near 21 minutes to load the world.

My question is can i bypass downloading the skins?  Or load them / redownload them in async .manner?

**Comment by Podshot** [comment]
Our next release will allow you to toggle this, and it will prompt you to allow it to download skins when there are more than 50-75 players

**Comment by OniOniOn-** [comment]
50 is still too much???

**Comment by ShawnsSpace** [comment]
50 would be perfect for us, our server are all over 1400 population.  Maybe even less for smaller since this causes alot of wait time just to load the world up from start.

**Comment by Podshot** [comment]
In our next release, you will be able to complete stop skin downloading by unchecking the option in the graphics menu. Just incase 50 is still too much

**Comment by Khroki** [comment]
Sounds like this has been fixed for next release, closing.
