### ISSUE TITLE
Deleted and repopped chunks never regen vanilla 1.8.3

### ISSUE THREAD

**Issue by ShawnsSpace** [Khroki/MCEdit-Unified#323]
Trying to regen  a few chunks but when i delete the chunks or repop they never repopulate, not sure if there are errors involved in this, but i will add them if you let me know where they would appear.

"we added bedrock to the bottom of the these chunks after we where unable to regenerate the terrain so users would not fall out of the world.

![2015-03-03_08 16 03](https://cloud.githubusercontent.com/assets/744488/6464128/a7eb2cb6-c17d-11e4-8ff9-e0ad73d3a4d1.png)

**Comment by Rubisk** [comment]
Possible solutions:
Disable all mods.
Make sure you deleted the chunk, not the blocks inside the chunk.
Make sure your world generation isn't set to superflat void or something.
Make sure the seed is still existent.

**Comment by Khroki** [comment]
If you are indeed deleting the chunk and not just the blocks inside it, try using MCEdit's generator function to regen the land. The repop function just repops ores, it doesn't regen land.

**Comment by ShawnsSpace** [comment]
This is vanilla 1.8.3, no server mods no client mods.  I used MCE to delete the chunks themselves, i was under the impression the chunk files where just deleted and the server jar would regenerate with my gen settings upon loading that area.

**Comment by Khroki** [comment]
That's what should happen, chunks are stored in region files though and the region file isn't deleted unless the entire area is. There has been some strangeness with bukkit/spigot and mcedit though, any chance you're using either? Isn't the first report we've had with chunk behavior and those two.

**Comment by Khroki** [comment]
Have you tried deleting them in MCEdit and loading the world in single player, that may regen them for you.

**Comment by ShawnsSpace** [comment]
Thank you Khroki, we did not try to repop in single player, but tonight after our full backup i will try.  I will post back late with results.

**Comment by L3ice** [comment]
Any news?
@ShawnsSpace

**Comment by Khroki** [comment]
Going to assume it worked, and is therefore a bukkit issue. Reopen if you're still having problems.
