### ISSUE TITLE
MCEDIT IMPORT CRASH 1.3

### ISSUE THREAD

**Issue by zxnakzxz** [Khroki/MCEdit-Unified#325]
Whenever I try to import something it keeps crashing, and I have no clue what to do. So I decided to ask for some help. 
Visit the website for a crash report:

http://pastebin.com/xfzN3U4L

![screen shot 2015-03-06 at 20 23 14](https://cloud.githubusercontent.com/assets/11355851/6540503/32a46760-c498-11e4-8585-202cb7c31f9c.png)

**Comment by zxnakzxz** [comment]
Extra Information:
I'm running MAC OS X
I'm running the latest version of MCEDIT 1.3

**Comment by naor2013** [comment]
It's actually 2 bugs and not 1..
We fixed both for next release, you'll have to wait, sorry
