### ISSUE TITLE
Is it still possible to download MCEdit for 1.7.10?

### ISSUE THREAD

**Issue by Quojil** [Khroki/MCEdit-Unified#329]
I have a modded world on 1.7.10 and I need to import a schematic to it. The 1.8 version crashes when I try to load the world, and I think the older versions of MCEdit will work.

**Comment by Khroki** [comment]
1.0.11.0 should be fully compatible with 1.7.x, minus stuff that was fixed later ofc.

**Comment by Quojil** [comment]
I can load my world in it now, but my movement keys do not work. I can look around and do other stuff, just cannot use WSAD, shift, and space.

**Comment by Khroki** [comment]
Check your key config, it may need to be reset to a preset. 1.0.11.0 was before the key redo.
