### ISSUE TITLE
Error when opening MCedit2.exe

### ISSUE THREAD

**Issue by jozzo402** [Khroki/MCEdit-Unified#330]
Whenever I open the MCedit file everything goes normally, then I get this error message:

[ERROR][mcedit2.main:135]:Unhandled Exception: 
	exception: access violation writing 0xFFFFFFFFEF2E7800

And then it all crashes and shuts down. I'm relatively new to this so there is probably something I'm doing wrong but I don't know what...

**Comment by jozzo402** [comment]
![capture](https://cloud.githubusercontent.com/assets/11382131/6548779/7a90f914-c658-11e4-8403-927895216cc5.PNG)
This is the log file.

**Comment by Khroki** [comment]
Is this MCEdit 1 or MCEdit 2?

**Comment by Khroki** [comment]
Reopen if it is actually mcedit 1.
