### ISSUE TITLE
Not all maps appear in Quick Load

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [Khroki/MCEdit-Unified#332]
Having more than 13 worlds will not cause more to appear on the list by scrolling or otherwise.  Typing a entry for a file that does not appear in the list of 13 would pretend that it does not appear at all, despite being there.  Attempting to remove other files to make it appear fails.

**Comment by LaChal** [comment]
Please verify that you have a level.dat in the worlds you can't see.
If this file is missing, the world won't appear.

You can see that the worlds name appears first in the list. If the folder which contains the world does not have the same name, it is displayed in parenthesis.

**Comment by TrazLander** [comment]
I cannot reproduce this. But it sounds like an issue that feature had in an early part of the development that was fixed already. Just to verify, what version of MCEdit are you using?

**Comment by CoWinkKeyDinkInc** [comment]
I am using version 1.3.0.0, and yes there is a level.dat

**Comment by TrazLander** [comment]
Can you post any screenshots? and what's your OS?
Here's what mine looks like, scroll bar and all:
![2015-03-09 - 19 08 18](https://cloud.githubusercontent.com/assets/4455904/6566415/b1583476-c68f-11e4-8fe7-47f00f461df2.png)

**Comment by CoWinkKeyDinkInc** [comment]
OS X Yosemite (10.10)
![http://puu.sh/gtL1c.png](pic)

**Comment by LaChal** [comment]
I tried to reproduce the issue, but I could not...
![MCEdit 1](https://cloud.githubusercontent.com/assets/7809746/6606566/b6465170-c838-11e4-8c55-010e299fa66f.png)

The OS is OSX 10.10 and MCEdit version is 1.3.0.0 too.
I created a folder (`save1`) with a fake `level.dat` in it. Then I copied the folder around 20 times.
I can see them all and the search function is working:
![MCEdit 2](https://cloud.githubusercontent.com/assets/7809746/6606764/299bd338-c83a-11e4-8936-76854d61d1c8.png)

Do you use some save tweaks/toolkit, or have downloaded some worlds which may contain some tweaks?

**Comment by CoWinkKeyDinkInc** [comment]
I downloaded a world from this repo https://github.com/msalihov/ParaPGM-Maps.  Airship Battles does not appear when dragging it in.  The only modification to the world is that there is an XML file inside the folder that allows it to work with a plugin.

**Comment by naor2013** [comment]
This map is an Pre-Anvil map (an old map) and we don't support those atm.
Try using one of the legacy MCEdit version: https://github.com/Khroki/mcedit-old/releases

**Comment by CoWinkKeyDinkInc** [comment]
Thank you, this probably was the same issue I was having in #331
