### ISSUE TITLE
CSS not loading on Documentation and other issues

### ISSUE THREAD

**Issue by Podshot** [Khroki/MCEdit-Unified#335]
* CSS Is not loaded properly, which causes the HTML to look, unpleasantly
* Documentaion calls its-self "pymclevel" due to how I (accidently configured it)

Both of these will be address later

**Comment by codewarrior0** [comment]
>CSS Is not loaded properly, which causes the HTML to look, unpleasantly

Got you covered.  https://github.com/mcedit/mcedit2/commit/f0b3f79a32d715317c63d893cd524260bc289ac9

The name thing is somewhere in `conf.py`, it appears a couple of times for different things.

**Comment by Podshot** [comment]
Thank your for your help, @codewarrior0, could you help me with one more thing? On the [directories](http://khroki.github.io/MCEdit-Unified/docs/directories.html#directories.getAllOfAFile) documentation, the :param file_dir: does not seem to be parsed like the example sphinx has [here](https://pythonhosted.org/an_example_pypi_project/sphinx.html#function-definitions)

**Comment by codewarrior0** [comment]
It expects a newline between the description and the params/rtypes/etc.

**Comment by Podshot** [comment]
Ahh, ok. Thank you!
