### ISSUE TITLE
[Filter Request]

### ISSUE THREAD

**Issue by Azounstone** [Khroki/MCEdit-Unified#339]
Hi all, still doing a great job!

Not sure how to post this request so my apologies for it being here, do not know anyway other than this of posting it.

Anyway, you have the add store/shop filter which is excellent but I would like to request a few extra features being added to it please as this will improve the adventure map I am currently making. It would be very handy if you can add the ability to make the villages silent and also (this is the key part) have a custom head please.

Is this something you will be able to assist with?

If it isn't then I understand and I will go to the community to see if I can get it made for my use.

Thanks :)

**Comment by naor2013** [comment]
You can always go to our reddit page for more help: http://www.reddit.com/r/MCEdit/
I think I can help with that and add it to the actual filter but what do you mean by having custom head? Choosing a block as a head, or what?

**Comment by Azounstone** [comment]
Hi,

If you can help with this then excellent as I have a lot of shops to add to our map (50 plus). With regards to custom head I mean the ability to add a players head, skull3 or even mhf_xxxx type head. We use player heads on villagers most of the time so this would be the one most used.

Let me know please if you can do this and add it?

Regards,

Andy

**Comment by naor2013** [comment]
This is not an easy one because of the way MCEdit block picker use, but I think I can do
It may not be in the next release since we're close to a release but I'll try to it ASAP

**Comment by Azounstone** [comment]
Fingers crossed it makes it then :)

Thanks again!

**Comment by naor2013** [comment]
I added the Silent option for the near version but the Heads would be only in the release after that

**Comment by Azounstone** [comment]
Hi,

Appreciate you doing this but with the heads not in the version it doesn't help having the option to make them silent as would have to remove all the shops and add them back when the heads version is there.

Do you know how long it will be for the next version as without this we can't add shops to the map and we have over 100 to add. Yes a very large map (www.drobnovia.com is the website for the adventure map if you are interested)

**Comment by naor2013** [comment]
If it's that important to you, I'll try to add a simple prototype for heads support for the near version and add the full one for the release after that, but I can't promise anything
We're now bug-testing the version so I hope it will be out in the next few days

**Comment by Azounstone** [comment]
It is indeed very important and I appreciate your assistance a lot! I look forward to testing it and seeing how it works etc. Key thing is ability to be able to add a player name so it uses his or her head, or skull3 as a head or any of the mhf_ heads.

**Comment by naor2013** [comment]
Added a basic Custom Head chooser for the filter, I'm not sure if I'll make a better one.
I'll close this issue, then.
Thanks for your feature request and for all of your help!

**Comment by Azounstone** [comment]
Many thanks and look forward to seeing this in the next release :)

**Comment by Azounstone** [comment]
I can't find the ability to change the shop to make the villages silent and give him a custom head in the new version. Do I need to download the filter and if so where do I get it from?

**Comment by naor2013** [comment]
There should be a Silent option in the General tab and a new Tab called Head where the custom head tags are.
If you can't see them, please send me a screenshot of the filter, because it might be a problem with MCEdit
