### ISSUE TITLE
Mod support

### ISSUE THREAD

**Issue by Ct4thg** [Khroki/MCEdit-Unified#340]
Hello! I am currently using a mod based on moonquest set in minecraft 1.6.4 Full. I wanted to spice up my world but I'm worried. When I first began I noticed a whole mountain was replaced with spruce stairs. I looked around more and realized a whole load of things were replaced with stairs and other things. Do you know anyway to fix this? Or is this something you may need to fix?

**Comment by codewarrior0** [comment]
Sounds like you were using a very, very old version of MCEdit. Newer ones are compatible with the extended IDs used by mods. Try using a version from here: http://khroki.github.io/MCEdit-Unified/

**Comment by Khroki** [comment]
No response for a couple weeks, assuming you figured it out.
