### ISSUE TITLE
Slime blocks and Sky Light

### ISSUE THREAD

**Issue by Someone3x7** [Khroki/MCEdit-Unified#343]
MCedits light calculations do not seem to take into account that slime blocks are like glass in that they do not block sky light at all. After an MCEdit re-light sky light under a slime block will be 14 instead of the 15 it should be. Manually replacing 96 slime blocks to correct this was not fun :p

**Comment by OniOniOn-** [comment]
I think I just fixed it.

**Comment by naor2013** [comment]
Seems to me like only MCEdit looks at the light as 14 but Minecraft sees it as 15
Was your problem only on MCEdit or was it affecting Minecraft as well? If it was only MCEdit, then it's fixed for next release (By Oni)

**Comment by Someone3x7** [comment]
You can check light levels inside MCEdit? I might have to hunt for that feature. However, my issue was in Minecraft. In the game before succumbing to the temptation of using an editor to execute a large tweak to a design I was working on I had 15 sky light under the slime blocks. The slime blocks were not directly affected by the changes made in MCEdit, but were within the area that was re-lit. Afterwards I had sky light of 14 or less under them. As if they were stone. I replaced them all and they were fixed. Then I tried a chunk relight in MCEdit and they were broke again. At which point I restored the backup and reported the issue here. When I see the next release I'll test it again.

**Comment by naor2013** [comment]
Ok, I think it's fixed but I'll keep this issue open until we'll release the new version and when it comes out, tell us if it's fixed for you
BTW, to see the Sky Light in MCEdit, click 0 (It's like F3 in Minecraft) and there's a "SL" part there (Sky Light) which tells you the level and to see it in a specific block in the air, you can right click while moving and see the number it's showing there

**Comment by Khroki** [comment]
Let us know if this is fixed.

**Comment by TrazLander** [comment]
> BTW, to see the Sky Light in MCEdit, click 0 (It's like F3 in Minecraft) and there's a "SL" part there (Sky Light) which tells you the level and to see it in a specific block in the air, you can right click while moving and see the number it's showing there

Or just *hold Alt* while your cursor is over the block.

and ya this seems fixed I'ma just closing it.

**Comment by Someone3x7** [comment]
Yes, I just got around to testing it on the same world with the new version and its fixed now. Thanks Oni.

**Comment by OniOniOn-** [comment]
Np.
