### ISSUE TITLE
MCEdit icon really big in Volume Mixer

### ISSUE THREAD

**Issue by L3ice** [Khroki/MCEdit-Unified#345]
If you open the Volume Mixer after MCEdit is open the Icon is in the original picture size(REALLY BIG).
![mcedit bug mixer 2](https://cloud.githubusercontent.com/assets/5413827/6741992/75fc4836-ce8c-11e4-81e6-697c6cad4fa5.png)
If you have the Volume Mixer open during MCEdit is starting/loading the icon is normal/small.
![mcedit bug mixer 1](https://cloud.githubusercontent.com/assets/5413827/6742005/81c10b7a-ce8c-11e4-9fc8-a987d405c15f.png)
OS:Windows 7 64Bit

**Comment by naor2013** [comment]
If I understand the bug correctly, I don't get it on Windows 10..
What OS are you using? Can you send some screenshots?
Thanks

**Comment by LaChal** [comment]
This sounds like an OS issue...

But the fact is that the icon file has six layers: 16, 32, 48, 64, 128 and 256 pixels wide.

**Comment by MobileCrafter** [comment]
Oh sorry.
I just made that issue on an app.
You can add there labels but as I am just a Reporter this does not work.
So I forgot to add the Informations.
OS: Windows 7 64 Bit
I will add pictures when I can access the pc again.

**Comment by LaChal** [comment]
It sounds like Windows choose the biggest layer when the mixer is opened after MCEdit...

The only solution I have for this is to suppress the layers bigger than 64*64 pixels. (Since I don't believe that Microsoft will fix this bug...)

**Comment by OniOniOn-** [comment]
I don't think we're the only people who uses icon bigger than 64*64 pixels in the world...

**Comment by MobileCrafter** [comment]
http://stackoverflow.com/questions/17949693/windows-volume-mixer-icon-size-is-too-large

**Comment by LaChal** [comment]
We made some tests, and read some docs (including the above one), and it's definitively a MS side bug.
But we'll find a workaround...

**Comment by TrazLander** [comment]
Can confirm
![screenshot 2015-07-08 05 38 52](https://cloud.githubusercontent.com/assets/4455904/8567493/af0445cc-2533-11e5-8cd9-8458d67b5851.png)
Windows 7

That link he posted has a solution doesn't it?

**Comment by Rubisk** [comment]
Yes, but it's in C, hooking directly into the windows API. I can try something though.
