### ISSUE TITLE
MCEdit v1.3.0.0 aborts execution on start

### ISSUE THREAD

**Issue by AkiraTakizawa** [Khroki/MCEdit-Unified#346]
Hello

I'm trying to run MCEdit v1.3.0.0 on OpenSUSE 13.2, but I'm it cannot find specific modules, which it seems to look for a file in a home directory that's not mine ;-) All the dependencies are up-to-date & respect MCEdit's requirements.

```
NCC-1701@linux-ygih:~/mcedit> ./mcedit.sh 
Starting MCEdit...
Splash load...
Running in fixed mode. Support files are in your Documents folder.
Traceback (most recent call last):
  File "mcedit.py", line 94, in <module>
  File "/home/dens/Projets/Python27/MCEdit-Unified/master/MCEdit-Unified/leveleditor.py", line 27, in <module>
  File "/home/dens/Projets/Python27/MCEdit-Unified/master/MCEdit-Unified/ftp_client.py", line 4, in <module>
ImportError: No module named error
Press any key to close.
```

**Comment by LaChal** [comment]
Some stuff is hardcoded in the program. It does not try to use something on someone else computer.

I'll have a look at this.

**Comment by AkiraTakizawa** [comment]
Hi LaChal
Yup, no dens on my box ;-)

Initially, version 2.6-1.1 is installed, but I let the the installer upgrade it system-wide and it reportedly installed v3.2. However, it's not visible to the package manager (zypper). I think it downloaded & and deployed ftputil 3.2 using pip? I didn't pay attention.
```
S | Name           | Type    | Version | Arch   | Repository       
--+----------------+---------+---------+--------+------------------
i | python-ftputil | package | 2.6-1.1 | noarch | (System Packages)
```

**Comment by LaChal** [comment]
Actually, the installer uses setuptools easy_install script. If it is not found, the installer warns the user about.

It looks like the library wasn't installed system wide.
To check this, you can look for `~/.local/lib/python2.7/site-packages`. If this folder contains the library, that means it is installed for the user only.
You can also make another check:
- Open a terminal;
- Type `python`
- Type `import ftputil`
- Type ` ftputil.__version__`
To exit the python console, hit Ctrl-D.
We'll know which version Python uses.

Anyway, you have to install `ftputil` manually on your system to fix this issue...

**Comment by AkiraTakizawa** [comment]
Hi LaChal

I noticed that xlib cannot be installed system-wide by the installer and that ftputil doesn't get recognized as 3.2 but still 2.6
```
What is your coice [s/u/c]? s
You will be asked to confirm the installation of every needed library.
Answer 'no' to skip one.

Upgrade your ftputil 2.6 to 3.2 [y/n]? y

root's password:
Searching for ftputil==3.2
Best match: ftputil 3.2
Processing ftputil-3.2-py3.4.egg
ftputil 3.2 is already the active version in easy-install.pth

Using /usr/lib/python3.4/site-packages/ftputil-3.2-py3.4.egg
Processing dependencies for ftputil==3.2
Finished processing dependencies for ftputil==3.2

Upgrade your python-xlib 0.12 to 0.14 [y/n]? y

Can't install Xlib system wide. Installing for user only.
```

The commands to run within the python environment don't work out as expected:
```
AttributeError: 'module' object has no attribute '__version__'
```
So here's what I did now:
- grab noarch RPM for python-xlib 0.14 & install it.
- download ftputil-3.2-1.tar, turn it into an rpm :package: with the command ```python setup.py bdist_rpm``` and install it. 
*Packing ftputil 3.2 requires a little modification.* For some reason it can't see the file VERSION right under its nose. I forced it by changing line 19 in setup.py: 
Change ```_version = open("VERSION").read().strip()``` into ```_version = "3.2"``` and it's good to go.
- run the installer:

```
-------------------------------------------------------------------------------
Detecting state of the dependencies...
* Libraries found and compliant:
  - PyOpenGL is 3.1.0, is between 3.0.1 and 3.1.0.
  - ftputil is 3.2, is at least 3.2.
  - numpy is 1.9.0, is at least 1.6.2.
  - pillow is 2.5.1, is between 1.7.8 and 2.6.1.
  - pygame is 1.9.1, is 1.9.1.
  - python-xlib is 0.14, is at least 0.14.
  - pyyaml is 3.11, is at least 3.10.

All the dependencies are satisfied.

Start step 3 (move MCEdit-Unified) [y/n]? 
```

After installation, it's worse... 
```
NCC-1701@linux-ygih:~> mcedit/mcedit.sh 
Starting MCEdit...
Splash load...
Running in fixed mode. Support files are in your Documents folder.
Traceback (most recent call last):
  File "mcedit.py", line 94, in <module>
  File "/home/dens/Projets/Python27/MCEdit-Unified/master/MCEdit-Unified/leveleditor.py", line 27, in <module>
 File "/home/dens/Projets/Python27/MCEdit-Unified/master/MCEdit-Unified/ftp_client.py", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/ftputil/__init__.py", line 50, in <module>
    from ftputil.host    import FTPHost
  File "/usr/lib/python2.7/site-packages/ftputil/host.py", line 19, in <module>
    import ftputil.error
  File "/usr/lib/python2.7/site-packages/ftputil/error.py", line 15, in <module>
    import ftputil.version
  File "/usr/lib/python2.7/site-packages/ftputil/ftputil.py", line 51, in <module>
    import stat
  File "/usr/lib/python2.7/site-packages/ftputil/stat.py", line 19, in <module>
    import ftputil.stat_cache
  File "/usr/lib/python2.7/site-packages/ftputil/stat_cache.py", line 13, in <module>
    import ftputil.error
ImportError: No module named error
Press any key to close.
```
Something bad happened to ftputil?
After some digging it turns out that I have conflicting packages.
```
S | Name           | Type    | Version | Arch   | Repository       
--+----------------+---------+---------+--------+------------------
i | ftputil        | package | 3.2-1   | noarch | (System Packages)
i | python-ftputil | package | 2.6-1.1 | noarch | (System Packages)
```
I remove both and reinstall ftputil, the rpm I created earlier & check the version and check the version
```
>>> print ftputil.__version__
3.2
```
Next: 
- rm -rf mcedit/
- reinstall
- launch the application

It works \(^_^)/

Thank you for your help LaChal :+1: 

![snapshot12](https://cloud.githubusercontent.com/assets/8864848/6798301/1f8c9478-d20c-11e4-9bcd-72411b7865f6.png)

**Comment by LaChal** [comment]
Thank you Akira for the report!
It will be usefull for people who encounter the same issue on openSuse.

The reason for Xlib can't be installed system wide, is the bad version on PyPi site (where both pip and easy_install look for packages). Since this lib is pure Python and does not require complation of C/C++ sources, it is distributed as a .zip in the installer.
MCEdit should be able to run using some system wide libs, and some other installed only for the user.

More work will be done on the installer and MCEdit to force Python to use libs installed with the program instead of the other ones. (I only hope it will be possible...)

**Comment by MythicalZ10n** [comment]
tried everything. when i run mcedit.sh, it keeps saying "no module named error" how do I fix this on mint 18?

**Comment by LaChal** [comment]
Please, open a new issue, and include these information:

* Your Linux version.
* The MCEdit version you're using.
* The `mcedit.log`, if any. It is located in the program folder.
* The copy of the messages displayed in the shell if they report errors. A screenshot can do the job.

If you have trouble with the installer:

* Your Linux version.
* The MCEdit version you're trying to install.
* The `mcedit-<some version>-install.log` file. This one shall be located in `~/.local/log`.
