### ISSUE TITLE
Saving work in MC Edit can show -1 day on time progress

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [Khroki/MCEdit-Unified#348]
It is much more noticeable on work that would take a few seconds to save.
http://gyazo.com/df35e45685b0deef0663f2bb04ed46ab

![Stuff](http://i.gyazo.com/df35e45685b0deef0663f2bb04ed46ab.gif)

**Comment by naor2013** [comment]
I didn't experience this issue but I think I might fixed it for next release..
When 1.3.1.0 comes out, tell me if it's fixed
For now I'll keep this issue open
Thanks for the help!

**Comment by naor2013** [comment]
Was it fixed for you in 1.3.1.0?

**Comment by naor2013** [comment]
Closing but it can really help if you'll tell us if it's fixed

**Comment by CoWinkKeyDinkInc** [comment]
It's gone now, thanks for fixing it.
