### ISSUE TITLE
translation template corrupted

### ISSUE THREAD

**Issue by Estevo-Aleixo** [Khroki/MCEdit-Unified#350]
o714 Ticks mode accouplement

This should be English text. Seems the original error comes from this commit 1c47cafd5c0ca32038a1a6255d063ec32fbac46c and is a copy of the cs_CZ.trn translation of "o354 Breeding Mode Ticks"

There are probably more items here that should be removed.

**Comment by Estevo-Aleixo** [comment]
More information here https://github.com/Khroki/MCEdit-Unified/pull/349


The file to edit would be lang/template.trn (and then subsequent updating of each translation) I'll try to have a pull req tomorrow, if someone hasnt done this for me.

**Comment by LaChal** [comment]
Don't worry, it will be corrected in few minutes ;)

Thank you for the report!

**Comment by Estevo-Aleixo** [comment]
commit bc0f74b048b9bc7f9ea9d461e4072dc4407cd202

To integrate with github you may want to reference the bug in the commit log https://help.github.com/articles/closing-issues-via-commit-messages/ I believe you can also do "affects #350"
