### ISSUE TITLE
Can't use different Resourcepacks within MCedit.

### ISSUE THREAD

**Issue by Emiel97** [Khroki/MCEdit-Unified#352]
When i go to the "graphics" tab in MCedit 1.3.1.0 only the Default resourcepack is available.

Do i need to place custom resourcepacks in special folders?

![knipsel](https://cloud.githubusercontent.com/assets/11050811/6871800/54245392-d4a5-11e4-8a8b-e404d11cde3a.JPG)

**Comment by naor2013** [comment]
They should be in the default resource pack folder for MCEdit (Not texture pack folder)
Please send here a link for one of your resource packs and the folder path for where the resource pack is in

**Comment by Emiel97** [comment]
Here's the link: http://www.mediafire.com/download/gga9j9quucw2cms/Resourcepack.zip

It's currently located in .minecraft > resourcepacks

Thanks for your help!

**Comment by naor2013** [comment]
We only support up to x32 resource packs, sorry :(

**Comment by Emiel97** [comment]
Then why doesn't it just ignore that texture instead of ignoring the whole pack?!

**Comment by naor2013** [comment]
We set the maximum of "big textures" to 10, which means that if there are 10 textures that are bigger than x32, it will ignore the pack

**Comment by Emiel97** [comment]
Okay. I know removed all 64x64 textures and it works. Except for the glass panes, which are still the default ones somehow.

Any idea what causes this?
