### ISSUE TITLE
Inputs are broken

### ISSUE THREAD

**Issue by nike4613** [Khroki/MCEdit-Unified#356]
IN filters it throws an error because it cant figure out the inputs.

COde:
    inputs = (
        ("Instant", ("Yes","No"))
    )
    ...
    useInstant = options["Instant"]

Error:
    ValueError: ('Unknown option type','s')

**Comment by Podshot** [comment]
Your example works for me, could you post the entire filter code?

**Comment by nike4613** [comment]
Ok

from pymclevel import TAG_List
from pymclevel import TAG_Byte
from pymclevel import TAG_Byte_Array
from pymclevel import TAG_Int
from pymclevel import TAG_Int_Array
from pymclevel import TAG_Compound
from pymclevel import TAG_Short
from pymclevel import TAG_Double
from pymclevel import TAG_String
import math
from pymclevel import MCSchematic
import mcplatform
import json
import inspect

displayName = "One Command"

inputs = (
	("Instant", ("Yes","No"))
)

global afterComma
global beforeColon
	
afterComma = "ASLDFKASERWEULKFWEF" #Don't question my sanity, question Mojang.
beforeColon = "ZLASDFASELZLDASFDD"

global heigthDiff
heigthDiff = 5

def perform(level, box, options):
	global GlobalLevel
	GlobalLevel = level
	
	useInstant = options["Instant"]
	
	instant = False
	if useInstant is "Yes":
		instant = True
	if useInstant is "No":
		instant = False
	
	editor = inspect.stack()[1][0].f_locals.get('self', None).editor

	width = 8
	
	onceCmd = []
	clockCmd = []
	once = []
	clock = []
	
	signs = []
	
	for x in xrange(box.minx, box.maxx):
		for z in xrange(box.minz, box.maxz):
			for y in xrange(box.miny, box.maxy):
				if not isCommandBlock(x,y,z):
					te = getSignTile(x,y,z)
					if te == None:
						continue
					signs.append(te)
				else:
					cmd = getval(level.tileEntityAt(x,y,z)["Command"])
					if isPowered(x,y,z):
						clockCmd.append(cmd)
					else:
						onceCmd.append(cmd)
	
	height = 2
	yp = 0
	xp = 0
	length=0
	
	tower = []
	
	onceCmd.append("/kill @e[type=MinecartCommandBlock]")
	onceCmd.append("/tellraw @a {text:\"Construction Complete!\",color:\"green\"}")
	
	if len(signs) > 1:
		height = 3
	if len(clockCmd) > height and len(clockCmd) <= 6:
		height = len(clockCmd)
	if len(clockCmd) >= 6:
		height = 6
	if len(onceCmd) > height and len(onceCmd) <= 6:
		height = len(onceCmd)
	if len(onceCmd) >= 6:
		height = 6
	
	#onceCmd.append("/fill ~-3 ~-1 ~1 ~-3 ~-4 ~1 air 0 replace")

	
	
	for o in onceCmd:
		once.append("/setblock ~"+ str(3+xp) + " ~" + str(yp) + " ~1 command_block 0 replace {Command:\"" + o.replace("\"","\\\"") + "\"}")
		yp = yp+1
		if yp >= height:
			yp = 0
			xp = xp+1
	length=xp
	yp = 0
	xp = 0
	
	for o in clockCmd:
		clock.append("/setblock ~"+ str(4+xp+length) + " ~" + str(yp) + " ~1 command_block 0 replace {Command:\"" + o.replace("\"","\\\"") + "\"}")
		yp = yp+1
		if yp >= height:
			yp = 0
			xp = xp+1
	
	lent = xp+length
	if lent <= 0:
		lent = 1
	
	clock.append("/setblock ~" + str(4+length) + " ~ ~-1 command_block 0 replace {Command:\"/fill ~ ~ ~1 ~" + str(lent-1) + " ~" + str(height-1) + " ~1 stone 0 replace\"}")
	clock.append("/setblock ~" + str(4+length) + " ~1 ~-1 command_block 0 replace {Command:\"/fill ~ ~-1 ~1 ~" + str(lent-1) + " ~" + str(height-2) + " ~1 redstone_block 0 replace\"}")
	#clock.append("/fill ~" + str(4+length) + " ~ ~ ~" + str(4+length) + " ~1 ~ redstone_block 0 replace")
	
	once.append("/setblock ~3 ~ ~-1 command_block 0 replace {Command:\"/fill ~ ~ ~1 ~" + str(length) + " ~" + str(height-1) + " ~1 stone 0 replace\"}")
	once.append("/setblock ~3 ~1 ~-1 command_block 0 replace {Command:\"/fill ~-3 ~-1 ~1 ~-3 ~-4 ~1 air 0 replace\"}")
	
	#once.append("/fill ~3 ~ ~ ~" + str(3+length) + " ~" + str(heigth) + " ~ redstone_block 0 replace")
	tower.append("/gamerule commandBlockOutput false")
	tower.append("/fill ~2 ~-1 ~-2 ~"+str(5+lent)+" ~" + str(height) + " ~2 stained_glass 0 replace air 0")
	tower.append("/fill ~2 ~-1 ~-2 ~"+str(5+lent)+" ~-1 ~2 bedrock 0 replace")
	tower.append("/fill ~2 ~" + str(height) + " ~-2 ~"+str(5+lent)+" ~" + str(height) + " ~2 bedrock 0 replace")
	tower.extend(once)
	tower.extend(clock)
	#tower.append("/fill ~" + str(4+length) + " ~ ~ ~" + str(4+length) + " ~1 ~ redstone_block 0 replace")
	y = 0
	#signs.insert(0,sign("{text:\"                 \",strikethrough:\"true\",color:dark_red}","{text:\"[DELETE]\",bold:\"true\",color:red,clickEvent:{action:\"run_command\",value:\"/fill ~ ~ ~ ~ ~ ~ air 0 replace\"}}","",""))
	for s in reversed(signs):
		tower.append("/setblock ~1 ~" + str(y+height-1) + " ~ wall_sign 4 replace " + NBT2Command(s))
		y = y-1
	
	tower.append("/setblock ~1 ~ ~ wall_sign 4 replace " + NBT2Command(sign("{text:\"                 \",strikethrough:\"true\",color:dark_red}","{text:\"[DELETE]\",bold:\"true\",color:red,clickEvent:{action:\"run_command\",value:\"/fill ~ ~-1 ~-2 ~" + str(lent+5) + " ~" + str(height+1) + " ~2 air 0 replace\"}}","{text:\"[DELETE]\",bold:\"true\",color:red}","{text:\"                 \",strikethrough:\"true\",color:dark_red}")))
	tower.append("/fill ~3 ~ ~ ~" + str(4+lent) + " ~" + str(height-1) + " ~ redstone_block 0 replace")
	for c in tower:
		print c
	
	main = minecartStack(tower,instant)
	#print NBT2Command(main)
	summon = "/summon MinecartCommandBlock ~ ~2 ~ "+NBT2Command(main)

	schematic = MCSchematic((1,1,1), mats = level.materials)

	schematic.setBlockAt(0, 0, 0, 137)
	control = cmdBlockTe(summon, 0, 0, 0)
		
	schematic.TileEntities.append(control)

	editor.addCopiedSchematic(schematic)

						

def minecartStack(tower,ui):
	#tower.append("/kill @e[type=Zombie,name=BillyBob]")
	if not ui:
		tower.insert(0,"/entitydata @e[type=MinecartCommandBlock] {Motion:[0.0,-10.0,0.0]}")
	if ui:
		tower.insert(0,"/tp @e[type=MinecartCommandBlock] @e[type=MinecartCommandBlock,r=0]")
	tower.insert(0,"/fill ~ ~1 ~ ~ 255 ~ air")
	#tower.insert(0,"/kill @e[type=Zombie,name=BillyBob]")
	#tower.append("/kill @e[type=MinecartCommandBlock,r=2]")
	tower = reversed(tower) #We have to iterate over the reversed list of commands, because the riding tag lets them be execute in the inverted order
	
	main = None
	last = None
	zmb = None
	nw = None
	
	for cmd in tower:	
		nw = cmdBlockMinecart(cmd)
		if last is not None:
			last["Riding"] = nw
		last = nw
		if main is None:
			main = last
		zmb = TAG_Compound() 
		zmb["CustomName"] = TAG_String("BillyBob")
		zmb["id"] = TAG_String("Villager")
		zmb["NoAI"] = TAG_Byte(1);
		zmb["Silent"] = TAG_Byte(1);
		zmb["isBaby"] = TAG_Byte(1);
		if last is not None:
			last["Riding"] = zmb
		last = zmb
	nw = cmdBlockMinecart("/kill @e[type=Villager,name=BillyBob]")
	last["Riding"] = nw
	last = nw
	#nw = cmdBlockMinecart("/kill @e[type=Zombie,name=BillyBob]")
	#last["Riding"] = nw
	#last = nw
	
	blocks = fallingBlock("activator_rail")
	block = blocks
	nw = fallingBlock("redstone_block")
	block["Riding"] = nw
	block = nw
	nw = fallingBlock("stone")
	block["Riding"] = nw
	block = nw
	last["Riding"] = blocks

	return main

def sign(line1,line2,line3,line4):
	s = TAG_Compound()
	s["id"] = TAG_String("Sign")
	s["Text1"] = TAG_String(line1)
	s["Text2"] = TAG_String(line2)
	s["Text3"] = TAG_String(line3)
	s["Text4"] = TAG_String(line4)
	return s
	
def calcHeigth(once, clock):
	return int(max(math.ceil((once+1)/6.0) + 1, math.ceil((clock+2)/18.0)))

def isCommandBlock(x,y,z):
	return GlobalLevel.blockAt(x,y,z) == 137

def getSignTile(x,y,z):
	te = GlobalLevel.tileEntityAt(x,y,z)
	if not te == None:
		if te["id"].value == "Sign":
			return te
	return None

#This is not perfect (yet!), since diagonally powering
#Redstone Blocks still count as power sources.
def isPowered(x,y,z):
	if GlobalLevel.blockAt(x+1,y,z) == 152 or GlobalLevel.blockAt(x,y+1,z) == 152 or GlobalLevel.blockAt(x,y,z+1) == 152 or GlobalLevel.blockAt(x-1,y,z) == 152 or GlobalLevel.blockAt(x,y-1,z) == 152 or GlobalLevel.blockAt(x,y,z-1) == 152:
		return True
	return False

def cmdBlockTe(cmd,x=None,y=None,z=None):
	control = TAG_Compound()
	control["Command"] = TAG_String(cmd)
	control["id"] = TAG_String("Control")
	if not x == None:
		control["z"] = TAG_Int(z)
		control["y"] = TAG_Int(y)
		control["x"] = TAG_Int(x)
	
	return control

def cmdBlockMinecart(command):
	newcommand = TAG_Compound()
	newcommand["id"] = TAG_String("MinecartCommandBlock")
	newcommand["Command"] = TAG_String(command)
	return newcommand

def fallingBlock(blockname, te=None):
	block = TAG_Compound()
	block["id"] = TAG_String("FallingSand")
	block["Time"] = TAG_Short(1)
	block["Block"] = TAG_String(blockname)
	if not te == None:
		block["TileEntityData"] = te
	return block

def getval(nbt):
	if type(nbt) == TAG_Compound or type(nbt) == TAG_List:
		return fill_arr(nbt)
	else:
		try:
			return nbt.value
		except:
			return nbt

def fill_arr(nbtdata):
	array = None
	if type(nbtdata) == TAG_Compound:
		array = {}
		for key in nbtdata:
			array[key] = getval(nbtdata[key])
		return array
	if type(nbtdata) == TAG_List:
		array = []
		for entry in nbtdata:
			array.append(getval(entry))

	return array

def NBT2Command(nbtdata):
	return validate_json(json.dumps(getval(nbtdata), ensure_ascii=False, separators=(","+afterComma, beforeColon+":")))

def validate_json(json):
	json = json.replace(afterComma+"\"", "")
	json = json.replace("\""+beforeColon, "")
	json = json.replace("{\"", "{")
	json = json.replace(afterComma, "")
	json = json.replace(beforeColon, "")
	return json

**Comment by Podshot** [comment]
Try putting a ',' after the second ')' on the '("Instant", ("Yes","No"))'. Options can be finicky some times, I'll see if I can fix this in the next version

**Comment by nike4613** [comment]
Thanks! it worked

**Comment by LaChal** [comment]
In Python `object == (object)`.
When we need a tuple containing a single element, we have to put a coma after this element.
