### ISSUE TITLE
Resourcepacks loading is slow (and 'incomplete')

### ISSUE THREAD

**Issue by Neui** [Khroki/MCEdit-Unified#363]
I've got many Resourcepacks (~39 valid ones). Now if i start MCEdit, it takes quiet long to show me the start screen. I can shorten this by rename the Resourcepacks-Folder (so MCEdit dont find them). 
This is annoying with users with many packs.
I timed it: 1 minute 10 seconds with all the 39 packs, About one second without the packs.

An idea would be only do the process in the background so you dont have to wait very long.

In addition, the list of the packs is actually 'incomplete': (Out of 39 vaild ones)
![Resourcepacks list](https://puu.sh/h3BJC/24fccc9c20.png)
Also, "mctextures" is NOT a Resourcepack (it lacks of pack.mcmeta) but MCEdit just says its a valid pack.

I am using MCEdit 1.3.1.0 (64-bits). This also happend with older versions (1.2?). 
Most packs are for MC 1.8, some of them are made for 1.7. There are 2 "duplicates".
MCEdit runs on Windows 7 HE 64-Bits.

mcedit.log doesnt include any information about the resourcepacks.

**Comment by codewarrior0** [comment]
I suggest using zipfile.open instead of zipfile.extract. You don't need to extract all the textures to disk.

**Comment by Podshot** [comment]
I'll modify the code to use that, but it might now improve loading times significantly.

**Comment by TrazLander** [comment]
https://github.com/Khroki/MCEdit-Unified/commit/c928b622290a540c78b47b557a1cb55e6c257610 Zipped Resource Packs no longer extract to disk, as per @codewarrior0's suggestion

**Comment by Neui** [comment]
I finally can run MCEdit from source, now with your little change it take about **4 seconds** to get the window to appear.

**Comment by Podshot** [comment]
Is that a good enough improvement for you, or would you like me to do some more fine tuning with it?

**Comment by TrazLander** [comment]
Does your fine tuning involve more Podshot patented bugs :P

**Comment by Neui** [comment]
Heh, no, 4 seconds is acceptable. Better than waiting a minute.
