### ISSUE TITLE
[Linux] MCEdit fails to start (and a workaround)

### ISSUE THREAD

**Issue by jaromero** [Khroki/MCEdit-Unified#365]
EDIT: Just to clarify, I suspect this happens when windows with weird names are also present, but I have no idea which application is causing this.

Simply put, MCEdit fails to start in Linux. The splash screen shows for a fraction of a second, then vanishes and the program stops.

Version: 1.3.1.0 (this happens with both the installer, and also from source)
OS: Ubuntu 14.10 x86_64

Strangely enough, I seem to be getting two different error messages, and I haven't figured out what triggers each one.

The messages are:

    [nsdragon:~mcedit]$ ./mcedit.sh
    Starting MCEdit...
    Splash load...
    Running in fixed mode. Support files are in your Documents folder.
    Minecraft_Server.jar storage initialized.
    Each server is stored in a subdirectory of /home/nsdragon/.mcedit/MCEdit/ServerJarStorage named with the server's version number
    Cached servers:  []
    <class 'Xlib.protocol.request.QueryExtension'>
    [   ERROR][                   root.py:745]:MCEdit version Unified v1.3.1.0 for Minecraft 1.8
    Traceback (most recent call last):
    File "mcedit.py", line 784, in <module>
        main(sys.argv)
    File "mcedit.py", line 743, in main
        MCEdit.main()
    File "mcedit.py", line 459, in main
        displayContext = GLDisplayContext(splash.splash)
    File "/home/nsdragon/mcedit/utilities/gl_display_context.py", line 21, in __init__
        self.reset(splash)
    File "/home/nsdragon/mcedit/utilities/gl_display_context.py", line 95, in reset
        name = window.get_wm_name()
    File "/usr/lib/python2.7/dist-packages/Xlib/xobject/drawable.py", line 636, in get_wm_name
        d = self.get_full_property(Xatom.WM_NAME, Xatom.STRING)
    File "/usr/lib/python2.7/dist-packages/Xlib/xobject/drawable.py", line 458, in get_full_property
        val = val + prop.value
    UnicodeDecodeError: 'utf8' codec can't decode byte 0xb7 in position 10: invalid start byte

    ==================================
                            MCEdit has crashed
    ==================================
    Press the Enter key to close this window
    Press any key to close.

and

    [nsdragon:~/mcedit]$ ./mcedit.sh 
    Starting MCEdit...
    Splash load...
    Running in fixed mode. Support files are in your Documents folder.
    Minecraft_Server.jar storage initialized.
    Each server is stored in a subdirectory of /home/nsdragon/.mcedit/MCEdit/ServerJarStorage named with the server's version number
    Cached servers:  []
    <class 'Xlib.protocol.request.QueryExtension'>
    [   ERROR][                   root.py:745]:MCEdit version Unified v1.3.1.0 for Minecraft 1.8
    Traceback (most recent call last):
    File "mcedit.py", line 784, in <module>
        main(sys.argv)
    File "mcedit.py", line 743, in main
        MCEdit.main()
    File "mcedit.py", line 459, in main
        displayContext = GLDisplayContext(splash.splash)
    File "/home/nsdragon/mcedit/utilities/gl_display_context.py", line 21, in __init__
        self.reset(splash)
    File "/home/nsdragon/mcedit/utilities/gl_display_context.py", line 96, in reset
        if "MCEdit ~ Unified" in name:
    TypeError: argument of type 'NoneType' is not iterable

    ==================================
                            MCEdit has crashed
    ==================================
    Press the Enter key to close this window
    Press any key to close.

I noticed the WM_NAME reference in the first log, so I thought it had to do with my current window manager (kwin), but after switching to both mutter _and_ xfwm4 I started getting the second error message (also while not running any WM at all), and even after switching back to kwin, I stopped getting the first message.

I'm not very familiar with python at all, but apparently it chokes because https://github.com/Khroki/MCEdit-Unified/blob/master/utilities/gl_display_context.py#L95 this line ends up with not-a-string. I suspect it's one of my other windows screwing it up, but I'm not sure how to find which one it is, if at all. By adding a crude `print` statement after L95 I figured that it was at least being shown as the string "None" (at which point it crashed), but I was also seeing previous windows with a name of '' (empty string).

## Workaround

Either way, I figured out how to work around it by adding to https://github.com/Khroki/MCEdit-Unified/blob/master/utilities/gl_display_context.py#L96 so it becomes:

```python
                if isinstance(name, basestring) and "MCEdit ~ Unified" in name:
```

to make sure it's a string. It's probably a horrible hack that I devised in about 30 minutes of googling, and as I said I haven't worked with python at all, but I got it to run. Hopefully this will help.

**Comment by TrazLander** [comment]
calling @LaChal

**Comment by LaChal** [comment]
Hmmm...

Thank you for reporting this.
The Linux stuff is tested on several flavors, and I did no noticed such an error yet.

Your workarround is welcome! (And may be the only solution for this.)

A question: what is the version of your Python Xlib package?
If it is different to 0.14, you may consider to install this one.

**Comment by jaromero** [comment]
According to apt, it's version 0.14+20091101-1ubuntu2

I'm starting to get the UnicodeDecodeError message once more (`UnicodeDecodeError: 'utf8' codec can't decode byte 0xb7 in position 9: invalid start byte`) and apparently this one is actually a bug in xlib: it complains about byte 0xb7, and that means that if I'm viewing this very issue page, MCEdit crashes on startup, since they're using that very character 0xb7 (the middle dot ·) as a separator. If I tab away (to, for example, the google homepage), then MCEdit starts normally. Even if I change the document's title with javascript to remove those middle dots or replace them with something else, MCEdit works.

I thought it was Chrome at first doing some weird window name shenanigans, turns out I have to avoid certain websites altogether, no matter what browser I use.

**Comment by codewarrior0** [comment]
@jaromero, could you check around line 133 of `Xlib/protocol/rq.py` and see if there's something that looks like this:

```
         s = data[:length]
         try:
             s = s.decode('UTF-8')
         except UnicodeDecodeError:
            pass  # return as bytes
         return s, data[slen:]
```

That's part of a patch for python 3, and shouldn't be there since you're using python2.7 (at least I'm not aware of MCEdit even working with python 3).

If it's there, remove all of those lines and replace them with this:

```
return str(data[:length]), buffer(data, slen)
```

It looks to me like there's a bug in that patch for python 3, too. `parse_binary_value` can be asked to  return only a portion of the data parsed by a `PropertyData` field. If that portion happens to chop a UTF-8 byte sequence in half, you'll get a different unicode encoding error.

**Comment by codewarrior0** [comment]
I suppose another solution would be to install the base xlib using `pip` instead of using ubuntu's version, since it won't have the python3 patch.

**Comment by jaromero** [comment]
Yeah, the code was there, but making the changes didn't help.

I ended up having to uninstall the thing twice (`apt-get remove python-xlib` _and_ `pip uninstall python-xlib`) and reinstalling it as on [this StackOverflow answer](http://stackoverflow.com/a/10055013), and now it stopped choking altogether.

**Comment by codewarrior0** [comment]
Yeah, that would do it. `pip` is probably pulling from debian's repo instead of the main python one.

This really should be reported to the Debian maintainers. I'm certain that last thing about the strings being split in the middle of a UTF-8 byte sequence is a problem.

**Comment by LaChal** [comment]
Good to know that some distro package can be bugged.
I've already remarked that it can happen the version of this library is bugged, and updating or uninstalling/reinsatlling it does not change anything.

The Xlib package is bundled in the Linux installer, and is installed in the user's local dist-pakcages, but it's not seen if another version is installed 'system wide'.
It will be corrected in the future versions of MCEdit.

**Comment by LaChal** [comment]
MCEdit now loads the libraries installed for the user instead of the system ones.
This shall fix this issue.

Can you can test, following these instructions?

1. Pull from this repo, or add the lines added by the commit https://github.com/Khroki/MCEdit-Unified/commit/538520341e502380a9c24cf1181aa569411fce97.

2. Dowload the latest installer and put it somewhere it won't mess up you MCEdit.

3. Launch the installer and choose 'I disagree'.

4. Open `xlib.tar.gz` in the fresh created `mcedit` folder and uncompress its content in `~/.local/lib/python2.7/site-packages`. Create this folder if needed.
If you already have the content of the archive in the folder, you can skip this step.
If you have another version, or you don't know which one is installed there, move this version temporaly.

5. Launch your MCEdit.

6. Look at the console. A line `*** Xlib version [...]` tells what version of the library is detected and wether it is in the user's `site-packages` or in the system one.

7. Report here ;)

**Comment by jaromero** [comment]
Looks like it worked fine! Haven't been able to make it crash, I've rotated WMs a couple of times so far and it still works. Detects user-installed xlib 0.14.

The output: (launching and then closing after it's loaded)
```
[nsdragon:~/Minecraft/dev/MCedit-Unified]$ ./mcedit.sh                (master) 
Starting MCEdit...
Splash load...
Running in fixed mode. Support files are in your Documents folder.
*** Xlib version 0.14 found in user's libraries.
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of /home/nsdragon/.mcedit/MCEdit/ServerJarStorage named with the server's version number
Cached servers:  []
Xlib.protocol.request.QueryExtension
Xlib.protocol.request.QueryExtension
Press any key to close.
```

**Comment by LaChal** [comment]
Nice!

**Comment by AdmiralMemo** [comment]
I'm having this issue (specifically the second one, with "TypeError: argument of type 'NoneType' is not iterable") with MCEdit, and I am completely unfamiliar with how to fix it, even by trying to read these solutions. Can someone help me? I tried to open gl_display_context.pyc to change the code, but it ends up as garbage in the text editor. I need to have this fixed within the next 3 days.
