### ISSUE TITLE
Several bugs when doing zh-CN translation

### ISSUE THREAD

**Issue by fhfuih** [Khroki/MCEdit-Unified#366]
1. I'm using the latest MCEdit(Uni,1.3.1.0), on Win8.1,64bit. These bugs exists in older version(tested from Uni 1.2.0.0-1.3.1.0), but I haven't tested a different OS. Using Noto as Chinese font. There aren't any error log.
2. Some parts don't display big enough to contain the whole strings:

![image](https://cloud.githubusercontent.com/assets/11222265/7104557/3a49b960-e11d-11e4-9d25-2061bffb2a6f.png)

↑Binding a key
![image](https://cloud.githubusercontent.com/assets/11222265/7104566/64de82e6-e11d-11e4-9a91-5e878de30969.png)

↑"Player" tool
![1](https://cloud.githubusercontent.com/assets/11222265/7104582/2ddebb0c-e11e-11e4-8b0d-bc6cf2cbd0c0.png)
![default](https://cloud.githubusercontent.com/assets/11222265/7104583/33b67862-e11e-11e4-9ef2-321ecb33cdc7.png)

↑Almost everything(maybe?) that isn't in bold font and haven't been translated.(the Note in CreateShop filter lost the last line.)

3. block picture can't perfectly match its name in the block list. Also the lower ones don't load their block pictures. Scroll them up then they'll be loaded.

![image](https://cloud.githubusercontent.com/assets/11222265/7104599/6ef91d70-e11f-11e4-89ed-ab25e9ac1cec.png)

4. some strings that has been translated in the .trn file still appears in English.(I can't make up a whole list of those "bug" strings)

![2](https://cloud.githubusercontent.com/assets/11222265/7104617/6ea4a60e-e120-11e4-87d4-05925b2a638e.png)
![3](https://cloud.githubusercontent.com/assets/11222265/7104618/7e90abc6-e120-11e4-89d9-7ccfc2a490a6.png)

5. Reducing font Proportion doesn't solve those bugs

**Comment by OniOniOn-** [comment]
Bug 3 isn't just Chinese thing if it was fixed very recently. It's been like that for very long time.(Which IS bug)

**Comment by LaChal** [comment]
Thank you for pointing this.

Corrections are curently being made.

**Comment by LaChal** [comment]
The layout bugs has been identified and fixed.

Concerning the strings which aren't translated, some correction has been made before you reported the issue. The 'Notes' in the 'Create Shops' filter and the 'Documentation' in the 'Search' filter are now correctly translated.

By the way, strings used in MCEdit (and the translations resources) sometime change. Consider to re-translate the changed ones.

If you are the simplified Chinese translation author, you can participate. Or you can ask this person to!
Just fork the project, make your changes and ask for a merge!

Issue closed now.
If you see something not fixed, just comment/reopen.

**Comment by fhfuih** [comment]
Thank you guys! Actually I am doing the Chinese translation. But I'll first learn how to use Github ,ask my cooperator and do a bit more before I'll post it! Thanks again!^_^
