### ISSUE TITLE
Find filter: focus lost upon viewing results after switching to other window / Results list too long.

### ISSUE THREAD

**Issue by Geethebluesky** [Khroki/MCEdit-Unified#368]
This happens on Windows 7 with MCedit Unified 1.3.1.0 64 bits, world is from Minecraft version 1.7.1.0.

Steps to reproduce:
1. Select a largeish area with the leftmost Select tool in Camera view.
2. Select "Chunks".
3. Go to Filters-->Find. 
4. Set up filter on "Emerald Ore" block, with Dump Found Coordinates.
5. Activate a different program window (because the filter takes a long while to run).
6. Come back to MCEdit when it's finished running (successfully).
--> 7. Try to click "OK" on the dialog list with coordinates: impossible.
---> 8. Try to activate the Filter window: not possible.
---> 9. The focus seems to be on the selected volume; its various dimensions handles still change on mouseover.
---> I have to hit a bunch of random keys, exit out the window etc. basically spazz out to get MCEdit to focus on a usable part of the window that lets me regain control of the application. The system X button works fine and lets me exit, though.

My second issue is: the dialog list is extremely long, and cuts off. It would be useful to output the results list to a log file within the MCEdit folder.
Please see attached screenshot.
![find filter results issue_sm](https://cloud.githubusercontent.com/assets/1903792/7150782/f754c91c-e2dc-11e4-9aad-0e0e42de95a2.jpg)

**Comment by LaChal** [comment]
As said in the commit message, this issue has been partially fixed.

The whole problem may be due to the coordinate dialog messed layout.

Can you let us know if all of this is fixed in the next release?

Thanks!

**Comment by Geethebluesky** [comment]
No problem!
