### ISSUE TITLE
Select bug

### ISSUE THREAD

**Issue by Mikeoz28** [Khroki/MCEdit-Unified#370]
I select a block and want to increment by 1 or say want a select block 14 10 8. In 1.3.2 this is very hard to get and fiddling it increments 2 intermittently. This was no problem in 1.3.1 which I have gone back to. Update to 1.3.2 is no good for me.

**Comment by TrazLander** [comment]
Just need to tap the button quickly! but yaaaa it's still a bit iffy.

Hey @naor2013 this is you...The speed when holding down the nudge button is a pretty nice and fast speed now, but it seriously could use a little acceleration before it actually gets up to that speed if that's possible.

**Comment by Mikeoz28** [comment]
Tried taping quickly and usually get it after a few tries but becomes 
painful. So I will stay on 1.3.1. Overall your program is a marvellous 
bit of kit thank you for it.

On 20/04/2015 12:22 PM, TrazLander wrote:
>
> Just need to tap the button quickly! but yaaaa it's still a bit iffy.
>
> Hey @naor2013 <https://github.com/naor2013> this is you...The speed 
> when holding down the nudge button is a pretty nice and fast speed 
> now, but it seriously could use a little acceleration before it 
> actually gets up to that speed if that's possible.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Khroki/MCEdit-Unified/issues/370#issuecomment-94341418>.
>



---
This email has been checked for viruses by Avast antivirus software.
http://www.avast.com

**Comment by TrazLander** [comment]
Fixed with https://github.com/Khroki/MCEdit-Unified/commit/41bd6bfe85956ff43da6ebbf1e02c00e83a4161e in next release.
