### ISSUE TITLE
Installer not working

### ISSUE THREAD

**Issue by tkdberger** [Khroki/MCEdit-Unified#379]
It's simple: Ir an the installer, answered yes / I agree to everything, and... well...
![image](https://cloud.githubusercontent.com/assets/8628974/7339973/78beefac-ec4f-11e4-9276-8ac6d92466ce.png)

**Comment by LaChal** [comment]
It looks like you have to install [setuptools](https://pypi.python.org/pypi/setuptools) for Python 2.x.

Thus, MCEdit is allready unpacked on your machine. According to your screenshot, a `mcedit` folder should be in your `Downloads`. If all the dependencies are satisfied, you can run it using the script `mcedit.sh`.

**Comment by edwanvi** [comment]
Alright, I'll see if this works...
While I'm here, are any code gods going to be mad if I make a script to do this?

**Comment by tkdberger** [comment]
Nope. Hmm... could someone refine the install instruction for Debian/Ubuntu? (I assume you use apt-get to get the libraries, and pip install to actually install them, but does pip need to be sudo? Which order? minor irritant really.)

**Comment by tkdberger** [comment]
Success! Muchas Gracias! I'm going to make that script now, cause why not?

**Comment by LaChal** [comment]
No specific distro stuff used in the installer.
Almost each distro uses its own method to get packages. Writing code for everyone is not very productive...

The method used to install python dependencies is `setuptools`, which is the most convinient Python library to check and install Python stuff.

Two exceptions: `pygame` and `Xlib`.
The first one is downloaded directly from [pygame.org](pygame.org) (version 1.9.1release).
The second one is embeded in the installer as an achive and is untared in the user's Python libraries folder (usualy `~/lib/python2.7/site-packages`).

The cheks for `pygame` binary dependencies is made by `pygame` installer itself. These binary dependencies have to be installed 'system wide' (with administrator rights using `sudo`). No workaround for now...

You can use `pip` to install the Python libraries, except the binaries dependencies of `pygame`. You'll need to compile them on your system.

This Linux installer is in beta phase, and need more work.
Other ways will be explored ;)

**Comment by tkdberger** [comment]
Ok, nvm then. Carry on.

**Comment by tkdberger** [comment]
I'm done with this... I have a Windows machine anyway, guess I'll just use it.
