### ISSUE TITLE
Prototype for blocks/items names: Note to translators

### ISSUE THREAD

**Issue by LaChal** [Khroki/MCEdit-Unified#382]
The functions which handles the translations for the names of the blocks and items gather as much as possible strings from Mincraft resources.
But some strings aren't present in these resources.
These strings has to be added in files located in the `Items` subfolder of MCEdit. They are named with the language code, and their internal format is like Minecraft language resources.
The reason for this, is adding the needed strings to MCEdit resources could mess translations up, and more code would be needed.
Another reason is the ease of maintenance. If Minecraft data changes, only these Minecraft related files has to be changed.

The 'template' file for these resources is `en_GB`. It is not yet complete, and only contains additional strings, not the missing blocks/items names.

Please, pay attention that the 'template' file can change.

**Comment by OniOniOn-** [comment]
Can't we just take the translated item names from Minecraft itself like mcedit2 does with almost everything?

**Comment by LaChal** [comment]
Like I said in the first comment, MCEdit takes as much as possible from Minecraft resources.
But some stuff can't be found in these resources. So we have to translate them ourselves.

**Comment by MobileCrafter** [comment]
:+1:
