### ISSUE TITLE
Item frames cannot rotate in MCedit

### ISSUE THREAD

**Issue by Zoracraft** [Khroki/MCEdit-Unified#391]
Just spent about an hour trying to flip lanes in MCedit 0.1.7.1 for a race for the wool map. When I did, I got a KeyError saying something like "Direction not found". Since I know this version is fairly outdated (several newer blocks have pink texture), I killed all of the banners in the lane. After doing this, I still received the error. I then tried flipping signs which, as expected, worked perfectly. Even Armor stands flipped! (well, they copied. They were facing the wrong way.) It turns out Item frames were the culprit, as MCedit sees them as entities for some reason. I'm not very knowledgeable about how MCedit's rotations work, but if you guys could fix this in MCedit 2, that would be great.

(Minecraft 1.8.4)

Until then, don't flip item frames!,
Zoracraft

**Comment by Rubisk** [comment]
Update to 1.3.2.0

**Comment by TrazLander** [comment]
www.mcedit-unified.net for latest version

**Comment by TrazLander** [comment]
> It turns out Item frames were the culprit, as MCedit sees them as entities for some reason.

They are entities! http://minecraft.gamepedia.com/Data_values/Entity_IDs
