### ISSUE TITLE
Shop Filter Issue

### ISSUE THREAD

**Issue by Azounstone** [Khroki/MCEdit-Unified#392]
Please see closed ticket for info.....

Update below....

Hi,

It is still doing this. If I delete the contents then install again it works fine however if I exit mcedit and start it up again it then does not add names etc as I explained originally. I then have to delete the folder again and go through this all over again.

I have hundreds of npcs to add and exit after doing a few in an area to then login to single player to look etc and move to next area/find next one to run filter on.

I simply can't do it with the filter as it is (for me anyway) and this is stopping us from releasing our map to PMC.

Again let me stress this is the same in a newly created world so nothing to do with my world. It does it in as many worlds as I want to test it on. I am using the 64bit version of mcedit and windows 7 ultimate, service pack 1 and 1.8.4 of Minecraft.

I am stuck now sadly and can't finish this map as things currently are. Please help :)

Thanks,

Andy

**Comment by Rubisk** [comment]
Please be patient when commenting on a closed issue for us to reopen it, instead of immediately starting a new issue.
