### ISSUE TITLE
"Find" filter issues

### ISSUE THREAD

**Issue by TrazLander** [Khroki/MCEdit-Unified#393]
I think this is @Podshot and maybe @LaChal area?

1. Running the filter at all adds 1 unsaved edit even when it doesnt edit anything.

2. The "Find Next" operation gives a "list index out of range" error and doesn't work at all anymore.
![mrszcap](https://cloud.githubusercontent.com/assets/4455904/7625900/3a765e6c-f9cc-11e4-8c20-0fbcad6c15d1.png)

**Comment by LaChal** [comment]
1. The undo/redo stuff for this filter (and maybe some other) need to be reworked, apparently.

2. The 'Find Next' option is outdated. It will be removed since double clicking on a tree item in the 'Results' panel does the same thing.

**Comment by TrazLander** [comment]
Ehhh Find Next provided a way to cycle through every command block with the tag I searched for nice and easily without adding the need to double click on every single one in the NBT tree, and sometimes getting lost on which one I last clicked on if the list is kinda long. I guess it's not a big deal, but adding two mouseclicks to that process for every command block found sounds like a downgrade to me.

**Comment by Khroki** [comment]
This still an issue?

**Comment by TrazLander** [comment]
There's actually a few filters that have an "issue" similar to the first one I reported here. I guess it would be up to the filter to compare and decide whether there was an edit or not.

**Comment by Khroki** [comment]
Well, even if the filter didn't do anything, it was still an operation, even photoshop adds an entry if you delete an empty area or crop after using ctrl+a. Was more asking relating to the second part.

**Comment by TrazLander** [comment]
Removing the feature wasn't much of a fix, but ya I guess.
