### ISSUE TITLE
MCEdit: Error During "Deleteblocks" and more [Spanish]

### ISSUE THREAD

**Issue by GeorgioMC** [Khroki/MCEdit-Unified#400]
[Este tema ha sido escrito en español]

-version Del Minecraft: 1.8.4 
-version Del mcedit: 1.0 (Versión Recomendada, y en ALGUNAS antiguas) 
-Sistema Operativo: Windows 7 
-Mods Instalados: Ninguno.

-Este Tipo de Errores Como "Error de deleteblocks" Saltan CUANDO trato de ELIMINAR Una amount grande de bloques o también de aunque Pocas Veces en Pequeñas Cantidades. De Cuando trato de relleno Hacer un, copia Una y pegar la copia, Cuando necesito guardar ... error this Salta.

* ¿Como Producir el error ?:

1) Seleccionas Una gran Cantidad de bloques 
2) Haces relleno ONU 
3) El Problema salta en la Pantalla casi al final de del Proceso o en La Mitad.

Imagen:

http://www.subeimagenes.com/img/error-mcedit-1324252.png

Registro de Errores:

http://pastebin.com/3y1eM4Qn

**Comment by LaChal** [comment]
Hello GeorgioMC,  

Sorry for the late answer, but we have trouble understanding Spanish...  

The problem you reported is not related to MCEdit, but to your system.
The text on the image says your account can't write data in a folder it need to write. This is a Windows side stuff.
Try to run MCEdit as administrator. If you can, it shall fix the problem.

Regards,
LaChal
