### ISSUE TITLE
There should be separated translatation strings for 'Delete'

### ISSUE THREAD

**Issue by fhfuih** [Khroki/MCEdit-Unified#402]
In many languages, 'Delete' can either refer to the action of trimming something, or the 'Delete' key on the keyboard. But in many Asian countries, like China and Korea, etc. we use the English word 'Delete' for the Delete key, but use native languages when referring to the verb 'delete'.

In MCEdit, 'Delete' can only be translated globally. So no matter we translate the string or not, there is always contradiction. Can anybody come up with an idea?

**Comment by LaChal** [comment]
This will be added in the next translations update.

Can you tell if there's other key names which need separate translations?

**Comment by fhfuih** [comment]
Oh yes. I think"option"," control" and" command" need it, too. Since they may refer to MAC OS keyboard.

**Comment by LaChal** [comment]
Hmm... You're right.  
But these words may to be translated under some circumstancies.
We'll look at this.

**Comment by fhfuih** [comment]
I think Naor has a good idea. Maybe simply changing those key names into 'Del', 'Opt', 'Cmd' will work.

**Comment by TrazLander** [comment]
Close this if it was done. Trying to clean up issues to finalize a release.

**Comment by fhfuih** [comment]
Not yet I guess... Someone may have to check if "option", "Command" is used as key names

**Comment by naor2013** [comment]
We don't use Cmd since when you click Cmd in Mac, it acts like you click Ctrl so there isn't needed and the Option string is just the key, not anything else so no problems there.
Closing the issue now
