### ISSUE TITLE
Call to translators.

### ISSUE THREAD

**Issue by LaChal** [Khroki/MCEdit-Unified#404]
To: @OniOniOn- @violine1101 @L3ice @Neui @MG-5 @vongola12324 @fhfuih

Beeing concerned with easyness of use for everyone, it is important we can provide as much as possible up to date translations in our releases.  

If you find your pseudo in the first line of this message, it's because you took part to a translation.
This list will be used to warn all of you when major changes are made in the translation resources. Not every time a string is added or changed. The aim of this list is not to spam people. (But if you *realy* want to be spammed, I can do this :o) )  

If you don't want to be in, just post here 'I don't want to be considered as a regular translator'. Your pseudo will be removed :)
If you think someone is missing, please report here too, and we'll contact this person. (At least, we'll try...)
To: @OniOniOn- @violine1101 @L3ice @Neui MG-5 @vongola12324 @fhfuih

Beeing concerned with easyness of use for everyone, it is important we can provide as much as possible up to date translations in our releases.  

If you find your pseudo in the first line of this message, it's because you took part to a translation.
This list will be used to warn all of you when major changes are made in the translation resources. Not every time a string is added or changed. The aim of this list is not to spam people. (But if you *realy* want to be spammed, I can do this :o) )  

If you don't want to be in, just post here 'I don't want to be considered as a regular translator'. Your pseudo will be removed :)
If you think someone is missing, please report here too, and we'll contact this person. (At least, we'll try...)

**Comment by MG-5** [comment]
Good idea!

**Comment by Neui** [comment]
(Huh, the text two times? Also, good Issue number, hehe)
I already thought making a program watching the translations.. But ok.
I would prefer if you contact me on twitter because then i can see from the title that someone mention me/posted something and react to it (I don't always check github and very rarely my e-mails but twitter is most of the time open)

**Comment by OniOniOn-** [comment]
I wasted double the time... I don't care if you call me. I would like you to update every single string.

**Comment by LaChal** [comment]
Huh, yeah, text two times. I guess I spammed a bit Ctrl-V...
And yes, the issue number is quite good :)  

@Neui: I don't have a Twitter account...  

@OniOniOn-: I can add your name in the commits I make concerning the translations, if you want.

**Comment by Neui** [comment]
@LaChal Oh ok. Well, you can also mention me if you change the translations.

**Comment by violine1101** [comment]
You can also mention me if you want. I just don't know if my help is needed because there already are three other translators for German. But if it's needed, I'll help :)

**Comment by TrazLander** [comment]
I got bored, I made a thing:

cs_CZ	(Czech Rep.)	@martinhanzik
de_DE	(Deutschland)	@violine1101 @Neui @L3ice @MG-5 @Marcono1234 @freundTech
fr_FR	(France)		@LaChal
ko_KR	(Korea)		@OniOniOn- @ChalkPE
nl_NL	(Nederlands)	@Rubisk @DragonQuiz
zh_CN	(China)		@fhfuih
zh_TW	(Taiwan)		@vongola12324
en_EN	(US)			goddamn everybody

Also if you get called by this and missed @LaChal's comment above:
> Being concerned with easiness of use for everyone, it is important we can provide as much as possible up to date translations in our releases.

> If you find your pseudo in the first line of this message, it's because you took part to a translation.
This list will be used to warn all of you when major changes are made in the translation resources. Not every time a string is added or changed. The aim of this list is not to spam people. (But if you really want to be spammed, I can do this :o) )

> If you don't want to be in, just post here 'I don't want to be considered as a regular translator'. Your pseudo will be removed :)
If you think someone is missing, please report here too, and we'll contact this person. (At least, we'll try...)

**Comment by OniOniOn-** [comment]
Don't call me on 1 string add. Please call when like 10 or 100 or 1000 or 10000(I woundn't do this) strings added

**Comment by Rubisk** [comment]
Oh whoops. Forgot I'm considered a 'translator' too. I'll update the dutch translation someday I guess.

**Comment by fhfuih** [comment]
Hmmm... That's a good idea. But how do we check the translations IN the software since the new version is not released?

**Comment by Neui** [comment]
@fhfuih You mean checking the translation in software? You can just run from the source. It was painful for me but it worked.

**Comment by L3ice** [comment]
@Neui I dont know how to run from source :pensive:
Already tried it once!

**Comment by fhfuih** [comment]
@Neui Neither can I... Actually I'm a newbie to that sort of developing stuff😥😥😥

**Comment by Neui** [comment]
@L3ice @fhfuih I followed the instruction in the [README](https://github.com/Khroki/MCEdit-Unified/blob/master/README.md) file. Heres how i did it:
* Download [Python 2.7.x](https://www.python.org/downloads/) 32-bit *(I got 2.7.9 but i see 2.7.10 is already out)* and install it 
* Download easy_install and install it (i downloaded [ez_setup.py](https://bootstrap.pypa.io/ez_setup.py) and ran it via phyton on command line `python ez_setup.py`)
* Ran `easy_install <name>` where `<name>` was the package - see the [README](https://github.com/Khroki/MCEdit-Unified/blob/master/README.md).
* On those who failed, i googled it and install it via their installer.

**Comment by L3ice** [comment]
@Neui 
I installed Python 2.7.10 and easy_install
Now I have setuptools 17.0
When I ran now `easy_install <whatever package>`
It just says that it cannot find the command: `easy_install`

**Comment by Rubisk** [comment]
Make sure C:\Python27\Scripts is on the PATH (Computer -> properties -> advanced settings -> environment variables -> system variables -> PATH

Also, make sure there's an easy_install.exe in that folder.

**Comment by L3ice** [comment]
Okay I just had to add the path and now I can use it.
I installed every package with `easy_install`
Only pygame, and pywin32 with an installer.
But I think there is something wrong with pywin32.
It fails to load DLLs
Here have a video:
https://www.dropbox.com/s/lbcgunskoe1ljta/MCEdit%20Fehler.mp4?dl=0

**Comment by Rubisk** [comment]
I can't even read that, a simple output of the console in a pastebin would be much preferred over whatever that video is.

But if it fails to load DLLs you probably got the wrong version of one of your modules, or you messed something up during installation. I don't know.

**Comment by L3ice** [comment]
I dont know how to log that (Noob)
Maybe its because I used Python 2.7.10 instead of 2.7.9

**Comment by Rubisk** [comment]
No it's not. If it is what I *think* it is you don't have ran the installer with admin rights. Try the following:

open a cmd with adminrights (right click -> run as admin)
```
\prefix-path-to-python-dir\python.exe \prefix-path-to-python-exe\Scripts\pywin32postinstall.py -install
```

For example:
```
C:\Python27\python.exe C:\Python27\Scripts\pywin32postinstall.py -install
```

That should fix it.

**Comment by L3ice** [comment]
Thank you!
Now it works :+1:

**Comment by Marcono1234** [comment]
I am sorry, I but I am just not familiar enough with github and I don't feel like I can really help that way. I can still help with translations now and then if you want

**Comment by TrazLander** [comment]
I'm closing this as it's not an active issue report but you can continue discussing here as needed.
