### ISSUE TITLE
Error on loading

### ISSUE THREAD

**Issue by datsme** [Khroki/MCEdit-Unified#405]
I am trying to fix some problems on my server so I downloaded my server files and saved them to a singleplayer game. The ssp loads fine and is playable however when I try to open the world with mcedit 2.0 release, alpha 409, & 407 (haven't tried other versions) I get an error that says Unhandled Exception: 'RegionFile' Object has no attribute 'WriteChunk' and then it closes. It only happens with this world it opens my other worlds just fine. Any suggestions?

**Comment by Rubisk** [comment]
This is the Github Repository for MCEdit-Unified. You seem to be using an MCEdit 2.0 alpha build. You can report Mcedit 2.0 issues here: https://github.com/mcedit/mcedit2, but note that it's in an alpha state and not safe to use yet.
