### ISSUE TITLE
Feature enhancement req: Swap button on Replace brush

### ISSUE THREAD

**Issue by Geethebluesky** [Khroki/MCEdit-Unified#407]
Just for convenience, as the title states, I'd like to see a Swap button on the brush's Replace filter dialog. It would work the same way as the Swap button on the cubic selection's Replace dialog.

Thanks!

**Comment by TrazLander** [comment]
This feature is already there, press the swap hotkey. I suppose the Swap button could be added for clarity.

**Comment by Rubisk** [comment]
2748751ec846ce4d751fc3b55f9f62822dba159e
