### ISSUE TITLE
Can't edit certain tiles since version 1.3.1.0+

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Khroki/MCEdit-Unified#413]
Since version 1310 I can't edit certain tiles. I'm getting this error:

http://i.imgur.com/5hWIxcS.jpg

**Comment by Khroki** [comment]
Have you updated your mods since 1.3.1.0? Might be a new incompatibility with Forestry apiaries.

**Comment by Unrepentant-Atheist** [comment]
Yes, I have.

**Comment by Rubisk** [comment]
Just to get things clear:
On McEdit 1.3.1.0 -> it breaks
On McEdit 1.3.0.0 -> It works

**Comment by codewarrior0** [comment]
https://github.com/Khroki/MCEdit-Unified/commit/9038427a58c3bfb8d2701b92dcedf17573aeab22#diff-ad5c3c6fa85951f43dc970a58b75971cR862

**Comment by Rubisk** [comment]
This should fix it, it'll be included in the next build. Let us know if it's fixed by then :-)

E: I can't github.

**Comment by Khroki** [comment]
If you can test it using the old mod version, if that works it's a new issue caused by forestry not by mcedit.

**Comment by Unrepentant-Atheist** [comment]
Sorry for my late reply @Rubisk , yes, that's it.
