### ISSUE TITLE
Improved session system/Waypoint system

### ISSUE THREAD

**Issue by Khroki** [Khroki/MCEdit-Unified#414]
After some chatting in Skype it has become apparent that a common reason people want to be able to steal session locks is due to the camera moving during a reload, and the extra steps involved in a reload.

Suggested solution is to add a function to save the camera's last position in MCEdit when the map is either saved or the world is closed and load that instead of Player. This should make editing in multiple programs more pleasant. Also add a prompt to reload the world if the lock is lost.

A improved goto system is also suggested, one that has the ability to set and teleport to waypoints, I suggest saving them in the world's folder ala Rei's Minimap so we don't keep around a bunch of deleted world waypoint files. But really however the implementer wants to do it is fine

**Comment by Podshot** [comment]
Fixed via c6f3730
