### ISSUE TITLE
Window sizing?

### ISSUE THREAD

**Issue by Kepler-445** [Khroki/MCEdit-Unified#416]
Either I just haven't found the configuration yet, or it's not there. My screen is not large enough for the size of the program's window, is there a possible way to add some kind of an option for this?

**Comment by Khroki** [comment]
For anyone looking for this in the future, the default window size is 1152x864, but will scale down to a minimum of 1000x700 on the second start if it can. You can resize it using the corners but it will never open at a resolution below 1000x700 to prevent people from making it so small it's unusable.
