### ISSUE TITLE
Bottom textures of heads are backwards

### ISSUE THREAD

**Issue by Halogen002** [Khroki/MCEdit-Unified#417]
Minecraft 1.8.7 Vanilla:
![a](https://cloud.githubusercontent.com/assets/5317071/8146051/7a328186-11e9-11e5-9c29-974a9224c5ed.png)

MCEdit Unified v1.3.3.0:
![b](https://cloud.githubusercontent.com/assets/5317071/8146055/98403768-11e9-11e5-96c6-d8de70925d51.png)

This is running it on OS X 10.10.2. 

It looks like it's only flipped vertically, as the pixels from the left side to the right side look correct.

**Comment by Rubisk** [comment]
Duplicate of #301

**Comment by Halogen002** [comment]
I'm not sure how this is the same problem.
