### ISSUE TITLE
McEdit v. 1.3.3.0 wont work

### ISSUE THREAD

**Issue by Spunge-madness** [Khroki/MCEdit-Unified#419]
I downloaded McEdit v. 1.3.3.0 both x32 bit and x64 bit. None of them work. When I click on the McEdit file that's not ICO the loading screen comes up and a window full of codes and then they close. I took a screenshot of the window with the codes and it said there was an error opening the file. What should I do? Someone please help me. I've buildt 5 ships I want to extract to another world.
![edfghjkhhjhgjffg](https://cloud.githubusercontent.com/assets/13053638/8362270/255c9910-1b78-11e5-8634-a40e172cd303.png)

**Comment by Khroki** [comment]
It's that strange character in your windows username, try moving it to C:\ and try again.

**Comment by Spunge-madness** [comment]
That worked. Thank you!
