### ISSUE TITLE
Holding Right-Click Doesn't Always Release Camera on Button Up

### ISSUE THREAD

**Issue by davidangel64** [Khroki/MCEdit-Unified#420]
Back in MCEdit 0.1.7.1, I could hold right-click to move the camera, and when I released right-click the camera would release the mouse cursor.

In MCEdit 1.3.3.0, this functionality is intact, but only roughly 70% of the time.  I'd say a good 30% of the time, releasing right-click fails to release the camera and cursor, and instead MCEdit behaves as if right-click is still being held.  (It takes a right-click to fix this.)

I am certain this is a bug and not intentional behavior, because the functionality works 100% properly in MCEdit 0.1.7.1.

Thanks,
David/X

**Comment by Rubisk** [comment]
This is in fact a feature. We added a delay to it, because people (Mostly @TrazLander :p) where complaining about the mouse getting stuck or something.

As of right now, if you right click and release within 0.3 seconds or so (can't remember the timing), it is always interpreted as a normal right click. It used to be only interpreted that way when you didn't move the mouse.

**Comment by TrazLander** [comment]
I fucking hate this feature too man. I seriously want an option to just remove it. It still isn't short enough and just pisses me off when I get the damn camera stuck to my mouse all the goddamn time.

**Comment by davidangel64** [comment]
Ah, I see.  Well, it sincerely is a frustrating feature.  Truly, it's enough to make me quit mapping very soon.  And I don't want to do that.  :(

I submit this response as a humble request for an option to allow a user to keep the current feature, or return to the former "only if you don't move the mouse" functionality.

Ideally, a slider bar that lets users set their own delay from no delay at all (classic) to, say, 1 second, would solve this problem.  But I simply request a checkbox to toggle between the two (no delay, and whatever delay is there now).

The camera is just no longer fully in the user's control, and I'd like to have that back.  :)

**Comment by davidangel64** [comment]
Also, I'd like to add that even if I hold the mouse button down for a while (far longer than 1 or 2 full seconds), MCEdit still very often interprets it as a normal right-click.  This definitely seems like a bug.

**Comment by TrazLander** [comment]
here's where I changed it, though I think this isn't in the latest release and is still on the master: https://github.com/Khroki/MCEdit-Unified/commit/c0df7a3ac98f217dc93b351d9b8588e2a0aee6f2
Still isn't enough. A slider isn't too possible atm, but something in the options where you can change the amount of milliseconds before it detects that to 0 would be nice.

**Comment by TrazLander** [comment]
Oh, I get why it's useful...

Hey @Rubisk, how possible would it be to disable right-click camera locking for everything but the Selection Tool and Brush tool? Far as I know it's only useful when you have an actual thing attached to your mouse, and there's no reason for it when you don't.

I have a feeling you'll say this is a bad idea for some reason, or there's some other reason that this is useful...Maybe we could just add it to the controls? Then I could just re-bind it to something off to the side (like "L" for lock). I think the whole thing too easy to accidentally hit and should be something else by default, but that's just me. Adding it to the controls under "camera" category would be a pretty good option to resolve this.

**Comment by Rubisk** [comment]
Played around with it a little:
5bde6d9ce0f87a80b0962a5e460fcd8935b2b2f2

For me, this feels fine, I never manage to lock it while looking around, yet it's still really easy to lock it by just right clicking. Would be happy to hear what you guys think.

**Comment by davidangel64** [comment]
I'd love to try it.  I'm mostly new to the whole github thing (and have only the barest experience with code repositories), so if you could let me know how to download this version to try it out, I'll respond with my feedback on it.  :)

**Comment by TrazLander** [comment]
Well I'm able to test it out, and holy shit @Rubisk that fixes the whole issue. Good freaking idea. I'm just going to mark this as resolved cuase this is goddamn perfect.

Posting what Rubisk told me it does now here for reference:
> If you right click, and drag your mouse around, it will ALWAYS release.
If you right click, and do not drag your mouse around, it will ALWAYS lock

**Comment by davidangel64** [comment]
I'd still like to know how to access this.

**Comment by Estevo-Aleixo** [comment]
@davidangel64 https://github.com/Khroki/MCEdit-Unified#running-from-source

**Comment by davidangel64** [comment]
Tyvm.  :)
