### ISSUE TITLE
Extending sys.path and using imp.load_source on unicode names

### ISSUE THREAD

**Issue by Rubisk** [Khroki/MCEdit-Unified#421]
02d7683d69c2b9a31b7c51d6482f26fb8dcde47c fixed a lot of unicode crashes on startup.

However, it's still not possible to import filters if there's non-ASCII characters in the path.
The main issue is that (from the stuff I read), pythons import internals convert any unicode path to a string before handling it. Encoding with sys.getfilesystemencoding (which returns 'mbcs' on windows for some awkward reason) isn't always possible, it will throw an error on any non-ASCII character.

A way needs to be found to import modules from a path containing non-ASCII characters. To keep libraries working, we'll also have to extend the sys.path with a unicode character somehow, OR we'll have to copy the files over to a directory containing just ASCII characters (which would be much less preferred).

**Comment by codewarrior0** [comment]
[I described this here.](http://www.reddit.com/r/MCEdit/comments/38j402/mcedit_1330_crashes_on_startup/crvxwke)

You shouldn't ever call getfilesystemencoding. The filesystem functions take care of encoding `unicode` objects correctly, since the underlying FS APIs on each platform expect a different encoding. What you need to do is operate on filenames as `unicode` objects at all times.

**Comment by codewarrior0** [comment]
Ah, you specifically mentioned importing modules. This is a known bug that wasn't fixed until Python 3.2. I don't think there are any plans to backport the fix to 2.7

http://bugs.python.org/issue3080
http://bugs.python.org/issue9425

As a workaround, you may need to import the file "manually" by creating a new empty module, reading the source code from the filter, and executing it in the module's namespace:

```
source_code = file("my_filter.py").read()
mod = imp.new_module("my_filter")
exec(source_code, mod.__dict__)
```

If it's important that filters be importable by other filters, you should also add the newly created module to `sys.modules`:

```
sys.modules["my_filter"] = mod
```

**Comment by TrazLander** [comment]
Dunno if this is related, or this IS the issue you're talking about, but maybe you know why this filter won’t take “§” as an input and gives me this error: http://i.imgur.com/wViKWfq.png

Filter is here: https://github.com/TrazLander/FindandReplace/blob/master/Find%20and%20Replace%20%2B.py

**Comment by codewarrior0** [comment]
Looks to me like it gives an error because you're trying to print a `unicode` that can't be encoded using the command window's charset. I think it will take the § as input - you just can't `print` it.

**Comment by codewarrior0** [comment]
You can `print repr("Replace " + replace)` and it will output the `\uXXXX` escapes instead.

**Comment by Rubisk** [comment]
https://github.com/Khroki/MCEdit-Unified/commit/84c43fd1e6bcf1c78de6727e0125ccf023f63366

May need improvement in the future, but at least it works. Kind of hackish though.
