### ISSUE TITLE
pocket.yaml make-sure lists

### ISSUE THREAD

**Issue by OniOniOn-** [Khroki/MCEdit-Unified#422]
- [x] leaves' data values were different from PC (asked for testing)
- [x] wet sponge wasn't implemented
- [x] rails didn't have powered/unpowered. it was always powered before
- [x] tall grass data is correct?(needs testing)
- [x] there was no nether brick slab, which affects data values later than that
- [x] snow layer stacking wasn't implemented
- [x] all fence woods types WERE implemented but not present
- [x] id 95 isn't stained glass but is invisible bedrock
- [x] pumpkin stem have '(Max)' next to Age 7 but wheat doesn't have one
- [x] pillar quartz block didn't have sideways orientation
- [x] id 157 is wooden double slab instead of activation rail
- [x] id 158 is wooden slab instead of dropper
- [x] not sure about id 161, 162 as they are not in the wiki page
- [x] id 198 IS grass path
- [x] id 243 is duplicated
- [x] stonecutter top texture is [14, 29], and forward, backward are [13, 29]. sides and bottom are same as furnace
- [x] update game block names should be updated to follow wiki
* furnace has useless tex_direction_data help # thing which chest doesn't have

You must have stopped around 157 but I just checked everything so you can rest.... I can't make sure I got everything... but this must help. I used past tense because things might have changed when I was gone.(but this is highly unlikely and probably none of those detailed things were changed) I will check things again when 11.0 is fully out(or is it already?)

**Comment by TrazLander** [comment]
I basically copy/pasted and then just compared the whole thing to this wiki page: http://minecraft.gamepedia.com/Pocket_Edition_data_values

Figured it would tackle the majority, and if any would be wrong, someone would come along and fix em :P You going to do those or you asking one of us to?

**Comment by OniOniOn-** [comment]
I think I will start at least next week or later, someone should do it if release cannot be delayed too much anymore.

**Comment by naor2013** [comment]
MCPE 0.11 was released almost a month ago..
I'll try to do it myself if I'll have the time but I'm not sure I will

**Comment by TrazLander** [comment]
> -pillar quartz block didn't have sideways orientation

You mean it's not supposed to for pocket? Weird.

**Comment by OniOniOn-** [comment]
I installed MCPE along with BlockLauncher and PocketInvEditor. Acasia, Dark Oak leaves and woods does exist. Before release, I'd like someone to send me compiled MCEdit and Minecraft debug world so I can test if everything works correctly...(MCPE infinite map editing, all blocks, textures, etc.)

**Comment by OniOniOn-** [comment]
How do you add those checkbox thingy next to everything? I saw it on github somewhere...

**Comment by codewarrior0** [comment]
```
- [ ] fix thing
- [ ] fix other thing
```

Spaces are significant.

**Comment by OniOniOn-** [comment]
@codewarrior0 Thanks, this looks awesome.

**Comment by TrazLander** [comment]
>  tall grass data is correct?(needs testing)

I'm 100% positive it's correct for PC. I carefully went over that shit a while back. Don't know if it's different for pocket.

> rails didn't have powered/unpowered. it was always powered before

You mean pocket only has powered?

>  pumpkin stem have '(Max)' next to Age 7 but wheat doesn't have one

Fixed with https://github.com/Khroki/MCEdit-Unified/commit/cd2df1349e2c59318c86ac12389dcf67604a12d0

**Comment by OniOniOn-** [comment]
Pocket only had normal rail and powered rail. Unpowered rail doesn't exist.
I tested the grass data long time ago and it was different from PC

**Comment by TrazLander** [comment]
"Unpowered Rail" doesn't exist in PC version either, and isn't in the yamls, so I don't know where you're getting that from, and I don't know what we're talking about anymore :P

Block 27 = "Powered Rail" is its name in english. block name is golden_rail
* Data 0-5   Powered Rail is in an unpowered state.
* Data 8-13   Powered Rail is in a powered state.

-----------------

2-high grass also received some data additions in 1.8. I remember cause I updated them https://github.com/Khroki/MCEdit-Unified/commit/8290dcf8c03d6c5e05ce34106b1cc87c78def94f

**Comment by OniOniOn-** [comment]
Yes, but I don't know if data 0-5 exists as unpowered state in mcpe. You can't make it normally.
I will check grass data values soon.

**Comment by fhfuih** [comment]
Guys, if you are busy working on other issues, maybe I can do this job. I've just managed to learn pocket.YAML structure. But before that someone plz teach me how to install MCPE_LEVELDB in a detailed way? 
If it's no more than a checking job, I would be glad to help😄

**Comment by OniOniOn-** [comment]
You dont have to install mcedit to test those... Just get blocklauncher and worldedit script and test data values... Well I was about to test it just now so you can just test it after I edit all of the issues here...

**Comment by fhfuih** [comment]
Ok, I will start as soon as the school is over!

**Comment by OniOniOn-** [comment]
I will tell you here when the pocket.yaml update is done.

**Comment by OniOniOn-** [comment]
Finished everything. Making commit right now.

**Comment by Yuugen0127** [comment]
btw on 7/29 Minecraft Pocket Edition is getting a ton of new features like the Nether and potions as well as the related blocks and mobs.
You might want to work on a 0.12.0 version.

**Comment by OniOniOn-** [comment]
I don't have access to 0.12.0 version, not even beta.

**Comment by OniOniOn-** [comment]
@Yuugen0127 I don't have access to 0.12.0 version, not even beta.

**Comment by Yuugen0127** [comment]
That's because it'ｓnot out yet. Sorry.
I was just trying to suggest that you release after 0.12.0 comes out.

**Comment by Yuugen0127** [comment]
Also, I know this is stupid, but can I take a look at the .js MCPE mod you were making? I really get the feeling that could be a good mod with a few tweaks. Of course I'll give you credit.

**Comment by OniOniOn-** [comment]
Make an issue in there.

**Comment by fhfuih** [comment]
I checked that. Nothing's wrong

**Comment by fhfuih** [comment]
I found some issue. I'll post it here. Wait for a moment

**Comment by L3ice** [comment]
I really would like to help but since Im in the holidays its not possible :/
But I want to give you some tips(If you do not already know about them).
The Windows 10 Version(A modified PE Version which aims for Windows 10 Tablet Users) will be released on 29.07.
tomcc(PE Developer) said that 0.12 on PE will be released eventually on the same date.

So if thats the case the Google Doc list must be empty before that date.
Because 0.12 adds and fixes many things, like(leaked on minecon):
-Snow layers
-Nether brick slabs
-new blocks & mobs
-maybe wet sponge?
-multiple levels(nether)


(I didnt link anything since Im writing on a phone)

**Comment by OniOniOn-** [comment]
Yeah, there were also soul sand and enchanting table and blah blah... If 1.4.0.0 release data is later than that, I will think of updating this. (because I can't be sure about PE block id is same or not)
And devs, how will we manage Windows 10? We can't just add windows 10 blocks and break original MCPE.

**Comment by OniOniOn-** [comment]
Wait, I will test stone slabs/double slabs again from data 0~15, I finally know what seamless means.

**Comment by TrazLander** [comment]
Seamless isnt literal, its based on the blockstates. Some seamless seamed blocked arent really seamed (at the moment). and are the same as the seamless ones. That doesnt make their labeling wrong.
