### ISSUE TITLE
[Question] Change mod id

### ISSUE THREAD

**Issue by Frontrider** [Khroki/MCEdit-Unified#424]
One of the mods what I used had different modules, with different mod ids. Now all is one id. Nothing else changed (the data within the blocks remain unchanged). Could I change the mod id in the save, so no block will dissappear? (would result things like holes in the bedrock)

**Comment by Rubisk** [comment]
Yes...

Just select the fill tool (4), and do:
find (id to replace)
replace (id to replace with)

If you want to keep the data value intact, there's a checkbox for that.
