### ISSUE TITLE
False Positive

### ISSUE THREAD

**Issue by MegaBoy128** [Khroki/MCEdit-Unified#425]
Steps: Downloaded
Version: MCEdit Unified v1.3.3.0 for MC1.8
MC Version: 1.8.4
OS: Windows 8
My virus & Malware Protection, Norton, deleted the installer for having no or poor reputation.
Luckily they have a document for who to fix the problem! 
More info can be found here: http://www.symantec.com/security_response/writeup.jsp?docid=2010-051308-1854-99

**Comment by Khroki** [comment]
This will be fixed when norton supports windows 10, I usually use it so it gets whitelisted when I compile it, but since upgrading to win 10 norton no longer works and therefore MCEdit has no reputation information. Basically a false positive.

**Comment by MCMASTER06** [comment]
Thx M8y
