### ISSUE TITLE
No module named mcinterface Bug

### ISSUE THREAD

**Issue by WeeGreenNinja5** [Khroki/MCEdit-Unified#428]
**Minecraft 1.8.7**; 

**MCEdit v1.3.3.0 64bit** for **Minecraft 1.8**; 

Windows **8.1 64-Bit**; 

**OptiFine_1.8.7_HD_U_D6**

Hello, I am here to talk about a bug that I have recently encountered from using the Filter tool in MCEdit. The bug is that I cannot us the Forester option with the Filter tool (like I've seen in previous versions) due to MCEdit not finding some module named mcinterface. Here are the steps I took to get to this problem:

1) I opened MCEdit

2) Quickly opened a map that I've been working on

3) I selected a plot to where I wanted to use the Filter tool

4) I selected the Filter tool

5) **BAM** I got 2 different screens that looked like this:

![mcedit bug_1](https://cloud.githubusercontent.com/assets/13194741/8516492/ad34b004-2369-11e5-80f3-8c2356871576.png)
![mcedit bug_2](https://cloud.githubusercontent.com/assets/13194741/8516493/ad38499e-2369-11e5-892e-73f1229d00c2.png)

I thought to myself how weird it appeared right when I clicked the Filter tool. So then when I check the console, this is how it looked like:
![mcedit bug_4](https://cloud.githubusercontent.com/assets/13194741/8516938/97f2c7a2-236f-11e5-8edb-1b9a3ecf8fe7.png)

Then I checked the files for the Forester filter and... it's in here...
![mcedit bug_3](https://cloud.githubusercontent.com/assets/13194741/8516583/b6d5cc46-236a-11e5-96f5-4212dc15761f.png)

I just can't find any modules at all. Please reply if anyone can help me fix this bug so that I can use the forester option with the Filter tool.

**Comment by Rubisk** [comment]
Fixed in source, will be fixed in the next releasr. Thanks for the report : -)

**Comment by OniOniOn-** [comment]
He even added arrows on picture.
