### ISSUE TITLE
Entity mirroring isn't working properly

### ISSUE THREAD

**Issue by TrazLander** [Khroki/MCEdit-Unified#430]
Since @naor2013 @Khroki took one look at this issue and ran away, I'll post it here for anyone else that may know how to resolve this. @codewarrior0 maybe you'll know something about this too.

Currently:
![2015-07-06_23 41 57 - copy](https://cloud.githubusercontent.com/assets/4455904/8538389/a4be0fee-2439-11e5-8411-df3fede2bde7.png)

What it should do:
![2015-07-06_23 43 32 - copy](https://cloud.githubusercontent.com/assets/4455904/8538391/a9175a64-2439-11e5-9dfb-1bf24df7bef1.png)

That's because it's treating it like a block and rotating it twice by adding 180 degrees to the rotation tag, when it's more of a circle that goes from -360 to 0 back up to 360, mirroring doesn't work on these diagonal angles. @Khroki did a working method for banners/signs/player heads that have 16 rotations by just matching the mirrored values here: https://github.com/Khroki/MCEdit-Unified/blob/master/pymclevel/blockrotation.py#L377 but here we need a formula for decimals. And I found it:

east <-> west = Rot * -1
north <-> south = Rot * -1 + 180

If anyone knows how to get that formula working, feel free to take a crack at it.

**Comment by codewarrior0** [comment]
Which direction does Rot=0 face?

**Comment by codewarrior0** [comment]
Whichever it is, one of them is going to be `-Rot` and the other `90-Rot`

**Comment by TrazLander** [comment]
Ahh nevermind, found it! Fixed with https://github.com/Khroki/MCEdit-Unified/commit/cfb9b278d3e611c86f9a4488505f3625a602bc4d
