### ISSUE TITLE
Translations broken

### ISSUE THREAD

**Issue by LaChal** [Khroki/MCEdit-Unified#433]
The filter translations are broken (once more...) for the stock-filters and the categorized custom filters.
The un-categorized custom filters are correctly translated.

The other GUI elements are translated at startup, but 'loose' their translations later. The work around is to select open the options panel and choose another language and select back the one you want.

Since I'm busy with my work, please, consider to correct this, and test before comitting :)

**Comment by TrazLander** [comment]
tagging @Rubisk

**Comment by Rubisk** [comment]
Yes. I left that code alone. Dunno how it works. Up to dens to explain me how it should work.

**Comment by LaChal** [comment]
It shall work like it worked for the last release...

I can't fix that myself for now, because I'll have to analyse every commit... And I don't have the time to.
You're one of the people who changed the code and you saw the evolution. You know what you did. I don't. It'll take ages for me to do something without breaking othe stuff...

**Comment by Rubisk** [comment]
I left the translate code in filtet.py alone. Theresa comment in tryImport saying tgat I have no idea what those lines do. If you could explain how it SHOULD work I can fix it.

**Comment by Rubisk** [comment]
Ok, so I did a little bit more digging (about 2 hours)

And it looks like you were trying to use the module "albow" as a non-static object, by importing it again and again, then deleting it.

Modules are static. You are never supposed to set global variables, without changing them all over your program. To create something that isn't static, a class instance should be used instead.

If we want filters to work properly, what really should be done is setup some Translator class in albow. It's constructor could take something like a path to the lang file.

The class will then handle building the translation, and storing the cache. In translate.py, at the end something could be done like (pseudocode):
```python
translator = Translator(config.getPathToTranslateFile())
translator.buildTranslation()
_ = translator.translate
```
after which all of mcedit's component could still call _(string) to translate a string. (And to fit Pycharm-OCD feeling, maybe rename _ to translate and then:
```python
from albow.translate import translate as _
```

**Comment by LaChal** [comment]
The fact is the code I wrote 'injects' the translation module into filters at runtime.
Doing this, it is needed to reload this module after filters imported to keep the general GUI translated.
That explain why there was variables and code related to translation surrounding `tryImport`.
I made the choice to inject tr translation module at runtime to keep the filters author work simple. They don't have to bother with importing too much MCEdit stuff in their code.

The translation has been broken when this code was removed and `tryImport` moved (I guess).
Restoring this like it was will correct the problem or, at least restoring the code which handled the translation reloading.

On an other hand, modifing a code to fit an editor feeling sounds bad. I don't use Pycharm, but Eclipse.
What will happen if I decide to change the code to fit to Eclipse?

Renaming a function that is used in almost every file is not a good idea. Especially when this function will be renamed to its original name in another part of the code...

**Comment by Rubisk** [comment]
Importing a module should never do stuff like that. Calling import should provide an interface you can interact with, and the only code it should run is that required to use the interface. 

It really sound like you try to create multiple versions of the same module or something?

I cant access a pc for now, but ill try fix this once back.

And about the name: its python naming convention, not editor-preference. But we can leave it _, just confusing to have a function called _ imho.

**Comment by LaChal** [comment]
Fixed :)
