### ISSUE TITLE
Filter Issue

### ISSUE THREAD

**Issue by Azounstone** [Khroki/MCEdit-Unified#434]
When clicking filter it generates these two error messages which I reported before but as part of another ticket.

![image1](https://cloud.githubusercontent.com/assets/9461336/7577599/04c0095c-f842-11e4-96e5-dce7c2c7ee0c.jpg)

![image2](https://cloud.githubusercontent.com/assets/9461336/7577601/11bc9b84-f842-11e4-9ee6-3ac877dca207.jpg)

Just wanted to make sure that this got fixed?

**Comment by TrazLander** [comment]
I'll let @Rubisk confirm and close this, but ya should be. We're TRYING to finalize a release but it's a big one and the bugs have been endless.

**Comment by Rubisk** [comment]
Fixed already.
