### ISSUE TITLE
Crashes when binding key to "Fast Nudge" in zh-CN & zh-TW

### ISSUE THREAD

**Issue by fhfuih** [Khroki/MCEdit-Unified#435]
Yes, it's very similar to #418. I mentioned it in a pull request but it seems not a good idea...I also change some details here.

MCEdit crashes when pressing "Assign Key..." button to set keybind to "Fast Nudge"(only this function). But this time only Simplified Chinese and Traditional Chinese are affected, while Korean is fine. I checked translation files and there's no error. 
Latest dev. version hasn't fixed this bug. Only tested in Windows

mcedit.log:
https://gist.github.com/fhfuih/fd9734d9d7ad8c2ff2f9

console:
![default](https://cloud.githubusercontent.com/assets/11222265/8567821/fe181cb2-259a-11e5-9361-82d46f4208a5.PNG)

**Comment by LaChal** [comment]
The issue is closed, but other strings may be concerned.

Everything seem to be allright for the translated strings, but not for the untransleted.
We are currently patching the code to avoid this in the future.
