### ISSUE TITLE
A few strings not included in translation template

### ISSUE THREAD

**Issue by fhfuih** [Khroki/MCEdit-Unified#445]
I made a collection of all strings not included in the translation file. This may be helpful but is not very important. After all, most strings are translated.
*Note that I didn't add any trailing spaces. The string may need to be adjusted afterwards.*

- CB Panel(Double-click on a CB)
  - Edit Command Block
  - Command:
  - Custom Name:
  - Track Output

- Chest panel
  - Slot
  - Slot:
  - ID/ID Name
  - ID/ID Name:
  - Unknown Item
  - DMG
  - DMG:
  - Count:
  - New Item (1.7+)
  - Delete This Item
  - Delete All Instances Of This Item From World

**Suggest: Delete ": ", only use word without colon.**
**(Currently using colon before input areas, w/o colon in chart header)**
**"Count"(w/o colon) is already included in trn**

- CB COMMANDS in selection tool
  - No command blocks found

- Analyse in selection tool
  - Analysis

- spawn
  - Click to set the spawn position.

*Below are strings included in trn but not implemented*

- World Info
  - Randomseed:

**"Randomseed"(w/o colon) shouldn't be translated. It's an NBT tag.**

*Below are some other minor suggestions related to strings*
- Currently using "[RECOMMENDED]" in REGENERATE UUID, but "(Not Recommended)" in SESSION LOCK. unify the brackets and cases may look better.
- Currently using "Keep data intact" in Fill/Replace, but it only works in Replace mode. Someone can add "replace only" to the hovertext.

**Comment by LaChal** [comment]
Thank you for the report.

I was also tracking the missing translations, and will continue before pushing an update.
You'l be informed when it'll be done :)

Concerning "Randomseed" (without colon), it is not present in the teranslations, AFAIK. And I'v remarked that the correct syntax for NBT data is "RandomSeed".
By the wat, the NBT tags (and more generaly everything in a tree widget) aren't sent to the translation functions ;)

Concerning "Keep data intact" not working in fill mode, it was a bug...

Finaly, we'll have a look to harmonize some strings.

**Comment by fhfuih** [comment]
"Click to set the spawn position." Is not included. I just moved it out of "not implemented" subtitle.

**Comment by LaChal** [comment]
The missing strings has been added int hte latest translation update (https://github.com/Khroki/MCEdit-Unified/commit/5ec4cdd2f3facd2b6c277a2b13fdd10aee085fec).  
  
If you find more missing strings, just reopen this issue and report!

**Comment by fhfuih** [comment]
Ok. Thank you! :)

**Comment by fhfuih** [comment]
I found some more missing strings:

- Deleting the item 'item name' from the entire world('number' chunks)
- WARNING: You are about to modify the entire world. This cannot be undone. Really delete all copies of this item from all land, chests, furnaces, dispensers, dropped items, item-containing tiles, and player inventories in the world?

Concerning string harmonization, string632 "Damage" & string864 "DMG" can be unified.

Besides, I want to know...
what is a Blocks-Only/Fast Increment modifier, 
what is button 3,
what does "No key means right click to fast nudge." mean.

**Comment by fhfuih** [comment]
reopen

**Comment by fhfuih** [comment]
open

**Comment by fhfuih** [comment]
open #445

**Comment by fhfuih** [comment]
reopen #445

**Comment by LaChal** [comment]
Thank you for the report :)

Button 3 is the mouse middle button.
"No key means right click for fast nudge" means the if no key is defined for this action, holding the right mouse button will permit to move a selection point or face or the whole selection (or an imported/copied object) to be moved faster.  
  
The "Fast increment modifier" is used in the numerical fields to increment the value faster.

**Comment by TrazLander** [comment]
Blocks-Only Modifier:
E = Rotate schematic
Alt+E = Rotate all the blocks in the schematic (without rotating the schematic)

**Comment by fhfuih** [comment]
Got it! Thank you guys, it helps me a lot to understand the software!

**Comment by fhfuih** [comment]
@LaChal Please consider add "(hold)" to "Fast increment modifier".
There are 2 Mega Spruce Taiga(o461 & 462. o462 has a trailing whitespace). The latter one should be Mega Spruce Taiga Hills.

BTW, I can't figure out how exactly "Snap clone to axis" works.

**Comment by LaChal** [comment]
@fhfuih: with "" do you mean an empty string?
  
Since a modifier can only be Ctrl, Alt or Shift, it seem obious to hold these keys to modify something. But your remark is good since the other modifier keys contain this "(hold)".

Concerning the string 462, it will be corrected.  

For now, feel free to add the correct translations to the erroneous strings. They will be corrected later.

"Snap clone to axis" is used when clicking a face of a cloned object and dragging it. It makes the clone to move only on the axis you first moved it, until you release the "Snap clone to axis" key.
"Swap axes looking down", like the tooltip says (string 158), inverts the forward and backward keys whe the camera looks down.

**Comment by fhfuih** [comment]
@LaChal the empty"" was meant to be'<toolbar>'. I made a typo.

**Comment by fhfuih** [comment]
"Toolbar" with a pair of <
