### ISSUE TITLE
Correcting String Formatting

### ISSUE THREAD

**Issue by LaChal** [Khroki/MCEdit-Unified#451]
The string formatting using the `.format()` function need to be checked and changed.  
  
It will be performed one file a time. 71 occurences have been found in 18 files (for now). It may take time to analyze and correct :)  
  
Help is welcome. The task is not hard, but tedious.
It consists in adding a single character (`u`) in front of each string which is sent to `_()` and uses `.format()`.
E.g.: `_("The fancy word is: {0}.").format(the_fancy_word)` have to be changed to: `_(u"The fancy word is: {0}.").format(the_fancy_word)`. Notice the `u` between the first `(` and `"`.

**Comment by codewarrior0** [comment]
This is a waste of time. Instead, change `_()` to decode its argument to `unicode` if it a `str`.

**Comment by LaChal** [comment]
This is currently studied.

Thank you for pointing this (in another place we know both ;))
