### ISSUE TITLE
Enhancement of sign, spawner, chest function

### ISSUE THREAD

**Issue by fhfuih** [Khroki/MCEdit-Unified#454]
**Double Click Sign panel:**
- Choose a color code doesn't show immediately on the text line. You must enter or delete something in the same line to make the newly-added color code update.
- Can't support some "Advanced" input methods, like "Alt+167" to enter "§".

**Double Click Spawner panel:**
- Add "OK"&"Cancel" Button for custom spawner ID input area. Or simply add a string "Press Enter to confirm. Press ESC to cancel."
- Can't open a spawner with no entity ID. (For example, spawners that are freshly generated by brush tool)

**Chest panel:**
- "DMG" can be set to negative. The negative value are recognized as their absolute value. A value limit seems necessary, just like how you deal with "Repeat" in clone tool. Besides, if an item has DMG `0~x` and you set it to `-(x+1)`, there will be an error `List out of range`, and that chest cannot be open again, returning the same error. "DMG" can be set  to +∞ without error, though.

**Comment by OniOniOn-** [comment]
This might be the last issue before 1.4.0.0

**Comment by fhfuih** [comment]
Well, lemme tell you a frightening story, MCPE 0.12 alpha is out. XD

**Comment by Podshot** [comment]
Don't worry, we are ready

**Comment by LaChal** [comment]
The quotation mark in every line has been fixed in the latest dev version. It shall not appear anymore.  

Concerning the copy/paste issue, it looks like key binding related.

A commit has been pushed concerning this crash, @fhfuih (and anyone willing), would you mind to test?

**Comment by fhfuih** [comment]
Sorry, I'm out traveling now. I can't use my computer until August 3rd.😶

**Comment by fhfuih** [comment]
Just tested & revised this issue. @LaChal  @Podshot (or anyone else :P)

**Comment by Khroki** [comment]
I think the bug parts of this were fixed a while ago, closing. Please reopen if any part of this is still a problem or still needs doing.

**Comment by fhfuih** [comment]
Eh, I think I should re-open issues for still-existing bugs. I had stuffed many bugs in one issue and I should have done specifically.

**Comment by Khroki** [comment]
Your new issues are a lot clearer, thanks for taking the time to repost those bugs.
