### ISSUE TITLE
Some blocks don't show up correctly

### ISSUE THREAD

**Issue by billym357** [Khroki/MCEdit-Unified#464]
Can't see path blocks, Fence post aren't connected (Not sure if that's normal), Half slabs are shown as full blocks. Can't open 0.12.1 maps for mcpe.

**Comment by naor2013** [comment]
I don't know about all of them but we wrote in the "known issues" that we don't support 0.12 MCPE yet
We'll add it in the next release

**Comment by L3ice** [comment]
Please make a report for each issue.
Also you did not provide any information from a log.

**Comment by L3ice** [comment]
>Can't see path blocks

@OniOniOn- 
>Fence post aren't connected (Not sure if that's normal)

I think thats normal.

>Half slabs are shown as full blocks

What thats weird.
A screenshot and world download would help.
>Can't open 0.12.1 maps for mcpe

From @LaChal :
Can you, please, provide the `mcedit.log` file? It shall be in MCEdit folder, and contains more information.
If, for understandable privacy reason, you don't want to send personal information, just open the file in a text editor and replace the things you don't want to expose (a good old Notepad will do the job :) ).
In this case, we ask you to tell us if there's special/accented/non english characters in the replaced parts.

**Comment by billym357** [comment]
The map I was using is from Minecraft Pocket Edition 0.11.1.  http://www.mediafire.com/download/h5jvpq1g5xmrg62/April_30_2015.zip

https://i.imgur.com/B41LSKc.png The dark brown blocks above the glowstone are suppose to be half slabs. The roof is also suppose to be half slabs.

https://i.imgur.com/e7itpNp.png The birch blocks are suppose to be slabs.

I don't see a log file in document/mcedit. I tried opening the 12.1 world again and still nothing happens.

In the console it says "IndexError(string index out of range",)

**Comment by OniOniOn-** [comment]
I did something, it might do something.

**Comment by L3ice** [comment]
I found the issue.
So there is the [materials.py](https://github.com/Khroki/MCEdit-Unified/blob/master/pymclevel/materials.py)
There are:
-alphaMaterials = normal Minecraft
-classicMaterials = classic Edition of Minecraft
-indevMaterials = indev Edition of Minecraft
-pocketMaterials = Pocket Edition of  Minecraft

You have to add the new IDs to the list in pocketMaterials.

**Comment by Khroki** [comment]
If someone with pocket wouldn't mind adding the missing IDs that would be great, none of the main developers own pocket edition.

**Comment by billym357** [comment]
[The block and item ID's can be found on this page](http://minecraft.gamepedia.com/Pocket_Edition_data_values#Block_IDsl)

**Comment by L3ice** [comment]
PR from @ShinkoNet #606 should fix this :pray:
