### ISSUE TITLE
Apply for software repost in domestic website

### ISSUE THREAD

**Issue by fhfuih** [Khroki/MCEdit-Unified#465]
@Khroki  Can I repost this software in a Chinese domestic Minecraft forum(mcbbs.net) and offer a self-uploaded download link? I will specify original contributors and sites, as well as any other information needed.

**Comment by Rubisk** [comment]
Why not just post a link through our release/download instead? Remember of that if a new version comes out, you should keep it updated otherwise.

**Comment by fhfuih** [comment]
@Rubisk Yes, I have to update it. But many people don't understand English. And it's not fast and convenient to access exotic sites in China due to network censorship. Downloading is even slower.

**Comment by Khroki** [comment]
That's fine, as long as you provide a link back to the official site somewhere.

**Comment by fhfuih** [comment]
close #465

**Comment by fhfuih** [comment]
Thanks :p
