### ISSUE TITLE
IndexError on loading MC: Win10 maps.

### ISSUE THREAD

**Issue by D3thw0lf** [Khroki/MCEdit-Unified#466]
[   ERROR][                  root.py:1601]:Failed to load file C:\Users\myname\AppData\Local\Packages\Microsoft.MinecraftUWP_somenumbershere\LocalState\games\com.mojang\minecraftWorlds\nbEBALjoAQA=: IndexError('string index out of range',)

This also happens when I copy the map "nbEBALjoAQA=" into the mcedit Folder and try open it from there. :)

I hope someone can explain me if I did something wrong or if this is a Problem with MCedit Unified.

Version used: 1.4.0.0 x64

**Comment by LaChal** [comment]
Can you, please, provide the `mcedit.log` file? It shall be in MCEdit folder, and contains more information.

If, for understandable privacy reason, you don't want to send personal information, just open the file in a text editor and replace the things you don't want to expose (a good old Notepad will do the job :) ).
In this case, we ask you to tell us if there's special/accented/non english characters in the replaced parts.

> I hope someone can explain me if I did something wrong or if this is a Problem with MCedit Unified.

If you did not tweak MineCraft or MCEdit, you did not do anything wrong. This can be related to many causes...
  
Note that modded worlds are not supported in MCEdit for now.

**Comment by L3ice** [comment]
Same issue here.
Log:
http://pastebin.com/jjJC7xwA

**Comment by Rubisk** [comment]
Could you please provide a download-link to a not working file?

**Comment by L3ice** [comment]
https://www.dropbox.com/sh/hynj1gs3ey9b5ll/AAD3fMFis6JpLmzZyA800XZ6a?dl=0

**Comment by D3thw0lf** [comment]
Fix not working for me. :(

Here's my logfile:
http://pastebin.com/FyXGjtcf

**Comment by Rubisk** [comment]
You have to wait for a new release to swe tge changes. To check them now you can consider running from source if you have a valid python install. Check the readme for info on how to do so.

**Comment by D3thw0lf** [comment]
I've added your fix with Notepad++ on my own (so I was updated)

**Comment by L3ice** [comment]
I also added the code manually and it did not fix it.
Does the compiled version make difference?

**Comment by Rubisk** [comment]
Don't mess with the files in pymclevel from the build, most of them aren't even used by the executable it seems.

If you want to test, checkout the repo using git, setup a python environment and check it out that way instead.
