### ISSUE TITLE
translation string 183 broken down

### ISSUE THREAD

**Issue by fhfuih** [Khroki/MCEdit-Unified#472]
string 183 is not working in every language.
![default](https://cloud.githubusercontent.com/assets/11222265/9289083/763f8194-4396-11e5-8976-b2750d58de05.png)
![default](https://cloud.githubusercontent.com/assets/11222265/9289084/7685bc18-4396-11e5-8cef-26968c7e02e7.png)

Besides, if no key is set to fast nudge apart from right click, it will say "None to nudge a greater distance", which is weird.

**Comment by LaChal** [comment]
The string is missreferenced in the translation resources.
