### ISSUE TITLE
Error reading chunk: NBT Stream too short.

### ISSUE THREAD

**Issue by L3ice** [Khroki/MCEdit-Unified#473]
I opened this 0.11 PE world: https://www.dropbox.com/sh/gwyvhwj79axr5zi/AACcwOPc-0CK7Y7_K0-qdUUFa?dl=0
And I get these errors as I fly arround:
http://pastebin.com/PQAAfJjm

**Comment by Khroki** [comment]
Anyone tested this?

**Comment by Khroki** [comment]
Closing this as a duplicate of https://github.com/Khroki/MCEdit-Unified/issues/568 We will post further updates there. Thanks for the world though.
