### ISSUE TITLE
An error has occured float division zero

### ISSUE THREAD

**Issue by IBllade** [Khroki/MCEdit-Unified#474]
I am copieng something about 20 blocks tall and 20 sides and when I click the copy MCedit crashes.

**Comment by OniOniOn-** [comment]
log log log read guidelines!!!

**Comment by Rubisk** [comment]
https://github.com/Khroki/MCEdit-Unified/blob/master/CONTRIBUTING.md

**Comment by naor2013** [comment]
If you won't give us more info, we'll have to close the issue
What OS are you using? Is that a PC or MCPE map? send us the log please

**Comment by Khroki** [comment]
No response for 20 days, sorry, can't fix it without a crash report.
