### ISSUE TITLE
All textures turn white (Potentially due to a filter)

### ISSUE THREAD

**Issue by gentlegiantJGC** [Khroki/MCEdit-Unified#476]
Like I said I have no idea what exactly is causing this other than it has done it a few times and every time it has done it has been while I am running a filter I am making. There is no crash report or anything because mcedit is still fully functional after just the blocks are all white. 
The whole log if that is of any use. http://pastebin.com/Kc2LqpLK
If there is any more that I can give you just say

![2015-08-17 10-13-26-pm](https://cloud.githubusercontent.com/assets/11940194/9316708/a20ed45c-452e-11e5-86b4-e2574920410c.png)

**Comment by Rubisk** [comment]
If you're running a filter, it'd be nice to share the filter too. 
First guess would be you're messing with the materials object of level.

**Comment by gentlegiantJGC** [comment]
You can but it is over 1000 lines long. All I am doing with it is extracting a schematic duplicating said schematic and messing with them then adding a schematic to the clipboard.

**Comment by gentlegiantJGC** [comment]
The only thing that I am doing that is odd is setting a block id in the schematic of either 65530 or 65529 if the block is empty but I am then just discarding the schematics. They are not getting written to the world. I will do some debugging to try and work out exactly what is causing this and then get back to you

**Comment by gentlegiantJGC** [comment]
Further testing: It doesn't do that every time the filter is run just sometimes (using the same selection)

**Comment by gentlegiantJGC** [comment]
I have narrowed it down to duplicating the schematic with the copy.deepcopy() method. It may not be that specifically but I have a 7 line script that replicates it on my end. I need to run it a varying number of times for it to reproduce the issue so try it a good 20 times to make sure

https://www.dropbox.com/s/ie1eaum04ofh6hp/temp_whitetexture.py?dl=0

**Comment by codewarrior0** [comment]
`copy.deepcopy()` would duplicate the schematic, and also schematic.materials, schematic.materials.textureAtlas, schematic.materials.textureAtlas.texture, schematic.materials.textureAtlas.texture.textureID....

Basically nothing in MCEdit is really prepared to be `deepcopy`'d.

**Comment by gentlegiantJGC** [comment]
ah right ok then. How would one go about duplicating a schematic without that?

**Comment by codewarrior0** [comment]
Export it to another schematic?

**Comment by gentlegiantJGC** [comment]
Ok thanks. This can probably have the bug tag remove then

**Comment by Rubisk** [comment]
We could maybe, someday, add a warning/exception when people try this. Closing for now though.
