### ISSUE TITLE
Problems with "Find" filter & "Setbiome" filter

### ISSUE THREAD

**Issue by fhfuih** [Khroki/MCEdit-Unified#479]
- **Find**
  -  In "Match tag type", "Any"(string 369) seems like a string argument itself. That means if "Any" is translated into other languages, for example, "任何" in Chinese, the filter will not understand what to do with "任何". It only understand "Any" and directly read this argument from translation strings.
![1](https://cloud.githubusercontent.com/assets/11222265/9322508/b375fbf8-45a6-11e5-82a9-c9a108ff3d2b.png)
(P.S. `\u4efb\u4f55` equals "任何". )
EDIT: I think this bug involves every option in this slidebar, but "Any" is the only one to be translated.
Another Edit: I found the same bug in external filter "Modify Item Strings". It seems that many filters may have the same bug as well. Probably it's better to do some MCEdit-side tweaks to help filters translate instead of adjusting filters themselves?

  -  "Find Next" is deleted, so the last line in the Documentation can be deleted, too.
![3](https://cloud.githubusercontent.com/assets/11222265/9322567/862e8074-45a7-11e5-9c21-612be2201004.png)

- **Setbiome**
o462 is "Mega Spruce Taiga "(with a trailing whitespace) and it should be "Mega Spruce Taiga Hills". 
![2](https://cloud.githubusercontent.com/assets/11222265/9322561/794e61b2-45a7-11e5-97d6-4384210f53b4.png)

**Comment by fhfuih** [comment]
"Mega Spruce Taiga Hills" is done now.

About the filter translation, some filter **doesn't** have this issue. For example Decliff and Create Shop. Now I'm totally confused :(

**Comment by LaChal** [comment]
I've remarked that some filters seem bugged with some GUI widgets (especially the dropdown lists).
We'll have a look to this.
