### ISSUE TITLE
Program to Window Sizing

### ISSUE THREAD

**Issue by brandond1999** [Khroki/MCEdit-Unified#480]
Sizing of program is too big for my fullscreen window size, making it so I can only see half of the bottom toolbar and not all of the left side, and doesn't change to the correct size even after restarting the program. I can't even adjust the window size on my own, as there's no way to drag the corners to resize as it's in a fullscreen mode and I don't see any option to make it windowed.. Any help? 
![screenshot 4611686018427388021](https://cloud.githubusercontent.com/assets/13863033/9348759/20fcab9a-4601-11e5-9690-192e7020480f.png)

**Comment by Khroki** [comment]
Have you tried using the alt+spacebar menu to resize/move the window? If that ends up still not being small enough what is your resolution? It defaults to 1152x864, but can be resized to as low as 1000x700.

**Comment by brandond1999** [comment]
Yes, nothing comes up with that either, even though that works on other fullscreen applications

**Comment by Khroki** [comment]
Wait, mcedit doesn't have a fullscreen mode, what resolution is your monitor?

**Comment by Khroki** [comment]
No information, closing, reopen if you have more details.
