### ISSUE TITLE
MCEdit crashes on startup

### ISSUE THREAD

**Issue by MulverineX** [Khroki/MCEdit-Unified#481]
So I open up MCEdit and it tells me there's a new update so I close
out mcedit and delete its files then go to mcedit.net download the
latest realease version and when I extract it and start mcedit it
crashes on startup

Log:

[ INFO][ config.py:36]:Loading config...
[ DEBUG][ config.py:194]:Property Change: Settings hiddable ores = [7, 16, 15, 21, 73, 14, 56, 153]
[ DEBUG][ config.py:194]:Property Change: Settings Recent Worlds = ['']
[ DEBUG][ config.py:194]:Property Change: Selection Colors white = (1.0, 1.0, 1.0)
[ DEBUG][ config.py:194]:Property Change: Selection Colors blue = (0.75, 0.75, 1.0)
[ DEBUG][ config.py:194]:Property Change: Selection Colors green = (0.75, 1.0, 0.75)
[ DEBUG][ config.py:194]:Property Change: Selection Colors red = (1.0, 0.75, 0.75)
[ DEBUG][ config.py:194]:Property Change: Selection Colors teal = (0.75, 1.0, 1.0)
[ DEBUG][ config.py:194]:Property Change: Selection Colors pink = (1.0, 0.75, 1.0)
[ DEBUG][ config.py:194]:Property Change: Selection Colors yellow = (1.0, 1.0, 0.75)
[ DEBUG][ config.py:194]:Property Change: Selection Colors grey = (0.6, 0.6, 0.6)
[ DEBUG][ config.py:194]:Property Change: Selection Colors black = (0.0, 0.0, 0.0)
[ INFO][OpenGL.acceleratesupport.py:17]:No OpenGL_accelerate module loaded: No module named OpenGL_accelerate
[ INFO][ pymclevel.materials.py:199]:Loading block info from <_io.BytesIO object at 0x0857A120>
[ DEBUG][ pymclevel.materials.py:201]:Trying YAML CLoader
[ DEBUG][ pymclevel.materials.py:204]:CLoader not preset, falling back to Python YAML
[ INFO][ pymclevel.materials.py:199]:Loading block info from <_io.BytesIO object at 0x0857A120>
[ DEBUG][ pymclevel.materials.py:201]:Trying YAML CLoader
[ DEBUG][ pymclevel.materials.py:204]:CLoader not preset, falling back to Python YAML
[ INFO][ pymclevel.materials.py:199]:Loading block info from <_io.BytesIO object at 0x0857A120>
[ DEBUG][ pymclevel.materials.py:201]:Trying YAML CLoader
[ DEBUG][ pymclevel.materials.py:204]:CLoader not preset, falling back to Python YAML
[ INFO][ pymclevel.materials.py:199]:Loading block info from <_io.BytesIO object at 0x0857A120>
[ DEBUG][ pymclevel.materials.py:201]:Trying YAML CLoader
[ DEBUG][ pymclevel.materials.py:204]:CLoader not preset, falling back to Python YAML

**Comment by Khroki** [comment]
Hmm, not seeing an error here, could you run mcedit from the command line to get an error? (Make sure the prompt is set to the right folder before running)

**Comment by naor2013** [comment]
If you won't send us the log, we can't help you, please send it here or I'll have to close the issue
If you don't know how to do, tell us

**Comment by Khroki** [comment]
Closing for now, if you're still having problems reopen it. Just not enough information.
