### ISSUE TITLE
Mc edit doesn't open

### ISSUE THREAD

**Issue by tmacc22** [Khroki/MCEdit-Unified#484]
what version of windows does mc edit support

**Comment by Khroki** [comment]
It should work on XP SP3 through Windows 10. If you can get us a log we may be able to figure out the problem assuming you're not on XP SP1 or 98 or somesuch.

**Comment by tmacc22** [comment]
im using windows 10

**Comment by naor2013** [comment]
Can you please find the log that describes the issue? We can't help without knowing what caused it to close

**Comment by Khroki** [comment]
If you're still having problems with this reopen it, there's not enough info to work on at the moment.
