### ISSUE TITLE
Map it! filter doesn't work for 1.7.10

### ISSUE THREAD

**Issue by WhiteObama** [Khroki/MCEdit-Unified#490]
The title say it all, map it! filter doesn't seem to work for 1.7.10 version. When I use my Map it! and log in to my work in 1.8 it  work fine but when I log in in 1.7.10 all the map disappear and only leave the item frame behind.
Any of you guys know the problem of this issue and what cause it? like the filter or the mcedit version?
Or maybe another filter similar to the Map it! filter is find, too
Thanks in advance:)

**Comment by codewarrior0** [comment]
This is a Minecraft issue. You can't go backwards from a 1.8 world to a 1.7 world. The item format was changed.

**Comment by Podshot** [comment]
That is an issue with the Minecraft updates, it's not MCEdit or the filters fault

**Comment by WhiteObama** [comment]
so is there a way to fix it?

**Comment by Podshot** [comment]
MCEdit-Unified supports any Anvil type world, so you don't need to downgrade. If you're not opening the world in 1.8 before opening it in 1.7.10, then it is a filter issue, which can only be fixed by the filter creator

**Comment by WhiteObama** [comment]
Well the world i'm talking about was created in 1.7.10 and always used in 1.7.10 and I have never done anything 1.8 to it, but it still isn't working, is this still the filter issue that can only be fixed by the creator?

**Comment by Podshot** [comment]
Yes
