### ISSUE TITLE
Crash when you scroll down the Control setting in dev

### ISSUE THREAD

**Issue by fhfuih** [Khroki/MCEdit-Unified#493]
When I scroll the Control settings list, it crashes on reaching the Fast Increment line (the 4th line in <Misc>), returning the log below:
![1](https://cloud.githubusercontent.com/assets/11222265/9653720/2725b832-5258-11e5-9f81-27e346e8d7a5.PNG)
![2](https://cloud.githubusercontent.com/assets/11222265/9653719/2723f29a-5258-11e5-8dc7-bca4b5fb58f2.PNG)
![3](https://cloud.githubusercontent.com/assets/11222265/9653721/272b3b54-5258-11e5-8b73-264d848b794f.PNG)

**Comment by LaChal** [comment]
Allright. I'm guilty. Something I did not tested before pushing...
