### ISSUE TITLE
Converting Map-Format?

### ISSUE THREAD

**Issue by D3thw0lf** [Khroki/MCEdit-Unified#498]
Sorry I just don't know how else I can ask this and you guys are helpful since I landed here...Is there a way to convert the map-format from levelDB to mcregion or anvil with mcedit unified or do you know any Tools that can handle this? 

I hope you can help me even if this is not an issue with anything. :3

Thanks in advance (btw. a Forum would be great)

**Comment by Podshot** [comment]
Export the LevelDB world as a schematic, then go to an anvil format world (it can just be filled with air) and then import your previously exported schematic.

**Comment by D3thw0lf** [comment]
Oh okay...I'll try that. Please let this open so I can edit/answer if I have another question related to this. Would be great. thanks :3

**Comment by Khroki** [comment]
if you could screenshot weird, please reopen this so we can investigate.
