### ISSUE TITLE
Error during save: Chunk not Present

### ISSUE THREAD

**Issue by AliffanI** [Khroki/MCEdit-Unified#500]
Minecraft PE 0.12.1 Worlds
MCEdit 1.4.0.1
Windows 10
No Mods Installed
Attachments:
Log 1 http://gist.github.com/AliffanI/08141eaa3d7a40df93f9
Log 2 http://gist.github.com/AliffanI/ed7262740921cbdadf0b

I Can't save MCPE Worlds in my client. It shows the following error:
![screenshot 2](https://cloud.githubusercontent.com/assets/14256409/9835343/c6ba1d56-5a10-11e5-9861-6cc5c4fd9704.png)

When i tried to save changes on a PE world, mcedit is processing world lighting (i guess), and then the error message popped up. As you may see in log 1 (http://gist.github.com/AliffanI/08141eaa3d7a40df93f9), I successfully saved a schematic, but not the mcpe world. First i think, it is only that world had this problem. Turns out, all my pe worlds are not saveable. Re copied all of them, redownloaded mcedit, still no luck.

I thought, the changes was incompatible with a pe world. But as you may see in Log 2 (http://gist.github.com/AliffanI/ed7262740921cbdadf0b), i tried to save the world without changes. same error has appeared.

If needed to reproduce the error, it is really simple:

1. Open a minecraft pe world.
2. Save the world
3. Error appears.

I know Minecraft PE is not fully supported yet, so this issue is FYI only. Any help would be appreciated.

**Comment by naor2013** [comment]
We still didn't test with 0.12
Can you send us your maps?

**Comment by AliffanI** [comment]
Here is the map. https://drive.google.com/file/d/0BxdEcB486ii_UGlYMnl4U2xuNU0/view?usp=docslist_api

**Comment by AliffanI** [comment]
Wait, i am dumb. I accidentally sent an empty folder... :P Here is the actual file.https://drive.google.com/file/d/0BxdEcB486ii_LWUwUGlJajFOZVU/view?usp=docslist_api

**Comment by OniOniOn-** [comment]
Also other issues: Map generator randomly changes(superflat, infinite, old), map seed resets to 0

**Comment by AliffanI** [comment]
Okay, minecraft pe 0.12.1 is out like a month ago. Should'nt this issue get discussed?

**Comment by Khroki** [comment]
Rubisk has been busy with other stuff and hasn't been available to improve pocket support, sorry.

**Comment by AliffanI** [comment]
Can i downgrade the map first in 0.11 then edit it? Would that be possible?

**Comment by jose-vm** [comment]
I didn't had this issue when porting PE worlds

The only one I had was that some random stone blocks appeared in lines like if I was in the Farlands.

**Comment by AliffanI** [comment]
still waiting...
0.14.0 is out btw.
i also downloaded MCE 1.5.0.1
still happens

**Comment by AliffanI** [comment]
I have just found out something!

I pressed Ctrl+A in Camera View after Chunk View,
and somehow i've discovered that the actual PE world is outside of the normal world in the corner:
![screenshot 39](https://cloud.githubusercontent.com/assets/14256409/13195267/bce307ea-d7e0-11e5-984b-49d4afcd62fc.png)
![screenshot 40](https://cloud.githubusercontent.com/assets/14256409/13195268/bce32b62-d7e0-11e5-93eb-f9d0741cfca4.png)
I think that "Chunk Not Present" error is because the world itself is outside somehow...

I tried to save, lighting calculation begins:
![screenshot 41](https://cloud.githubusercontent.com/assets/14256409/13195342/2077121e-d7e2-11e5-80b2-028b7d7f0935.png)
but the same thing worked:
![screenshot 42](https://cloud.githubusercontent.com/assets/14256409/13195351/7a094450-d7e2-11e5-9fd4-b147db744c11.png)

I really hoped this would help for the troubleshooting.

**Comment by Rubisk** [comment]
Heya,

So, I don't have MCPE or Win10 edition, which makes debugging this quite tough.
The patch notes mention: "Better ordering on chunk scheduling."
Together with you finding the chunks in the wrong spot, I *think* there's something wrong with the function calculating the coordinates. (https://github.com/Khroki/MCEdit-Unified/blob/master/pymclevel/leveldbpocket.py#L163).

Could you (or someone with win10) do something for me?

Please go into the world, and write down the coordinates of the chunks you're at. Then, go into MCEdit. Press [0] to bring up the debug menu, fly over to where it's rendering the chunks, and find the coordinates of this spot.

**Comment by AliffanI** [comment]
Every coordinate in PE and MCEdit seems to be the same.
![quickmemo _2016-02-23-18-04-07](https://cloud.githubusercontent.com/assets/14256409/13249757/b2956452-da58-11e5-8129-5b82035f10e8.png)
![screenshot 44](https://cloud.githubusercontent.com/assets/14256409/13249989/e7f91b7e-da59-11e5-878e-70be747a4b10.png)

I think the function 'calculating the coordinates' has no error. But somehow, the function 'save file' still thinks that the first chunk is in the coordinate of:

**X=2036427888, Y=845116005**

and it will always be that exact coordinate.
The Z coordinate is even undefinable:

<pymclevel.leveldbpocket.PocketLeveldbDatabase object at **0x00000000110B6F28**>
the context in **bold** above is variative (changes when a different world is loaded, loading the same world results difference)

I hope these informations are helping.
Thanks.

**Comment by Rubisk** [comment]
Yeah those coords were created by nether chunks, I disabled nether chunks for now, will need to fix that and implement a nether somehow I guess.

**Comment by AliffanI** [comment]
Could i be because of i haven't created nether chunks yet?

**Comment by Rubisk** [comment]
Nononono.

The code was interpreting nether chunks as chunks with huge coordinates. It now ignores those chunks instead ;-)

**Comment by AliffanI** [comment]
Oh no....

This still happens in 1.5.1.0

![screenshot 49](https://cloud.githubusercontent.com/assets/14256409/13721323/773374e8-e855-11e5-8007-e2ba11ac8259.png)

it looks like, we need further troubleshooting...

**Comment by Khroki** [comment]
A new version hasn't been released yet since the fix was applied, people are still working on other things before it's ready.

**Comment by AliffanI** [comment]
Ah, i see. I'll wait for it! Thanks Khroki for letting me know :) .   I was misdirected by the changelog "fixed key error on pocket worlds" :P

**Comment by Khroki** [comment]
Yeah that was relating to block IDs missing, pocket doesn't have the unknown block fallback regular worlds do.

**Comment by AliffanI** [comment]
Hi, i see in 1.5.2.0, there is the bugfix of this problem. But there is a notice saying:

POCKET SUPPORT IS BROKEN IN THIS BUILD. PLEASE USE 1.5.1.0 TO EDIT POCKET EDITION WORLDS UNTIL FURTHER NOTICE.

So... I still can't use it?

**Comment by naor2013** [comment]
It was fixed but we have some issue with the windows version, we'll release a fixing version probably tomorrow or in the next few days

**Comment by AliffanI** [comment]
Ok, great to hear that! Thank you!

**Comment by AliffanI** [comment]
I've updated to 1.5.2.1, loading the world seems fine.

The original error is not occuring any longer. But a new error takes place:
![screenshot 51](https://cloud.githubusercontent.com/assets/14256409/14639058/a8f2c916-0664-11e6-944f-6acdaf448da1.png)

After saving once, editing entities are not a problem.
But editing blocks seems to be impossible while 'saving' is taking place.
![screenshot 52](https://cloud.githubusercontent.com/assets/14256409/14639138/11b1ee82-0665-11e6-9d0b-f563d9b2d8c1.png)
Editing blocks before the first save does no difference.

Is this going to be another pain in the neck?
I hope not...

**Comment by naor2013** [comment]
It's already fixed

**Comment by AliffanI** [comment]
In this update?

**Comment by naor2013** [comment]
For the next one

**Comment by AliffanI** [comment]
Wow that was fast... Thank you naor2013!
