### ISSUE TITLE
NBTEdit filter hovertext doesn't show properly

### ISSUE THREAD

**Issue by fhfuih** [Khroki/MCEdit-Unified#501]
It returns Entities, TileEntities, and TileTicks after I click "filter". It says double-click to go to this item, but nothing happened as I double-click on each label. 

**EDIT**: See comment below about this bug.

**Comment by LaChal** [comment]
The fact is there's a bug here.
The popup saying "Double-click to go to this item." is shown when the mouse is over the widget containing the results:
![img0009](https://cloud.githubusercontent.com/assets/7809746/9975739/90983d64-5ec7-11e5-890a-b6ba25ceee33.png)

It shall be visible only when hovering elements that can be double-cliked to be reached.
<br>

<hr>
The widget actualy works.
Click on the bullet on the left of the elements to deploy them:
![img0010](https://cloud.githubusercontent.com/assets/7809746/9975742/9c1c8ba4-5ec7-11e5-817b-03972fc7846c.png)


Then, if you double-click on one sub-element, the camera will focus it:
![img0011](https://cloud.githubusercontent.com/assets/7809746/9975763/44a94b90-5ec8-11e5-8a6f-766678ae65f8.png)

**Comment by fhfuih** [comment]
I see... I'll test it later!

**Comment by fhfuih** [comment]
Yes, it do works as you say. But I guess I'd better keep this issue since the hovertext is not showing properly.

**Comment by LaChal** [comment]
You're right.

I'm currently working on.
