### ISSUE TITLE
Plz Help: No downloads

### ISSUE THREAD

**Issue by MulverineX** [Khroki/MCEdit-Unified#503]
I got a mirror for a old(laggy) 2.0 copy but I want to use the 1.0 but the download is gone

**Comment by Khroki** [comment]
Releases are on the release page, alternatively there's a link to the 1.0 homepage on both mcedit.net and the top of this repo's main page. For pre-unified versions see the link on the 1.0 homepage for old releases.

**Comment by MulverineX** [comment]
THERE IS NO DOWNLOAD
