### ISSUE TITLE
How to open world via FTP

### ISSUE THREAD

**Issue by BAILANDO** [Khroki/MCEdit-Unified#516]
Hello, im using MCEdit long time, it's best editor, but i need to try load my server world via FTP, i see FTP Upload when i editing a world, but how to download it first? Thanks for help :) :+1:

**Comment by naor2013** [comment]
I don't exactly remember but I think it's in the "Load" menu, there's an option to download from FTP
Please tell me if you find it

**Comment by BAILANDO** [comment]
Hello, thanks for fast answer, in Open menu i can select only local world, with quick load cnat load world because i using official MultiMC not .minecraft folder. When i make Windows FTP in Explorer and select level.dat from FTP connection, then mcedit give me an error.
![mcedit1](https://cloud.githubusercontent.com/assets/11508622/10664754/14b305c6-78c6-11e5-8552-77d11f8b067a.png)
![mcedit2](https://cloud.githubusercontent.com/assets/11508622/10664757/14b6fafa-78c6-11e5-9b82-8d7f5d353221.png)
![mcedit3ftp](https://cloud.githubusercontent.com/assets/11508622/10664755/14b3e48c-78c6-11e5-9a99-6515b0106fff.png)
![mcedit4ftp](https://cloud.githubusercontent.com/assets/11508622/10664758/14b740f0-78c6-11e5-9268-ece57c3fd89b.png)
![mcedit5ftp](https://cloud.githubusercontent.com/assets/11508622/10664756/14b630c0-78c6-11e5-87c7-e74532a2dac5.png)

**Comment by naor2013** [comment]
When you click "Quick Load", you can see from there the option "From FTP Server"

**Comment by BAILANDO** [comment]
Yea i got it :) i must add one save from multimc to see this menu, but small question, is possible to load custom world which i add extra and load using MutliVerse addon for example? :) i got world, nether, end and my event world

**Comment by naor2013** [comment]
I don't really understand the question? Can you try to explain it better maybe?

**Comment by BAILANDO** [comment]
I have 5 worlds (testovaci is on screen too) but in mcedit i see only 3 worlds (Classic survival worlds) and dimensio 13 is 'dont now what', it's created when i 'Go To' to the player, maybe world 'Testovaci' is empty, cuz MCEdit ask me to create chunks. But my world eventworld is not listed here :/

![mceditworlds](https://cloud.githubusercontent.com/assets/11508622/10665373/ff8da732-78ca-11e5-8b1d-da3976b54a05.png)
![mceditworlds1](https://cloud.githubusercontent.com/assets/11508622/10665374/ff901850-78ca-11e5-9ef3-6f199e828411.png)

**Comment by naor2013** [comment]
Can you please send me the world file?
What worlds should appear there?

**Comment by BAILANDO** [comment]
All survival worlds appear normally, world, world_nether and world_the_end, but my own world not. Here is file:
http://leteckaposta.cz/905453112

**Comment by Khroki** [comment]
if you want to open the event world file you need to use the open... function and navigate to the level.dat inside to open it, it won't show as a dimension in the map labelled world because it's not stored that way, they're all stored as separate maps and the plugin access them all independently from my understanding. sorry this is so late. Reopen if you still have problems.
