### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Hunter5204** [Khroki/MCEdit-Unified#517]
When ever i try to export it it says this and then it crashes
MCEdit version: 2.0.0alpha-823
Python version: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-post2012Server-6.3.9600
Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.4
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True

Driver info:
GL_VERSION: 4.4.0 (4, 4)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce GTX 760/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "out00-PYZ.pyz\mcedit2.editorsession", line 825, in export (self is a EditorSession)
  File "out00-PYZ.pyz\mceditlib.worldeditor", line 805, in exportSchematicIter (self is a WorldEditorDimension)
AttributeError: 'NoneType' object has no attribute 'size'

**Comment by LaChal** [comment]
Sorry, but I close this issue.

You are on MCEdit-Unified GitHub.
MCEdit 2 is [there](https://github.com/mcedit/mcedit2) :)
