### ISSUE TITLE
Server Generated Worlds Cannot Be Loaded

### ISSUE THREAD

**Issue by StanleyMines** [Khroki/MCEdit-Unified#522]
I have generated a world with the server and when I try to load into MCEdit it doesn't work. I tried logging in to the world and then try MCEdit and it doesn't work. Any version on any device that I have doesn't seem to work with the work. When I try to open it, it says: 
"
I don't know how to open /Users/Stanley.../world/level.dat:

OSError(20, 'Not a directory')
"
https://www.dropbox.com/s/ffadk8kslvspv91/Screenshot%202015-10-31%2000.25.47.png?dl=0

I tried deleting all ##MCEDIT.TEMP## files from all the folders within the world, and it still didn't work after that.

**Comment by LaChal** [comment]
This message says that the `level.dat` file is not a directory, which is quite obvious...

How do you try to open the world?

If you open it with `Quick Load` or from a FTP server, MCEdit waits for a folder, not a file. But, opening worls these ways don't allow people to explores filders and subfolders...
Using `Open` let you choose a `level.dat` file.

By the way, if you're not using MCEdit-Unified 1.4.0.1, you may want to update...

**Comment by LaChal** [comment]
Hmmm...
Which server did you use to create the world?
Do you or the srever use mods? (This is a source of uncompatibility in MCEdit actualy...)

What happens if you open the faulty `level.dat` with the internal NBT Explorer? (*)
<br>
<hr>
Technicaly, `level.dat` is a file containing nested objects. For this reason, we can display its content like a folder tree.
If you open a world in MCEdit and use the internal NBT Explorer you'll be able to access to the `level.dat` structure through a tree too :wink:
<br><br><hr>(*) Open a working world (or create a dummy one) and click on the righmost icon in the toolbar. In the panel select open. You'll be able to select a `.dat` file to be displayed in the explorer.

**Comment by StanleyMines** [comment]
Yes true...
World was generated in 15w42a(or somewhere around there)
Was able to access the world before, I think after the 15w44a snapshot, I wasn't able to.

**Comment by LaChal** [comment]
Looks like the latest 1.9 snapshot causes issues...

Can you host this world on some file share, so we can test it?

**Comment by StanleyMines** [comment]
It is the world for a public server, so I would prefer not. I will see if I can get another one generated, so I can post it here. Thanks!

**Comment by StanleyMines** [comment]
![screenshot 2015-11-11 20 26 13](https://cloud.githubusercontent.com/assets/4878558/11110795/677c8198-88b5-11e5-91ac-5f30dab7edba.png)


Still not working.


level.dat file; set most playerdata info to 0 to prevent cheating on the server.
https://www.dropbox.com/s/5ha3qf85bmi8zxr/level%20copy.dat?dl=0

**Comment by StanleyMines** [comment]
My Computer:


Java: 1.6.0_65 64 bit
MacBook Pro(2012): OS X 10.8.5
Memory: 8 GB 1600 MHz DDR3
CPU: 8x Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
Python 2.7.2 ([GCC 4.2.1 Compatible Apple Clang 4.0 (tags/Apple/clang-418.0.60)] on darwin)

**Comment by LaChal** [comment]
Thank you for the file.

I just tested the `level.dat` by loading it in an existing world using the internal NBT explorer, and all went well. No error.
I also created a new world and replaced the `level.dat` by yours. All the same.

By the way, when you use `Open` to load a world, there must be some folders beside the `.dat` file. Without these folders (at least `region`), the world can't be loaded...

**Comment by StanleyMines** [comment]
Could it make a difference that my world is 600 MB large?

**Comment by StanleyMines** [comment]
ls *:
`level copy.dat	level.dat	level.dat_old	players		session.lock

DIM-1:
players	region

DIM1:
players	region

data:
EndCity.dat		Temple.dat		map_1.dat		map_14.dat		map_2.dat		map_7.dat		scoreboard2.dat
Fortress.dat		Village.dat		map_10.dat		map_15.dat		map_3.dat		map_8.dat		villages.dat
Mineshaft.dat		idcounts.dat		map_11.dat		map_16.dat		map_4.dat		map_9.dat		villages_end.dat
Monument.dat		loot_tables		map_12.dat		map_17.dat		map_5.dat		scoreboard OLD.dat	villages_nether.dat
Stronghold.dat		map_0.dat		map_13.dat		map_18.dat		map_6.dat		scoreboard.dat

playerdata:
01b5a906-19e7-4229-98bd-43e0a37dceb2.dat	38b8a067-7523-4fc8-aeba-a3f53a39f649.dat	916785f8-49d0-4c3c-b396-d9fe56ef5ac2.dat	c95d9ade-2e45-4970-9c84-a98911a86da5.dat
08a6de5c-99b2-4db5-9d73-06fa3d138ab8.dat	3b03b010-e27b-455c-af79-f73cfece0316.dat	920b4da1-4779-4a3b-a99b-904b9bb5e83c.dat	d1c40ad6-af7b-48a6-8b78-a48e0f8a306e.dat
0b7f8b0d-e9cb-4e80-b7c7-81be2379b45a.dat	3c8be686-5119-4fbc-be47-19628f26759a.dat	9be4e7b0-d209-4fd4-8131-a1c51d163624.dat	d60547bd-83d4-41f4-bc91-9151385ea527.dat
0b936815-dbd7-4b81-9cec-6fd206b721eb.dat	3ea6b123-adde-4552-8e34-187b4fe25707.dat	9cc1929f-7267-4078-a220-45be5eebb0fd.dat	dbde4787-1252-49b1-afa0-756bec472d8c.dat
0c4665b0-1fa8-494c-b7e0-bf4951446089.dat	44bcc4cc-f45b-4342-9246-9413fa440418.dat	a2e16b75-90cb-4674-8781-76a865a90019.dat	e152e0b3-34f8-4add-8f4f-b673643f13f8.dat
0d98d433-b163-48e1-9787-1f262a87553a.dat	477af77f-938b-41e2-b8a6-14bd62232a37.dat	a308fa80-3103-490d-b1e8-b901d7093f21.dat	e1efdcb3-267b-4524-96bb-553f7267e34a.dat
0e62d3c8-39af-4a78-940b-dbe7dc7f9869.dat	4fd01ff3-f8ab-4503-b361-7a60e3185a33.dat	a4d2496d-9ae2-49b0-a55e-7f4767e02c8f.dat	e290cf96-3b3f-4937-9dd9-aa24e6916c94.dat
10ac6f28-362a-4584-848a-a5fe1fd7f618.dat	5679e0cc-a402-42d6-b450-3183d8e1bcd7.dat	a5e4e672-dc97-4f50-a10d-3f109522d7c2.dat	e4056907-f1de-4238-b760-0cbca7e6951d.dat
152d0485-0499-4cf4-b6e3-4f4385a19bae.dat	5ad84e98-f74d-407c-a936-1727b13171b4.dat	b20334b1-19a1-4b31-a684-4ea8e8f531fd.dat	e4892c4f-94bf-4aa2-9571-aa48d2bb4c52.dat
15c5d032-75b9-41bc-9c00-cdaba936dbf5.dat	5c7b35a5-45c3-4ce9-9225-21cbfdf8cc2e.dat	b2811617-cf64-4724-91dc-971c11f49b9e.dat	e834cb13-7fa4-4fcb-8256-404d7b0126e7.dat
16357689-e66e-4b98-a104-080810c24a55.dat	676d177e-a116-4a41-8ed4-63914733b767.dat	b4937d1a-a909-489f-94a8-d8ea0d62e949.dat	e94b8b2a-ccb9-4e59-b256-e2ea77515b1a.dat
18dda7b5-c28b-4d99-8c79-3bff16dfdab8.dat	6eebddbd-15f3-4b7e-8a64-fbded59e43ed.dat	b5b0a76c-7266-49bf-bf5d-1a9ddf6eaf39.dat	f3fe8e91-1702-402e-8423-c0d1c7eea7ef.dat
26969e72-09a5-4f3a-b79e-64346421bd76.dat	704e2751-ea73-4e6e-9f94-8c00d89fbc1a.dat	b938b0c2-72e7-4c49-adb1-e73535ba8a71.dat	f78bf7e9-709b-4901-acb1-efa94f299d4c.dat
288658b8-3de5-4595-bcba-72efe344263c.dat	73a45e29-2068-4b9b-af8f-7fe8bf24028c.dat	bb4450a5-de60-4e70-b2d8-aad8c0baba09.dat	f9cf6e2c-6903-4b7e-afc1-040b464d71c5.dat
37511755-3f6b-4690-8dfd-8c60dcbb6733.dat	7aac15af-095d-4cb9-9d17-2ca077620d35.dat	c3eb3a69-8d05-4b52-90f6-ac93502573d7.dat	fca6c819-997d-4f8b-82c1-cfcf2b0bab4d.dat

region:
r.-1.-1.mca	r.-1.5.mca	r.-2.3.mca	r.-3.1.mca	r.-4.0.mca	r.-5.5.mca	r.0.0.mca	r.1.-4.mca	r.2.-2.mca	r.3.-3.mca	r.3.5.mca	r.5.-3.mca
r.-1.-2.mca	r.-2.-1.mca	r.-2.4.mca	r.-3.2.mca	r.-4.1.mca	r.-6.-1.mca	r.0.1.mca	r.1.-5.mca	r.2.-3.mca	r.3.-4.mca	r.4.-1.mca	r.5.-4.mca
r.-1.-3.mca	r.-2.-2.mca	r.-2.5.mca	r.-3.3.mca	r.-4.3.mca	r.-6.-2.mca	r.0.2.mca	r.1.0.mca	r.2.-4.mca	r.3.-5.mca	r.4.-2.mca	r.5.0.mca
r.-1.-4.mca	r.-2.-3.mca	r.-3.-1.mca	r.-3.4.mca	r.-4.4.mca	r.-6.-3.mca	r.0.3.mca	r.1.1.mca	r.2.-6.mca	r.3.-6.mca	r.4.-3.mca	r.5.1.mca
r.-1.0.mca	r.-2.-4.mca	r.-3.-2.mca	r.-3.5.mca	r.-4.5.mca	r.0.-1.mca	r.0.4.mca	r.1.2.mca	r.2.0.mca	r.3.0.mca	r.4.-4.mca	r.5.2.mca
r.-1.1.mca	r.-2.-5.mca	r.-3.-3.mca	r.-3.6.mca	r.-4.6.mca	r.0.-2.mca	r.0.5.mca	r.1.3.mca	r.2.1.mca	r.3.1.mca	r.4.1.mca	r.5.4.mca
r.-1.2.mca	r.-2.0.mca	r.-3.-4.mca	r.-4.-1.mca	r.-5.-2.mca	r.0.-3.mca	r.1.-1.mca	r.1.4.mca	r.2.2.mca	r.3.2.mca	r.4.2.mca
r.-1.3.mca	r.-2.1.mca	r.-3.-5.mca	r.-4.-2.mca	r.-5.-4.mca	r.0.-4.mca	r.1.-2.mca	r.1.5.mca	r.2.3.mca	r.3.3.mca	r.5.-1.mca
r.-1.4.mca	r.-2.2.mca	r.-3.0.mca	r.-4.-3.mca	r.-5.-6.mca	r.0.-5.mca	r.1.-3.mca	r.2.-1.mca	r.3.-2.mca	r.3.4.mca	r.5.-2.mca

stats:
01b5a906-19e7-4229-98bd-43e0a37dceb2.json	38b8a067-7523-4fc8-aeba-a3f53a39f649.json	916785f8-49d0-4c3c-b396-d9fe56ef5ac2.json	c95d9ade-2e45-4970-9c84-a98911a86da5.json
08a6de5c-99b2-4db5-9d73-06fa3d138ab8.json	3b03b010-e27b-455c-af79-f73cfece0316.json	920b4da1-4779-4a3b-a99b-904b9bb5e83c.json	d1c40ad6-af7b-48a6-8b78-a48e0f8a306e.json
0b7f8b0d-e9cb-4e80-b7c7-81be2379b45a.json	3c8be686-5119-4fbc-be47-19628f26759a.json	9be4e7b0-d209-4fd4-8131-a1c51d163624.json	d60547bd-83d4-41f4-bc91-9151385ea527.json
0b936815-dbd7-4b81-9cec-6fd206b721eb.json	3ea6b123-adde-4552-8e34-187b4fe25707.json	9cc1929f-7267-4078-a220-45be5eebb0fd.json	dbde4787-1252-49b1-afa0-756bec472d8c.json
0c4665b0-1fa8-494c-b7e0-bf4951446089.json	44bcc4cc-f45b-4342-9246-9413fa440418.json	a2e16b75-90cb-4674-8781-76a865a90019.json	e152e0b3-34f8-4add-8f4f-b673643f13f8.json
0d98d433-b163-48e1-9787-1f262a87553a.json	477af77f-938b-41e2-b8a6-14bd62232a37.json	a308fa80-3103-490d-b1e8-b901d7093f21.json	e1efdcb3-267b-4524-96bb-553f7267e34a.json
0e62d3c8-39af-4a78-940b-dbe7dc7f9869.json	4fd01ff3-f8ab-4503-b361-7a60e3185a33.json	a4d2496d-9ae2-49b0-a55e-7f4767e02c8f.json	e290cf96-3b3f-4937-9dd9-aa24e6916c94.json
10ac6f28-362a-4584-848a-a5fe1fd7f618.json	5679e0cc-a402-42d6-b450-3183d8e1bcd7.json	a5e4e672-dc97-4f50-a10d-3f109522d7c2.json	e4056907-f1de-4238-b760-0cbca7e6951d.json
152d0485-0499-4cf4-b6e3-4f4385a19bae.json	5ad84e98-f74d-407c-a936-1727b13171b4.json	b20334b1-19a1-4b31-a684-4ea8e8f531fd.json	e4892c4f-94bf-4aa2-9571-aa48d2bb4c52.json
15c5d032-75b9-41bc-9c00-cdaba936dbf5.json	5c7b35a5-45c3-4ce9-9225-21cbfdf8cc2e.json	b2811617-cf64-4724-91dc-971c11f49b9e.json	e834cb13-7fa4-4fcb-8256-404d7b0126e7.json
16357689-e66e-4b98-a104-080810c24a55.json	676d177e-a116-4a41-8ed4-63914733b767.json	b4937d1a-a909-489f-94a8-d8ea0d62e949.json	e94b8b2a-ccb9-4e59-b256-e2ea77515b1a.json
18dda7b5-c28b-4d99-8c79-3bff16dfdab8.json	6eebddbd-15f3-4b7e-8a64-fbded59e43ed.json	b5b0a76c-7266-49bf-bf5d-1a9ddf6eaf39.json	f3fe8e91-1702-402e-8423-c0d1c7eea7ef.json
26969e72-09a5-4f3a-b79e-64346421bd76.json	704e2751-ea73-4e6e-9f94-8c00d89fbc1a.json	b938b0c2-72e7-4c49-adb1-e73535ba8a71.json	f78bf7e9-709b-4901-acb1-efa94f299d4c.json
288658b8-3de5-4595-bcba-72efe344263c.json	73a45e29-2068-4b9b-af8f-7fe8bf24028c.json	bb4450a5-de60-4e70-b2d8-aad8c0baba09.json	f9cf6e2c-6903-4b7e-afc1-040b464d71c5.json
37511755-3f6b-4690-8dfd-8c60dcbb6733.json	7aac15af-095d-4cb9-9d17-2ca077620d35.json	c3eb3a69-8d05-4b52-90f6-ac93502573d7.json	fca6c819-997d-4f8b-82c1-cfcf2b0bab4d.json`


du -hs *:
` 38M	DIM-1
199M	DIM1
1.4M	data
4.0K	level copy.dat
4.0K	level.dat
4.0K	level.dat_old
240K	playerdata
  0B	players
249M	region
4.0K	session.lock
492K	stats`

**Comment by Podshot** [comment]
> Could it make a difference that my world is 488 MB large?

Yes, that would be a very big difference. We need the exact world file to replicate this, since it's hard to create a world file that big and still fill it with relevant data to this issue.

**Comment by codewarrior0** [comment]
When MCEdit produces the `OSError(20, 'Not a directory')` error, check your Console app for the error traceback, and post it here.

**Comment by StanleyMines** [comment]
will do.

**Comment by StanleyMines** [comment]
Sorry it took me 22 days, I haven't been that free.
I hope this will do.


`
Stanleys-MacBook-Pro:~ Stanley$ /Users/Stanley/Desktop/MCEdit.app/Contents/MacOS/mcedit
Running in fixed install mode. MCEdit-schematics and mcedit.ini are in your Documents folder.
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of /Users/Stanley/Library/Application Support/pymclevel/ServerJarStorage named with the server's version number
Cached servers:  [u'Release 1.5.2']
/Users/Stanley/Desktop/MCEdit.app/MCEdit-0.1.7.1.macosx-10_6-x86_64/MCEdit.app/Contents/Resources/mcedit.py:1094: RuntimeWarning: use scrap: No module named scrap
(ImportError: No module named scrap)
[ WARNING][                  root.py:1096]:PyGame clipboard integration disabled.
[   ERROR][                  root.py:1921]:Wasn't able to open a file {file => /Users/Stanley/Dropbox/Minecraft/HyperEclipse/servers/main/world/level.dat}
Traceback (most recent call last):
  File "leveleditor.pyo", line 1918, in loadFile
  File "pymclevel/mclevel.pyo", line 215, in fromFile
  File "pymclevel/infiniteworld.pyo", line 1067, in __init__
OSError: [Errno 20] Not a directory: '/Users/Stanley/Dropbox/Minecraft/HyperEclipse/servers/main/world/players'
`

**Comment by StanleyMines** [comment]
Based on last two lines, I looked at the "players" file, and it was a file named "players" with nothing in it and a size of 0 bytes.

**Comment by StanleyMines** [comment]
file deleted, world openable, can't move though...

**Comment by LaChal** [comment]
Nice to read you can open the world now.

What do you mean with "can't move though"?

**Comment by StanleyMines** [comment]
its like I have a speed of 0. I press w,s,a,d,z,q,shift,space,c nothing can move my POV.

**Comment by LaChal** [comment]
You can't move the camera in MCEdit, right?

**Comment by Khroki** [comment]
Try resetting your keybinds and see if it helps.

**Comment by StanleyMines** [comment]
Yes; Nope, didnt work; I just downloaded a newer version and its working in that version...
Version where I cant move (anymore, used to be able to): 0.1.7.1 64bit mac
I guess thats kinda old, since i just got the 1.4.0.1 mac. :P

**Comment by LaChal** [comment]
Indeed, very old MCEdit version...

Closing this issue now :smile:

**Comment by StanleyMines** [comment]
it still has a few features that the new ones dont have so I still use that half the time... I cant move other than switching between chunk and camera view to move(chunk zooming in and out) Oh well though. There are work arounds in the new ones. (Ill post what it was that I liked about the older ones somewhere)
