### ISSUE TITLE
LevelDB World Crash

### ISSUE THREAD

**Issue by jose-vm** [Khroki/MCEdit-Unified#523]
When in Chunk View mode when opening a MCPE LevelDB world, if you select some chunks. MCEdit crashes.

**Comment by Monkey0x9** [comment]
Please provide more information, as described here: https://github.com/Khroki/MCEdit-Unified/blob/master/CONTRIBUTING.md. If you don't provide enough information we can't help you.

**Comment by LaChal** [comment]
There's a bug in the last release which make MCEdit crash when you try to select non-existant chunks.
This bug is fixed and won't happen in the next release.

Please, provide the console content. This will help us to know what happens.

**Comment by jose-vm** [comment]
@LaChal Thanks

**Comment by jose-vm** [comment]
Here's the crashlog: http://prntscr.com/90ogz7
couldn't get it in a file, sorry

**Comment by LaChal** [comment]
@jose-vm: that's the bug which had been fixed in the next release.
Anyway, thank you for the report :smile:
