### ISSUE TITLE
Some blocks don't turn correctly when cloned

### ISSUE THREAD

**Issue by MaxMatti** [Khroki/MCEdit-Unified#528]
I used MCEdit's clone tool (hotbar slot 3) to clone a few redstone machines and encountered some weird/unexpected behaviour:
When using rotate (E) or mirror (G) some blocks are not properly turned aka the orientation in their metadata is not changed as expected.
This issue might affect more functions or blocks than I encountered, I only found the following affected blocks:
* Trapped Chests
* Redstone Powered Hoppers
* Redstone Powered Stairs

Minecraft: 1.8 with Forge+Liteloader
MCEdit: window-title says "Unified v1.4.0.1 for Minecraft 1.8/1.9"
OS: Linux Mint 17.1 Rebecca, Kernel: 3.13.0-37-generic

**Comment by LaChal** [comment]
I've made few simple tests with stairs and hoppers ebove a redstone torch, and they were correctly rotated/mirrored: their orientation is visually changed in MCEdit and in the game, and their data is updated too (Alt key when pointing the block in MCEdit).

But concerning the trapped chest, I confirm what you say.
<br>
<hr>
My tests aren't complete... Please, give me more details about how these blocks are powered.

**Comment by LaChal** [comment]
Woops...

**Comment by MaxMatti** [comment]
Should I upload the schematic file of what I tried to clone? If yes I can do so in a few hours when I'm home.

**Comment by LaChal** [comment]
It'll be interesting to have a look at it, indded.

**Comment by MaxMatti** [comment]
Sorry, totally forgot.
schematic download-link: http://www.file-upload.net/download-11054210/CompactSorterBox.schematic.html

**Comment by LaChal** [comment]
Thanks for the file.
I'll study this and see if we can solve this issue for the next release.
