### ISSUE TITLE
What's the .schematic file format?

### ISSUE THREAD

**Issue by TropicSapling** [Khroki/MCEdit-Unified#530]
This is not an issue, it's a question, but since I wasn't sure where to post it I posted it here:

**Can anyone explain how the .schematic file works?** I'm working on a program that can import .schematic files into minecraft worlds or servers while they're on, using vanilla minecraft cmds (/setblock), but I can't do that without reading the .schematic file. And I have no idea how the schematic file works, when opened in Notepad++ it just shows strange characters and all the information I got is just the very basic file format from Minecraft Wiki but **I need to know exactly how it works.**

Thanks :)

(Yes I know about WorldEdit but I want to be able to edit worlds/servers from all newer Minecraft versions, including snapshots, so that's not an option)

**Comment by LaChal** [comment]
Basicaly, `.schemtic` files contain NBT data.

Look here for the exact structure: http://minecraft.gamepedia.com/Schematic_file_format

**Comment by TropicSapling** [comment]
@LaChal "...**all the information I got is just the very basic file format from Minecraft Wiki**..."
I already know that. What I meant was more specific information. If you can't explain it, could you atleast tell me how to open the file as text and not as MCEdit? If that's not possible, can I use a filter to make the program?

**Comment by LaChal** [comment]
The data is not stored as text in `.schemetic` files.

You'll have to write (or reuse) the needed code. You can find several libraries for this, written in Java, Python, C/C++ and many other languages, I guess.

Look at [nbt.py](https://github.com/Khroki/MCEdit-Unified/blob/master/pymclevel/nbt.py) on this repo to have a Pure Python NBT implementation examlpe.

**Comment by TropicSapling** [comment]
@LaChal Ok thanks :)

**Comment by LaChal** [comment]
Your're welcome!
