### ISSUE TITLE
MCEdit crashes on launch. never used to do this

### ISSUE THREAD

**Issue by TheD0ct0r101** [Khroki/MCEdit-Unified#531]
MCEdit Version: 1.4.0.1
Issue: When i click the application, the cmd prompt comes up as normal, but then it goes grey and a window pops up saying: mcedit.exe has stopped working.
When i click the View problem details arrow at the bottom of this window, it shows the 'error' as follows:
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	mcedit.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5121fefe
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.1.7601.19045
  Fault Module Timestamp:	56259295
  Exception Code:	c00000f1
  Exception Offset:	00000000000bffc2
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	c047
  Additional Information 2:	c047a51cd62bcbc284940babff3afacf
  Additional Information 3:	8409
  Additional Information 4:	8409a4adfb931a807267c83e1f88d764

This never used to happen. I am running 64bit windows. There is no error log printed out that i can find, just the error signature above. Fix this right away (and yes, i have reinstalled this but it didnt work)

**Comment by LaChal** [comment]
Did you tried both 64bit and 32bit MCEdit?

Is there no `.log` file in MCEdit folder at all?

**Comment by TheD0ct0r101** [comment]
Why should i try 32bit? I have a 64bit system and no, there was no log file. The cmd prompt simply stops working and does the windows 'not responding' thing

**Comment by LaChal** [comment]
Badly, I could not find anything relevant with the error information you gave...

Few information about problems with `ntdll.dll` and their solutions:
http://answers.microsoft.com/en-us/ie/forum/ie9-windows_vista/appcrash-fault-module-name-ntdlldll-internet/7aa85ed6-0859-e011-8dfc-68b599b31bf5?tab=question&status=AllReplies#tabs
https://social.technet.microsoft.com/Forums/en-US/bf54372a-8438-4612-9f3c-f3fd22665f32/appcrash-lyncexe-ntdlldll?forum=sfbfr
https://social.technet.microsoft.com/Forums/windows/en-US/bab89f87-1563-40e4-b762-244d5bc08d7f/faulting-application-explorerexe-faulting-module-ntdlldll?forum=itprovistadesktopui

These links are from the result of a `appcrash ntdll.dll` search on http://windows.microsoft.com/en-us/windows/support#1TC=windows-7.

**Comment by Khroki** [comment]
What's the last version that does work, that error is extremely generic so there's not much to gather from it. Also what are your system specs, including CPU, OS, and Video Card.

**Comment by TheD0ct0r101** [comment]
The version i used ive had for a while and simply stopped working. My important pc specs are: CPU: AMD A10-5800k 4x core 3.80ghz. OS: Win7 Ultimate. Video Card: EVGA GTX 960. RAM: 16gb DDR3 1866mhz

**Comment by Khroki** [comment]
What version?

**Comment by Khroki** [comment]
Any news on what version you were on? If it's a recent version we need to explore it more, if it's an old one it might just be good old code rot. Also what antiviruses are involved, and does it run if said antivirus is disabled?

**Comment by TheD0ct0r101** [comment]
i was using a 0.4 or 4.0 version or something like that for a long time, It
was working fine before, but then one day it started crashing for some
reason. And ive always had the same antivirus before and after... I have
tried reinstalling it, but to no avail. Im simply waiting for MCEdit 2
now...

**Comment by Khroki** [comment]
Hmm, 0.1.4 is really really old, well before we started working on the project, still odd it just upped and stopped working. Either way, without confirmation the current release is broken; we can't really help here, especially since the 0.x series used a different compiler.

**Comment by TheD0ct0r101** [comment]
Could you link me to the most stable and latest version you have?

**Comment by Khroki** [comment]
http://khroki.github.io/MCEdit-Unified/ releases are there, latest are at the top. If you can give us a report from the latest version we can see about fixing it.

**Comment by Khroki** [comment]
No response, if you try it and can get an error from the newest version reopen this and post.
