### ISSUE TITLE
I can't fix chunk errors

### ISSUE THREAD

**Issue by RayK22** [Khroki/MCEdit-Unified#532]
My world has been created in minecraft version 1.1 and I am now in 1.8.8 and there are a few chunk errors. I tried deleting the chunks and letting them reload automatically but they regenerate a random ocean chunk. I thought of accessing my backup world from 1.1 and just take the chunk from there and put it in my current world but the world doesn't show up on the list of worlds to load. Any ideas?

**Comment by LaChal** [comment]
You can use the `Open` button to open a file explorer and then select the `level.dat` file in the save folder.

You can also use the `Setbiome` filter to change the biome type.

**Comment by RayK22** [comment]
It says "AssertionError (Pre-Anvil world formates are not supported)"

**Comment by LaChal** [comment]
Hmmm... That's what I guessed. Too old world format.

You can try the second solution I proposed (with your current world, not the 1.1 one), or you can use an older version of MCEdit: https://github.com/mcedit/mcedit/releases.

The pre-release 665 is usable on Windows directly (just uncompress the archive somewhere and run the `.exe`). You can also use a newer one (click the `Show 5 newer tags` text), but you'll have to run from source, and therefore, install Python and the dependencies...

**Comment by Khroki** [comment]
https://github.com/Khroki/mcedit-old/releases?after=0.1.6build315 has 2 builds that directly support pre-anvil, and there are 2 other releases (0.1.6 and 0.1.7) a few pages back from there if you need them.

**Comment by RayK22** [comment]
It worked! Thanks for your help!

**Comment by robske110** [comment]
Could anyone close this issue?
