### ISSUE TITLE
Mcedit2 wont launch (alpha-907)

### ISSUE THREAD

**Issue by AwesomeGunGuy** [Khroki/MCEdit-Unified#534]
Steps to Reproduce: Double click the mcedit2.exe. The prompt comes up and closes very fast after that.
Nothing happens then. It did work before, but it suddenly stopped.
Might have been a system restore or new conflicting program, I dont know. Maybe I am missing some required programs.

MCEdit Version Number:
All (I tried like 10) of the development builds in the download section, but 907 gave me a log file for the first time. Both 64 and 32 bit do this.

Minecraft Version Number:
1.8.8, im using some shaders,

Operating System Version:
Windows 7 64bit.

Log file in the attachment.
[logfile.txt](https://github.com/Khroki/MCEdit-Unified/files/42636/logfile.txt)

**Comment by codewarrior0** [comment]
Does it work if you move the app to your C: drive instead of D: ?

**Comment by codewarrior0** [comment]
It seems like your "Null" device is disabled. Open Device Manager, choose View -> Show hidden devices, and then look under "Non-Plug and Play Devices" for the Null device and make sure it is enabled and running:

![image](https://cloud.githubusercontent.com/assets/307683/11367210/49b3e142-9256-11e5-9db3-3b4b09184155.png)

**Comment by AwesomeGunGuy** [comment]
Thanks for the fast response,
It doens't run on C: too and Null was already enabled.

**Comment by codewarrior0** [comment]
Could you try stopping and starting the Null service?

**Comment by AwesomeGunGuy** [comment]
Sorry for the late reaction,
I tried stopping it, but it wouldn't let me. it tells me that it is running and working correctly though.

Today I had some strange computer issues, alot of blue screens etc, dont know if it is related. But I did some registery fixes and checkdisks, removed temporary files etc. and now mcedit is working too again.

So problem is solved, but I dont know what caused it and how I eventually fixed it.
Thanks for your help.

**Comment by codewarrior0** [comment]
Great news. For future reference, can you tell me what programs you used to check your disk and fix your registry?

**Comment by AwesomeGunGuy** [comment]
I restarted my computer, and it died again :(. can't get it to work again too..
I used CCleaner to delete unused files and registery clean, checkdisk from windows to repair problems, if any on my harddisk. Ram checker utility from microsoft and run a complete virus scan AVG. After a few reboots it suddenly did work again.
But now it won't :(, same log and error as before.

**Comment by Khroki** [comment]
Sounds like a system specific issue, besides this is the MCEdit 1 repo so if you find more info please post it on the mcedit 2 repository. Might want to look into a clean install, this is the kind of issue you could chase for a long time, also I advise against CCleaner, from my experience it has a tendency to break some of window's basic functions from time to time. Especially on non-default /upgrade installs.
