### ISSUE TITLE
McEdit crashes on selecting not loaded or chunks, that don't exist

### ISSUE THREAD

**Issue by robske110** [Khroki/MCEdit-Unified#538]
**I will soon add more information and screenshots**
(This is only tested on MacOSX and i think it's only there)
McEdit1.4.0.1 crashes EVERY time in chunk view, if you try to select chunks, but hovet with your mouse over not generated chunks MCEdit will immediatly crash with an error like ~Mouse pointer not allocated~ (will soon post the log)
This error did not occur in earlier versions

**Comment by LaChal** [comment]
This is a known issue, and is fixed for the next release.

Anyway, thank you for the report :smile:

**Comment by robske110** [comment]
When will the next release release?

**Comment by Podshot** [comment]
> When will the next release release?

Hopefully very soon!
