### ISSUE TITLE
Copy crashes MCEdit (Newest version only)

### ISSUE THREAD

**Issue by AlbertMN** [Khroki/MCEdit-Unified#540]
Title says it all, previous version works, but newest one crashes when I copy anything.

**Comment by Podshot** [comment]
Could you please provide what OS you are using, the steps to reproduce this, and either a screenshot of the console window, your entire `mcedit.log` file, or both.

**Comment by AlbertMN** [comment]
I didn't look much in to it, needed a quick fix so I didn't take tike to take a screenshot or anything

**Comment by robske110** [comment]
Could you provide it now, otherwise we will not be able to help you!

**Comment by AlbertMN** [comment]
mcedit.log http://pastebin.com/ELn9Jedu

**Comment by LaChal** [comment]
This is the MCEdit-Unified issue tracker...

To report an issue concerning MCEdit 2, please see here: https://github.com/mcedit/mcedit2/issues.
