### ISSUE TITLE
Errors in Terminal Window Upon Closing MCEU

### ISSUE THREAD

**Issue by EvilSupahFly** [Khroki/MCEdit-Unified#543]
When I shut down MCEdit on Linux, I see a lot of this in the terminal, though it doesn't seem to impact the use of MCEdit at all.

```
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/subprocess.py", line 1559, in terminate
    self.send_signal(signal.SIGTERM)
  File "/usr/lib/python2.7/subprocess.py", line 1554, in send_signal
    os.kill(self.pid, sig)
OSError: [Errno 3] No such process
```

**Comment by Podshot** [comment]
Hmmm, what do you in MCEdit before this happens? (IE: run a filter, create a world)

**Comment by EvilSupahFly** [comment]
Everything and nothing. Literally. I can open it and close it again having
done nothing and the errors are still there.

**Comment by LaChal** [comment]
MCEdit tries to kill already dead processes.

Nothing critical, but the output is annoying, I confess...

**Comment by EvilSupahFly** [comment]
Ah. So MCEdit is the official editor of The Mining Dead then. Cool.

**Comment by LaChal** [comment]
Nice :smile:

By the way, I think this is the same issue as #286.
And you used the chunk generator...

**Comment by EvilSupahFly** [comment]
So it is! Completely forgot I sunmitted this last year! Sorry for the
duplicate! :-P

**Comment by LaChal** [comment]
No problem :p

We closed the former one, because we could not find a fix at the moment.
The error output is now redirected to the log file (as we can't supress it: it is internal Python stuff) and won't be shown in the terminal anymore.
