### ISSUE TITLE
How to get block at pos when making a filter?

### ISSUE THREAD

**Issue by TropicSapling** [Khroki/MCEdit-Unified#544]
I've decided that instead of making a separate program it would be a lot easier to just make a filter for MCEdit that "turns blocks into cmds" so that you can import buildings into a world by pasting the cmd into the cmd blocks and then running it.

So to "turn blocks into cmds" **I need to know what block is at a certain position inside of the marked box, how do I do that?**

**Comment by Podshot** [comment]
Take a look at the `filterdemo.py` file [here](https://github.com/Khroki/MCEdit-Unified/blob/master/stock-filters/demo/filterdemo.py)

**Comment by TropicSapling** [comment]
Thanks :)
