### ISSUE TITLE
CRASH: Zooming or Selecting chunks (Chunk view)

### ISSUE THREAD

**Issue by StanleyMines** [Khroki/MCEdit-Unified#550]
Info: 
  MCEdit: v1.4.0.1
  OS: Mac OS 10.8.5
  Minecraft v.: 15w51b

While in chunk view:
Zooming(scrolling) while mouse is not over a generated chunk, MCEdit crashes.
When selecting chunks and mouse moves over a chunk that isn't generated it crashes.

Error log (The zooming one): 
"12/30/15 10:23:43.723 AM mcedit[7240]: Running in fixed mode. Support files are in your App Support Folder (Available from the main menu of MCEdit)
12/30/15 10:23:44.064 AM mcedit[7240]: Splash load...
12/30/15 10:23:46.165 AM mcedit[7240]: *** MCEDIT DEBUG: file_dialog: /Users/Stanley/Desktop/mcedit-1.app/Contents/Resources/lib/python2.7/site-packages.zip/albow/file_dialogs.pyc
12/30/15 10:23:46.165 AM mcedit[7240]: *** MCEDIT DEBUG: directory: /Users/Stanley/Desktop/mcedit-1.app/Contents/Resources/lib/python2.7/site-packages.zip/albow
12/30/15 10:23:46.165 AM mcedit[7240]: *** MCEDIT DEBUG: current directory: /Users/Stanley/Desktop/mcedit-1.app/Contents/Resources
12/30/15 10:23:46.283 AM mcedit[7240]: [ WARNING][      pymclevel.BOParser.py:16]:The `bo3.def` file is missing in `/Users/Stanley/Desktop/mcedit-1.app/Contents/Resources`. The BO3 support will not be complete...
12/30/15 10:23:46.332 AM mcedit[7240]: Minecraft_Server.jar storage initialized.
12/30/15 10:23:46.332 AM mcedit[7240]: Each server is stored in a subdirectory of /Users/Stanley/Library/Application Support/pymclevel/ServerJarStorage named with the server's version number
12/30/15 10:23:46.332 AM mcedit[7240]: Cached servers:  [u'Release 1.5.2']
12/30/15 10:24:31.074 AM mcedit[7240]: Shutting down...
12/30/15 10:26:51.139 AM mcedit[7320]: Running in fixed mode. Support files are in your App Support Folder (Available from the main menu of MCEdit)
12/30/15 10:26:51.242 AM mcedit[7320]: Splash load...
12/30/15 10:26:52.983 AM mcedit[7320]: *** MCEDIT DEBUG: file_dialog: /Users/Stanley/Desktop/mcedit-1.app/Contents/Resources/lib/python2.7/site-packages.zip/albow/file_dialogs.pyc
12/30/15 10:26:52.984 AM mcedit[7320]: *** MCEDIT DEBUG: directory: /Users/Stanley/Desktop/mcedit-1.app/Contents/Resources/lib/python2.7/site-packages.zip/albow
12/30/15 10:26:52.984 AM mcedit[7320]: *** MCEDIT DEBUG: current directory: /Users/Stanley/Desktop/mcedit-1.app/Contents/Resources
12/30/15 10:26:53.065 AM mcedit[7320]: [ WARNING][      pymclevel.BOParser.py:16]:The `bo3.def` file is missing in `/Users/Stanley/Desktop/mcedit-1.app/Contents/Resources`. The BO3 support will not be complete...
12/30/15 10:26:53.104 AM mcedit[7320]: Minecraft_Server.jar storage initialized.
12/30/15 10:26:53.104 AM mcedit[7320]: Each server is stored in a subdirectory of /Users/Stanley/Library/Application Support/pymclevel/ServerJarStorage named with the server's version number
12/30/15 10:26:53.104 AM mcedit[7320]: Cached servers:  [u'Release 1.5.2']
12/30/15 10:26:56.089 AM mcedit[7320]: Exception in thread Thread-2:
12/30/15 10:26:56.089 AM mcedit[7320]: Traceback (most recent call last):
12/30/15 10:26:56.089 AM mcedit[7320]:   File "threading.pyc", line 810, in __bootstrap_inner
12/30/15 10:26:56.089 AM mcedit[7320]:   File "threading.pyc", line 763, in run
12/30/15 10:26:56.089 AM mcedit[7320]:   File "/Users/Stanley/Desktop/mcedit-1.app/Contents/Resources/mcedit.py", line 490, in fetch_version
12/30/15 10:26:56.090 AM mcedit[7320]:   File "release.pyc", line 46, in fetch_new_version_info
12/30/15 10:26:56.090 AM mcedit[7320]:   File "urllib2.pyc", line 127, in urlopen
12/30/15 10:26:56.090 AM mcedit[7320]:   File "urllib2.pyc", line 404, in open
12/30/15 10:26:56.090 AM mcedit[7320]:   File "urllib2.pyc", line 422, in _open
12/30/15 10:26:56.090 AM mcedit[7320]:   File "urllib2.pyc", line 382, in _call_chain
12/30/15 10:26:56.090 AM mcedit[7320]:   File "urllib2.pyc", line 1222, in https_open
12/30/15 10:26:56.090 AM mcedit[7320]:   File "urllib2.pyc", line 1184, in do_open
12/30/15 10:26:56.090 AM mcedit[7320]: URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
12/30/15 10:26:56.092 AM mcedit[7320]: An error occurred checking for updates.
12/30/15 10:27:11.223 AM mcedit[7320]: [   ERROR][                   root.py:776]:MCEdit version Unified v1.4.0.1 for Minecraft 1.8/1.9
12/30/15 10:27:11.304 AM mcedit[7320]: Traceback (most recent call last):
12/30/15 10:27:11.304 AM mcedit[7320]:   File "/Users/Stanley/Desktop/mcedit-1.app/Contents/Resources/mcedit.py", line 815, in <module>
12/30/15 10:27:11.304 AM mcedit[7320]:   File "/Users/Stanley/Desktop/mcedit-1.app/Contents/Resources/mcedit.py", line 774, in main
12/30/15 10:27:11.304 AM mcedit[7320]:   File "/Users/Stanley/Desktop/mcedit-1.app/Contents/Resources/mcedit.py", line 629, in main
12/30/15 10:27:11.304 AM mcedit[7320]:   File "albow/root.pyc", line 168, in run
12/30/15 10:27:11.304 AM mcedit[7320]:   File "albow/root.pyc", line 271, in run_modal
12/30/15 10:27:11.304 AM mcedit[7320]:   File "albow/widget.pyc", line 399, in handle_mouse
12/30/15 10:27:11.304 AM mcedit[7320]:   File "albow/widget.pyc", line 481, in call_handler
12/30/15 10:27:11.304 AM mcedit[7320]:   File "viewports/chunk.pyc", line 54, in mouse_down
12/30/15 10:27:11.305 AM mcedit[7320]:   File "viewports/chunk.pyc", line 45, in zoomOut
12/30/15 10:27:11.305 AM mcedit[7320]:   File "viewports/chunk.pyc", line 29, in zoom
12/30/15 10:27:11.305 AM mcedit[7320]: TypeError: 'NoneType' object is not iterable
12/30/15 10:27:11.305 AM mcedit[7320]: Traceback (most recent call last):
12/30/15 10:27:11.325 AM mcedit[7320]:   File "/Users/Stanley/Desktop/mcedit-1.app/Contents/Resources/__boot__.py", line 399, in <module>
12/30/15 10:27:11.325 AM mcedit[7320]:     _run()
12/30/15 10:27:11.325 AM mcedit[7320]:   File "/Users/Stanley/Desktop/mcedit-1.app/Contents/Resources/__boot__.py", line 336, in _run
12/30/15 10:27:11.325 AM mcedit[7320]:     exec(compile(source, path, 'exec'), globals(), globals())
12/30/15 10:27:11.325 AM mcedit[7320]:   File "/Users/Stanley/Desktop/mcedit-1.app/Contents/Resources/mcedit.py", line 824, in <module>
12/30/15 10:27:11.325 AM mcedit[7320]:     raw_input("Press the Enter key to close this window")
12/30/15 10:27:11.326 AM mcedit[7320]: EOFError: EOF when reading a line
12/30/15 10:27:11.326 AM mcedit[7320]: ==================================
12/30/15 10:27:11.326 AM mcedit[7320]: 			  MCEdit has crashed
12/30/15 10:27:11.326 AM mcedit[7320]: ==================================
12/30/15 10:27:11.337 AM mcedit[7320]: mcedit Error
12/30/15 10:27:13.426 AM mcedit[7320]: Press the Enter key to close this window
"

**Comment by naor2013** [comment]
This is fixed for 1.5 which you can download right now

**Comment by StanleyMines** [comment]
Oh. Awesome! :D
