### ISSUE TITLE
Command block text file don't consider new 1.9 command blocks

### ISSUE THREAD

**Issue by EBTheHero** [Khroki/MCEdit-Unified#552]
MCedit version: v1.5.0.0
Minecraft version: 15w51b
Step to reproduce:
-Launch Minecraft in 15w51b or latest
-Create an new world and place in 3 command blocks
-Add some random commands in them
-Change some option so there is 1 normal cmd block, 1 repeating cmd block and 1 chain cmd block
-Close Minecraft and load the world in MCedit
-Select all the command blocks and press "CB command" in the left menu to open a text file with all the commands in it
-Save the file

Now, MCedit will say that there 3 lines and 1 command block. It should be the same and you will not be able to change them.

This issue is caused by MCedit not counting the repeating and chain command blocks. There is 3 lines and 3 command blocks, but MCedit only see the normal command block.

Strange enough, MCedit can read the commands in all type of command block.

**Comment by naor2013** [comment]
It's a known issue, I'll try to fix it for the next release
Thanks for reporting it :)

**Comment by EBTheHero** [comment]
Thanks! And by the way, you should update your download page; you can only download v1.4.x version ;)

Étienne

**Comment by naor2013** [comment]
Fixed for next release + added a way to order the command blocks in the text file based on the chain

**Comment by Podshot** [comment]
> And by the way, you should update your download page; you can only download v1.4.x version ;)
That might be a problem with our caching system. If you could, go into your webbrowser's console, type "localStorage.clear()" press Enter, then type "location.reload()" and press Enter again. That should hopefully fix the problem.

**Comment by EBTheHero** [comment]
Yep! It worked!

You are doing an awesome job!!!!

Étienne
