### ISSUE TITLE
MCedit Crash Pressing Import-ChunkControl-Import

### ISSUE THREAD

**Issue by EBTheHero** [Khroki/MCEdit-Unified#554]
This is a weird crash I've just found:
MCedit version: v1.5.0.0
Minecraft version: 15w51b (but seems not important)

Step to reproduce:
-Launch MCedit (duh...)
-Load an random world
-Click import and select a random schematic
-Click Chunk control
-Click import again
-Notice that MCedit crashed

In the MCedit terminal, it's written
KeyError: 'pop from an empty set'

**Comment by naor2013** [comment]
Already fixed by @Podshot for the next release
Thanks for reporting, though :)
