### ISSUE TITLE
KeyError: 20 when trying to open a Minecraft Pocket Edition v0.13.1 alpha world.

### ISSUE THREAD

**Issue by mjduniverse** [Khroki/MCEdit-Unified#555]
<b>Minecraft Version:</b> Pocket Edition v0.13.1 alpha
<b>MCEdit Version:</b> MCEdit Unified v1.5.0.0
<b>Operating System:</b> For MCEdit: Windows 8.1, and for MCPE: Kindle Fire HD 6 (4th generation)
<b>Mods:</b> None
 
<b>How to reproduce the error:</b>
1. Open Minecraft World. (See attachment.)
2. Error happens. 

<b>Cmd Console:</b> https://gist.github.com/mjduniverse/322f681b6f63a98c4927

<b>Map:</b> [My World--old-old-old-old.zip](https://github.com/Khroki/MCEdit-Unified/files/76452/My.World--old-old-old-old.zip)

**Comment by DomPrice** [comment]
It appears the PE Entities have not been updated for pocket edition yet. Should be a quick fix.

http://minecraft.gamepedia.com/Pocket_Edition_data_values#Entity_IDs

**Comment by naor2013** [comment]
Thanks for the report, will be fixed for next release
