### ISSUE TITLE
Chunk Renderer Fails

### ISSUE THREAD

**Issue by blueForestIcarus** [Khroki/MCEdit-Unified#556]
When chunk view is selected, the fallowing is outputted repeatedly, and the overhead view does not render.

```
Traceback (most recent call last):
  File "/home/bficarus/Downloads/MCEdit-Unified/renderer.py", line 3800, in workOnChunk
    for _ in faceInfoCalculator:
  File "/home/bficarus/Downloads/MCEdit-Unified/renderer.py", line 3781, in calcFacesForChunkRenderer
    for _ in calc:
  File "/home/bficarus/Downloads/MCEdit-Unified/renderer.py", line 383, in calcFaces
    for _ in self.renderer.chunkCalculator.calcFacesForChunkRenderer(self):
  File "/home/bficarus/Downloads/MCEdit-Unified/renderer.py", line 870, in calcFacesForChunkRenderer
    for _ in br.makeChunkVertices(chunk):
  File "/home/bficarus/Downloads/MCEdit-Unified/renderer.py", line 1558, in makeChunkVertices
    flatcolors[..., :3] *= heightfactor[:, numpy.newaxis, numpy.newaxis]
TypeError: Cannot cast ufunc multiply output from dtype('float64') to dtype('uint8') with casting rule 'same_kind'
```

I suspect this has to do with differing numpy versions (pip is sometimes a bit behind the arch repos).

**Comment by blueForestIcarus** [comment]
Replacing               
>flatcolors[..., :3] *= heightfactor[:, numpy.newaxis, numpy.newaxis]
with
>flatcolors[..., :3] = flatcolors[..., :3] * heightfactor[:, numpy.newaxis, numpy.newaxis]
eliminates the error.

This is because numpy has different rules for the * and *= operator. This is probably not the cleanest solution, however I don't know enough about Numpy or your codebase to offer another solution. If someone could figure out how to set the Numpy rule to the proper value ("same_kind" is clearly not what you want.) that would be the safest solution.

**Comment by naor2013** [comment]
It's a known issue since we updated numpy, there are those errors a lot in the code and we fixed a lot of them before release but we missed some of them like this one
Thanks for the report
