### ISSUE TITLE
Error Saving/Relighting Minecraft PE Worlds (KeyError:69)

### ISSUE THREAD

**Issue by DomPrice** [Khroki/MCEdit-Unified#557]
Encountered an additional error "KeyError:69", I believe adding a placeholder for entry 69 into the PocketEntities hash here:

https://github.com/Khroki/MCEdit-Unified/blob/master/pymclevel/entity.py#L646

may bandage the issue. I'm not sure what Minecraft PE is putting there to cause an error. It may be a placeholder for some future mob. Nonetheless, MCEdit is complaining about it.

![relighterror69](https://cloud.githubusercontent.com/assets/857194/12081754/2adb8588-b252-11e5-9ab2-f63f1943a88f.jpg)

You can use my world to debug and test, you should be able to duplicate the errors:

https://www.dropbox.com/s/6bh7yblz7tw4if5/Ignas.zip?dl=0

MCEdit v 1.5.0
MCPE v 0.13.1

**Comment by naor2013** [comment]
Can you send here the console output?
It doesn't look like an entity missing since it's in the relightChunks function but having the full console output would help, thanks :D

**Comment by naor2013** [comment]
Never mind, you were right, it was just a missing not-existing entity
Thanks for the help :)

**Comment by DomPrice** [comment]
No problem! Can't wait for the patched release. I play MCPE a lot, so I'll keep posting any issues I find.
