### ISSUE TITLE
First time using MCEdit & it keeps crashing.

### ISSUE THREAD

**Issue by nessiesmommy** [Khroki/MCEdit-Unified#558]
Hiya, brand new to this program, excited to use it, but can't get it to run. I've tried old & new versions, 32 & 64 and nothing works. I'm on a PC, not sure what other info to give. Any ideas?

Minecraft: 1.8.8
Windows 7, 64 bit

MCEdit version: 2.0.0alpha-919
Python version: 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]
Platform: win32
System version: Windows-7-6.1.7601-SP1
Processor: Intel64 Family 6 Model 15 Stepping 11, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 2.1
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True

Driver info:
GL_VERSION: 2.1.2 (2, 1)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce 9300 GE/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\worldview\worldview.py", line 574, in paintGL (self is a MinimapWorldView)
  File "mcedit2\rendering\scenegraph\rendernode.py", line 261, in renderScene  
  File "mcedit2\rendering\scenegraph\rendernode.py", line 84, in callList (self is a RenderNode)
  File "mcedit2\util\glutils.py", line 165, in call (self is a DisplayList)
AssertionError

**Comment by Khroki** [comment]
This is the repository for the 1.x series of MCEdit, go to https://github.com/mcedit/mcedit2 for support for that version. Note the 2.x series is still in early development and it is generally recommended to use the 1.x series at this time. Downloads for that are at http://khroki.github.io/MCEdit-Unified/ If that errors too please reopen this and post the error.
