### ISSUE TITLE
Add "tag_mcversion" in RELEASE-VERSION.json

### ISSUE THREAD

**Issue by L3ice** [Khroki/MCEdit-Unified#561]
If someone would add a tag for the supported Minecraft version(like ["tag_name"](https://github.com/Khroki/MCEdit-Unified/blob/master/RELEASE-VERSION.json#L3)), we would be able to translate that [string](https://github.com/Khroki/MCEdit-Unified/blob/master/RELEASE-VERSION.json#L2), without retranslate it, everytime the string gets changed.

**Comment by LaChal** [comment]
The title never was part of the translations (by design)...

But, if it's required by translators, we'll make efforts for!

**Comment by Khroki** [comment]
Since there is an issue discussing this suggestion I'm going to close this. Please see the other issue if you want to make any suggestions/ weigh in.
