### ISSUE TITLE
MCEdit won't start up, error

### ISSUE THREAD

**Issue by Pigums** [Khroki/MCEdit-Unified#562]
So, I downloaded mcedit, everything was okay, imported a schematic, saved the world and closed the program. I then realized that I must of done something wrong cause my schematic wasn't showing up on mineways(another program). So I thought to redo it, thinking that I've missed a step in properly pasting a schematic into a world, till this error came up. 

1st error:
http://pastebin.com/hf5UcGmD
Looks like this; http://i.imgur.com/Be9RykG.png

After I click continue, another error pops up with more info
http://pastebin.com/GSTuuhMz

And keeps on going, in an infinite loop. I tried quitting and re-opening, I've tried restarting it, I've also tried re-installing it. Nothing works. 

How can I fix this?

Thanks

**Comment by Podshot** [comment]
That is a mcedit2 error. Please report that [here](https://github.com/mcedit/mcedit2/issues)
