### ISSUE TITLE
Mirroring selections with tripwire hooks in them do not mirror the tripwire hooks.

### ISSUE THREAD

**Issue by inasm** [Khroki/MCEdit-Unified#566]
Rotating seems to be working fine, but mirroring seems to keep the tripwire hooks pointing the same way, making them not be attached to the block they should be.

**Comment by Khroki** [comment]
Hmm, most likely just a missing entry in the rotations file.

**Comment by Khroki** [comment]
Fixed, EW and NS were swapped in the rotation file, will be included in next release.
