### ISSUE TITLE
When renaming the mcedit folder it won't open

### ISSUE THREAD

**Issue by DragonQuiz** [Khroki/MCEdit-Unified#567]
As what the title says I've changed the mcedit folder to MCEdit.v1.5.1.0.Win.64bit and for some reason it won't open. I've done this in the past and mcedit would open.

[![https://gyazo.com/dcfb073a3ddd4ec629c6a89ecb1e1b4f](https://i.gyazo.com/dcfb073a3ddd4ec629c6a89ecb1e1b4f.png)](https://gyazo.com/dcfb073a3ddd4ec629c6a89ecb1e1b4f)

and a gif of when I try to open the program
https://i.gyazo.com/aa43e43dbfb17ec081c47048d44e5096.mp4

**Comment by LaChal** [comment]
Delete the file called 'splash' in the folder where MCEdit can be found. This will fix the issue shown in the .gif.

Can you please report here when done?

Thank you!

**Comment by DragonQuiz** [comment]
Yep it worked for whatever reason. Thanks.
