### ISSUE TITLE
Crashing on start, 2.0.0alpha-921 

### ISSUE THREAD

**Issue by FrozenBeard** [Khroki/MCEdit-Unified#569]
Windows 10
2.0.0alpha-921
Minecraft 1.8.8 with optifine

Download, unzipped and ran, and it crashed.
Creates this log:
http://pastebin.com/AcC6aH3a

**Comment by Khroki** [comment]
This is the 1.x series repository, go to https://github.com/mcedit/mcedit2 for support with the 2.x series.
