### ISSUE TITLE
Error: Float division by zero

### ISSUE THREAD

**Issue by Boefjim** [Khroki/MCEdit-Unified#573]
I'm trying to copy an area of my map, but sometimes when I copy it crashes giving an error like this:

![screenshot 1](https://cloud.githubusercontent.com/assets/16748131/12379870/c898ebdc-bd63-11e5-8822-8ce174c64066.png)

And then I click "OK" and then I need to restart it.
It either happens when I press "copy", but sometimes also when I press "paste"
But, sometimes, it doesn't crash at all, which seems a bit weird...

**Comment by Podshot** [comment]
That is a mcedit2 error. Please report that [here](https://github.com/mcedit/mcedit2/issues)

**Comment by Boefjim** [comment]
Ok, I've posted it there :)
