### ISSUE TITLE
Reuploading world to server causes world to reload from seed

### ISSUE THREAD

**Issue by Skotavus** [Khroki/MCEdit-Unified#575]
Hi, I've recently had issues with using MCEdit 1.5.1 and the previous version - I'm using it on a Resonant Rise 3.2.7.2 instance in Minecraft 1.7.10, and I run Windows 10 64-bit.

Upon downloading my /data, /playerdata, /region and level.dat files from our server, I'm able to go in and edit them normally. However, when I reupload these files AND the newly created session.lock file, I join the world to find the terrain wiped and rebuilt from the seed, thus destroying all the buillds on the server. My inventory is completely intact, but the world is wiped clean.

Any help that you could offer as to where I'm going wrong would be much appreciated.

**Comment by Skotavus** [comment]
I've attempted to reupload all the level.dat and session.lock files from a backup I took prior to downloading for using MCEdit, and it continuously loads me into a reset world - I'm not sure if it's pointing to incorrect region files?
There hasn't been a new world created, all the data and region files should have been put back exactly where they were before.

**Comment by Skotavus** [comment]
Attempted to use MCEdit on a complete world folder, including all dimension and mod folders - reuploaded it all and still no luck, the world still loads from seed.

Not sure if anyone has read this yet, but if anyone knows a possible fix for this I'd be very grateful to hear it.

**Comment by Khroki** [comment]
Hmm, might be a mod conflict, if you just open the world and delete one block or just save after opening it does it still reset on you? If so something in the pack doesn't get resaved properly, especially if forge is using the new name based block ID system as we still use the old numerical ID system.

**Comment by Khroki** [comment]
Also does the server output any errors before regenning the world? We haven't gotten any reports of this happening on non-modded standard MC worlds.

**Comment by Khroki** [comment]
Any news?

**Comment by Skotavus** [comment]
Our server has updated to the latest Resonant Rise version and we've unfortunately had to abandon the old world - so far I haven't had a chance to try repeating the error.

If I bring down all the server files onto my PC and then run the server from there, should that be an OK method of testing if this error occurs again?

**Comment by Khroki** [comment]
That should work, sorry, didn't notice your reply.

**Comment by Khroki** [comment]
Going to guess you've figured it out, if you do get this again just reopen this and provide your server startup log when it regens the world.
