### ISSUE TITLE
No scrollbar in the items list.

### ISSUE THREAD

**Issue by Dushess** [Khroki/MCEdit-Unified#578]
Many changes was occured, but i can't understand this. Yes, here exist search by name, but it's not always convenient. Plus now i should scroll trough all block parts (pistons in all positions, water of all levels, etc.). Founded in version 1.5.0.0 and 1.5.1.0 (just not check earlier)

**Comment by Khroki** [comment]
I don't think there was ever a physical scrollbar, but if it helps page up/down scroll it a lot faster.

**Comment by LaChal** [comment]
Right, there never was any scroll bars, and I confess this feature is (still) missing...

**Comment by LaChal** [comment]
Done in commit 9b9b8f88b5cab516b883c6656a3eb3cc5bcf575b!

**Comment by Dushess** [comment]
That's right, but problem is here again.
1st - I cannot grab scrollbar by mouse in blocks/items list, he's just too small.
and 2nd - he moves with little delay, but this is secondary.
