### ISSUE TITLE
Title Translation

### ISSUE THREAD

**Issue by LaChal** [Khroki/MCEdit-Unified#579]
A very visible string remains untranslated since the origin:
The program window title!

@OniOniOn-, @violine1101, @L3ice, @Neui @MG-5, @vongola12324, @fhfuih, @Monkey0x9, @TropicSapling,

it's actually `MCEdit ~ Unified v1.5.1.0 for Minecraft 1.8/1.9`.
Do you think it shall be translated?
And what about the abbreviations like `MC`, `MCPE`?

Again, thank you all to make MCEdit-Unified usable by non English speakers :smile:

**Comment by fhfuih** [comment]
In our local Chinese communities, we all call it "MCEdit", we don't have a translation for it. We also use abbreviations like MC MCPE. So to me the original is all right! :smiley:

**Comment by robske110** [comment]
I could translate it to German (MCEdit ~ Unified v1.5.1.0 für Minecraft 1.8/1.9)

**Comment by TropicSapling** [comment]
Oh, so you want to translate only the for word?

**Comment by Neui** [comment]
Names shouldn't be translated (keep it at `MCEdit ~ Unified v1.5.1.0` and `Minecraft 1.8/1.9`)
Of course, we could translate the little word `for` (in german you would use `für`) but is then that's it.

For the Minecraft-Version, i would use `Minecraft 1.8/1.9/PE xxx` (with `PE`, if it is actually supported), so the word `Minecraft` persists while the versions are sperated by a `/`. (Maybe, on multiple version (version range), maybe use eg. `1.7-1.9`)

**Comment by L3ice** [comment]
If its not hard todo... It would be nice!

**Comment by LaChal** [comment]
Adding an entry in the translation resources and reformatting a string shouldn’t be that hard :wink:

**Comment by OniOniOn-** [comment]
Not a good idea to translate program name..

**Comment by TropicSapling** [comment]
@OniOniOn- just translating the for word :)

**Comment by Khroki** [comment]
Looks like the general consensus is to leave it alone, so we shall.
