### ISSUE TITLE
Error starting MCedit. (Application Breaking Bug) (Please Help)

### ISSUE THREAD

**Issue by bbfresh420** [Khroki/MCEdit-Unified#580]
Getting a error in the command prompt when starting mcedit. running windows 7 64bit. I'm running Minecraft 1.7.10 

Running in fixed mode. Support files are in your Documents folder.
Splash load...
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of C:\Users\House\Documents\MCEdit\Serve
rJarStorage named with the server's version number
Cached servers:  []
mcedit.main MCEdit exited with errors.
[   ERROR][                   root.py:791]:MCEdit version Unified v1.5.1.0 for M
inecraft 1.8/1.9
[   ERROR][                   root.py:794]:Attempt to call an undefined function
 glWindowPos2d, check for bool(glWindowPos2d) before calling
Traceback (most recent call last):
  File "<string>", line 788, in main
  File "<string>", line 516, in main
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\utilities.gl_display_context",
 line 21, in __init__
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\utilities.gl_display_context",
 line 55, in reset
  File "C:\build\bin64\build\mcedit\out00-PYZ.pyz\OpenGL.platform.baseplatform",
 line 407, in __call__
NullFunctionError: Attempt to call an undefined function glWindowPos2d, check fo
r bool(glWindowPos2d) before calling
Press RETURN or close this window to dismiss.

**Comment by bbfresh420** [comment]
Is this one of those places where you never get help unless your some popular user on the site? I would sure appreciate a tiny bit of help at least. I know absolutely nothing about this code and it always shows when I run the application.

**Comment by bbfresh420** [comment]
It's kinda sad I can see people getting help on here as I speak... And they want help with translations but I have a legit problem and it gets looked over. I've googled my issue and I've found threads with the same problem but nobody has ever helped those people either. MCedit has always worked for me until they started using the installer instead of letting you unzip the files yourself.

**Comment by Khroki** [comment]
Calm down, it's only been 17 hours, we're not on all the time and this isn't an instant messanger. Anyway we need your system specs to really diagnose this, mainly CPU and Video card.

**Comment by Khroki** [comment]
And let us know if any older versions work as well.

**Comment by bbfresh420** [comment]
I apologize. Anyways. How exactly would I get the specs? I'm not that good with that stuff. Is there a program or something that would be able to tell me.?  All I know is that I have 4 gb of ram. And a nvdia graphics card.

**Comment by bbfresh420** [comment]
I tried 5 other older versions and I keep getting the same error. Also this kinda happened out of the blue. I use mcedit all the time and after using it and leaving it alone for a few days I came back and this error kept reoccurring.

**Comment by LaChal** [comment]
Five older version also crash...

Looking at the log you posted, I would say you have a problem with your video drivers, especially the OpenGL part.

Concerning you system, uploading the file `mcedit.log` (alongside the program itself), can also help us to diagnose.

**Comment by Khroki** [comment]
If you press the windows key plus R it'll bring up the run menu, type dxdiag in that window and press enter to bring up the direct x diagnostic tool, press save report and upload it somewhere if you want to make it easier.

**Comment by Khroki** [comment]
If you're still around/having the problem let us know with your specs, otherwise I'll assume you figured it out and close this soonish.

**Comment by Khroki** [comment]
Closing, feel free to reopen if you get the requested information.
