### ISSUE TITLE
MC-Edit wont start on second opening

### ISSUE THREAD

**Issue by Xbox180** [Khroki/MCEdit-Unified#582]
When I open MC-Edit for the first time, it works great! I close and shut down. Then I go back the next day, I find that it can't open splash2. I look every where in the Documents folder and main folder for a python, or setup file on it so it will focus on the newer splash, but their is non. The problem fixes if I re-download it. This problem appeared on MC-Edit versions 1.5.0.0 and 1.5.1.0. I'm running Win 10 x64 on a Laptop. I've never had this problem on a Desktop.

If it helps, I'm running on 3 GB of RAM, Intel Core Duo, and Intel Mobile 4 Series Chipset Family that is rolled back to the Win 7 version for OpenGL problems so minecraft runs fine.

**Comment by Xbox180** [comment]
Oh, also Win 10.

**Comment by LaChal** [comment]
`splash2` (in fact `splash2.png`) is referenced in the file `splash`. You can find it in the folder where MCEdit is installed.

To solve your issue, just open `splash` with notepad and delete the whole content, and save.

This issue is already fixed for the next release.

**Comment by Xbox180** [comment]
How do you open the folder with notepad?

**Comment by LaChal** [comment]
There's a `splashes` folder containing images, but it does not matter for this bug.

`splash` is a text file and is alongside `mcedit.exe`.

**Comment by Xbox180** [comment]
Thx
