### ISSUE TITLE
Error trying to SaveAs from a PocketWorld (Pi Edition)

### ISSUE THREAD

**Issue by willkessler** [Khroki/MCEdit-Unified#583]
Trying to use MCEdit 1.5.11 Latest MacOSX, to convert a pocketworld world into a more modern format. I can load the world up. But when I try to SaveAs I get:

Error during <function SaveAs at 0x10c042e60>:
AttributeError("PocketWorld" object has no attribute "worldFolder"",) 

Would love to use to the tool to accomplish this task. Anybody have any suggestions on how to work around the issue?

**Comment by Khroki** [comment]
You can try to either make a schematic of the world, or import the world as a schematic in another world.

**Comment by willkessler** [comment]
Thanks for this reply! I'll try it. When I create a new world, it has lots
of scenery in it. Is there a way to create a totally empty world that I
could import the schematic into? and is there a way to specify the format
of the resulting newly saved world? (to ensure it's compatible with recent
versions of MC). Thanks again!

**Comment by Khroki** [comment]
If you create your world as a flatland it would be an empty field with some villages, you can raise the depth of the field by adding dirt layers in there when setting the options and turn off villages by disabling structures.

**Comment by willkessler** [comment]
Thank you ! This worked well. I just created a flatland, did select all, then delete/replace with air, then placed my schematic, then executed Save, and it worked!

**Comment by Khroki** [comment]
Yeah, modern pocket support has been kinda shaky since Rubisk hasn't been around, but glad it worked for you.
