### ISSUE TITLE
Value limit problem in chest(dispenser, dropper, etc.) setting panel

### ISSUE THREAD

**Issue by fhfuih** [Khroki/MCEdit-Unified#584]
![default](https://cloud.githubusercontent.com/assets/11222265/12974661/a0d0a590-d0f0-11e5-99bc-3e4c1c5d75aa.png)
*Never mind the language:)*

It's probably necessary for "DMG" & "Count" values to have **stricter** limitation. 

- "Count"
~~Can be and shouldn't be set to negative.~~(Can be useful in custom maps/dangerous in servers?)

- "DMG"
This is a little bit complex. Let's assume the target block has DMG value 0~N. We set the DMG to x.

x can be and shouldn't be negative.

When -(N+1) <= x <= -1, MCEdit recognizes x as N + 1 - |X|. For example, -16 for white wool, -1 for black wool.  

The moment you input (or scroll) a value smaller than -(N + 1), error occurs and the panel closes. Then this container cannot be edited again. Every time you attempt to edit it, the same error shows up instead of the panel. You'll have to delete this container.
![default](https://cloud.githubusercontent.com/assets/11222265/12974585/fb0ddea2-d0ef-11e5-813a-8fecefdd2aeb.png)

PS DMG should be allowed to set to any positive value, since different textures can be included for them in resource packs(maybe 1.8+?) or mods. So only negative values should be forbidden in the fix.

**Comment by Khroki** [comment]
DMG is already set to cap out at 32767, but I just set both DMG and Count to positive only. I'm not sure what you were getting at with N, let me know if there is anything more I need to do.

**Comment by Khroki** [comment]
Also if anyone has any good reason either should allow negative values let me know, I know you used to be able to set negative counts to achieve some infinite tricks in custom maps, but I don't know if that still applies.

**Comment by fhfuih** [comment]
To mention N I just want to show the interesting thing that different negative value have different effects. I don't know the trick of negative DMG but if it does apply, some fix for negative DMG is required so MCEdit and the container won't corrupt.

**Comment by cleverca22** [comment]
i have seen a dup bug in vanilla MC, if you do a certain set of actions you can get an item stack with a negative count

if you then put that into a dropper, it will dispense, decrements, and check if 0, due to the negative, it will never run out

i can see that being useful for an adventure map maker

**Comment by Khroki** [comment]
Alright, I'll set it to positive damage only and min -1 count then.

**Comment by Khroki** [comment]
Committed, closing. Let me know if there are further problems.
