### ISSUE TITLE
Linux Package does not match md5

### ISSUE THREAD

**Issue by Dupplicate** [Khroki/MCEdit-Unified#588]
md5sum MCEdit.v1.5.1.0.Lin.Universal.run
3c3088a77a2ed44678c6a43c381e4f62  MCEdit.v1.5.1.0.Lin.Universal.run

the download page 
https://github.com/Khroki/MCEdit-Unified/releases
reports a different md5

4ce1754b5c9565d16d1314ddc78d4ba8

**Comment by LaChal** [comment]
Hmmm...

The checksum provided on the download page is automatically generated during the build. Something shall be wrong there.

Changes will be made accordingly.
Thank you for pointing this!

**Comment by Xavom** [comment]
Linux version MD5 mismatch for MCEdit.v1.5.1.0.Lin.Universal.run :
3c3088a77a2ed44678c6a43c381e4f62 MCEdit.v1.5.1.0.Lin.Universal.run
I have check the last 3 versions and all of the MD5 hashes are different from thos on the download page.
