### ISSUE TITLE
Light and shadow errors when saving MCPE worlds

### ISSUE THREAD

**Issue by jose-vm** [Khroki/MCEdit-Unified#591]
Whenever you save a MCPE world or export an schematic out of a MCPE world with MCEdit v1.5.1.0, many lightning errors come with it.

A good idea might be settings the skylight to max by default so it won't look bad.

PD. Probably a fix would be changing 16,16,64 to 16,16,128? Because 128 is MCPE max height, and a size of a MCPE chunk is 16x16x128 and not 16x16x64. (https://github.com/Khroki/MCEdit-Unified/blob/master/pymclevel/pocket.py#L389)

**Comment by Rubisk** [comment]
Should alraedy be fixed in ecd17478a578122d8cc48e6f2c49e64179da5fdb

**Comment by jose-vm** [comment]
Thanks!
