### ISSUE TITLE
Plz help.i dont know what happen

### ISSUE THREAD

**Issue by jasonwgg** [Khroki/MCEdit-Unified#593]
[http://photo.weibo.com/1738373382/wbphotos/large/mid/3947528397965109/pid/679d7906gw1f1f4hgrkgbj20is0c9di9](url)

Win7 64

**Comment by jasonwgg** [comment]
[http://ww4.sinaimg.cn/large/679d7906gw1f1f4hgrkgbj20is0c9di9.jpg](url)

**Comment by jasonwgg** [comment]
http://ww4.sinaimg.cn/large/679d7906gw1f1f4hgrkgbj20is0c9di9.jpg

**Comment by Khroki** [comment]
Ah, make sure you put the program in a directory containing only English characters, it is a known issue.

**Comment by jasonwgg** [comment]
I'm sure that Mcedit has been installed in an English position and I have been used it for a period of time，which is a mistake of an incorrect shutdown at sometime.

**Comment by jasonwgg** [comment]
@Khroki I'm sure that Mcedit has been installed in an English position and I have been used it for a period of time，which is a mistake of an incorrect shutdown at sometime.

**Comment by Khroki** [comment]
What is the windows username you're logged into while trying to run mcedit?

**Comment by jasonwgg** [comment]
Administrator, and i only have this username

**Comment by Khroki** [comment]
Try going to your documents folder and deleting the mcedit folder in there, I think your config file got messed up.

**Comment by jasonwgg** [comment]
I have to download MCedit and Reinstalled Windows again,it still Error~

**Comment by Khroki** [comment]
did any older versions work?

**Comment by Khroki** [comment]
did 1.5.1.0 work at one point or has it never worked? Just trying to clarify.

**Comment by jasonwgg** [comment]
Nope ，the same Error

**Comment by LaChal** [comment]
What is the content of the `mcedit.log` file?

**Comment by jasonwgg** [comment]
@LaChal  I can't find the Mcedit.log file, you can kick the link and see the Error picture.

**Comment by Khroki** [comment]
If it was a system crash that messed it up, the log could be useful, if you just want to do a fresh install of MCEdit Delete the mcedit folders in both of the following locations: C:\ and C:\Users\Administrator\Documents\ then extract. If you just extract over the old folder it won't fix anything. Also if @fhfuih is around, we could use your chinese to help diagnose.

**Comment by jasonwgg** [comment]
@Khroki  Thank you very much.

**Comment by fhfuih** [comment]
'Kay, let me try, if you still need a hand.

Khroki的建议是重新安装一下Mcedit，去我的文档看看有没有MCEdit文件夹，有的话删掉。然后你之前解压出来的Mcedit路径也完全删掉。删掉旧的再解压新的，不要简单地把新版本解压覆盖旧文件。然后mecdit.log文件在解压路径/mcedit/里面，也就是和mcedit.exe在一个文件夹。

**Comment by jasonwgg** [comment]
@fhfuih 看到中文十分感动，四级不过很难沟通，问题已经解决~
             话说MCedit 2.0 64位下载地址是Error 404求个拦截。

**Comment by fhfuih** [comment]
也就是删掉d:/mcedit 文件夹和我的文档的MCEdit文件夹，再解压新版。console显示是和Unicode有关的问题，这个错误应该会写入log的，如果有log的话他们帮助你估计会更容易

**Comment by fhfuih** [comment]
哈哈解决了就好！mcedit2的下载地址不是很清楚，我这边也一直看到404。mcedit2的问题你可以去mcedit2的GitHub页面问问
@Khroki His problem is solved. :)

**Comment by Khroki** [comment]
Nice, thanks for handling that, I don't think any information was getting across before.

**Comment by jasonwgg** [comment]
@Khroki  i find a guy who pass the CET6 translate them into Chinese~Thx again.

**Comment by fhfuih** [comment]
哥们，他刚刚问你你那边到底哪里出错了…如果你还有当时错误的log或者解决方法的话说一下，也能帮助他们完善软件啦！

**Comment by jasonwgg** [comment]
@fhfuih 麻烦帮忙转达，因为无法打开我重装了系统和mcedit,所以log文件也找不到了。

**Comment by fhfuih** [comment]
@Khroki he said his problem was solved after system reinstalling, so the log is lost. Not certain what problem it was but maybe a dirty install or file conflict of something

**Comment by Khroki** [comment]
Ah ok, thanks for letting me know.
