### ISSUE TITLE
Pymclevel: generating worlds can be faster?

### ISSUE THREAD

**Issue by Monkey0x9** [Khroki/MCEdit-Unified#601]
To start off, when you generate a world with MCEdit, it starts a Minecraft server to generate chunks around the spawnpoint and then moves the spawnpoint. That way it can generate whole worlds.

Now what I've seen is that pymclevel thinks that the Minecraft server only generates a 11X11 chunkgrid centered around the spawnpoint (or the center spawnchunk with a radius of 5). This you can also see here in the source code: 
https://github.com/Khroki/MCEdit-Unified/blob/master/pymclevel/minecraft_server.py#L452 .

With the tests I did I saw that the Minecraft server always generates a 25X25 chunkgrid centered around spawn with southest and eastest chunks being non populated. My second test was changing the variable "minRadius" to 12 (= 25X25 chunkgrid 12*2 + 1)and generate a few worlds with mcedit to see if it would still generate worlds correctly. And it did it, while being much faster! (It still has the same little issue as before that the southest and eastest chunks are non populated).

So this leads me to the question, why is the radius 5 when the server actually generates much more chunks? If there is no reason to keep it on 5 I would highly suggest changing it, because it's like a free performance boost :).

**Comment by Khroki** [comment]
I imagine it was due to a very old version not supporting a greater area, I can see about raising this later or you can put in a pull request. We had to do similar to the texture grid limitation and the spawn point minimum height.

**Comment by Monkey0x9** [comment]
Thanks for the clarification :) I also made a PR.
