### ISSUE TITLE
Latest MCEdit build download

### ISSUE THREAD

**Issue by jose-vm** [Khroki/MCEdit-Unified#604]
Sorry for my stupid question. I don't know how to build this project but I wished I could have the latest update so I can use it now that pocket chunk relightning (https://github.com/Khroki/MCEdit-Unified/commit/ecd17478a578122d8cc48e6f2c49e64179da5fdb) has been fixed. Is there any way I can get a download to it?

**Comment by Khroki** [comment]
Unfortunately some player handling is being rewritten so it's not ready, but you can always run from source if you really want to use it now. You need python 2.7.x and the libraries listed at the bottom of the main repository page.

**Comment by jose-vm** [comment]
Oh, I see. Thanks!
