### ISSUE TITLE
Mouse cursor not visible/working after pressing Ctrl+W while holding right mouse button on open world

### ISSUE THREAD

**Issue by juozaspo** [Khroki/MCEdit-Unified#609]
Like previous now fixed issue, this happens when world is open.
**How to reproduce**
Load a world => hold right mouse button (don't release) => press Ctrl+W => Release the button
**Effect**
The world closes normally but there's no visible mouse; only keyboard controls are working. can't alt-tab out; Ctrl+q only way to exit. Also happened before while looking at unloaded chunks on loaded world.
 
**MCEdit** - Latest (v1.5.1.0) or whatever version on github (w->ctrl crash fixed)
**Minecraft** 1.9.1-pre3
**OS** Ubuntu _Linux_ 64bit (xfwm4 4.12.3/Xfce 4.12)
**Python** 2.7.10
_No errors_ on log.

**Comment by LaChal** [comment]
I don't experience this on my side, even disabling the window management with '--no-wm' CLI switch.
It may be due to your desktop environment.

Can you reproduce this issue in the default Unity desktop?
What is the version of your OS?

**Comment by juozaspo** [comment]
> Can you reproduce this issue in the default Unity desktop?
Unity is not installed here (xubuntu); to check I have to install it whitch takes time; will update later
> What is the version of your OS?
Linux; Ubuntu 15.10, running Xubuntu (xfce) desktop environment

**Comment by juozaspo** [comment]
I can confirm this from Ubuntu live cd.  Installed all prerequisites and made a test world. Holding right click and hitting Ctrl+w still hides the cursor after you release the mouse button. So it meens it's reproduceable in default Unity desktop :/ p.s. typing this from live cd atm.

**Comment by naor2013** [comment]
Fixed!
Thanks for all the help, keep the bugs coming :)

**Comment by LaChal** [comment]
By the way, you shall install PyGTK 2 with `sudo apt-get install python-gtk2`
This fixed the issue on my VM even before Naor's commit.
Moreover, MCEdit will use the Linux file/folder chooser instead of the internal one.

**Comment by juozaspo** [comment]
> By the way, you shall install PyGTK 2 with `sudo apt-get install python-gtk2`

Package already installed before, no need to reinstall. Btw thanks.

**Comment by LaChal** [comment]
You're welcome!

Does Naor's stuff fixed the issue?

**Comment by juozaspo** [comment]
Fixed. MCEdit Working ok.

**Comment by LaChal** [comment]
OK

Thank you for the report!
