### ISSUE TITLE
Add languages as Subproject

### ISSUE THREAD

**Issue by L3ice** [Khroki/MCEdit-Unified#611]
**https://github.com/Khroki/MCEdit-Unified/tree/master/lang as Subproject**

- :+1: Decrease Commit and PR "Spam"
- :-1: Loosing Commit History from files

_This is a suggestion._

**Comment by Khroki** [comment]
You know, you commit often enough i can just give you collaborator status, this applies to any translator that regularly commits.

**Comment by naor2013** [comment]
Ok, we'll make all of the translators who commit a lot a collaborator status to reduce PR spam
Thanks for the idea, though, L3ice! :D

**Comment by L3ice** [comment]
Wow, thanks! :hushed: :blush:

**Comment by Khroki** [comment]
You've been added, enjoy
