### ISSUE TITLE
Repository access thread (Translators et. al.)

### ISSUE THREAD

**Issue by Khroki** [Khroki/MCEdit-Unified#612]
This topic is for people who have been contributing to the project to get collaborator status so you don't have to use a pull request every time. It's open to anyone who has been helping out lately, and is how most of the people working on this got access. This applies to translators too, we settled on the unified name as it is a community project so come get in on it.

Note though that I will revoke this if you are found to be abusing it or fighting with other collaborators.

**Comment by robske110** [comment]
I could translate English->German

**Comment by robske110** [comment]
But as I'm not doing much, I can just continue PRs

**Comment by Khroki** [comment]
Yeah, it's more for people who are submitting requests semi regularly, the activity records show you've only had one.

**Comment by robske110** [comment]
Yeah, I just discovered that there is an repo for MCEdit :)

**Comment by OniOniOn-** [comment]
I don't even know how to delete branch. lol

**Comment by Khroki** [comment]
Closing due to lack of interest, you can still post in here though and I'll see it.
