### ISSUE TITLE
askOpenFileWin32

### ISSUE THREAD

**Issue by gentlegiantJGC** [Khroki/MCEdit-Unified#614]
It is not possible to pass alternative suffixes to the windows file opener. They are not actually passed to the function that calls the windows process.

It looks like someone has had a go but has hard coded the suffixes in the windows function instead of passing the original ones on.

**Comment by LaChal** [comment]
Thank you for pointing this.
We'll have a look :smile:

**Comment by naor2013** [comment]
Should be fixed for the next update
Now there's a fourth optional parameter to this function which is suffixes
It will look something like: ["zip", "docx"] and the name there would be shown in the file opener
Of course we can't promise the code will know what to do with those file, it will just show them to the user in the file opener
I hope it helps and thanks for the support :)

**Comment by gentlegiantJGC** [comment]
Thanks for working on this and keeping development ticking over.

I can't seem to get it to work. I am running the following

`file = mcplatform.askOpenFile(title="Select Post-Commands text document", suffixes=["txt"])`

and all that is appearing in the box is All and *,* am I doing something wrong?
