### ISSUE TITLE
"Analyse" in selection tool uses template.trn rather than specific block translations

### ISSUE THREAD

**Issue by fhfuih** [Khroki/MCEdit-Unified#615]
It's probably better for "Analyse" result list to use the same translation template as the block picker, which is in \Items\* and is not implemented yet. Currently it's using \lang\*.trn which is for the MCEdit UI. There may be a few ambiguous strings.

BTW, when will \Items\* translations be planned to implemented?

**Comment by LaChal** [comment]
Sorry, I forgot to answer your question...

MCEdit is able to load few language resource from the game.
The files in `Items` contain some missing strings.
The `en_GB` can be considered as a template. So, if someone wants to add translation here, just do :smile:

**Comment by fhfuih** [comment]
I mean, I have done a little bit translation there in my own local computer, but it seems they are not shown in the software. I wonder if this function is implemented *now*, and where can i see those translations in MCEDIT? And considering the lack of block names, do you need any help?

Im a little busy these days, so it may take longer to finish translation @_@

**Comment by LaChal** [comment]
The 'Analyse' results are now showing the translated string when running from source.

If you want to see these strings translated, open the 'Brush' tool. You may see the block name in the panel is translated, provided MCEdit found the right resource.

By the way, if you have created a translation file from `en_GB` in `Items`, we can include it in the next release :smile:
