### ISSUE TITLE
[pymclevel] Import Error: no module named mclangres

### ISSUE THREAD

**Issue by RoiEXLab** [Khroki/MCEdit-Unified#617]
When writing a script based on mclevel.py mclangres.py won't get found because it's in the directory above. Copying it won't help because then other modules won't get found etc.
 I'm not sure if this belongs here, but in the pymclevel repo was no issues section.
I would appreciate all of your help.

**Comment by Khroki** [comment]
Unfortunately that file isn't part of the pymclevel subproject, you would need to copy it and it's dependencies over to pymclevel and rewrite their imports to function if you want to use it.

**Comment by Khroki** [comment]
Speaking of I'll update the pymclevel repo, I didn't think anyone was still using it.

**Comment by Khroki** [comment]
Closing since we don't really officially support pymclevel outside of it's use here, sorry :/
