### ISSUE TITLE
I think I have found the source of the mcpe world corruption

### ISSUE THREAD

**Issue by hdjackill** [Khroki/MCEdit-Unified#618]
I think I have found the source of the mcpe world corruption. I have attached a txt file showing three separate pieces of code that I've labelled 1-3
The code under 1 is the level.dat file before being put into mcedit
The code under 2 is the same level.dat file after being loaded and saved in mcedit
The code under 3 is the same level.dat file after reopening it in minecraft after being in mcedit.
I hope this helps.
[seeTheProblem.txt](https://github.com/Khroki/MCEdit-Unified/files/190570/seeTheProblem.txt)

**Comment by naor2013** [comment]
I don't see the problem because 1 and 2 look the same and we have anything to do with 3... One of our developers think he fixed the issue but we need to do a few more tests

**Comment by hdjackill** [comment]
the difference between one and two unless I messed up the file is that 1 has the whole thing in one line and 2 has the whole thing in three lines and I forgot to add this but my theory is that because of format mcedit saves the file as, when you open mcpe it sees the file is wrong and corrects it and in the process corrupts that world.

**Comment by Khroki** [comment]
Hmm, not completely sure if the mismatched line breaks would impact world loading, we need to see if the previously committed fixes work before we explore this further I think. The new version should be out in the next few days. Leaving this open though as it is possible it's related.

**Comment by hdjackill** [comment]
Since I first posted this I have did the exact same thing with two other worlds and I have noticed that in the third version of the code:
1. The first letter always becomes a U.
2. The limited world and spawn X,Y&Z's are always the same.
3. That the spawnMobs always looses the first rectangle after it.
4. doesn't have the world name.
5. and looses the code that follows RandomSeed.
So if the these fixes don't work I say this defiantly needs looking into.

**Comment by Rubisk** [comment]
The only difference is some \r\n and \n interchanging according to my analyzer. Only problem, I don't have a setup to run mcedit right now and I can't tell if mcedit's doing it or your copy-pasting. Can u upload all 3 files instead?

**Comment by hdjackill** [comment]
I can't upload the files themselves because .dat files aren't supported by this website so I've taken screen shots of them, but I don't have the version of the files before they get corrupted, and also I only have the first one still because I thought I wouldn't need them anymore.

![image](https://cloud.githubusercontent.com/assets/18045710/14136060/958c93f6-f6ac-11e5-804c-43d4b55774b8.png)
![image](https://cloud.githubusercontent.com/assets/18045710/14136080/ae8c1bec-f6ac-11e5-8303-9557e9d70fc9.png)
![image](https://cloud.githubusercontent.com/assets/18045710/14136148/0fa474ba-f6ad-11e5-8319-2bc350953517.png)

**Comment by Khroki** [comment]
Could you try the latest release and tell us if pocket world corruption is still a problem?

**Comment by hdjackill** [comment]
I cant even  check because I keep getting a 98 error when ever I try to save it though I can definably tell you that MCedit still doesn't load pe worlds properly

**Comment by naor2013** [comment]
@hdjackill What 98 error?

**Comment by hdjackill** [comment]
KeyError: 98

**Comment by naor2013** [comment]
Can you send a screenshot of the error in the console?

**Comment by hdjackill** [comment]
How do take screen shots I've forgetin how to

**Comment by Khroki** [comment]
The previous key errors were all missing block entries, we need unknown block handling for pocket.

**Comment by hdjackill** [comment]
I'm indeed using V0.14.2 of pocket edition pacifilly the one for windows if that makes a diffrence

**Comment by L3ice** [comment]
I saved the code from level.dat.
Then I saved the world in mcedit.
After that I replaced the current code from level.dat with the code before saving.
The world did open with no corruption except the worldname.

**Comment by L3ice** [comment]
The corruption is still a problem, but not occuring because level.dat gets modified.
So I close this issue for now..
