### ISSUE TITLE
MCEdit Unified 1.5.1.0 crash

### ISSUE THREAD

**Issue by DreaD4m** [Khroki/MCEdit-Unified#619]
When I open MCEdit Unified, it immediately crashes and nothing happens. (I am using win8)

sorry for bad English (not native speaker)

**Comment by DreaD4m** [comment]
+ I can barely see it is an error of python27.dll

**Comment by LaChal** [comment]
The error itself can be usefull...

If you can provide the `mcedit.log` file, and what is in the console, we'll check this :smile:
No importance if you don' have a `mcedit.log`.

**Comment by Khroki** [comment]
Might I ask what locale your system is/what directory you have mcedit installed in? Also system specs.

**Comment by DreaD4m** [comment]
Oh, i just knew that Unicode doesnt work with MCEdit. thanks for replies

**Comment by Khroki** [comment]
Is this resolved or are you still having problems?

**Comment by Khroki** [comment]
Assuming resolved.

**Comment by Dibro89** [comment]
@Khroki I have the same issue. Running Windows 7 Ultimate

**Comment by Khroki** [comment]
Would you mind running it from the command line and posting the output?

**Comment by Dibro89** [comment]
Error Loading python27.dll Error Code 14001

**Comment by Khroki** [comment]
Could anyone having this problem try this build and let me know if it fixes it? https://www.dropbox.com/s/pau7qkhclakhnzq/mcedit.exe?dl=0

**Comment by Dibro89** [comment]
It works! Thank you. :)
