### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by LaChal** [Khroki/MCEdit-Unified#621]
@OniOniOn- @violine1101 @L3ice @Neui @MG-5 @vongola12324 @fhfuih      @Monkey0x9 @TropicSapling

Hello all,

We may be very close to a release.
So, if you have some ready translation update on your side, please send :smile:

Otherwise, consider to have a look to the new stuff in the template!
You also may look at the `Items` folder, which contains additional resource for the game items and blocks.

Regards,

LaChal

**Comment by TropicSapling** [comment]
Well I'm on vacation atm so :P

**Comment by violine1101** [comment]
May I ask in which context the strings in the `Items` folder are used? For example, what's meant by `misc.lower`, `misc.upper` and `misc.level`? The translation depends on the context.

**Comment by robske110** [comment]
If no one is here, for ENG->GERMAN, I can do it

**Comment by LaChal** [comment]
@TropicSapling: don't worry. The translations aren't 'hard coded'. The `.trn` files are loaded 'as is' at run time. We can make an update/patch for them only!

@violine1101: the translation files in `Items` are used to translate the block and item names in the block picker. These files are built like internal Minecraft language resources, and contain strings which are used in MCEdit but not in the game.

Looking to the examples you gave, I can guess that `misc.lower` and `misc.upper` apply to slabs, and `misc.level` apply to water an lava levels when they're flowing.
If you don't know how to translate some entries, don't include them in the file. Or you can spend time adding dummy translation for them an look for them in the block/item picker. (The fact is comments are not implemented in these files for now... I'll have a look at this after my vacation :smile:)

**Comment by violine1101** [comment]
@robske110: Not necessary, I already translated most strings.

@LaChal: Those are the ones I'm not too sure with yet: `misc.armed` and `misc.disarmed` (I guess those are for dispensers/droppers?), `misc.stem` and `misc.allStem` (what does "stem" mean in this context?), `misc.bites` (what is this used for?) and, finally, `misc.curved` (although I think it applies to pumpkin and melon stems?). All the others were easier to translate.

**Comment by fhfuih** [comment]
Just updated translations! but seems new version has been already commited :sweat_smile:

**Comment by Khroki** [comment]
Yeah, we'll release a hotfix for the pocket issues soon, so any translations will get into that version.

**Comment by Neui** [comment]
There is `Found a previous portable installation` but [the code](https://github.com/Khroki/MCEdit-Unified/blob/24b51d4e1300748d538d71a0674fbae920e8aa9f/panels/options.py#L307) says (from what i understand), that there might be also `Found a previous fixed installation`, but i can't find it in the translation file. Is this a mistake?

**Comment by fhfuih** [comment]
@Neui Possibly yes, the '''found a previous portable installation''' is just added by me after I encountered this string in the software. I haven't met the other string so I didn't add that.

**Comment by fhfuih** [comment]
Ok I've made a PR to add `Found a previous fixed installation`. Sorry about my mistake.

**Comment by Khroki** [comment]
Since this is no longer timely, I'm going to close it.
