### ISSUE TITLE
Extracted - try to open - nothing happen

### ISSUE THREAD

**Issue by Benjii35** [Khroki/MCEdit-Unified#622]
I exctrated/instaled this version.
I clicked mcedit.exe - for a second there is some black window - in a second it is gone.
What to do to work properly?

**Comment by Khroki** [comment]
What are your system specs/install folder directory? Also if you can get a screenshot of that black window it can help.

**Comment by Benjii35** [comment]
It is working now.. It didn't work just because I installed it on my external harddrive... (I don't why. I wanted  it there.)

So.. RESOLVED

**Comment by Khroki** [comment]
That's strange, anyway glad it works.
