### ISSUE TITLE
Create Shop still has Unicode error in drop-down selections

### ISSUE THREAD

**Issue by fhfuih** [Khroki/MCEdit-Unified#627]
Similar issue(#479 , the first part) was posted before, that some filters use the translated strings of drop-down selections probably as arguments, causing the filters confused about those selections' meanings. The same problem still exists in Create Shop. only when you select a chest and filter will the error occur. Filtering a selection without chests will not show the error. (but also will do nothing to the map:P)

**Comment by naor2013** [comment]
Can you send a screenshot of the error that caused by the filter?

**Comment by fhfuih** [comment]
Yes of course.
![default](https://cloud.githubusercontent.com/assets/11222265/14225502/76abe28c-f8f7-11e5-9b78-9c5b5841ac19.PNG)
The error Unicode string matches the translated "村民（绿衣）", which originally means villegar green

**Comment by naor2013** [comment]
Can you get the error from the console too?

**Comment by fhfuih** [comment]
Ehh...I'm so forgetful :sweat: 
![default](https://cloud.githubusercontent.com/assets/11222265/14225527/34fa5dfe-f8f8-11e5-998f-6f90e7f57ccb.PNG)
Seems it directly read it as a key

**Comment by naor2013** [comment]
Thanks, I'll fix that for a future version but since we released a new version recently, I'm not sure how much time it's going to take..

**Comment by fhfuih** [comment]
Alright, it's okay. Thanks :smile:

**Comment by LaChal** [comment]
This is not an Unicode error, but a list reference one.
The fact is some filters has been adapted to the translation system, but some other were not...
Thank you for reporting this :smile:
