### ISSUE TITLE
Forester filter still has Unicode error in drop-down selections

### ISSUE THREAD

**Issue by fhfuih** [Khroki/MCEdit-Unified#628]
May be another remaining filter-dealing-translation issue. ~~In non-English UI, only "procedual" type of trees will successfully generated.~~(<-That's because I haven't translated "procedual" in the S.Chinese version)

Any translated selections in drop-down menu will not be recognized. 
As for "tree type", choosing a translated selection will cause error " 'newtree' referenced before assignment "
Console traceback:
![default](https://cloud.githubusercontent.com/assets/11222265/14225731/759434aa-f8ff-11e5-9c50-e5fe2462c64e.PNG)
As for "root", it will (probably) use the default choice regardless of the corresponding English string.

The filter action will only happen if enough space is given in the selected area. So if anyone wants to observe or reproduce the problem, running this filter in small selections with tree arguments set too high won't result in anything.

**Comment by fhfuih** [comment]
In case anyone has started looking into this issue: it has been edited. Previously I said only "procedural" works, it was not true. Any translated selection will confuse this filter.

**Comment by LaChal** [comment]
The forester filter is different from the other ones, since the MCEdit filter uses an external file.
Efforts will be make to fix this issue.
