### ISSUE TITLE
Crash when selecting chunks in chunk view

### ISSUE THREAD

**Issue by jamaa** [Khroki/MCEdit-Unified#629]
MCEdit crashes when I try to select chunks in chunk view and accidentally drag my mouse beyond the edge of the generated world.

I previously reported this here: https://github.com/Khroki/MCEdit-Unified/issues/520#issuecomment-154152324

The issue was marked as fixed for the "next release", I'm now using MCEdit 1.5.2 (win64) and still experiencing the same problem. However, now I've noticed that the crash only occurs when you make a **second** selection.

# Steps to reproduce:
1. Open a world in MCEdit
2. Switch to Chunk Mode
3. Select some chunks by clicking and dragging
4. Make **another, second** selection and drag until the mouse moves beyond the edge of the generated world
5. MCEdit crashes

Here's a screenshot of the console:

![mcedit_console](https://cloud.githubusercontent.com/assets/90166/14226230/0cf36646-f8dc-11e5-92d5-77b1cb5bbb24.png)

And here's my mcedit.log: http://pastebin.com/77xDQL0f

**Comment by naor2013** [comment]
Fixed for next release, thanks for the help!
