### ISSUE TITLE
Some coordinates in command blocks not updated on paste.

### ISSUE THREAD

**Issue by abregado** [Khroki/MCEdit-Unified#630]
I haven not yet nailed down exactly which blocks are not getting updated. So far it is only with absolute coordinates within target selectors "@a[x=10,y=2,z=50] which are not getting updated. SOME do get updated but others not which means checking them all by hand anyway.

MCEdit version. started on 1.5 and persisted on 1.5.1 and 1.5.2
MC version. started on 1.9 update with new command blocks, persisted on 1.9.2

I can provide my specific command block output if needed

**Comment by naor2013** [comment]
Yeah, sending us the commands before movement and after would help, especially if you'll give us examples of both things that work and things that don't work. btw, are you both copying and pasting in MCEdit 1.5 or are you using schematics that got created with an old MCEdit version?

**Comment by LaChal** [comment]
No update from the post author for more than one year.
Closing...
