### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by normanfeltz** [Khroki/MCEdit-Unified#632]
Hey,

 I have download the last version

Running in fixed mode. Support files are in your Documents folder.
Splash load...
[ WARNING][            mcplatform.py:1182]:Initializing window management...
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of D:\Documents\MCEdit\ServerJarStorage
named with the server's version number
Cached servers:  []
mcedit.main MCEdit exited with errors.
[   ERROR][                  root.py:1004]:MCEdit version Unified v1.5.2.0 %s Mi
necraft 1.8/1.9 | PE 0.11
[   ERROR][                  root.py:1007]:'250' is not in list
Traceback (most recent call last):
  File "<string>", line 1001, in main
  File "<string>", line 732, in main
  File "<string>", line 270, in __init__
  File "<string>", line 323, in reloadEditor
  File "leveleditor.py", line 221, in __init__
  File "albow\extended_widgets.py", line 184, in selectedChoice
ValueError: '250' is not in list
Press RETURN or close this window to dismiss.

Cordialy

**Comment by jobensingh** [comment]
Next Time use pastebin when posting errors. If you want to continue using mcEdit just downgrade to 1.5.1 or go to 2.0 for now. Iv had my own share of problems, not on launch though, with 1.5.2. Just Make sure you delete the McEdit folder in your documents before you launch the installer 1.5.1 or a lower version. Hope I helped

**Comment by naor2013** [comment]
I couldn't reproduce that bug and it doesn't seem logical to me to get that bug but I hope I got it fixed for the next release
Do you know how you got this error? Did you change anything or do anything?
