### ISSUE TITLE
Opening leveldb worlds is broken

### ISSUE THREAD

**Issue by L3ice** [Khroki/MCEdit-Unified#633]
Trying to open PE worlds returns an error.
Or can actually someone open PE worlds?
I can't open any of mine.

**Comment by Khroki** [comment]
Huh, I'm not sure how that one slipped by, we really need a pocket dev. Anyway we'll make a hotfix release as soon as this is fixed.

**Comment by Khroki** [comment]
Ok, it is working on OSX, so this is some kind of windows-specific error.

**Comment by Khroki** [comment]
I found the problem, Pyinstaller 3 is to blame, We'll release a new version in the next couple days depending on when our linux guy is around.
