### ISSUE TITLE
Software title translation doesn't work properly

### ISSUE THREAD

**Issue by fhfuih** [Khroki/MCEdit-Unified#635]
In the recent changes, "for" in title is able to translate. But the translation can't work properly.
On startup, the title is not translated:
![default](https://cloud.githubusercontent.com/assets/11222265/14232025/8a6f83ca-f9cc-11e5-92c0-8e58d9630cde.PNG)
After loading up a world, the title changes, in a wrong way:
![default](https://cloud.githubusercontent.com/assets/11222265/14232030/ab492b00-f9cc-11e5-9917-046300c34aaf.PNG)
The title keeps showing in the wrong way afterwards, even if you return to the main menu. Closing and reopening MCEdit will make the title go back to the untranslated stage.

**Comment by Khroki** [comment]
Since this was debated anyway, I just disabled the for translation for the time being.
