### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Nyannikins** [Khroki/MCEdit-Unified#636]
I'm new to using this program, so unfortunately I don't understand a lot of the errors and whatnot that the program has given me. Every time I click on the .exe application to open the program, there is a sign that it's working but it immediately crashes (never has it loaded the actual interface). 

 I have downloaded the 1.5.2.0 32 bit version of MCEdit and have also tried the 64 bit version but neither have worked. I'll provide the errors for both versions when they crash.
32 bit: http://pastebin.com/89js0ENJ
64 bit: http://pastebin.com/LHeuGze5

 I downloaded the development versions and they do function, however I don't know how to use it as I can't find any tutorials matching it. I use Windows 10 which I desperately hope is compatible with MCEdit :/

Thank you in advance! ^_^

**Comment by Khroki** [comment]
What are your system specs? That looks like an opengl error. Also it is fully windows 10 compatible, I build it on windows 10.

**Comment by Nyannikins** [comment]
(I hope I got the right information I'm really dumb with this sort of stuff sorry XD)
Processor: Intel(R) Core(TM) i3-2330M CPU @ 2.20GHz
Installed RAM: 4.00 GB
System type: 64 bit

**Comment by KoopaEnder** [comment]
Same here, i tried every thing and nothing

**Comment by jobensingh** [comment]
Try Deleting your MCEdit fodler in your Documents folder, then try opening it. That fixed it for me when I was having a similar problem on version 1.5.1

**Comment by Nyannikins** [comment]
Tried it, still doesn't work ;_; Thank you anyway

**Comment by jobensingh** [comment]
So then like Khroki said it is likely an openGl Error. You can try updating your graphics drivers, which is really simple to do and is likely to fix the problem, unless your graphics card is really really old, either way its a good idea to try

**Comment by Khroki** [comment]
Hmm, yeah you may have an early intel i series integrated video chip, which we have had reports of not working properly in the past. You can find out your video card by pressing the windows key+R and typing Dxdiag and pressing enter, go to the video tab to find your video card's name and driver date..

**Comment by Nyannikins** [comment]
I have an "intel(R) HD Graphics 3000" thingy. I managed to find updates of it online however I'm not sure which one to download since there were none for Windows 10 (I assume I should download the Windows 7 ones since I had that before updating but I don't want to risk it yet DX).
https://downloadcenter.intel.com/product/81500/Intel-HD-Graphics-3000-for-2nd-Generation-Intel-Core-Processors

**Comment by Khroki** [comment]
The newest version that's windows 8 compatible should also work on Windows 10

**Comment by KoopaEnder** [comment]
I updated my graphic card is Intel HD Graphics 3000 it worked here, thanks a lot :+1:

**Comment by Khroki** [comment]
Good to hear, going to make sure nyannikins' works too before closing this.

**Comment by Nyannikins** [comment]
Still not working I'm afraid... I believe I am still getting the same error: http://pastebin.com/RaQr029m
I checked my drivers and it also seems like the version didn't change either. I followed the installation process and restarted my laptop.

**Comment by Khroki** [comment]
Does the version installed match the version of the downloaded driver? if not you may have to install it in compatibility mode.

**Comment by Nyannikins** [comment]
Yes the versions were different when I was installing a new one. How would I download it in that mode?

**Comment by Khroki** [comment]
Right click the downloaded installer and click properties, then go to the compatibility tab and set it to Win 8.1, it should work that way.

**Comment by Khroki** [comment]
Also failing that, you can try this build to see if it's any better: https://www.dropbox.com/s/bfnu0ahrxxvdcm2/mcedit1.5.2.x.Accelerated.Opengl.exe?dl=0

**Comment by Nyannikins** [comment]
Both tries didn't work... I've always had this with applications not working no matter what I do ._. 
http://pastebin.com/hNEuXd8C in case anything has changed

**Comment by Khroki** [comment]
Could you try the driver from the MS catalog: https://catalog.update.microsoft.com/v7/site/Search.aspx?q=intel%20hd%203000 This link requires Internet Explorer to view. 4th one down.

**Comment by Nyannikins** [comment]
How do I use it? It comes as a WinRAR archive thing

**Comment by Khroki** [comment]
extract the .rar using either 7zip or winrar anywhere you like, press the windows key+pause|break and click device manager on the top left. Find your graphics card under display adapters and doubleclick it. Click the driver tab, click update driver, browse computer, and browse to the folder you extracted earlier. It should automatically find and install it.

**Comment by Nyannikins** [comment]
It says I already have the latest driver installed nooooo
I've always had bad luck with applications that don't work with my laptop, thank you so much for replying quickly to help. ^_^

**Comment by jobensingh** [comment]
Since that didnt work You might want to take a deeper look into weather its a software problem or a Hardware problem. When I say software problem I mean there is probably a program or such thats causing problems, and in the event of a hardware problem it might be a faulty graphics card. First off check to make sure you have open gl 1.1 or higher, I mean if you can run minecraft you almost defiantly do. Then you could try booting of a live usb, although thats not the easiest thing in the world but its certainly not difficult. You most likely want to install ubuntu onto it and live boot. You can install McEdit onto there and if it launches then great, its a problem with your windows. A much easier way would be to reset your pc, but I doubt you want to do that.

**Comment by jobensingh** [comment]
If you dont want to do any of that you could continue searching for drivers or see if you have any programs that have anything to do with graphics and or OpenGL, or if you do want to live boot all you have to do is download a program called Yumi, and a Ubuntu iso which you can get from google

**Comment by jobensingh** [comment]
Forgot to mention this earleir but you could try running McEdit itself in Compatibility mode

**Comment by Nyannikins** [comment]
I tried running that in compatibility mode and it still doesn't work. I think it may be because my only options were to run it as windows 8 even though I have windows 10. 
I think I'll have to pass on the rest of your suggestions because this situation has consumed too much of my time considering I wanted to use this program for a project with a deadline. Thank you so much for the help though! I'll refer back to this when I do have time and try those methods.

**Comment by jobensingh** [comment]
No Problem, probably one last thing you could try is running a different version of mcedit, just be sure to delete the mcedit folder in your documents before installing a new version, id start with 2.0 if you havent already then 1.5.1, if neither of these work you could resort to using Dynamap + worldedit

**Comment by Nyannikins** [comment]
OH MY GOD
USING AN OLDER VERSION WORKED
THANK YOU AT LAST

**Comment by jobensingh** [comment]
Your welcome, I myself have had issues with 1.5.2 and I personally hate how the 2.0 works so u use 1.5.1, wish there was a way to get rid of the update notification though

**Comment by jobensingh** [comment]
Guess you can close it whenever you can now Khorki

**Comment by Khroki** [comment]
Yeah I'll close this now, but I'd like to know what version worked for you, so we can possibly fix it.

**Comment by Khroki** [comment]
And there are some issues with 1.5.2 we're trying to work out, will release a hotfix when we can. They seem to be compiler related.

**Comment by Nyannikins** [comment]
the one right before it, 1.5.1

And if this is still active I have one last question: the window is way too tall to fit my screen so my taskbar is covering all the buttons behind it. How do I resize it?  XD
