### ISSUE TITLE
Rotating Schematic Bug

### ISSUE THREAD

**Issue by Tenna** [Khroki/MCEdit-Unified#637]
Hello,

When I imported a schematic of a building into McEdit and then simply rotated it, all the wooden logs changed type. However, the direction of the logs were facing was not affected. For example, when I rotataed the schematic once, the oak logs turned into spruce, and when I rotated it again, the logs tuned into wood. From my observation, only wood is affected by this, though I could be wrong.
This bug only seems to affect McEdit version 1.5.2.0, and produced no error log of any sort.

**Comment by Khroki** [comment]
Did they change types in minecraft, or only in mcedit itself? The log rotations haven't changed in a long time so that's definitely strange.

**Comment by Khroki** [comment]
Fixed for next release, there was some old code interfering with logs.
