### ISSUE TITLE
World won't completely render, and I cannot move.

### ISSUE THREAD

**Issue by TheNerdyGinger** [Khroki/MCEdit-Unified#638]
When I load a world in MC Edit 1.5.2.0, the world does not completely render and looks weird. I also cannot move around. However, all of the functions of the program work fine. As you can see in the screenshot, I copied a selection of the world in front of me, and all of the correct blocks are there, but I cannot see it in the world. This is a 64 bit version on a 64 bit computer, and I am loading a 1.9.2 world.
![screenshot 15](https://cloud.githubusercontent.com/assets/18317395/14335804/1a70a632-fc2c-11e5-99da-bc91478dfdfb.png)
![screenshot 16](https://cloud.githubusercontent.com/assets/18317395/14335805/1bebb7c2-fc2c-11e5-9f6e-e48c1dee033d.png)

**Comment by Khroki** [comment]
Hmm, I wonder if that's not a side effect of the new window handler, does restarting mcedit fix it? also did it work in MCEdit 1.5.1?

**Comment by TheNerdyGinger** [comment]
No, nothing seems to fix it. I do not know what version I last had, but I had to download the new version today because the version I had suddenly started crashing repeatedly. It couldn't even start up. I had been using that version for months without any problems.

**Comment by Khroki** [comment]
If that's the case try to delete the contents of Documents/MCEdit, something most likely glitched out.

**Comment by TheNerdyGinger** [comment]
That worked! I basically deleted every mcedit file on my computer and re-downloaded it. Thanks!
