### ISSUE TITLE
cannot run: No module named OpenGL

### ISSUE THREAD

**Issue by klokie** [Khroki/MCEdit-Unified#642]
Hi, I'm interested in looking into issue #496 which is also affecting me (tools menu isn't available), but I'm having trouble getting the project to run from source on my Mac (OS 10.10.5). I have to admit I'm a noob when it comes to Python package management (though I'm an experienced dev), so any advice you have would be most welcome.

Here's the essence of my install process:
```
easy_install virtualenv
virtualenv ENV
. ENV/bin/activate

pip install PyOpenGL PyOpenGL_accelerate
pip install numpy
pip install hg+http://bitbucket.org/pygame/pygame
pip install pyyaml
pip install Pillow
pip install ftputil
pip install svn+https://svn.code.sf.net/p/python-xlib/code/trunk/
```
That all worked out ok, but when I try to run: 
```
$ python mcedit.py
Running in fixed mode. Support files are in your App Support Folder (Available from the main menu of MCEdit)
Splash load...
Traceback (most recent call last):
  File "mcedit.py", line 14, in <module>
    import OpenGL
ImportError: No module named OpenGL
(ENV)
```

Again, I'm no expert when it comes to Python packages, but I would think this should work:
```
$ python -c "from OpenGL import GL"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named OpenGL
(ENV)
```

Am I missing a package, or have I done something wrong? Thanks in advance!

**Comment by LaChal** [comment]
I'm not a virtualenv expert, but did you run MCEdit from the directory you installed MCEdit and its dependencies?

**Comment by Khroki** [comment]
Hmm, not completely sure about virtualenv, but are you trying to do this on the system python or did you download the current python? I ended up having to download the current python due to some compatibility issues with how apple tweaked the system one. Also pyopengl must be 3.0.2 or greater but we use 3.1.0 due to it fixing some bugs.

**Comment by klokie** [comment]
Yes, I'm trying to run `python mcedit.py` from the same directory as I've run the other commands listed in my previous post. Using Python 2.7.11, PyOpenGL 3.1.0.

**Comment by Khroki** [comment]
What happens if you try import opengl from the python interpreter?

**Comment by klokie** [comment]
Do you mean like this?
```
$ python
Python 2.7.11 (default, Dec  5 2015, 14:44:47)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import opengl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named opengl
>>> import pyopengl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pyopengl

**Comment by Khroki** [comment]
Hmm, it looks to me like your virtualenv is messed up somehow, either it's not activating or it's working through the system python.

**Comment by klokie** [comment]
You're probably right, but after spending hours on this, I can't seem to figure it out.
I've grepped the entire project as well as all my dotfiles and everything seems to indicate that the local Python is being used, but still opengl is not found.
Even deleting the `pymclevel` and MCEdit project folders and reinstalling doesn't reset the missing tool menu.

**Comment by Khroki** [comment]
I think I found your issue, according to a guide I found, to install modules in a virtual env, you need to do the following:

    Installing inside a virtualenv:

 # Example: pip install [env name] [package name]
 # This will either install inside an environment, or create one
 # Let's install requests inside a virtualenv called *venv*
 pip install -E venv requests

**Comment by klokie** [comment]
Thanks for the tip, but I'm afraid the `-E` option doesn't work with my pip (8.1.1).

Also, prefixing the package names with the environment name, e.g. 
  $ pip install ENV PyOpenGL PyOpenGL_accelerate
doesn't seem to have any effect, either on where the packages get installed (still in `./ENV/lib/python2.7/site-packages`, just as before) or in preventing the crash (still happens, due to missing `opengl` module). Any other ideas???

**Comment by Khroki** [comment]
hmm, not sure how the new pip does it, but if you're only using python for mcedit, do you need virtualenv at all?

**Comment by klokie** [comment]
It doesn't matter if I use virtualenv or not, the module just cannot be imported.

FWIW, it seems like I can successfully import modules like `pygame`, `numpy`, and `pip` that exist in my `/usr/local/lib/python2.7/site-packages`, whereas other modules that only include package metadata in a `.dist-info` subdirectory of that one such as e.g. `PyOpenGL-3.1.0.dist-info` or `PyYAML-3.11.dist-info` cannot be imported.

**Comment by LaChal** [comment]
Do you have `OpenGL` and `pyaml` directories alongside the `dist-info` files?
If yes, are they populated?

**Comment by Khroki** [comment]
Also try uninstalling pyopengl accelerate, we don't actually use it.

**Comment by Khroki** [comment]
Did you ever figure out what was wrong?

**Comment by klokie** [comment]
I think I figured out the problem, though I'm at a loss as to the cause or the solution. 
The problem is that pip is installing the `OpenGL` package, and only that package, as
`/usr/local/lib/python2.7/site-packages/Users/$USER/Library/Python/2.7/site-packages/OpenGL`. All other packages have been nicely installed into my `/usr/local/lib/python2.7/site-packages` directory.

I'll need to do some more research to figure out how to fix that.

**Comment by Khroki** [comment]
That is strange, have you tried installing via wheel? You can find common packages at http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyopengl in wheel format. to use them you'll need to install the wheel package though.

**Comment by klokie** [comment]
I'm already in over my head with `pip`, trying to avoid `wheel`… here's what I've done now:
```
# manually moved the OpenGL package to where it's supposed to be
$ mv -iv /usr/local/lib/python2.7/site-packages/Users/klokie/Library/Python/2.7/site-packages/* /usr/local/lib/python2.7/site-packages/
/usr/local/lib/python2.7/site-packages/Users/klokie/Library/Python/2.7/site-packages/OpenGL -> /usr/local/lib/python2.7/site-packages/OpenGL
/usr/local/lib/python2.7/site-packages/Users/klokie/Library/Python/2.7/site-packages/ftputil -> /usr/local/lib/python2.7/site-packages/ftputil

# install additional dependencies I didn't see listed anywhere else, trial and error here
$ pip install Cython
$ python setup.py build_ext --inplace
$ brew install libyaml
```
Now I get `ImportError: No module named yaml`, even having tried the usual `pip` commands plus
```
$ sudo python -m easy_install pyyaml
$ sudo pip install PyYAML
```
I'm giving up, this is far too much of a time sink just to try to fix a UI bug in MCedit. If there's any way you could put together a Docker file then I'd be willing to have another go.

Thanks again for your help.

**Comment by Khroki** [comment]
I'm not sure what a docker file is, but wheels are relatively simple, just install the wheel module then pip install directory/wheelfilenamehere.whl

**Comment by klokie** [comment]
> just install the wheel module then pip install directory/wheelfilenamehere.whl

Ok, maybe if I have time in the future I will give it a shot.

> I'm not sure what a docker file is, sorry.

It's a single file that encapsulates all the dependencies for any dev project, in a working setup that anyone running Mac, Linux or Windows can quickly and easily get up and running in a manner of seconds, rather than weeks. It's my hope that Docker will help eliminate these sorts of issues (i.e. "works on my machine") in the future.

See [Why and How to Use Docker for Development](https://medium.com/iron-io-blog/why-and-how-to-use-docker-for-development-a156c1de3b24#.1nez27wh2).
cheers

**Comment by Khroki** [comment]
I can see docker being useful, but those examples don't mean much to me, not being python or osx/windows examples (Not good with Linux).

**Comment by Khroki** [comment]
Read more into it, docker won't work because I develop OSX in a VMWare virtual machine, I can't run the requisite oracle VM software inside that VM.

**Comment by binitshah** [comment]
Kinda hacky, but have you tried:

```
import sys
sys.path.append('/usr/local/lib/python2.7/site-packages/Users/$USER/Library/Python/2.7/site-packages/OpenGL')
```
