### ISSUE TITLE
mcplatform.py needs to import subprocess

### ISSUE THREAD

**Issue by bencoman** [Khroki/MCEdit-Unified#643]
Having cloned the repository, running
   python mcedit.py 

produces that following...
Traceback (most recent call last):
  File "/home/minecraft/Repos/MCEdit-Unified/mcplatform.py", line 611, in is_running
    s = subprocess.Popen(["tasklist", "/v"],stdout=subprocess.PIPE)
NameError: global name 'subprocess' is not defined

Its starts okay after editing mcplatform.py as follows...
    import subprocess    # <---ADDED
    import logging
    log = logging.getLogger(__name__)

HTH, Ben

**Comment by Khroki** [comment]
That's odd, never seen that before, What version of python are you using and what OS?

**Comment by LaChal** [comment]
I can see the cause: the import is effectively missing.

@Ben, you're running on a Linux platform, with xfce-mcs-manage or ksmserver desktop environment, right?
