### ISSUE TITLE
Crash on startup: 'ascii' codec can't encode character u'\xfc'

### ISSUE THREAD

**Issue by L3ice** [Khroki/MCEdit-Unified#644]
> Running in fixed mode. Support files are in your Documents folder.
> Splash load...
> [ WARNING][            mcplatform.py:1182]:Initializing window management...
> Minecraft_Server.jar storage initialized.
> Each server is stored in a subdirectory of C:\Users\Robin\Documents\MCEdit\ServerJarStorage named with the server's version number
> Cached servers:  []
> mcedit.main MCEdit exited with errors.
> [   ERROR][                  root.py:1006]:MCEdit version Unified v1.5.2.1 %s Minecraft 1.8/1.9 | PE 0.11
> [   ERROR][                  root.py:1009]:'ascii' codec can't encode character u'\xfc' in position 27: ordinal not in range(128)
> Traceback (most recent call last):
>   File "<string>", line 1003, in main
>   File "<string>", line 734, in main
>   File "<string>", line 256, in __init__
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 27: ordinal not in range(128)
> Press RETURN or close this window to dismiss.

**Comment by LaChal** [comment]
Running on Windows, right?

**Comment by L3ice** [comment]
Windows 10 64 Bit

**Comment by LaChal** [comment]
OK.
I'm not surprized...

After some debugging, pygame does not support unicode strings as window titles.
Actually working on :smile:
