### ISSUE TITLE
Bug with signs

### ISSUE THREAD

**Issue by Mikeoz28** [Khroki/MCEdit-Unified#645]
Signs lose their text. I have found this with 1.5.2.1 64bit. Extract and save then place back in a world sign is still there but no text. 1.5.2.0 okay.

**Comment by LaChal** [comment]
Thank you for the report!

This issue has already been reported [elsewhere](https://www.reddit.com/r/MCEdit/comments/4ekwr6/signs_being_blanked_after_relighting_chunks/), and is fixed for the next release :smile:
