### ISSUE TITLE
Error during saving

### ISSUE THREAD

**Issue by Robbeedee** [Khroki/MCEdit-Unified#647]
Hi there,

Getting an error message when attempting to save any pocket edition world in 1.5.2.1. Error message is;

`Error during <function saveFile at 0x118492a8>:
TypeError("'generator' object is not callable",)`

Any help on what I could do to fix?

**Comment by naor2013** [comment]
Can you send the error from the console?

**Comment by Robbeedee** [comment]
Sorry. had to learn how to do that...


17/04/2016 11:15:05.653 PM mcedit[2056]: [   ERROR][                    root.py:62]:Exception:
17/04/2016 11:15:05.654 PM mcedit[2056]: Traceback (most recent call last):
17/04/2016 11:15:05.654 PM mcedit[2056]:   File "mceutils.pyc", line 56, in _alertException
17/04/2016 11:15:05.654 PM mcedit[2056]:   File "leveleditor.pyc", line 1376, in saveFile
17/04/2016 11:15:05.654 PM mcedit[2056]:   File "albow/extended_widgets.pyc", line 349, in showProgress
17/04/2016 11:15:05.654 PM mcedit[2056]:   File "albow/widget.pyc", line 546, in present
17/04/2016 11:15:05.654 PM mcedit[2056]:   File "albow/root.pyc", line 233, in run_modal
17/04/2016 11:15:05.654 PM mcedit[2056]:   File "albow/widget.pyc", line 787, in gl_draw_all
17/04/2016 11:15:05.654 PM mcedit[2056]:   File "albow/widget.pyc", line 794, in gl_draw_all
17/04/2016 11:15:05.654 PM mcedit[2056]:   File "albow/widget.pyc", line 355, in draw_all
17/04/2016 11:15:05.654 PM mcedit[2056]:   File "albow/extended_widgets.pyc", line 265, in draw
17/04/2016 11:15:05.654 PM mcedit[2056]:   File "leveleditor.pyc", line 1372, in copyChunks
17/04/2016 11:15:05.654 PM mcedit[2056]:   File "pymclevel/leveldbpocket.pyc", line 604, in saveInPlaceGen
17/04/2016 11:15:05.654 PM mcedit[2056]: TypeError: 'generator' object is not callable

**Comment by Robbeedee** [comment]
For the record, this is running on Mac OSX
