### ISSUE TITLE
mcedit didnt load last update

### ISSUE THREAD

**Issue by ki2005kevin** [Khroki/MCEdit-Unified#650]
Hi guys i have a problem here.i used quick load to my world
but its only load the old update. also after edit in mcedit. i saved and quit but it didnt change in the game. i have been deleted and download mcedit again. the problem still here.
is any way to fix it?? plz tell me

**Comment by LaChal** [comment]
Hi!

What do you mean with 'old update'? Is this an old 'version' of your world
Did you try the 'Open' option in the MCEdit main menu?
What is the version of MCEdit you use?

**Comment by ki2005kevin** [comment]
i just download minecraft and update to version 1.9 and then i copy my old save date and replace on it.
Then i  get in to the game and update the save data. after i download mcedit release version, exhaust it and open my world then i have been change edited the world and save. then i open my world in the game, but it didnt change either i edit my world in the game and save. it didnt change in mcedit when i click quick load

**Comment by Khroki** [comment]
I'm having some trouble understanding the problem, but if I'm reading it right we recommend against opening the world in both mcedit and minecraft at the same time, and it won't refresh unless you close and reopen the world.

If mcedit broke due to messing with files, delete the mcedit folder where you extracted it and in your documents folder.

**Comment by ki2005kevin** [comment]
now i got the issus
![error](https://cloud.githubusercontent.com/assets/18581571/14754781/7426158a-08d5-11e6-9d61-71ea500ebd26.png)

when i open mcedit, it displays this black command then closed by itself

**Comment by Khroki** [comment]
Did you completely delete the mcedit folder in documents?

**Comment by Khroki** [comment]
Could you try the latest version?

**Comment by LaChal** [comment]
No answer from the post author for more than one year.
Closing...
