### ISSUE TITLE
1.5.2.1 Crash after changing language

### ISSUE THREAD

**Issue by fhfuih** [Khroki/MCEdit-Unified#652]
In the latest 1.5.2.1 release only, after changing the language(whether in ASCII or Unicode) and close MCEdit, you can't open it again. The only way is to delete mcedit.ini, which will reset the preference, including language setting, of MCEdit. 
Error log:
![default](https://cloud.githubusercontent.com/assets/11222265/14744133/fd8c1732-08d7-11e6-9b42-2879206f0eb7.PNG)

**Comment by LaChal** [comment]
This bug is known, and has been reported as #644.
It is already fixed in the source code :wink:

My advice is to edit you language resource file and remove the translation for the string \#949.

**Comment by fhfuih** [comment]
Oh, sorry I missed that issue. :sweat_smile:

**Comment by Khroki** [comment]
It's alright, we should have tested that change in non-latin languages before releasing with it. We should have a new build soonish, all depends when I get the time to redo the build environment.
