### ISSUE TITLE
Rotate schematic

### ISSUE THREAD

**Issue by JCBianor** [Khroki/MCEdit-Unified#653]
I would like to make a statement about something missing in the program: Option rotaqcionar a schematic. For example the pixel arts, which are perhaps the largest source of search for your program, however the schematic are always in wonderful vertical.a position has a tool to lay it. This could be of great help to the world of builders, using a pixel art of any program to generate a detailed map for example.
I appreciate your generozidade for offering us this wonderful tool called mcedit.

**Comment by Khroki** [comment]
If I understand this correctly you want to rotate a vertical schematic flat, why not use the existing roll function?

**Comment by JCBianor** [comment]
I apologize for my English terribly translated. My question was about rotate an object in an angle that I want. For example the tower of Pisa. I tried to do up there in his hand, but was terrible kkkk. Using pixel art and trying to fill to make it cylindrical. Google translate has not helped me as before hahaha

**Comment by Khroki** [comment]
I think there is a filter that can do that, try searching around for it. As far as built in functionality we don't really plan to add something of that sort.

**Comment by JCBianor** [comment]
Thank you for your kindness. You were very attentive to me to answer. Thank you.

**Comment by Khroki** [comment]
No problem, going to close the issue now.
