### ISSUE TITLE
Can't start programm / crash in MCEdit Unified v1.5.2.

### ISSUE THREAD

**Issue by HimbeersaftLP** [Khroki/MCEdit-Unified#655]
When using this version the program crashes immediately after starting. Using Mac

**Comment by Khroki** [comment]
Are you using a translation that doesn't use latin characters?

**Comment by HimbeersaftLP** [comment]
I did use Enlglish as language, I even couldn't change it, bacause I can't open the programm

**Comment by Khroki** [comment]
Could you post the error from the system log?

**Comment by Khroki** [comment]
Could you try the latest release to see if it fixes it?

**Comment by HimbeersaftLP** [comment]
Sorry that I couldn't response, but I had no time to go to my PC.Will try in the afternoon.

**Comment by HimbeersaftLP** [comment]
Thx it works now!

**Comment by LaChal** [comment]
Great!

Thank you for the feedback.

**Comment by HimbeersaftLP** [comment]
But wait! Now I can't load worlds anymore... When I klick on load. Nothing happens. When I close the window then, this error pops up: 

![mcediterror](https://cloud.githubusercontent.com/assets/16354747/15439274/6f80cf5a-1ed0-11e6-9057-be771275ff24.png)

**Comment by Khroki** [comment]
We'd need the actual error, which would be in the system wide OSX console. If you can get that we can likely figure out what's wrong.

**Comment by HimbeersaftLP** [comment]
I made a new issue: #674

**Comment by HimbeersaftLP** [comment]
#674
