### ISSUE TITLE
MCEdit doesn't load correctly

### ISSUE THREAD

**Issue by BossosaurusRex** [Khroki/MCEdit-Unified#657]
So, I'm using the latest version of MCEdit(1.5.2.1), and when I load the application, the cmd popup and "MCEdit is Loading" logo thing comes up, but then, the logo disappears and a whole ton of text(errors, I assume) come up on the cmd popup. This is what happens every time I load the application.

![capture](https://cloud.githubusercontent.com/assets/19158959/14971674/7a8d64b2-10a2-11e6-894b-cf6c01fe1043.PNG)

My computer's specs: Windows 7, Intel core i7, 64 bit, 8 gigs of ram(7.8 gb usable), about 23 gigs of space free on my hard drive.

I have redownloaded multiple versions of MCEdit and relaunched it, but every time, I get the same result. I have searched the internet for a solution, but I can't seem to find an answer that matches my error. In case you need, here is a screenshot of my mcedit folder.

![capture2](https://cloud.githubusercontent.com/assets/19158959/14971740/32e65a14-10a3-11e6-8895-aea3414344f3.PNG)

I have no experience as a coder, and I only created this github acount to post this issue, so please don't facepalm if this is a really simple problem that any coder can fix.

If you respond with a solution to my problem, I will try it immediately and respond ASAP if it worked or not. Thank you in advance.

**Comment by Khroki** [comment]
What is your system's video card? That looks like a driver problem and would likely be fixed by a graphics driver update depending what card you have..

**Comment by BossosaurusRex** [comment]
![capture3](https://cloud.githubusercontent.com/assets/19158959/14995235/b7b52d12-1141-11e6-9a55-9b7072d88fd9.PNG)

Ok, this is what I found about my graphics card.

**Comment by BossosaurusRex** [comment]
Ok, I checked my graphic card updater thingy and I found that my graphics card _is_ up to date. So this might not be the graphic's card problem. I have used MCEdit on this computer before, and it worked perfectly. But now, for some reason, it doesn't work. Yesterday, when I clicked on the MCEdit application, it didn't work, so I posted this issue. But about 2 weeks ago, MCEdit was working fine.

**Comment by LaChal** [comment]
No update on you computer since two weeks?

Did you used the same MCEdit version until two weeks ago?

By the way, having a graphics card (especially Intel ones) may be the problem. But I 'll let people with more knowledge about this answer :wink:

**Comment by BossosaurusRex** [comment]
I found that I used MCEdit 3 weeks ago rather than 2. I used version 1.5.2.1 just as it came out. Also, I checked my computer update history, and yes, there were exactly 24 windows updates from now and then(some failed, and others successful).

**Comment by Khroki** [comment]
There was a huge windows update about a week ago that resolved some long standing problems, it may have done something with your drivers. Could you give us some more information on your video card such as cpu model or the specific intel card, there is a known issue with second gen intel graphics chips which has a potential workaround.

**Comment by Khroki** [comment]
Also the built in driver update checker often doesn't actually check the manufacturer's site, only Microsoft's driver repository.

**Comment by BossosaurusRex** [comment]
I think I have all the driver information in this screenshot

![capture4](https://cloud.githubusercontent.com/assets/19158959/15029155/6685f816-121a-11e6-9c5b-15144c3b57a7.PNG)

**Comment by Khroki** [comment]
Well, the actual model is missing, if you could get the CPU model from the system information pane I can look it up.

**Comment by BossosaurusRex** [comment]
Ok, I found my system model, which is 0831CTO.

**Comment by BossosaurusRex** [comment]
Okay, I just decided to run MCEdit for no apparent reason, and it worked! I swear it didn't work for me when I posted this issue, so I have no idea why it just started to work all of a sudden. I guess if MCEdit doesn't work, you just wait for a bit or something. I don't know. **:/**

**Comment by Khroki** [comment]
That's a first gen i7, haven't heard problems from them in the past, ah well at least it works now.
