### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by phrilser** [Khroki/MCEdit-Unified#658]
Didn't have any outstanding issues with the install (the NBT speedtest failed, but I recompiled as prompted by the installer, and it seemed satisfied enough to move forward), but running the program will only bring up the splash before it stops completely.
Here's the terminal readout:

> Starting MCEdit...
*** APP DIR: /home/philip/mcedit
Running in fixed mode. Support files are in your Documents folder.
Splash load...
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/release-master/MCEdit-Unified/__main__.py", line 38, in <module>
  File "/tmp/release-master/MCEdit-Unified/mcedit.py", line 73, in <module>
  File "/tmp/release-master/MCEdit-Unified/keys.py", line 4, in <module>
  File "/tmp/release-master/MCEdit-Unified/albow/__init__.py", line 13, in <module>
  File "/tmp/release-master/MCEdit-Unified/albow/fields.py", line 21, in <module>
  File "/tmp/release-master/MCEdit-Unified/pyperclip.py", line 179, in <module>
Exception: Pyperclip requires the gtk module installed or the xclip command.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/tmp/release-master/MCEdit-Unified/version_utils.py", line 54, in save
AttributeError: PlayerCache instance has no attribute '_cache'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/tmp/release-master/MCEdit-Unified/version_utils.py", line 54, in save
AttributeError: PlayerCache instance has no attribute '_cache'

And system info from inxi:
>System:    Host: [redacted] Kernel: 4.5.0-040500-generic x86_64 (64 bit)
           Desktop: KDE Plasma 5.5.5 Distro: Ubuntu 16.04 xenial
Machine:   Mobo: Acer model: Zoro_SL v: V1.10 Bios: Insyde v: V1.10 date: 11/27/2015
CPU:       Dual core Intel Core i5-6200U (-HT-MCP-) cache: 3072 KB 
           clock speeds: max: 2700 MHz 1: 499 MHz 2: 499 MHz 3: 499 MHz 4: 499 MHz
Graphics:  Card: Intel Sky Lake Integrated Graphics
           Display Server: X.Org 1.18.3 drivers: intel (unloaded: fbdev,vesa)
           Resolution: 1366x768@60.03hz
           GLX Renderer: Mesa DRI Intel HD Graphics 520 (Skylake GT2)
           GLX Version: 3.0 Mesa 11.2.0
Audio:     Card Intel Sunrise Point-LP HD Audio driver: snd_hda_intel
           Sound: Advanced Linux Sound Architecture v: k4.5.0-040500-generic
Network:   Card-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
           driver: r8169
           IF: enp1s0 state: up speed: 1000 Mbps duplex: full mac: [redacted]
           Card-2: Qualcomm Atheros Device 0042 driver: ath10k_pci
           IF: wlp2s0 state: up speed: N/A duplex: N/A mac: [redacted]
Drives:    HDD Total Size: 1000.2GB (33.5% used)
           ID-1: /dev/sda model: WDC_WD10JPVX size: 1000.2GB
Partition: ID-1: / size: 910G used: 305G (36%) fs: ext4 dev: /dev/sda1
           ID-2: swap-1 size: 8.45GB used: 0.00GB (0%) fs: swap dev: /dev/sda5
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 40.0C mobo: N/A
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 200 Uptime: 2:26 Memory: 2153.4/7850.1MB
           Client: Shell (bash) inxi: 2.2.35

**Comment by Khroki** [comment]
Try deleting MCEdit's player cache, it should be stored with the configuration files, I'm not entirely sure where it's stored on Linux, but I think it's somewhere in the home folder.

**Comment by phrilser** [comment]
Thank you for the suggestion.
I found a usercache.json in ~/.mcedit/MCEdit/, deleted it, then ran MCEdit. Same readout as before, unfortunately.

**Comment by LaChal** [comment]
> Pyperclip requires the gtk module installed or the xclip command.

Looks like you need to install GTK or xclip on your system.
(xclip has been removed in Ubuntu 16.04?)

By the way, the speed test failure will not prevent the NBT binary to work properly.

**Comment by phrilser** [comment]
And xclip was exactly the thing, it seems. Everything working smoothly now.
I'd tried installing MCEdit a while ago on Kubuntu 15.10 and hadn't had any luck then, either. Not sure, though, if the errors were related, or if xclip had been present or not.
Would it be possible to add xclip to the dependency check?
Thank you both for the fix and for the software.

**Comment by LaChal** [comment]
Thank you for the report.
xclip will be added to the dependency list on Linux :smile:
