### ISSUE TITLE
[Filter] Create Villager Shop - custom head not working

### ISSUE THREAD

**Issue by Azounstone** [Khroki/MCEdit-Unified#662]
Hello,

When using the Shop filter it does not add a custom head to the Villager. Everything else with the filter works but not the custom head which is an issue as I need to add over 100 custom NPC shops to an adventure map.

I am using Minecraft 1.9.2 and the latest release of MCEdit.

Would you be able to fix this for me please?

**Comment by Azounstone** [comment]
Do you have any idea when I could expect this to be fixed?

Regards,

**Comment by Khroki** [comment]
Fixed, if you don't want to wait for next release, you can download the filter at https://www.dropbox.com/s/813rdall4gy7han/CreateShops.py?dl=0.

**Comment by Azounstone** [comment]
Hi,

Thank you so much for fixing this so quickly. I really appreciate it :)

Regards,

Andy

**Comment by Khroki** [comment]
No problem, you can blame this one on mojang changing the tag format for equipment in 1.9.

**Comment by Azounstone** [comment]
I will blame it on them along with several other things :)

Thanks again, much appreciated!

**Comment by Azounstone** [comment]
Hello,

I have just gone to add the hundreds of NPCs to our adventure map and there is an issue with the filter that is delaying our launch. Allow me to explain.

I do not want a name for the village shop so I leave the name field empty however if you look at the shop in the game it has the name of the type of villager it is showing in black lettering.

Would you be able to edit the filter for me please to stop this from happening? If there is no name there should be no name showing.

Many thanks in advance for your help with this :)

Andy
