### ISSUE TITLE
Mcedit Save error

### ISSUE THREAD

**Issue by eastofgrand** [Khroki/MCEdit-Unified#664]
I have a minecraft pocket edition world which I have editied with mcedit in the past. I've frequently had to use mcedit's "relight" feature to fix lighting glitches. however, recently every time I try to save I get this:

![screen shot 2016-05-08 at 4 23 41 pm](https://cloud.githubusercontent.com/assets/19255397/15100505/4be0d536-1539-11e6-8eff-9e5fe4aa2fbf.png)

I don't have much experience with code or anything and I really have no idea what the problem is. I kind of assume that it has something to do with stone brick since 98 is it's value, but other than that i'm clueless. Any help is appreciated.

**Comment by hdjackill** [comment]
I'm running into the exact same error but its not the stone bricks cause my edits were with smooth stone. Also I know this unrelated to the topic but are you a map maker and if so were can I download them?

**Comment by Khroki** [comment]
Question, by any chance do both of these worlds have nethers? and if they do does it work if you try a world with no nether?

**Comment by LaChal** [comment]
Can you send MCEdit log entries, please?

This will help us to track the exact cause of the problem.

**Comment by Khroki** [comment]
Try the latest build, we (Lachal) has added code to handle missing entities on pocket.

**Comment by L3ice** [comment]
Missing entities are handled correct for me in the log.
Thanks :)
