### ISSUE TITLE
[MAJOR BUG] mcedit.ga is unavailable

### ISSUE THREAD

**Issue by hron84** [Khroki/MCEdit-Unified#669]
Your webpage (http://khroki.github.io/MCEdit-Unified/) redirects to mcedit.ga which is unavailable (confirmed by [IsUp.ME](http://isup.me/mcedit.ga)). Please take a look into it, mcedit 1.x versions aren't public anymore in this way.

Note: this is a crosslinked issue with mcedit/mcedit.github.com#2. Please, please work together on some solution, at least remove the misleading links and/or the broken redirection.

**Comment by naor2013** [comment]
We have the same site in this link: http://www.mcedit-unified.net
We're trying to fix the issue and hope the site would be back soon

**Comment by Khroki** [comment]
I fixed it, it now no longer redirects although it may take a bit before your local DNS updates.
