### ISSUE TITLE
MCEdit 1.5.3 64-Bit crashes on startup after upgrade from 1.5.2.1

### ISSUE THREAD

**Issue by GafferWiles** [Khroki/MCEdit-Unified#670]
Extracting the MCEdit files and into the mcedit folder on Program Files on Wiondows 7 64-Bit Pro caused a crash a spit second after the cmd window opens up on startup. Tried downloading the install again, deleting the entire mcedit folder and extracting into that folder. If I return to MCEdit 1.5.2.1 anc empty out the folder and copy 1.5.2.1 acrss the program works 100%, but not 1.5.3...
No log was generated in MCEdit

**Comment by Khroki** [comment]
Could you run it from the command line and post what appears?

**Comment by Dushess** [comment]
32-bit version too.

**Comment by Khroki** [comment]
What version of windows are you on?

**Comment by Dushess** [comment]
XP SP3

**Comment by Khroki** [comment]
I suspect it may be broken for all non-Windows 10 users, going to try and rebuild the windows releases.

**Comment by hdjackill** [comment]
For me Mcedit 1.5.2.1 crashes upon start up but occasonaly will let me use it, when it does it crashes a short time later. I am currently using the latest version of Windows 10 and MC:PC 1.9.4

**Comment by Khroki** [comment]
could anyone having this problem try this build and let me know if it fixes it? https://www.dropbox.com/s/pau7qkhclakhnzq/mcedit.exe?dl=0

**Comment by Khroki** [comment]
New builds uploaded to the main site, redownload from there if you want the fixed 64 bit version. 32bit is identical to the link above. Reopen if you are still having problems.

**Comment by GafferWiles** [comment]
I ran it from a command prompr on my Windows 7 64-bit machine: "Error loading Python DLL: ...path\mcedit\python27.dll (error code 140001)"

Hope that helps!

**Comment by Dushess** [comment]
WIn XP Pro 32-bit (SP3)
Started normally.
Basic functional - normal. Full check will do tomorrow.

**Comment by Khroki** [comment]
Gaffer, did you delete the prior download and re-download from the release page at https://github.com/Khroki/MCEdit-Unified/releases/tag/1.5.3.0 ?

**Comment by GafferWiles** [comment]
I did it before but after downloading the new build I see that the issue is resolved. So it was the Python dll issue. Many thanks. This  issue report can be closed. GW

-----Original Message-----
