### ISSUE TITLE
Cam't load world in version 1.5.3.0

### ISSUE THREAD

**Issue by HimbeersaftLP** [Khroki/MCEdit-Unified#674]
When I klick on load. Nothing happens. When I close the window then, this error pops up:
![error](https://cloud.githubusercontent.com/assets/16354747/15439274/6f80cf5a-1ed0-11e6-9057-be771275ff24.png)
Here's my console output:
###### When starting:
> 26.05.16 13:52:41,569 mcedit[882]: Running in fixed mode. Support files are in your App Support Folder (Available from the main menu of MCEdit)
26.05.16 13:52:41,938 mcedit[882]: Splash load...
26.05.16 13:52:42,250 mcedit[882]: 13:52:42.249 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
26.05.16 13:52:42,250 mcedit[882]: 2016-05-26 13:52:42.250 mcedit[882:401676] 13:52:42.249 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
26.05.16 13:52:43,432 mcedit[882]: [ WARNING][      pymclevel.BOParser.py:16]:The `bo3.def` file is missing in `/Users/censured/Desktop/mcedit.app/Contents/Resources`. The BO3 support will not be complete...
26.05.16 13:52:43,476 mcedit[882]: [ WARNING][            mcplatform.py:1184]:Initializing window management...
26.05.16 13:52:43,488 mcedit[882]: Minecraft_Server.jar storage initialized.
26.05.16 13:52:43,488 mcedit[882]: Each server is stored in a subdirectory of /Users/censured/Library/Application Support/pymclevel/ServerJarStorage named with the server's version number
26.05.16 13:52:43,488 mcedit[882]: Cached servers:  [u'Snapshot Unknown']

###### When loading the world:
> 26.05.16 13:53:33,644 mcedit[882]: [   ERROR][                   root.py:644]:Failed to load file /Users/censured/Library/Application Support/minecraft/saves/Hallo/level.dat: UnicodeEncodeError('ascii', u'Hallo/level.dat - MCEdit ~ Unified v1.5.3.0 f\xfcr Minecraft 1.8/1.9 | PE 0.11', 45, 46, 'ordinal not in range(128)')

###### When closing the program then:
> 26.05.16 14:01:39,316 mcedit[882]: Shutting down...
26.05.16 14:01:39,316 mcedit[882]: mcedit.main MCEdit exited with errors.
26.05.16 14:01:39,316 mcedit[882]: [   ERROR][                  root.py:1006]:MCEdit version Unified v1.5.3.0 %s Minecraft 1.8/1.9 | PE 0.11
26.05.16 14:01:39,320 mcedit[882]: Traceback (most recent call last):
26.05.16 14:01:39,320 mcedit[882]:   File "/Users/censured/Desktop/mcedit.app/Contents/Resources/mcedit.py", line 1066, in <module>
26.05.16 14:01:39,321 mcedit[882]:   File "/Users/censured/Desktop/mcedit.app/Contents/Resources/mcedit.py", line 1003, in main
26.05.16 14:01:39,321 mcedit[882]:   File "/Users/censured/Desktop/mcedit.app/Contents/Resources/mcedit.py", line 854, in main
26.05.16 14:01:39,321 mcedit[882]:   File "waypoints.pyc", line 82, in save
26.05.16 14:01:39,321 mcedit[882]:   File "posixpath.pyc", line 70, in join
26.05.16 14:01:39,321 mcedit[882]: AttributeError: 'NoneType' object has no attribute 'endswith'
26.05.16 14:01:39,321 mcedit[882]: Traceback (most recent call last):
26.05.16 14:01:39,321 mcedit[882]:   File "/Users/censured/Desktop/mcedit.app/Contents/Resources/__boot__.py", line 399, in <module>
26.05.16 14:01:39,321 mcedit[882]:     _run()
26.05.16 14:01:39,321 mcedit[882]:   File "/Users/censured/Desktop/mcedit.app/Contents/Resources/__boot__.py", line 336, in _run
26.05.16 14:01:39,321 mcedit[882]:     exec(compile(source, path, 'exec'), globals(), globals())
26.05.16 14:01:39,321 mcedit[882]:   File "/Users/censured/Desktop/mcedit.app/Contents/Resources/mcedit.py", line 1081, in <module>
26.05.16 14:01:39,321 mcedit[882]:     raw_input("Press the Enter key to close this window")
26.05.16 14:01:39,321 mcedit[882]: EOFError: EOF when reading a line
26.05.16 14:01:39,321 mcedit[882]: ==================================
26.05.16 14:01:39,321 mcedit[882]: 			  MCEdit has crashed
26.05.16 14:01:39,321 mcedit[882]: ==================================
26.05.16 14:01:39,444 mcedit[882]: mcedit Error
26.05.16 14:01:39,444 mcedit[882]: 2016-05-26 14:01:39.443 mcedit[882:401676] mcedit Error

**Comment by Khroki** [comment]
Looks like a unicode error when loading the world, could you try making sure your world does not have any non-English characters in it's name?

**Comment by HimbeersaftLP** [comment]
My username is only with small (English) letters and the world name was "Hallo" but I also tried with "dukmecommands" which is only in small letters...

**Comment by Khroki** [comment]
Oh, I think I see the problem, could you change the program's language to english and try again?

**Comment by HimbeersaftLP** [comment]
Tried again and: No errors.

**Comment by Khroki** [comment]
@LaChal The titlebar translation function is erroring on world load. We should fix that.

**Comment by Khroki** [comment]
If you go into the german translation file and remove the umlaut from für on translation line 949 it should work again, at least until we fix that.

**Comment by HimbeersaftLP** [comment]
Thx

**Comment by LaChal** [comment]
This error shall no more happen with the #682 changes.
