### ISSUE TITLE
[Filter] Create Villager Shop - Naming Issue

### ISSUE THREAD

**Issue by Azounstone** [Khroki/MCEdit-Unified#675]
I replied to a closed issue but not sure if it will be seen so I have opened another issue for this:

Hello,

I have just gone to a LOT of NPCs to our adventure map and there is an issue with the filter that is delaying our launch. Allow me to explain.

I do not want a name for the village shop so I leave the name field empty however if you look at the shop in the game it has the name of the type of villager it is showing in black lettering above the villager when you mouse over.

Would you be able to edit the filter for me please to stop this from happening? If there is no name there should be no name showing.

Many thanks in advance for your help with this :)

Andy

**Comment by Khroki** [comment]
Hmm, I'll try to look at this in the next few days to see if I can add that option.

**Comment by Azounstone** [comment]
Excellent and many thanks!
I look forward to seeing this :)

**Comment by Khroki** [comment]
Done for next release, if you want it now it's here http://lavaexpert.org/createshops.zip

**Comment by Azounstone** [comment]
Many thanks!

**Comment by Azounstone** [comment]
I am not seeing this checkbox in the latest version that I just downloaded to a different pc?

**Comment by LaChal** [comment]
The latest version (1.5.3.0) does not contain the new version of this filter. Future releases will.

You also can get the filter from here: https://raw.githubusercontent.com/Khroki/MCEdit-Unified/master/stock-filters/CreateShops.py

Just 'save as' the page :smile:

**Comment by Azounstone** [comment]
Okay thanks for clearing this up :)
