### ISSUE TITLE
New time editor react weirdly to mouse wheel scrolling

### ISSUE THREAD

**Issue by fhfuih** [Khroki/MCEdit-Unified#677]
On scrolling the time value in "World Info", it switches between AP and PM, rather than adjusts the time value.

**Comment by Khroki** [comment]
Did you interact with the AM/PM setting last? It may just be defaulting to the last used thing.

**Comment by fhfuih** [comment]
Oh, sorry it's my fault. The value bar reacts differently when I point my cursor to different fields of the value. I was pointing at "AM" at that time so I thought it's a bug. :sweat_smile:
