### ISSUE TITLE
MCedit filter Bug : Create Shop.

### ISSUE THREAD

**Issue by Swaggydogy** [Khroki/MCEdit-Unified#680]
hi im French, i on MacBook Pro version 10.10.5 and i use MCedit version 1.5.3.0 in minecraft 1.9.3.
(Before it worked but now nothing...)
So i have make the chest perfectly:
![capture d ecran 2016-05-29 a 14 20 02](https://cloud.githubusercontent.com/assets/19621748/15633237/df42354e-25a7-11e6-829f-ebefac85d284.png)

And i use the filter from Mcedit: Create Shop, make a personal farmer villager named "Jean" and it make this error:
![capture d ecran 2016-05-28 a 21 47 58](https://cloud.githubusercontent.com/assets/19621748/15633240/0680a5e6-25a8-11e6-89fb-3a2b03809f35.png)

Please help me...

How to make this never happened again

**Comment by Khroki** [comment]
We're going to need the console output, mcedit's output is put into the system console under applications -> utilities.

**Comment by LaChal** [comment]
Can you switch to English before using this filter?
Is this error still happen, then?

**Comment by Swaggydogy** [comment]
i try how to change the languages?

**Comment by Swaggydogy** [comment]
i don't know how to see the console, can see the console on the application mcedit?

**Comment by Swaggydogy** [comment]
Ha ok they must solve this for french it's work on english!!!! thank you!!! LaChal :D but i still don't know for French... and see the console...

**Comment by LaChal** [comment]
For the console, see Khroki post.

To change MCEdit language, just look in the options. You can open the options through the main menu (accessible at startup or the `Menu` button when editing a world).


<hr>
Pour la console, Khroki indique qu'on peut la trouver dans Applications --> Utilitaires (ou Accessoires ou quelque chose comme ça en français, désolé, je n'ai pas de Mac...).

La langue de MCEdit se change dans les options du programme. On peut y accéder via le menu principal (visible au démarrage, ou en cliquant sur le bouton `Menu` quand un monde est chargé).

**Comment by Swaggydogy** [comment]
here a screenshot:
![capture d ecran 2016-05-29 a 21 39 11](https://cloud.githubusercontent.com/assets/19621748/15635650/3a24f482-25e5-11e6-86e6-4cb524b26aeb.png)

**Comment by LaChal** [comment]
Looks like you don't have the version of this filter used in the release.

The screenshot you gave show a `Library/Application Support/pymclevel/filters` in your user's folder.
Try to override the `CreateShops.py` file in this folder with this file: [CreateShops.py](https://raw.githubusercontent.com/Khroki/MCEdit-Unified/522a7f9c70639eb09770c179cfc0de6e3c8130f6/stock-filters/CreateShops.py). (This is the filter as it is in the 1.5.3.0 release.)

<hr>

On dirait que ce filtre n'est pas comme il devrait l'être dans la dernière release.

Le screenshot de la console indique un répertoire `Library/Application Support/pymclevel/filters` dans le dossier de l'utilisteur.
Il faudrait essayer de remplacer le fichier `CreateShops.py` qui s'y trouve par celui-ci: [CreateShops.py](https://raw.githubusercontent.com/Khroki/MCEdit-Unified/522a7f9c70639eb09770c179cfc0de6e3c8130f6/stock-filters/CreateShops.py). (C'est le filtre tel qu'il est dans la release 1.5.3.0.)

**Comment by Swaggydogy** [comment]
Thank,you!! it's worked! tank you all!

**Comment by Khroki** [comment]
Good stuff, closing this issue.
