### ISSUE TITLE
Windows 10, MCEdit 1.5.3.0 start crash

### ISSUE THREAD

**Issue by Xbox180** [Khroki/MCEdit-Unified#691]
When I started MCEdit the first time, it starts normally, the splash that normally comes up (Splash0.png) does, and then it says error (see the log). Then the second time it came up with the Splash2.png and does the same thing. The log is from the second time:

[    INFO][                  config.py:36]:Loading config...
[   DEBUG][                 config.py:194]:Property Change:        Settings                  hiddable ores = [7, 16, 15, 21, 73, 14, 56, 153]
[   DEBUG][                 config.py:194]:Property Change:        Settings                  Recent Worlds = ['']
[   DEBUG][                 config.py:194]:Property Change: Selection Colors                          white = (1.0, 1.0, 1.0)
[   DEBUG][                 config.py:194]:Property Change: Selection Colors                           blue = (0.75, 0.75, 1.0)
[   DEBUG][                 config.py:194]:Property Change: Selection Colors                          green = (0.75, 1.0, 0.75)
[   DEBUG][                 config.py:194]:Property Change: Selection Colors                            red = (1.0, 0.75, 0.75)
[   DEBUG][                 config.py:194]:Property Change: Selection Colors                           teal = (0.75, 1.0, 1.0)
[   DEBUG][                 config.py:194]:Property Change: Selection Colors                           pink = (1.0, 0.75, 1.0)
[   DEBUG][                 config.py:194]:Property Change: Selection Colors                         yellow = (1.0, 1.0, 0.75)
[   DEBUG][                 config.py:194]:Property Change: Selection Colors                           grey = (0.6, 0.6, 0.6)
[   DEBUG][                 config.py:194]:Property Change: Selection Colors                          black = (0.0, 0.0, 0.0)
[    INFO][OpenGL.acceleratesupport.py:13]:OpenGL_accelerate module loaded
[    INFO][OpenGL.arrays.arraydatatype.py:270]:Using accelerated ArrayDatatype
[    INFO][    pymclevel.materials.py:199]:Loading block info from <_io.BytesIO object at 0x00000000073AE0A0>
[   DEBUG][    pymclevel.materials.py:201]:Trying YAML CLoader
[   DEBUG][    pymclevel.materials.py:204]:CLoader not preset, falling back to Python YAML
[    INFO][    pymclevel.materials.py:199]:Loading block info from <_io.BytesIO object at 0x00000000073AE0A0>
[   DEBUG][    pymclevel.materials.py:201]:Trying YAML CLoader
[   DEBUG][    pymclevel.materials.py:204]:CLoader not preset, falling back to Python YAML
[    INFO][    pymclevel.materials.py:199]:Loading block info from <_io.BytesIO object at 0x00000000073AE0A0>
[   DEBUG][    pymclevel.materials.py:201]:Trying YAML CLoader
[   DEBUG][    pymclevel.materials.py:204]:CLoader not preset, falling back to Python YAML
[    INFO][    pymclevel.materials.py:199]:Loading block info from <_io.BytesIO object at 0x00000000073AE0A0>
[   DEBUG][    pymclevel.materials.py:201]:Trying YAML CLoader
[   DEBUG][    pymclevel.materials.py:204]:CLoader not preset, falling back to Python YAML
[    INFO][     OpenGL.GLUT.special.py:36]:Using NT-specific GLUT calls with exit callbacks
[   DEBUG][      pymclevel.BOParser.py:19]:BO3 block definitions loaded. 199 entries found
[ WARNING][            mcplatform.py:1184]:Initializing window management...
[    INFO][            mcplatform.py:1195]:WWindowHandler initialized.
[   DEBUG][         albow.translate.py:66]:*** Platform information
[   DEBUG][         albow.translate.py:67]:    System: Windows
[   DEBUG][         albow.translate.py:68]:    Release: 10
[   DEBUG][         albow.translate.py:69]:    Version: 10.0.10586
[   DEBUG][         albow.translate.py:70]:    Architecture: 64bit, WindowsPE
[   DEBUG][         albow.translate.py:71]:    Dist: , , 
[   DEBUG][         albow.translate.py:72]:    Machine: AMD64
[   DEBUG][         albow.translate.py:73]:    Processor: Intel64 Family 6 Model 23 Stepping 10, GenuineIntel
[   DEBUG][         albow.translate.py:74]:    Locale: en_US
[   DEBUG][         albow.translate.py:75]:    Encoding: cp1252
[   DEBUG][         albow.translate.py:76]:    FS encoding: mbcs
[   DEBUG][         albow.translate.py:96]:    numpy version: 1.11.0
[   DEBUG][         albow.translate.py:96]:    pygame version: 1.9.2a0
[   DEBUG][         albow.translate.py:96]:    OpenGL version: 3.1.0
[   DEBUG][         albow.translate.py:97]:***
[   ERROR][                  root.py:1006]:MCEdit version Unified v1.5.3.0 %s Minecraft 1.8/1.9 | PE 0.11
[   ERROR][                  root.py:1009]:Attempt to call an undefined function glWindowPos2d, check for bool(glWindowPos2d) before calling
Traceback (most recent call last):
  File "mcedit.py", line 1003, in main
  File "mcedit.py", line 729, in main
  File "utilities\gl_display_context.py", line 25, in __init__
  File "utilities\gl_display_context.py", line 105, in reset
  File "site-packages\OpenGL\platform\baseplatform.py", line 407, in __call__
NullFunctionError: Attempt to call an undefined function glWindowPos2d, check for bool(glWindowPos2d) before calling

(Not in log) then it says

----------------------
            MCEdit crashed
----------------------
Hit enter to close.

**Comment by Xbox180** [comment]
I've tried to reinstall other versions of MCEdit. The same thing happens.

**Comment by LaChal** [comment]
This issue is mostly related to your video driver.

Try to update it (after having created a Windows restoration point :wink:)

**Comment by Khroki** [comment]
Yep, video driver issue, update it if possible.

**Comment by Xbox180** [comment]
Ah. Okay.

**Comment by jkgour** [comment]
You people and your old tech

**Comment by LaChal** [comment]
@Xbox180 
Any news about your issue?

**Comment by Xbox180** [comment]
Nope. You guys are probably right because I had to roll back my driver to
play minecraft.

**Comment by Khroki** [comment]
We have made MCEdit Opengl 1.1 software-rendering compatible, so this should be fixed even on the oldest of video cards for next release, closing.
