### ISSUE TITLE
Trying to pass a Unicode string to os.stat

### ISSUE THREAD

**Issue by KevOrr** [Khroki/MCEdit-Unified#705]
Similar to #486, this happens when I try to save a schematic named `stable.nbt` to `/home/kevin/.mcedit/MCEdit/Schematics`. It appears that the `path` passed to `os.stat` is unencoded unicode, whereas it should be an already encoded string. I've attached the terminal output for reference.

[mcedit.log](https://github.com/Khroki/MCEdit-Unified/files/397351/mcedit.log.txt)

Python version: 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
Platform: linux-x86_64
Commit: a0d1109
Pip freeze:

    Cython==0.21.2
    Pillow==2.9.0
    PyOpenGL==3.1.0
    PyYAML==3.11
    -e git+https://github.com/Khroki/MCEdit-Unified.git@a0d1109c81d0b0bf450c46367ff054ef8a556600#egg=UNKNOWN-origin/HEAD
    argparse==1.2.1
    ftputil==3.3.1
    numpy==1.9.3
    pygame==1.9.2b6
    python-xlib==0.16
    six==1.10.0
    wsgiref==0.1.2

**Comment by codewarrior0** [comment]
`os.stat` accepts unencoded unicode:

```
Rio@RIO-PC ~
$ touch foo

Rio@RIO-PC ~
$ python
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os; os.stat(u'foo')
nt.stat_result(st_mode=16895, st_ino=0L, st_dev=0, st_nlink=0, st_uid=0, st_gid=0, st_size=0L, st_atime=1470158905L, st_mtime=1470158905L, st_ctime=1403916800L)
>>>
```

It implicitly encodes the unicode object using the filesystem encoding. It then raises a complaint about NULL characters in the resulting encoded string.

NULL characters were apparently introduced in commit 1e186fe5c9f943e1fd68c234b949df3a1d1eb099.

**Comment by LaChal** [comment]
Looks like you're using the internal file chooser which is the fallback when your system hasn't GTK installed (or MCEdit can't see it).

Can you send the `mcedit.log` file which is alongside MCEdit itself, please?
