### ISSUE TITLE
MCEdit resource pack crash. (Mac OS X 10.11.5)

### ISSUE THREAD

**Issue by OmegaGmaster** [Khroki/MCEdit-Unified#712]
Hi,

I've been trying to run the latest "stable" version of MCEdit (1.5.3.0) and I get the same error as this one: https://github.com/Khroki/MCEdit-Unified/issues/703

The only difference is I have a different error. Here it is:

Aug 22 00:06:09  mcedit[8421] <Notice>: Running in fixed mode. Support files are in your App Support Folder (Available from the main menu of MCEdit)
Aug 22 00:06:09  mcedit[8421] <Notice>: Splash load...
Aug 22 00:06:09  mcedit[8421] <Notice>: 2016-08-22 00:06:09.704 mcedit[8421:730429] 00:06:09.704 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
Aug 22 00:06:11  mcedit[8421] <Notice>: [ WARNING][            mcplatform.py:1184]:Initializing window management...
Aug 22 00:06:11  mcedit[8421] <Notice>: Minecraft_Server.jar storage initialized.
Aug 22 00:06:11  mcedit[8421] <Notice>: Each server is stored in a subdirectory of /Users/*****_/Library/Application Support/pymclevel/ServerJarStorage named with the server's version number
Aug 22 00:06:11  mcedit[8421] <Notice>: Cached servers:  []
Aug 22 00:06:11  mcedit[8421] <Notice>: mcedit.main MCEdit exited with errors.
Aug 22 00:06:11  mcedit[8421] <Notice>: [   ERROR][                  root.py:1006]:MCEdit version Unified v1.5.3.0 %s Minecraft 1.8/1.9 | PE 0.11
Aug 22 00:06:11  mcedit[8421] <Notice>: Traceback (most recent call last):
Aug 22 00:06:11  mcedit[8421] <Notice>:   File "/Users/**_**_/Downloads/mcedit.app/Contents/Resources/mcedit.py", line 1066, in <module>
Aug 22 00:06:11  mcedit[8421] <Notice>:   File "/Users/**_**_/Downloads/mcedit.app/Contents/Resources/mcedit.py", line 1003, in main
Aug 22 00:06:11  mcedit[8421] <Notice>:   File "/Users/**_***/Downloads/mcedit.app/Contents/Resources/mcedit.py", line 729, in main
Aug 22 00:06:11  mcedit[8421] <Notice>:   File "utilities/gl_display_context.pyc", line 25, in **init**
Aug 22 00:06:11  mcedit[8421] <Notice>:   File "utilities/gl_display_context.pyc", line 140, in reset
Aug 22 00:06:11  mcedit[8421] <Notice>:   File "utilities/gl_display_context.pyc", line 168, in loadTextures
Aug 22 00:06:11  mcedit[8421] <Notice>:   File "utilities/misc.pyc", line 33, in Instance
Aug 22 00:06:11  mcedit[8421] <Notice>:   File "resource_packs.pyc", line 1022, in **init**
Aug 22 00:06:11  mcedit[8421] <Notice>:   File "resource_packs.pyc", line 1003, in setup_reource_packs
Aug 22 00:06:11  mcedit[8421] <Notice>:   File "resource_packs.pyc", line 893, in **init**
Aug 22 00:06:11  mcedit[8421] <Notice>:   File "resource_packs.pyc", line 904, in add_textures
Aug 22 00:06:11  mcedit[8421] <Notice>:   File "PIL/Image.pyc", line 1978, in open
Aug 22 00:06:11  mcedit[8421] <Notice>: IOError: cannot identify image file
Aug 22 00:06:11  mcedit[8421] <Notice>: 
Aug 22 00:06:11  mcedit[8421] <Notice>: ==================================
Aug 22 00:06:11  mcedit[8421] <Notice>:               MCEdit has crashed
Aug 22 00:06:11  mcedit[8421] <Notice>: ==================================

Before, there was an error regarding being unable to find "B03.def" but I managed to patch that problem by dropping in the B03.def from this repository into the Resources folder of the .app. However I still cannot figure out what is going on now, any help would be greatly appreciated.

I am running OS X El Capitan 10.11.5.

**Comment by Khroki** [comment]
The bo3 message is non-fatal, this is another problem completely. Try clearing out your resource packs in your minecraft folder, one of them may be incompatible. If this works could you upload the pack in question?

**Comment by OmegaGmaster** [comment]
Clearing out the pack did help. Here is the texture pack in question:

[oCd+ 1.10.zip](https://github.com/Khroki/MCEdit-Unified/files/431283/oCd.1.10.zip)

The MCPatcher folder within is likely the one that is causing issues, but I'm unsure. Thanks for your help!

**Comment by Khroki** [comment]
Np, yeah mcedit uses a texture stitcher for it's resource pack support and a rare few choke it up.

**Comment by Podshot** [comment]
Sorry for the delay, but I figured out the issue. The 'sand.png' and 'red_sand.png' files have had their metadata corrupted. This doesn't affect viewing the actual image, but it causes both to hang our texture stitcher. Open both of these files in a program like Paint.Net or GIMP (both are free to download and use, **don't** use Window's regular paint), then just save them with default settings with their original name, and then that should fix your issue.

**Comment by Podshot** [comment]
Closed since this isn't an issue on our side, but more a partially corrupt image file/compression
