### ISSUE TITLE
MCEdit Error - Failed to Download the required Minecraft version.

### ISSUE THREAD

**Issue by EzequielDM** [Khroki/MCEdit-Unified#716]
Hello, when i try to Run MCEdit, it gives me this error message: 

http://imgur.com/a/NApi2

What do I do?

Oops, i will add the required information

**Comment by Khroki** [comment]
Uh, that's a picture of the Imgur homepage

**Comment by EzequielDM** [comment]
It isn't a picture of the Imgur homepage, look at the error, its from MCEdit, i went to imgur and reopened the error page '-'

**Comment by Khroki** [comment]
Ah ok, I thought that was a picture since it blended in with imgur behind it, hmm, what MC version are you using?

**Comment by EzequielDM** [comment]
The latest, 2.0.0-beta2

**Comment by Khroki** [comment]
You're in the wrong github, this is for MCEdit 1.x, You'll need to report it here: https://github.com/mcedit/mcedit2

**Comment by EzequielDM** [comment]
Oops, sorry, i just clicked the link, can i c u there?

**Comment by EzequielDM** [comment]
I will create a issue named "MCEdit - Failed to download the required Minecraft Version - Khroki", see u there

**Comment by Khroki** [comment]
Sorry, I'm not involved in the MCEdit 2 project, you'll have to wait for codewarrior to address it. MCEdit 1 and MCedit 2 are separate active projects with different codebases

**Comment by EzequielDM** [comment]
What's the difference between the 1 and 2

**Comment by Khroki** [comment]
1 is the older codebase developed by community members after Codewarrior stopped working on it, MCEdit 2 is Codewarrior's rewrite of mcedit from scratch, but it is in alpha status at this time.

**Comment by Khroki** [comment]
Anyway, closing the issue as there's nothing we can do about it here :/.
