### ISSUE TITLE
[Error] StructureTooBigException error when exporting

### ISSUE THREAD

**Issue by Azounstone** [Khroki/MCEdit-Unified#722]
Hello,

I am trying to export a large area of a world (663Wx605Lx173H) and each time I try to save the export it gives the following error:

Error during <function exportSelection at 0x000000000A57C668>: StructureTooBigException()

This is obviously stopping me from creating the schematic that I need so could you help me to solve the issue so that I can create this schematic please?

Thanks in advance....

**Comment by Azounstone** [comment]
I am also getting the same error when trying to export a different structure that is a size I have exported many times before (166Wx200Lx105H):

0x000000000A404668

**Comment by Podshot** [comment]
I'll look into this. Could you send us a screenshot of the console window? It could give us some more I for that could help us

**Comment by Azounstone** [comment]
Hi,

I am not able to do so as I have reverted to using version 1.5.3.0 and the errors do not occur in this version. I am able to create both of the schematics.

regards

**Comment by MagboneD** [comment]
I'm getting the same error. Here's my console dump:


Running in fixed mode. Support files are in your Documents folder.
Splash load...
[ ****** ] ~~~~~~~~~~ Starting MCEdit-Unified v1.5.4.1
[ WARNING][            mcplatform.py:1276]:Initializing window management...
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of C:\Users\dagbel\Documents\MCEdit\Serv
erJarStorage named with the server's version number
Cached servers:  [u'Release 1.8.3']
[ WARNING][          version_utils.py:369]:Encountered an URLError while trying
to access "https://sessionserver.mojang.com/session/minecraft/profile/ebf374c287
d34de593ca55a3ad8c8bcc"
[ WARNING][          version_utils.py:370]:Error: [Errno 11004] getaddrinfo fail
ed
[ WARNING][          version_utils.py:369]:Encountered an URLError while trying
to access "https://sessionserver.mojang.com/session/minecraft/profile/76c47dc440
424411909cadf2681850f4"
[ WARNING][          version_utils.py:370]:Error: [Errno 11004] getaddrinfo fail
ed
[ WARNING][          version_utils.py:369]:Encountered an URLError while trying
to access "https://sessionserver.mojang.com/session/minecraft/profile/0f22d2ca32
b84eb4a4192b1cf493f210"
[ WARNING][          version_utils.py:370]:Error: [Errno 11004] getaddrinfo fail
ed
[ WARNING][          version_utils.py:369]:Encountered an URLError while trying
to access "https://sessionserver.mojang.com/session/minecraft/profile/bc32789416
664c1fbf6e411bbfed3adb"
[ WARNING][          version_utils.py:370]:Error: [Errno 11004] getaddrinfo fail
ed
[ WARNING][          version_utils.py:369]:Encountered an URLError while trying
to access "https://sessionserver.mojang.com/session/minecraft/profile/cc29829691
0445829dd6e21cc33a7a7e"
[ WARNING][          version_utils.py:370]:Error: [Errno 11004] getaddrinfo fail
ed
[ WARNING][          version_utils.py:369]:Encountered an URLError while trying
to access "https://sessionserver.mojang.com/session/minecraft/profile/c80c2fe25b
1d43909d6dc69de5b49612"
[ WARNING][          version_utils.py:370]:Error: [Errno 11004] getaddrinfo fail
ed
[ WARNING][          version_utils.py:369]:Encountered an URLError while trying
to access "https://sessionserver.mojang.com/session/minecraft/profile/6b9ade8514
ea4ec4b31091b760c6c3c3"
[ WARNING][          version_utils.py:370]:Error: [Errno 11004] getaddrinfo fail
ed
[ WARNING][          version_utils.py:369]:Encountered an URLError while trying
to access "https://sessionserver.mojang.com/session/minecraft/profile/3af15f5865
494c698b077e57eeae818c"
[ WARNING][          version_utils.py:370]:Error: [Errno 11004] getaddrinfo fail
ed
[ WARNING][          version_utils.py:369]:Encountered an URLError while trying
to access "https://sessionserver.mojang.com/session/minecraft/profile/1a2e965792
6141c2a8d6603d24c7ccf4"
[ WARNING][          version_utils.py:370]:Error: [Errno 11004] getaddrinfo fail
ed
[ WARNING][          version_utils.py:369]:Encountered an URLError while trying
to access "https://sessionserver.mojang.com/session/minecraft/profile/980c13d889
96459ea5ad865d1b761cb9"
[ WARNING][          version_utils.py:370]:Error: [Errno 11004] getaddrinfo fail
ed
[ WARNING][          version_utils.py:369]:Encountered an URLError while trying
to access "https://sessionserver.mojang.com/session/minecraft/profile/5d2b0d23ea
9344f0b3c6b2bdf5fee608"
[ WARNING][          version_utils.py:370]:Error: [Errno 11004] getaddrinfo fail
ed
[ WARNING][          version_utils.py:369]:Encountered an URLError while trying
to access "https://sessionserver.mojang.com/session/minecraft/profile/05e88dce71
4d4218be77fade8b5dfa3c"
[ WARNING][          version_utils.py:370]:Error: [Errno 11004] getaddrinfo fail
ed
[ WARNING][          version_utils.py:369]:Encountered an URLError while trying
to access "https://sessionserver.mojang.com/session/minecraft/profile/69b92341b9
2b465496e22e615ae97f0d"
[ WARNING][          version_utils.py:370]:Error: [Errno 11004] getaddrinfo fail
ed
[ WARNING][          version_utils.py:369]:Encountered an URLError while trying
to access "https://sessionserver.mojang.com/session/minecraft/profile/9f94b55930
fe417fa1875dfa336fcc71"
[ WARNING][          version_utils.py:370]:Error: [Errno 11004] getaddrinfo fail
ed
[ WARNING][          version_utils.py:369]:Encountered an URLError while trying
to access "https://sessionserver.mojang.com/session/minecraft/profile/3ca077aa67
fd3d32b5300253ac456d7f"
[ WARNING][          version_utils.py:370]:Error: [Errno 11004] getaddrinfo fail
ed
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "threading.py", line 754, in run
  File "mcedit.py", line 708, in fetch_version
  File "release.py", line 54, in fetch_new_version_info
  File "urllib2.py", line 154, in urlopen
  File "urllib2.py", line 431, in open
  File "urllib2.py", line 449, in _open
  File "urllib2.py", line 409, in _call_chain
  File "urllib2.py", line 1240, in https_open
  File "urllib2.py", line 1197, in do_open
URLError: <urlopen error [Errno 11004] getaddrinfo failed>

An error occurred checking for updates.
[ WARNING][          version_utils.py:369]:Encountered an URLError while trying
to access "https://sessionserver.mojang.com/session/minecraft/profile/cc29829691
0445829dd6e21cc33a7a7e"
[ WARNING][          version_utils.py:370]:Error: [Errno 11004] getaddrinfo fail
ed
Couldn't find Image file (player-skins\cc298296_9104_4582_9dd6_e21cc33a7a7e.png)
 or the file may be corrupted
Clipping:  _Vector(x=13, y=45, z=13)
C:\Users\dagbel\DOWNLO~1\Games\MINECR~1\SUPPLE~1\MCEDIT~1\154~1.1\mcedit\rendere
r.py:1115: VisibleDeprecationWarning: boolean index did not match indexed array
along dimension 0; dimension is 16 but corresponding boolean dimension is 13
Clipping:  _Vector(x=13, y=45, z=13)
Error getting file name:  (0, 'GetSaveFileNameW', 'No error message is available
')
Clipping:  _Vector(x=13, y=45, z=13)
[   ERROR][                    root.py:62]:Exception:
Traceback (most recent call last):
  File "mceutils.py", line 56, in _alertException
  File "editortools\select.py", line 1228, in exportSelection
  File "leveleditor.py", line 842, in exportSchematic
  File "pymclevel\schematic.py", line 809, in fromSchematic
    structure = cls(size=(schematic.Width, schematic.Height, schematic.Length),
mats=namedMaterials[schematic.Materials])
  File "pymclevel\schematic.py", line 776, in __init__
    self._check_bounds(self._size)
  File "pymclevel\schematic.py", line 729, in _check_bounds
    raise self.StructureTooBigException()
StructureTooBigException
Clipping:  _Vector(x=13, y=45, z=13)
[   ERROR][                    root.py:62]:Exception:
Traceback (most recent call last):
  File "mceutils.py", line 56, in _alertException
  File "editortools\select.py", line 1228, in exportSelection
  File "leveleditor.py", line 842, in exportSchematic
  File "pymclevel\schematic.py", line 809, in fromSchematic
    structure = cls(size=(schematic.Width, schematic.Height, schematic.Length),
mats=namedMaterials[schematic.Materials])
  File "pymclevel\schematic.py", line 776, in __init__
    self._check_bounds(self._size)
  File "pymclevel\schematic.py", line 729, in _check_bounds
    raise self.StructureTooBigException()
StructureTooBigException
Clipping:  _Vector(x=13, y=45, z=13)
[   ERROR][                    root.py:62]:Exception:
Traceback (most recent call last):
  File "mceutils.py", line 56, in _alertException
  File "editortools\select.py", line 1228, in exportSelection
  File "leveleditor.py", line 842, in exportSchematic
  File "pymclevel\schematic.py", line 809, in fromSchematic
    structure = cls(size=(schematic.Width, schematic.Height, schematic.Length),
mats=namedMaterials[schematic.Materials])
  File "pymclevel\schematic.py", line 776, in __init__
    self._check_bounds(self._size)
  File "pymclevel\schematic.py", line 729, in _check_bounds
    raise self.StructureTooBigException()
StructureTooBigException
Clipping:  _Vector(x=13, y=45, z=13)
[   ERROR][                    root.py:62]:Exception:
Traceback (most recent call last):
  File "mceutils.py", line 56, in _alertException
  File "editortools\select.py", line 1228, in exportSelection
  File "leveleditor.py", line 842, in exportSchematic
  File "pymclevel\schematic.py", line 809, in fromSchematic
    structure = cls(size=(schematic.Width, schematic.Height, schematic.Length),
mats=namedMaterials[schematic.Materials])
  File "pymclevel\schematic.py", line 776, in __init__
    self._check_bounds(self._size)
  File "pymclevel\schematic.py", line 729, in _check_bounds
    raise self.StructureTooBigException()
StructureTooBigException
Clipping:  _Vector(x=13, y=45, z=13)
[   ERROR][                    root.py:62]:Exception:
Traceback (most recent call last):
  File "mceutils.py", line 56, in _alertException
  File "editortools\select.py", line 1228, in exportSelection
  File "leveleditor.py", line 842, in exportSchematic
  File "pymclevel\schematic.py", line 809, in fromSchematic
    structure = cls(size=(schematic.Width, schematic.Height, schematic.Length),
mats=namedMaterials[schematic.Materials])
  File "pymclevel\schematic.py", line 776, in __init__
    self._check_bounds(self._size)
  File "pymclevel\schematic.py", line 729, in _check_bounds
    raise self.StructureTooBigException()
StructureTooBigException

**Comment by Podshot** [comment]
Fixed by fc47bec

**Comment by beetree** [comment]
Sorry to comment here, but could you please do a new official release post this fix...? The last release is from sep 3.

**Comment by LaChal** [comment]
I agree the last release is a bit old, but I can't figure how the issue you're experiencing is related to the structure size...

What are you trying to 'build' ?

**Comment by beetree** [comment]
So, I'm trying to copy large structures inside MCEDIT.

I'm trying to build the python repo from the last commit.

Build here refers to python, _not_ building inside MCEDIT :)

**Comment by LaChal** [comment]
If you want to use the last commit, you shall run from source.
The process to set up Python and install the dependencies can be found in the README.md file.

Note that PyOpenGL minimum version shall be 3.1.0.

The source code for the binary files `_nbt.pyd` and `leveldb_mcpe.pyd` has not changed since last release, so, you van reuse the ones in you current MCEdit-Unified installation.

**Comment by beetree** [comment]
Yeah, I tried running from source but failed. It wasn't as easy as I
thought, and then I even have years of (non-python) coding experience. I'm
sure there is a significant user base with no coding experience at all that
would love to see a new binary released.
