### ISSUE TITLE
blockPos for entity in structure is not using floor

### ISSUE THREAD

**Issue by Marcono1234** [Khroki/MCEdit-Unified#727]
When a schematic is saved as structure, the `blockPos`  tag values of an entity are not created correctly.

https://github.com/Khroki/MCEdit-Unified/blob/master/pymclevel/schematic.py#L970

It should instead use `math.floor(coord.value)`, otherwise -0.5 and 0.5 would become both 0.

**Comment by Podshot** [comment]
Fixed by fc47bec
