### ISSUE TITLE
x, y and z tags should be removed from copy during conversion from schematic to structure

### ISSUE THREAD

**Issue by Marcono1234** [Khroki/MCEdit-Unified#728]
https://github.com/Khroki/MCEdit-Unified/blob/master/pymclevel/schematic.py#L815

Should create a copy (`copy.deepcopy()`) and remove from the copy the tags, otherwise once a schematic is saved as structure it cannot be pasted in the world anymore as the tags `x`, `y` and `z` are missing.

**Comment by Podshot** [comment]
Fixed by fc47bec
