### ISSUE TITLE
Can't open saves, updated to v.1.5.4.1

### ISSUE THREAD

**Issue by ColonelS94** [Khroki/MCEdit-Unified#733]
Minecraft version 1.9.2 Only mod used is Optifine for this version
I have been having issues with world saves, one day i can open any level with no issues but then suddenly a level that had been used in mcedit will not open and i receive an error message. 
![20161006_233708](https://cloud.githubusercontent.com/assets/22757292/19254414/efabf188-8f18-11e6-9c5a-521886fcffc1.jpg)

**Comment by Podshot** [comment]
Can you give us a copy of the world?

**Comment by ColonelS94** [comment]
Its happening with 2 different worlds, but yeah if you tell me how to do it

**Comment by ColonelS94** [comment]
[level.zip](https://github.com/Khroki/MCEdit-Unified/files/522679/level.zip)
[level_1.zip](https://github.com/Khroki/MCEdit-Unified/files/522681/level_1.zip)
@Podshot

**Comment by Podshot** [comment]
I'll take a look at this

**Comment by ColonelS94** [comment]
Okay, thank you, fingers crossed because i use one world to build and the other is a city i am creating

**Comment by Podshot** [comment]
@ColonelS94 I can only see a level.dat file in both of those .zip files. Are there any other folders or files in the world folder?

**Comment by ColonelS94** [comment]
There are but it says the files are too large to copy here @Podshot

**Comment by Podshot** [comment]
Then can you try uploading them to somewhere else and giving me a link to download all of it? I need the entire world to properly fix this

**Comment by ColonelS94** [comment]
Yeah, what site should i use?

**Comment by ColonelS94** [comment]
http://www.planetminecraft.com/project/world-1-3823764/
@Podshot

**Comment by Podshot** [comment]
That link doesn't seem to work. Would you be able to upload the world to Dropbox?

**Comment by ColonelS94** [comment]
https://www.dropbox.com/s/miualaz8rb8lfi0/New%20World.zip?dl=0
@Podshot

**Comment by Podshot** [comment]
It seems the `mcedit_waypoints.dat` file has been corrupted. This causes the loading of the world to fail even though the rest of the world data is correct, I am making a fix that'll resolve this issue in our next release. For now, delete the `mcedit_waypoints.dat` file in the world folder then open the world normally in MCEdit.

**Comment by ColonelS94** [comment]
You are a godsend, thank you, this will save me hours trying to move
everything block by block
