### ISSUE TITLE
Unable to use MCEdit Unified

### ISSUE THREAD

**Issue by MythicalZ10n** [Khroki/MCEdit-Unified#738]
In response to LaChal's comment [here](https://github.com/Khroki/MCEdit-Unified/issues/346#issuecomment-258600573), I am creating a new forum post about my issue with MCEdit Unified.

Information:

**Linux version:** _Linux Mint 18 'Sarah'_
**MCEdit Version:** 1.5.4.1

**MCEdit Log:**
[    INFO][                    root.py:72]:Starting MCEdit-Unified v1.5.4.1
[    INFO][                  config.py:36]:Loading config...
[   DEBUG][                 config.py:194]:Property Change:        Settings                  hiddable ores = [7, 16, 15, 21, 73, 14, 56, 153]
[   DEBUG][                 config.py:194]:Property Change:        Settings                  Recent Worlds = ['']
[   DEBUG][                 config.py:194]:Property Change: Selection Colors                          white = (1.0, 1.0, 1.0)
[   DEBUG][                 config.py:194]:Property Change: Selection Colors                           blue = (0.75, 0.75, 1.0)
[   DEBUG][                 config.py:194]:Property Change: Selection Colors                          green = (0.75, 1.0, 0.75)
[   DEBUG][                 config.py:194]:Property Change: Selection Colors                            red = (1.0, 0.75, 0.75)
[   DEBUG][                 config.py:194]:Property Change: Selection Colors                           teal = (0.75, 1.0, 1.0)
[   DEBUG][                 config.py:194]:Property Change: Selection Colors                           pink = (1.0, 0.75, 1.0)
[   DEBUG][                 config.py:194]:Property Change: Selection Colors                         yellow = (1.0, 1.0, 0.75)
[   DEBUG][                 config.py:194]:Property Change: Selection Colors                           grey = (0.6, 0.6, 0.6)
[   DEBUG][                 config.py:194]:Property Change: Selection Colors                          black = (0.0, 0.0, 0.0)
[    INFO][OpenGL.acceleratesupport.py:17]:No OpenGL_accelerate module loaded: No module named OpenGL_accelerate
[    INFO][    OpenGL.formathandler.py:46]:Unable to load registered array format handler numeric:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/formathandler.py", line 35, in loadPlugin
    plugin_class = entrypoint.load()
  File "/usr/lib/python2.7/dist-packages/OpenGL/plugins.py", line 14, in load
    return importByName( self.import_path )
  File "/usr/lib/python2.7/dist-packages/OpenGL/plugins.py", line 28, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/numeric.py", line 15, in <module>
    raise ImportError( """No Numeric module present: %s"""%(err))
ImportError: No Numeric module present: No module named Numeric

[    INFO][    OpenGL.formathandler.py:46]:Unable to load registered array format handler vbo:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/formathandler.py", line 35, in loadPlugin
    plugin_class = entrypoint.load()
  File "/usr/lib/python2.7/dist-packages/OpenGL/plugins.py", line 14, in load
    return importByName( self.import_path )
  File "/usr/lib/python2.7/dist-packages/OpenGL/plugins.py", line 28, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/vbo.py", line 33, in <module>
    from OpenGL import GL
ImportError: cannot import name GL

[    INFO][    OpenGL.formathandler.py:46]:Unable to load registered array format handler vbooffset:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/formathandler.py", line 35, in loadPlugin
    plugin_class = entrypoint.load()
  File "/usr/lib/python2.7/dist-packages/OpenGL/plugins.py", line 14, in load
    return importByName( self.import_path )
  File "/usr/lib/python2.7/dist-packages/OpenGL/plugins.py", line 28, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/vbo.py", line 33, in <module>
    from OpenGL import GL
ImportError: cannot import name GL

[   DEBUG][    pymclevel.materials.py:321]:Cannot get resource_stream for minecraft.json [Errno 11] Resource temporarily unavailable: 'pymclevel/minecraft.json'
[   DEBUG][    pymclevel.materials.py:325]:Failed to read minecraft.json using pkg_resources. Trying /home/mythicalz10n/Desktop/Folders/MCEDIT_NEW/mcedit-1.5.4.1/pymclevel/minecraft.json instead.
[    INFO][    pymclevel.materials.py:329]:Loading block info from <open file '/home/mythicalz10n/Desktop/Folders/MCEDIT_NEW/mcedit-1.5.4.1/pymclevel/minecraft.json', mode 'r' at 0x7f8aaebeb5d0>
[   DEBUG][    pymclevel.materials.py:321]:Cannot get resource_stream for classic.json [Errno 0] Error: 'pymclevel/classic.json'
[   DEBUG][    pymclevel.materials.py:325]:Failed to read classic.json using pkg_resources. Trying /home/mythicalz10n/Desktop/Folders/MCEDIT_NEW/mcedit-1.5.4.1/pymclevel/classic.json instead.
[    INFO][    pymclevel.materials.py:329]:Loading block info from <open file '/home/mythicalz10n/Desktop/Folders/MCEDIT_NEW/mcedit-1.5.4.1/pymclevel/classic.json', mode 'r' at 0x7f8aaebeb5d0>
[   DEBUG][    pymclevel.materials.py:321]:Cannot get resource_stream for indev.json [Errno 0] Error: 'pymclevel/indev.json'
[   DEBUG][    pymclevel.materials.py:325]:Failed to read indev.json using pkg_resources. Trying /home/mythicalz10n/Desktop/Folders/MCEDIT_NEW/mcedit-1.5.4.1/pymclevel/indev.json instead.
[    INFO][    pymclevel.materials.py:329]:Loading block info from <open file '/home/mythicalz10n/Desktop/Folders/MCEDIT_NEW/mcedit-1.5.4.1/pymclevel/indev.json', mode 'r' at 0x7f8aaebeb5d0>
[   DEBUG][    pymclevel.materials.py:321]:Cannot get resource_stream for pocket.json [Errno 0] Error: 'pymclevel/pocket.json'
[   DEBUG][    pymclevel.materials.py:325]:Failed to read pocket.json using pkg_resources. Trying /home/mythicalz10n/Desktop/Folders/MCEDIT_NEW/mcedit-1.5.4.1/pymclevel/pocket.json instead.
[    INFO][    pymclevel.materials.py:329]:Loading block info from <open file '/home/mythicalz10n/Desktop/Folders/MCEDIT_NEW/mcedit-1.5.4.1/pymclevel/pocket.json', mode 'r' at 0x7f8aaebeb5d0>
[    INFO][ pymclevel.leveldbpocket.py:28]:Error while trying to import leveldb_mcpe, starting without PE support (/home/mythicalz10n/Desktop/Folders/MCEDIT_NEW/mcedit-1.5.4.1/pymclevel/leveldb_mcpe.so: undefined symbol: _ZTVN7leveldb14ZlibCompressorE)
[   DEBUG][      pymclevel.BOParser.py:19]:BO3 block definitions loaded. 199 entries found

**MCEdit Terminal Error:**
Starting MCEdit...
*** APP DIR: /home/mythicalz10n/Desktop/Folders/MCEDIT_NEW/mcedit-1.5.4.1
Running in fixed mode. Support files are in your Documents folder.
Splash load...
[ ****** ] ~~~~~~~~~~ Starting MCEdit-Unified v1.5.4.1
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/release-master/MCEdit-Unified/__main__.py", line 38, in <module>
  File "/tmp/release-master/MCEdit-Unified/mcedit.py", line 93, in <module>
  File "/tmp/release-master/MCEdit-Unified/leveleditor.py", line 27, in <module>
  File "/tmp/release-master/MCEdit-Unified/ftp_client.py", line 4, in <module>
ImportError: No module named error
Press any key to close.

I also have issues with an installer that keeps telling me that I don't have Python 2.7 installed, but I have python 3.0.2 installed. shouldn't it work, or do I have to install 2.7 and set it as default for the install? Thanks for any help you can provide.

**Comment by Khroki** [comment]
I don't really handle the linux end of things but you do in fact have to have python 2.7.x, 3.x is a different codebase and is incompatible with mcedit.

**Comment by MythicalZ10n** [comment]
Do you happen to have a working ppa for Python 2.7? Thanks.

**Comment by MythicalZ10n** [comment]
Never mind on the ppa thing. I found a guide to getting Python 2.7.11 (ended up installing 2.7.12 for some reason but I assume it will work) [here](http://mbless.de/blog/2016/01/09/upgrade-to-python-2711-on-ubuntu-1404-lts.html)

**Comment by MythicalZ10n** [comment]
I found an install for Python 2.7.12 but the installer still claims that I don't have Python 2.7 setuptools installed. Any idea why that is? And without running the installer and instead running mcedit.sh in the mcedit folder, it still keeps saying "no module named error." (also, in case you couldn't tell, I'm a linux noob :P)

**Comment by Khroki** [comment]
I'm not completely sure how installing it on linux works, but you may need to download and install setuptools separately assuming it's not something in your distro's package manager. Might need dens for help here.

**Comment by MythicalZ10n** [comment]
It wasn't something that originally came with my distro (as far as I know) but I do know when I try to download the python-setuptools package from the internet, it keeps telling me it's already installed.

**Comment by Khroki** [comment]
Make sure the setuptools you are installing are for 2.7 and not 3.x also you could use pip to install it from the terminal, assuming it works the same as windows.

**Comment by LaChal** [comment]
As you know, nothing is magic :) The installer tries to find the right 'setuptools', but may fail.

Python setuptools is typically instaled for every Python version you have on your system, and provide 'easy_install' commands.
I assume you have a 2.7.X and a 3.X Python versions intalled.
By default, on recent Linuxes, the command 'easy_install' points to the Python 3.X one. The 2.7.X one shall still be on the system, but with a different name.

Search 'setuptools' (related to Python 2.7) in your package manager. If not installed, just install it (*) , and launch the MCEdit installer again.

MCEdit needs some packages to run properly. The current installer can deal with most of them, but some have to be installed with your package manager, like pygame (idealy 1.9.1, not lower) and pillow.

The first thing the installer do after displaying the disclaimer and the installation notes, is to check your system and report which dependencies are compliant or not. You can run the installer and keep it on the check result page to help you.

Look also to the release notes (`LINUX_INSTALL.txt`). The file is in the `mcedit-1.5.4.1` folder created when you run the installer. You will find this folder in the same place you put the installer.

(*) You can verify by entering 'easy_install-2.7 --help' in a command shell.

**Comment by naor2013** [comment]
Can you tell us if you found a fix or is this still happening to you? If you won't respond in the next few days, we'll close the issue.

**Comment by Khroki** [comment]
No response for over a month, Closing.
