### ISSUE TITLE
MCEdit doesn't start after first start

### ISSUE THREAD

**Issue by OniOniOn-** [Khroki/MCEdit-Unified#741]
Version: 1.5.4.1
OS: Win7 SP1 64bit
First open mcedit: starts but map doesn't open
After open: black screen instantly disappears

**Comment by LaChal** [comment]
Any log file in MCEdit install folder?
And when running the program from a command shell, what is printed to screen?

**Comment by OniOniOn-** [comment]
I found out the reason, it was because of Korean letters in the directory. I changed my username to English and that fixed it.

**Comment by LaChal** [comment]
Right, using non-english characters in file and folder names in not recommended to run MCEdit on Windows.

So, this issue is now closed!
