### ISSUE TITLE
Pocket Edition World Open Error

### ISSUE THREAD

**Issue by OniOniOn-** [Khroki/MCEdit-Unified#743]
[   ERROR][                   root.py:647]:Failed to load file C:\Users\****\****\Minecraft\****\level.dat: AttributeError("'PocketWorld' object has no attribute '_MCLevel__gameVersion'",)
I changed to **** just for privacy.

**Comment by LaChal** [comment]
Hmmm...
Looks like something is missing somewhere.
We'll have a look :smile:

**Comment by OniOniOn-** [comment]
Sorry for late reply.
Here is the link: https://www.dropbox.com/s/srokzzzy78fk018/OniOniOn%200.8.0build3%20Map%20v.1.zip?dl=0
Maps were edited in old versions of mcedit, so I tried to find out since wheat version it didn't work. But my Windows 10 has some complicated account name issues which kept me from testing old versions...

**Comment by LaChal** [comment]
Which game version is this world?

**Comment by tuxutku** [comment]
[   ERROR][                   root.py:687]:Failed to load file /home/utku/MCPE/com.mojang/minecraftWorlds/OLD: AttributeError("'PocketWorld' object has no attribute '_MCLevel__gameVersion'",)

when trying to open map generated in mcpe 0.8.1

using 64bit ubuntu 16.10

**Comment by LaChal** [comment]
Badly, the current 1.5.6.0 version of MCEdit-Unified does not support very well PE...

Thus, some progress has been made for the next release.
This error was related to 'old' PE 0.8.0 or lower worlds.
It is fixed for the next release.

The support for version 0.9.0+ has been reworked too, and at the time I'm writing, the 1+ world can be loaded in the development version of MCEdit.

You can also see this related post: https://github.com/Khroki/MCEdit-Unified/issues/676#issuecomment-279105921

**Comment by Yqey** [comment]
> it is fixed for the next release

A release that never came...
