### ISSUE TITLE
MCEdit doesn't open, Mac OS 10.8.5

### ISSUE THREAD

**Issue by tomgreever** [Khroki/MCEdit-Unified#749]
Just downloaded MCEdit 2 beta release 2.0.0-beta6 and it will not open on my iMac (early 2008) running OS X 10.8.5

When double-clicking the app to open it, it briefly flashes in the dock and disappears. Nothing else happens.

Console shows:
```
12/23/16 7:26:12.740 AM Dock[170]: no information back from LS about running process
12/23/16 7:26:12.762 AM com.apple.launchd.peruser.501[156]: ([0x0-0x125125].net.mcedit.mcedit2[1723]) Exited with code: 255
```

Permissions on the app itself look ok.

**Comment by LaChal** [comment]
@tomgreever 
We can't help here, badly...
This is the MCEdit-Unified issue tracker.
(Anyway, if you try MCEdit-Unified and find some issue/bug, we may be interested :smile:)

I suggest you to open a new issue in the MCEdit 2 repository: https://github.com/mcedit/mcedit2/wiki/Reporting-Issues

**Comment by tomgreever** [comment]
My bad. Sorry and thanks for the correct repo
