### ISSUE TITLE
Minecraft PE 1.0.0 worlds are not supported

### ISSUE THREAD

**Issue by Aphys122** [Khroki/MCEdit-Unified#751]
There are empty world after opening MCPE 1.0.0 world

**Comment by LaChal** [comment]
As mentionned int MCEdit title bar, the compatibility for PE is limited to 0.11.
Actually, you can load PE 0.11 worlds, but saving them may cause MCEdit crashes, and, possibly, save corruption.
We regret this, but we currently lack information about this game data format (and testers).
You may want to send us your world, so we can see what happens, but I can't offer any warranty we can fix the issue, badly...
You can also send us the log file (located in your MCEdit install folder), and a copy or screenshot of the program console messages (the black window which pops up when your start MCEdit).

**Comment by Robbeedee** [comment]
Here's a world. The new 256 building height limit is causing problems. 

https://www.dropbox.com/s/2g0t6cs5yz6fvac/IaEDAEKL0QM%3D.zip?dl=0

**Comment by Robbeedee** [comment]
I should add that an older world will open but any chunk that has been edited by 1.0 appears blank.

**Comment by dmtaub** [comment]
I'd like to volunteer as a tester. I have pe and basic development knowledge (spent all day yesterday trying to get leveldb-mcpe running on genisys, no luck, seems to only compile on Windows :/ )

**Comment by robske110** [comment]
@LaChal maybe you want to look at what PM&MiNet did for 1.0.0. The format is more like anvil now.

**Comment by LaChal** [comment]
Thank you for your information :smile:
The PE support could be recompiled on Windows and Linux, and we can open and see parts of the world.
We're now fighting with the subchunk format data and access.

**Comment by LaChal** [comment]
Here is some information about our progress: https://github.com/Khroki/MCEdit-Unified/issues/676#issuecomment-279105921

**Comment by LaChal** [comment]
More advancement has been done on this topic.

PE 1.0 (and 1.1) shall be supported now.

If you still have issues, just reopen. (And search in the other issues, even closed.)
