### ISSUE TITLE
"Mcedit Error, Open Console or Terminate"- Mac

### ISSUE THREAD

**Issue by eastofgrand** [Khroki/MCEdit-Unified#752]
I downloaded MCedit version 1.5.5.0 for mac, but I have not yet been able to successfully open it. Every time I've tried I get the same rather unhelpful "mcedit error" message. It only gives me two options: open console and terminate. I have xquartz and my system is up to date. I have next to no understanding of code so I've simply included a screen capture of what happens, and of what console puts out.
<img width="645" alt="screen shot 2016-12-27 at 4 29 03 pm" src="https://cloud.githubusercontent.com/assets/19255397/21508773/b4085ace-cc51-11e6-9eb6-be5ab22ef53d.png">
<img width="506" alt="screen shot 2016-12-27 at 4 01 54 pm" src="https://cloud.githubusercontent.com/assets/19255397/21508774/b409e6e6-cc51-11e6-9198-6db599e308c8.png">

I'm not sure if that's helpful, but that's what console gives me when I open it.

**Comment by LaChal** [comment]
I'm not a Mac expert, but the answers to the next question will help:

1. Are you experiencing this issue with other MCEdit-Unified versions?
2. If you used a former MCEdit-Unified version, did you updated you system (or something on it) since you last used MCEdit and before you updated to MCEdit 1.5.5.0?

**Comment by xpoizon** [comment]
I am having the same problem.

1.) no version of MCedit unified will work. I've tried 3 computers, a Mac air, 2015 Macbook pro, and an older iMac. The iMac had a 1.0 beta version from probably 2 years ago, and its getting the same "Mcedit error" like in the image above.

2.) the map laptops are on macOS Sierra. The iMac is on El Capitan. I can see no reason why this all of a sudden won't work.

**Comment by Khroki** [comment]
I've seen a few reports on it not working on late El Capitan and Sierra Macs that are newer than my build VM's El Capitan version, I'll try to update it to Sierra and see if that helps.

**Comment by Khroki** [comment]
For anyone with this problem try this build and let me know if it works. It worked fine for me under the current version of Sierra. lavaexpert.org/mcedit.app.zip
Link will be valid for a couple days.

**Comment by eastofgrand** [comment]
Update: I managed to get the program to work by opening the package contents, going to contents>Mac OS and opening the "mcedit" console file there. When I click it, it opens a console panel and mcedit successfully launches.

**Comment by Khroki** [comment]
Closing this since you seem to have figured it out. Reopen if you have further issues.
