### ISSUE TITLE
Mouse View Issue?

### ISSUE THREAD

**Issue by AliffanI** [Khroki/MCEdit-Unified#755]
I'm having a problem. I don't really know if this is because i accidentally pressed something before, but if i control my view with a mouse, the view often slides away by itself. It occurs both using mouse and trackpad.

This happens on the latest update (v1.5.5.0). The problem persists even after deleting the MCEdit folder in Documents (i am running Fixed Mode).

Here is a zip file containing a screen recording.

[1_11_1 FireRace - RACE_level.dat - Unified ~ Unified v1.5.5.0 for Minecraft 1.8-1.11 _ PE 0.11 1_6_2017 23_23_45_1.zip](https://github.com/Khroki/MCEdit-Unified/files/690331/1_11_1.FireRace.-.RACE_level.dat.-.Unified.Unified.v1.5.5.0.for.Minecraft.1.8-1.11._.PE.0.11.1_6_2017.23_23_45_1.zip)

If you see the video, you should see the view slides away (in a constant speed) sometimes after i move my mouse. My mouse is perfectly still when it slides. Maybe i need to do something? Maybe i triggered something accidentally?

**Comment by LaChal** [comment]
Hard to say what happens.
Mouse control depends the operating system and its version, and the code we use.
It can also be related to your hardware and/or drivers you use.

So let us know which Linux/Mac/Windows you use; this will be a starting point :smile:

**Comment by AliffanI** [comment]
I am so, so, sorry for not responding too long.

I have resolved the problem.
It appears that DPI scaling was the source of the problem.
I have DPI scaling enabled in my system in order to (of course) scale my display.
After I went to the compatibility settings and ticked "disable DPI scaling", the view is not sliding away like I've described. Problem solved!

Should I close this issue? Or do you want to research this issue further?

**Comment by LaChal** [comment]
Nice to read you could figure what was happening an solve the issue :smile:
