### ISSUE TITLE
Chunk could not be generated

### ISSUE THREAD

**Issue by useenzhekoay** [Khroki/MCEdit-Unified#758]
I tried to create chunk in 1.11.2 version map but it show below and could not successfully create.

Each server is stored in a subdirectory of C:\Users\ASUSPC\Documents\MCEdit\ServerJarStorage named with the server's version number
Cached servers:  [u'Release 1.11.2']
Generating XXX chunks out of 6 starting from (59, 66)
No chunks were generated. Aborting.

**Comment by LaChal** [comment]
Thank you for the report.

This bug is known and shall be fixed in the next release :smile:
