### ISSUE TITLE
CreateShops Not Creating Shops

### ISSUE THREAD

**Issue by Coreycool99** [Khroki/MCEdit-Unified#760]
When I Click "Filter" The Chest Doesn't Turn Into An Entity (Red Cube)

Inventory Of Chest:
![0 1](https://cloud.githubusercontent.com/assets/25050640/21838929/0b806c1e-d829-11e6-8c66-94d901efffd3.png)

Before Clicking Filter:
![0 2](https://cloud.githubusercontent.com/assets/25050640/21838971/59e4ebe6-d829-11e6-8eab-51e1ac55ee41.png)

After Clicking Filter:
![0 3](https://cloud.githubusercontent.com/assets/25050640/21838979/66071c82-d829-11e6-84b2-befaa95ee909.png)

Why Does This Happen?

Edit:
I Updated MCEdit Unified To The Newest Version. When I Click "Filter" It Say's This:
Exception during filter operation. See console for details.
u'minecraft:chest'

**Comment by Coreycool99** [comment]
I Updated MCEdit Unified To The Newest Version. When I Click "Filter" It Say's This:
![image](https://cloud.githubusercontent.com/assets/25050640/21852157/1b20db9e-d866-11e6-99a1-890a2028dc1f.png)

**Comment by LaChal** [comment]
I guess the console message ends like this:
```
  File "/home/dens/bin/mcedit/stock-filters/CreateShops.py", line 123, in perform
    if e["id"].value == "Chest" or MCEDIT_IDS[e["id"].value] == "DEF_BLOCKS_CHEST":
KeyError: u'minecraft:chest'
```

We'll look at this, of course.

There are for now two work arounds for this.

If you create the chest in MCEdit using the brush tool, and then put items in, the filter runs fine, and your trader is working fine in game.

If you want to use custom items like the enchanted ones I can see in your screenshot, follow these steps:
* Select the chest.
* Use the `NBTEdit` filter, whit at least the `Tile Entities` box checked.
* Open the element in the `TileEntities` results panel.
* Change the `id` tag value for `Chest`. Pay attention to the capital C.
* Click on `OK`
* Select the `Create Shops` filter.
* Apply it.
* Enjoy!
