### ISSUE TITLE
Having trouble

### ISSUE THREAD

**Issue by Joshua-robotics** [Khroki/MCEdit-Unified#767]
I have MCPE version 1.0+  and mcedit only shows up as a blank world when I open the level.dat is there a reason for this? And will it get fixed anytime soon?

**Comment by LaChal** [comment]
Badly, the PE support is not working very well for any PE versions.
Sorry :/

**Comment by dmtaub** [comment]
I'd like to try to help given some insight into the problem...is there another open issue somewhere?

**Comment by dmtaub** [comment]
Duplucate #751
