### ISSUE TITLE
Unable to copy large part of world

### ISSUE THREAD

**Issue by Noiknez** [Khroki/MCEdit-Unified#768]
Greeting, i am trying to copy a part of my world but mcedit is unable to copy files that is superior to 4 gb. An error message appear and tell me to use ZIP64. I made some research and are unable to find a solution for it (i really dont want to copy small part of my world)
I really need help to know how to use Zip64 for McEdit.
Thank you very much

**Comment by Podshot** [comment]
Can you give us a screenshot of the console window? And what version of MCEdit are you using?

**Comment by Noiknez** [comment]
I use the 1.5.6.0 version, i cant get the screen now because the select-all --> copy take 20 hours.
I tried it 2 times : one with default setting and another with the cache at 50000 MB, same message
Therefore there is some information on zip64 on mcedit on this page : http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1260525-mcedit-minecraft-world-editor-now-open-source?page=451

**Comment by naor2013** [comment]
I think I know what the issue is. I need you to send me the map which I know will be an hard thing to do, but I hope you can try using dropbox or something, otherwise I can't test it...

**Comment by Noiknez** [comment]
@naor2013 I send you the download link via email

**Comment by naor2013** [comment]
Just giving an update, I think I fixed it, I'm testing at the moment, it will take a few hours.
BTW, explaining that cache setting you tried to change, what it means is basically asking you how much of your ram do you agree to use for copying the map before you want it to be saved in your computer as a zip file. So, even setting it to 50000 MB won't work since you don't actually have 50 GB of ram.
Just out of curiosity, why are you actually trying to copy a 32GB map for?

**Comment by Noiknez** [comment]
Great news
I understand know for the cache thanks you
For the copy it is to transpose it in a void world, deleting water and do other stuff like deleting tilesticks

**Comment by Noiknez** [comment]
Hi, thank you for adding this in the commit.
I tried to changed the old file with the new file and i get this error :
Console --> http://pastebin.com/vsPeFgb3
Msg in mcedit --> http://prntscr.com/efgbhx

Is it because i changed only the shematic.py file ?

**Comment by naor2013** [comment]
Are you running from source?
And did you see his second commit? The one after this one? He changed one more line that could be the cause of your issue
