### ISSUE TITLE
Can't create Shops in 1.11

### ISSUE THREAD

**Issue by Blacki017** [Khroki/MCEdit-Unified#771]
Hello!

I have a bug with mcedit V1.5.6.0 & V1.5.5.0 on minecraft 1.11. When I try to create an NPC, it puts me an error message with "exception during filter operation. See console for details. u 'minecraft:chest' "so I have been see in the console and it puts me the following error message:"

> Traceback (most recent call last):
> File "editortools\filter.py", line 63, in _func
> File "editortools\filter.py", line 877, in confirm
> File "editortools\filter.py", line 544, in confirm
> File "leveleditor.py", line 3176, in addOperation
> File "leveleditor.py", line 3187, in performWithRetry
> File "editortools\filter.py", line 900 in perform
> File "D:\Users\Black\Desktop\MC edit\mcedit v1.5.5.0\stock-filters\CreateShops.py", line 123, in perform
> e if ["id"] .value == "Chest" or [e ["id"] .value] MCEDIT_IDS == "DEF_BLOCKS_CHEST":
> KeyError: 'minecraft:chest' u

How to fix the problem?
P-S: sorry for my English...

**Comment by LaChal** [comment]
Hello,

Badly, some resource files are missing in the Windows and OSX releases...
Please, have a look to this post on Reddit: https://www.reddit.com/r/MCEdit/comments/5ukx18/to_windows_and_mac_users/
It will guide you to apply the fix by copying th right files in the right place.

If you still have the problem, just reopen this issue :smile:

**Comment by xLucasJan** [comment]
I have the same fucking error ;-; it's so sad, i just wanna play with my friends and some fucking stupid villagers ;-;
