### ISSUE TITLE
Key TrackOutput not Found

### ISSUE THREAD

**Issue by candyli0962** [Khroki/MCEdit-Unified#773]
I am getting an error when I try to edit a command block.

Version: 1.5.6.0
Minecraft Version: 1.11.2

Full Error: Error during <function EditCommandBlock at 0x000000000A47E588>: KeyError ('Key Output not found.',)

Error In The Log File: 
Traceback (most recent call last):
  File "mceutils.py", line 56, in _alertException
  File "viewports\camera.py", line 1092, in editCommandBlock
  File "_nbt.pyx", line 448, in _nbt._TAG_Compound.__getitem__ (_nbt.c:9734)
KeyError: 'Key TrackOutput not found.'

Filter Used: StructureToCmd_1_10

More Detailed Errors: https://www.dropbox.com/s/i817bmew59p8lr4/Mcedit%20Errors.zip?dl=0

**Comment by Jachael123** [comment]
Did you end up finding a solution for this error? I'm having the same problem... :(

**Comment by Podshot** [comment]
@Jachael123 Yes, we've fixed in our testing releases, you can find them [here](https://github.com/Podshot/MCEdit-Unified-Preview/releases/tag/MCEdit-Unified-1.6.0.52-testing)

### Make sure you backup any world before you open it in any testing release!
