### ISSUE TITLE
Another Key 'TrackOutput not Found' Again!

### ISSUE THREAD

**Issue by candyli0962** [Khroki/MCEdit-Unified#774]
I am getting an error when I try to edit a command block.

Version: 1.5.6.0 - MASTER Files Added
Minecraft Version: 1.11.2

**Full Error: Error during <function EditCommandBlock at 0x0000000009D05588>: KeyError ('Key Output not found.',)

[   ERROR][                    root.py:62]:Exception:
Traceback (most recent call last):
  File "mceutils.py", line 56, in _alertException
    return func(*args, **kw)
  File "viewports\camera.py", line 1092, in editCommandBlock
    #             commandField.value = tileEntity["Command"].value.decode("unicode-escape")
  File "_nbt.pyx", line 448, in _nbt._TAG_Compound.__getitem__ (_nbt.c:9734)
KeyError: 'Key TrackOutput not found.'

Filter Used: StructureToCmd_1_10

More Detailed Errors [Updated Link]: https://www.dropbox.com/s/m3cm50fgwejasjb/Mcedit%20Errors.zip?dl=0

**Comment by naor2013** [comment]
It's the same issue... Just changing the files will not fix the issue. You either need to run from source which means downloading all the needed libraries and all or just wait for the next release... I'm afraid we can't just fix this specific issue easily for you without the new release :(
