### ISSUE TITLE
Creating shops : u'minecraft:chest'

### ISSUE THREAD

**Issue by baptiste67980** [Khroki/MCEdit-Unified#778]
![capture](https://cloud.githubusercontent.com/assets/26577441/24157503/c8f14bae-0e59-11e7-8d1e-95ad50f6ae1e.PNG)

I can't create shops with mc edit. This message apears : u'minecraft:chest'

please help me ! ;) thanks !!

**Comment by LaChal** [comment]
I guess you're running on Windows or OSX.

The fix for this bug is already know and easy applicable.
Just read [in this reddit post](https://www.reddit.com/r/MCEdit/comments/5ukx18/to_windows_and_mac_users/) and all shall be fine with your shops :smile:
