### ISSUE TITLE
Importing schematic

### ISSUE THREAD

**Issue by KoiYT** [Khroki/MCEdit-Unified#788]
![no import](https://cloud.githubusercontent.com/assets/27504402/25048102/7cd66a42-2132-11e7-9d2b-2557303a5550.jpg)
Does anyone know why I keep getting this error when I try to import a schematic?

**Comment by LaChal** [comment]
According to your screen shot, you're using MCEdit 2.
You shall post there: https://github.com/mcedit/mcedit2

We can't do anything here, sorry :/

**Comment by KoiYT** [comment]
Ok thx.
