### ISSUE TITLE
Suggestion: Chunk coordinates shown while editing chunk.

### ISSUE THREAD

**Issue by HuskyTW** [Khroki/MCEdit-Unified#792]
It's a idea when I was copy a map and paste to new one.
In my server, there are several nether potals connected in every district.(It takes less time travel in nether than world.)
And if I paste a world map, I need to paste the nether map at a correct place so that the nether portal won't be offset.
Thus, I need to know what the coordinate I should paste exactly.
While in MCEdit, I couldn't check for it.
Hope that would be add.
Thank you for the effort to this project.

**Comment by LaChal** [comment]
Sorry for the late answer.

To see detailed information, you can use the 'debug' view by pressing the '0' (zero) key on the alphabetic part of your keyboard.

We're fixing some stuff with recent game version for now, and don't have much time for this type of enhancement :/

Anyway, thank you for the suggestion. We'll try to implement it :smile:

**Comment by HuskyTW** [comment]
It's OK. 
Feel free to do that!
---
I noticed that some translation in zh_tw is empty and some are unfamiliar in the meaning.
If you don't mind, I would like to do some effort on it.
If it is OK, where should I upload the file?

**Comment by LaChal** [comment]
Just create a fork and push your translation file here. Then, create a pull request. It will be reviewed, then, maybe merged into the main repo :wink:

Pay attention to the file format.
For more information, please, refer to [TRANSLATION.txt](https://github.com/Khroki/MCEdit-Unified/blob/master/TRANSLATION.txt).

If you're not familiar with git/github forks/branches/repos, please refer to the documentation. (Nothing very hard here :smile:).

**Comment by Podshot** [comment]
If I understand your request correctly, you want chunk coordinates shown on the info tooltip? (when you press Ctrl) Or do you want it when you're using the Chunk Tool?

**Comment by HuskyTW** [comment]
To Podshot:
For detail it might be:
When I pointing to the specific chunk, there would be ```chunk coordinate``` shown 
maybe bottom left or right the window. (while using chunk view)
(Apologize for the wrong meaning above I mean ```chunk view``` instead of ```chunk tool```)
Without pressing any key.
It shown when pointing the chunk.
That's what I expect.

Further more (I just pop up):
While in ```camera view``` it would show the ```chunk coordinate``` where user located.

Feel free to do that, it's just a suggestion😄😄

**Comment by LaChal** [comment]
You can also hit the `0` (the 'zero' one above the letters keys) key to show up a 'debug' ribbon on the top of the display.

**Comment by HuskyTW** [comment]
Got it!
Thank you~~~~
