### ISSUE TITLE
Error during schematic import on windows 10 mcedit version 1.5.6

### ISSUE THREAD

**Issue by Feltiks** [Khroki/MCEdit-Unified#793]
here is what pops up on the screen
Error during <function confirm at 0x000000000969EF28>:IOError(13, 'Permission denied')

and here is the log from opening to the attempted placement of the schematic.
[log.txt](https://github.com/Khroki/MCEdit-Unified/files/940893/log.txt)

please help

**Comment by LaChal** [comment]
This is a Windows access control issue, AFAIK.

Use the contextual menu to check the permissions on your user folder (in `C:\Users`) and it's sub-folders, especially `appdata\temp`.
Ensure your user is the owner and can read and writ in this folder and the ones in.

**Comment by Feltiks** [comment]
I did that and it didnt change

**Comment by LaChal** [comment]
The access rights and ownership of files and directories can be hard to set up in Windows 10. You may have to dive into ACL settings of the folder.

You also can have a look there:
https://answers.microsoft.com/en-us/windows/forum/windows_10-security/folder-and-file-permissions-changed-in-windows-10/38bb51a5-8cfb-4349-b635-0fdae1287eb0?page=1
https://answers.microsoft.com/en-us/windows/forum/windows_10-files/document-folders-marked-read-only-after-upgrade-to/4f00d3fe-82b0-4e6d-a92a-f81751aa6f51?auth=1
https://www.cnet.com/forums/discussions/windows-10-changed-all-my-documents-to-read-only/

**Comment by Feltiks** [comment]
It worked. Thankyou

**Comment by LaChal** [comment]
You're welcome :smile:
