### ISSUE TITLE
MCPE world crashing MCEdit (using source version with new-features)

### ISSUE THREAD

**Issue by neonerz** [Khroki/MCEdit-Unified#798]
[As reported here](https://www.reddit.com/r/MCPE/comments/6e7xnf/140_mb_minecraft_pe_world_experiences_consistent/), user has a 143mb world file that's lagging in game (I confirmed the lag in both Android and Win10).

Upon loading in MCEdit, the console spams the following error message:
`Traceback (most recent call last):  `
`  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3865, in workOnChunk  `
`    for _ in faceInfoCalculator:  `
`  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 3847, in calcFacesForChunkRenderer  `
`    for _ in calc:  `
`  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 389, in calcFaces  `
`    for _ in self.renderer.chunkCalculator.calcFacesForChunkRenderer(self):  `
`  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 858, in calcFacesForChunkRenderer  `
`    for _ in self.calcHighDetailFaces(cr, blockRenderers):  `
`  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 1014, in calcHighDetailFaces  
    areaBlocks = self.getAreaBlocks(chunk, neighboringChunks)  `
`  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\renderer.py", line 897, in getAreaBlocks  
    :nb_fxd.Blocks.shape[2]]  `
`ValueError: could not broadcast input array from shape (1,16,256) into shape (1,16,128)`

 for most of the chunks then eventually crashes with the following error:
`mcedit.main MCEdit exited with errors.`
`[   ERROR][                   root.py:939]:MCEdit version Unified v1.5.6.0 %s Minecraft 1.8-1.11.2 | PE 0.11`
`Traceback (most recent call last):`
`  File "mcedit.py", line 1002, in <module>`
`    main(sys.argv)`
`  File "mcedit.py", line 936, in main`
`    MCEdit.main()`
`  File "mcedit.py", line 814, in main`
`    rootwidget.run()`
`  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\albow\root.py", line 168, in run`
`    self.run_modal(None)`
`  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\albow\root.py", line 233, in run_modal`
`    self.gl_draw_all(self, (0, 0))`
`  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\albow\widget.py", line 766, in gl_draw_all`
`    subwidget.gl_draw_all(root, suboffset)`
`  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\albow\widget.py", line 766, in gl_draw_all`
`    subwidget.gl_draw_all(root, suboffset)`
`  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\albow\widget.py", line 766, in gl_draw_all`
`    subwidget.gl_draw_all(root, suboffset)`
`  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\albow\widget.py", line 766, in gl_draw_all`
`    subwidget.gl_draw_all(root, suboffset)`
`  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\albow\widget.py", line 763, in gl_draw_all`
`    self.gl_draw_self(root, offset)`
`  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\albow\openglwidgets.py", line 22, in gl_draw_self`
`    self.gl_draw_viewport()`
`  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\albow\openglwidgets.py", line 28, in gl_draw_viewport`
`    self.gl_draw()`
`  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\viewports\camera.py", line 1891, in gl_draw`
`    self.render()`
`  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\viewports\camera.py", line 1913, in render`
`    self.updateBlockFaceUnderCursor()`
`  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\viewports\camera.py", line 345, in updateBlockFaceUnderCursor`
`    100, config.settings.viewMode.get())`
`  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\raycaster.py", line 93, in firstBlock`
`    block = level.blockAt(*i[0])`
`  File "C:\Users\gbove\Desktop\mcedit\MCEdit-Unified\pymclevel\infiniteworld.py", line 536, in blockAt`
`    return ch.Blocks[xInChunk, zInChunk, y]`
`IndexError: index 140 is out of bounds for axis 2 with size 128`

[Full MCEdit log can be found here](https://pastebin.com/C5gdwAw6). World file could be found in the reddit link posted above, but here's a [direct link](https://drive.google.com/open?id=0B-NRsFEp5kmQX1JNanplNVp3N3M) for your convenience. 

Admittedly, the crashing seems to be related to an issue with the world itself, but the errors generated and hard crashed seemed to warrant further investigation. I've confirmed the issue in both windows and linux running MCEdit from source using new-features.

**Comment by naor2013** [comment]
Fixed the crash, now trying to find the cause for the repeating warning! Thanks for the submission :)

**Comment by naor2013** [comment]
Fixed both the crash and the warnings, maps from 1.0 should work well now! Now we'll need to fix 1.1 maps :P
