### ISSUE TITLE
Bedrock Edition (MCPE/Win10) in Windows

### ISSUE THREAD

**Issue by gentlegiantJGC** [Khroki/MCEdit-Unified#805]
Trying to open Bedrock edition worlds in MCEdit on Windows
I have been reading through the steps to run from source and have managed to boot to the menu however I am encountering problems loading bedrock worlds. I saw there is a build file for linux only so I can't run this.

Currently getting the following error. Any help or suggestions?
```
[    INFO][      pymclevel.mclevel.py:200]:Identifying C:\Users\james_000\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\-WEDACfOAAA=\level.dat
[   ERROR][                  root.py:1189]:Wasn't able to open a file {file => C:\Users\james_000\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\-WEDACfOAAA=\level.dat}
Traceback (most recent call last):
  File "C:\Users\james_000\Desktop\New folder (4)\MCEdit-Unified-master\leveleditor.py", line 1186, in loadFile
    level = pymclevel.fromFile(filename)
  File "C:\Users\james_000\Desktop\New folder (4)\MCEdit-Unified-master\pymclevel\mclevel.py", line 226, in fromFile
    return PocketLeveldbWorld(filename)
  File "C:\Users\james_000\Desktop\New folder (4)\MCEdit-Unified-master\pymclevel\leveldbpocket.py", line 585, in __init__
    self.worldFile = PocketLeveldbDatabase(filename, create=create)
  File "C:\Users\james_000\Desktop\New folder (4)\MCEdit-Unified-master\pymclevel\leveldbpocket.py", line 314, in __init__
    self.options = leveldb_mcpe.Options()
AttributeError: 'NoneType' object has no attribute 'Options'
[   ERROR][                   root.py:677]:Failed to load file C:\Users\james_000\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\-WEDACfOAAA=\level.dat: TypeError("object of type 'NoneType' has no len()",)
```

If you want you can use me to help test bedrock support on windows

**Comment by LaChal** [comment]
To open PE worlds, you have to use the new support, which is not accessible by default. Follow the steps [here](https://github.com/Khroki/MCEdit-Unified/issues/779#issuecomment-288840904) to activate this new support. It's talking about OSX, but the principle is the same on Windows. (The DLL is already in the sources.)
It will become the default method to open PE worlds soon :smile:

**Comment by gentlegiantJGC** [comment]
Thanks for the reply. Getting an issue with the LevelDB-MCPE.dll file

`[   ERROR][      pymclevel.leveldb.py:107]:[Error 193] %1 is not a valid Win32 application`

even trying to load the dll through IDLE is producing the same problem. From a quick google search of that error it could be an architecture issue but I don't know. My PC is 64bit and to my knowledge everything installed should be 64bit as well

**Comment by gentlegiantJGC** [comment]
Come back with a fresh head and realised the default python installer is a 32bit and you have to dig a little deeper to find the 64bit installer. Reinstalled and redownloaded all the 64bit libraries and it seems closer to working. Getting this error now.
```
  File "C:\Users\james_000\Desktop\New folder (4)\MCEdit-Unified-master\mclangres.py", line 91, in <genexpr>
    versions = ['%s.json' % '.'.join(map(u"{}".format, c)) for c in sorted((map(int, b) for b in (a.split('.')[:-1] for a in versions)))]
ValueError: invalid literal for int() with base 10: '4_af'
```

I tried debugging it but didn't get anywhere. Commenting that line out allows the world to open fine

**Comment by LaChal** [comment]
Looks like you're using a snapshot or pre-release game version.
Which one is it?

**Comment by gentlegiantJGC** [comment]
I am using Minecraft Windows 10 Edition V1.1.0 which is the latest main release. Not a snapshot or pre-release

**Comment by LaChal** [comment]
OK.

I found the reason for this bug.
You have installed a game version (or pre-release or snapshot) which contains '4_af', and this is why MCEdit crashes. (The crash is not related to the PE support, but to another part of the program.)

As a work-around until it's fixed, move all the files in the 'assets/indexes' game sub-directory which do not contain *only* digits and dots when you want to use MCEdit. Restore them before launching the game.
