### ISSUE TITLE
undefined symbol: Py_InitModule4 issue on Kali Linux

### ISSUE THREAD

**Issue by kernel-pan-ic** [Khroki/MCEdit-Unified#806]
Whenever I try to run mcedit.py, no matter what, it just throws up this:
`Running in fixed mode. Support files are in your Documents folder.`
`Traceback (most recent call last):`
`  File "mcedit.py", line 13, in <module>`
`    import splash`
`  File "/root/Desktop/MCEdit-Unified-1.5.6.0/splash.py", line 10, in <module>`
`    import pygame`
`  File "/root/.local/lib/python2.7/site-packages/pygame/__init__.py", line 95, in <module>`
`    from pygame.base import *`
`ImportError: /root/.local/lib/python2.7/site-packages/pygame/base.so: undefined symbol: Py_InitModule4`
I don't know anything about Python, so I just tried to Google the error, but I couldn't find anything that helped. I've installed all of the dependencies noted in README.md using pip. I'll give the output of any commands that you need. Thanks in advance.

SPECS:
OS: Kali Linux Rolling 64-bit (based on Debian)
Pygame version: 1.9.3

**Comment by LaChal** [comment]
You have a dependency issue.

On Linux, try to use pygame 1.9.1.
Also, pay attention to pygame dependencies. Install them if they're not satisfied.

Please, note that pygame is one of the dependencies that shall be installed with the package manager, because of it's own dependencies...

I hope I'll find a solution for this soon.

**Comment by kernel-pan-ic** [comment]
That didn't actually fix it, but I found what did. It turns out that it was actually running Pygame from /root/.local/lib/python2.7/site-packages/pygame because I ran the .run file from http://www.mcedit-unified.net/ earlier. That file must have put the wrong version in /root/.local/lib/…. The program started working just fine after I deleted that. Thanks anyway!
