### ISSUE TITLE
Bedrock Edition level.dat file corruption

### ISSUE THREAD

**Issue by gentlegiantJGC** [Khroki/MCEdit-Unified#810]
Opening a Windows 10 edition world and saving without modifying anything will cause 0D (in hex format) to be added to the level.dat file in a number of places. This character seems to be the carriage return character (\r).

Opening the world in game will cause the level.dat file to be recreated and new chunks generated using the new level.dat file. In the case tested going from a superflat world to the normal generator.

**Comment by Podshot** [comment]
Does the 0D occur with a certain NBT Tag type, or is it a random occurance?

**Comment by gentlegiantJGC** [comment]
just done a little digging and found that every 0D that is added is followed by at 0A as @LaChal just wrote in the bug report he just referenced.

**Comment by LaChal** [comment]
@gentlegiantJGC You're running from source, AFAIK, so you may confirm this issue is fixed :smile:

**Comment by gentlegiantJGC** [comment]
tested and that seems to have fixed it

**Comment by LaChal** [comment]
Thanks!

Closing :smile:
