### ISSUE TITLE
Pocket Edition Support Tests failing

### ISSUE THREAD

**Issue by tuxutku** [Khroki/MCEdit-Unified#811]
Start step 1 [y/n]? y

-------------------------------------------------------------------------------
Detecting state of the dependencies...
* Libraries found and compliant:
  - PyOpenGL is 3.1.0, is at least 3.1.0.
  - ftputil is 3.3.1, is at least 3.2.
  - numpy is 1.12.1, is at least 1.8.1.
  - pillow is 4.1.1, is at least 1.7.8.
  - pygame is 1.9.1, is 1.9.1.
  - python-xlib is 0.14, is at least 0.14.
  - pyyaml is 3.12, is at least 3.10.

All the dependencies are satisfied.

Start step 3 (move MCEdit-Unified) [y/n]? n
NBT Support Tests

The NBT library will be tested.
The tests may fail. This is not critical.
Depending on the failed test(s), the pure Python support will be used. It is slower, but it works!            

See 'LINUX_INSTALL.txt, 'NBT SUPPORT' section for more information.            

You will be asked to rebuild the NBT library if some tests fail.

NBT Support Tests

Running tests...

All NBT test performed successfully:

*** Starting NBT tests...
*** '_nbt.so' imported successfully.
*** Calling testCreate.
*** Calling testErrors.
*** Calling testList.
*** Calling testLoad.
MinecraftLevel
23
[7 7 7 ..., 0 0 0]
*** Calling testLoadNBTExplorer.
*** Calling testLoadUncompressed.
*** Calling testModify.
*** Calling testMultipleCompound.
*** Calling testSpeed.
*** Calling testToStrings.
 Hit ENTER to continue

Pocket Edition support

Installing Pocket Edition support...

Pocket Edition Support Tests

Running tests...

An error occured when runnig the test:
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from leveldb_mcpe import DB, Options, ReadOptions, WriteOptions, WriteBatch, RepairWrapper
ImportError: /home/utku/Programlar/mcedit/mcedit-1.5.6.0/leveldb_mcpe/leveldb_mcpe.so: undefined symbol: _ZTVN7leveldb14ZlibCompressorE

i created /home/utku/Programlar/mcedit and runned installer from there
utku@utku-Satellite-C655:~/Programlar/mcedit$ /home/utku/İndirilenler/MCEdit.v1.5.6.0.Lin.Universal.run
i installed pillow and ftputils with pip install --user, couse they are wasn't in the repository
i am using ubuntu 17.04 64bit *fresh install*

also when i try to open mcpe levels 

utku@utku-Satellite-C655:~$ /home/utku/Programlar/mcedit/mcedit-1.5.6.0/mcedit.sh
Starting MCEdit...
Running in fixed mode. Support files are in your Documents folder.
Splash load...
[ ****** ] ~~~~~~~~~~ Starting MCEdit-Unified v1.5.6.0
[ WARNING][       OpenGL.GLUT.fonts.py:23]:Unable to load font: GLUT_BITMAP_9_BY_15
[ WARNING][       OpenGL.GLUT.fonts.py:23]:Unable to load font: GLUT_BITMAP_8_BY_13
[ WARNING][       OpenGL.GLUT.fonts.py:23]:Unable to load font: GLUT_BITMAP_TIMES_ROMAN_10
[ WARNING][       OpenGL.GLUT.fonts.py:23]:Unable to load font: GLUT_BITMAP_TIMES_ROMAN_24
[ WARNING][       OpenGL.GLUT.fonts.py:23]:Unable to load font: GLUT_BITMAP_HELVETICA_10
[ WARNING][       OpenGL.GLUT.fonts.py:23]:Unable to load font: GLUT_BITMAP_HELVETICA_12
[ WARNING][       OpenGL.GLUT.fonts.py:23]:Unable to load font: GLUT_BITMAP_HELVETICA_18
[ WARNING][            mcplatform.py:1276]:Initializing window management...
[ WARNING][            mcplatform.py:1281]:Your desktop environment is not yet supported for window sizing/moving.
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of /home/utku/.mcedit/MCEdit/ServerJarStorage named with the server's version number
Cached servers:  []
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/tmp/release-master/MCEdit-Unified/mcedit.py", line 748, in fetch_version
  File "/tmp/release-master/MCEdit-Unified/release.py", line 54, in fetch_new_version_info
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>

An error occurred checking for updates.
[   ERROR][                   root.py:228]:Pocket support has failed
None
[ WARNING][     pymclevel.javalevel.py:45]:Can't guess the size of a 379 byte level
[   ERROR][                  root.py:1190]:Wasn't able to open a file {file => /home/utku/MCPE/com.mojang/minecraftWorlds/MQEAAE9nAgA=/level.dat}
Traceback (most recent call last):
  File "/tmp/release-master/MCEdit-Unified/leveleditor.py", line 1187, in loadFile
  File "/tmp/release-master/MCEdit-Unified/pymclevel/mclevel.py", line 280, in fromFile
LoadingError: (('Multiple errors encountered', NBTFormatError('Not an NBT file with a root TAG_Compound (file starts with "   \x05" (0x00000005)',), IOError('MCJavaLevel attempted for smaller than 64 blocks cubed',)), <traceback object at 0x7f6c70111128>)

i was able to open same maps with older build but same version (which had zlib url problem)

also

utku@utku-Satellite-C655:~/Programlar/mcedit/mcedit-1.5.6.0/leveldb_mcpe$ python setup.py build
Building Linux application 'leveldb_mcpe'...
ls: 'build/*/leveldb_mcpe.so''e erişilemedi: Böyle bir dosya ya da dizin yok (couldn't delete, no such file or directory)
Boost found in /home/utku/.local/lib/boost_1_58_0_mcpe.
Do you want to reinstall it [y/N]?n
Building boost_python...
sh: 1: ./b2: not found
Done.
Mojang's leveldb is already built. Rebuild [y/N] ?y
rm: 'leveldb-mcpe' silinemedi: Böyle bir dosya ya da dizin yok (couldn't delete, no such file or directory)
--2017-06-19 20:48:57--  https://github.com/Khroki/MCEdit-Unified/tree/master/leveldb_mcpe
github.com (github.com) çözümleniyor... 192.30.253.113, 192.30.253.112
github.com (github.com)[192.30.253.113]:443 bağlanılıyor... bağlantı kuruldu. (connected)
HATA: github.com sertifikası doğrulanamıyor. `CN=DigiCert SHA2 Extended Validation Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US' tarafından sağlanmış:
  Yerel olarak sağlayıcının kimliği doğrulanamaıyor. (can't confirm local user certificate)
github.com adresine güvenliği gözardı ederek bağlanmak için `--no-check-certificate' seçeneğini kullanın. (to dissmis security use '--no-check-certificate' option)
--2017-06-19 20:48:58--  https://github.com/Mojang/leveldb-mcpe/tree/
github.com (github.com) çözümleniyor... 192.30.253.112, 192.30.253.113
github.com (github.com)[192.30.253.112]:443 bağlanılıyor... bağlantı kuruldu. (connected)
HATA: github.com sertifikası doğrulanamıyor. `CN=DigiCert SHA2 Extended Validation Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US' tarafından sağlanmış:
  Yerel olarak sağlayıcının kimliği doğrulanamaıyor. (can't confirm local user certificate)
github.com adresine güvenliği gözardı ederek bağlanmak için `--no-check-certificate' seçeneğini kullanın. (to dissmis security use '--no-check-certificate' option)
wget: URL kayıp (missing url)
Kullanımı: wget [SEÇENEK]... [URL]... 

Daha fazla seçenek için `wget --help' yazın.
Extracting Mojang's leveldb-mcpe...
unzip:  cannot find or open leveldb-mcpe-master.zip, leveldb-mcpe-master.zip.zip or leveldb-mcpe-master.zip.ZIP.
ls: '*/''e erişilemedi: Böyle bir dosya ya da dizin yok (no such file or directory)
mv: 'leveldb-mcpe' sonrasında hedef dosya işleyeni eksik
Try 'mv --help' for more information.
Traceback (most recent call last):
  File "setup.py", line 179, in <module>
    os.chdir('leveldb-mcpe')
OSError: [Errno 2] No such file or directory: 'leveldb-mcpe'

i am not a native english speaker so forgive any mistake

**Comment by LaChal** [comment]
The current support for PE worlds is not working. Even if you can compile it. It _**may**_ read PE 0.9 and below worlds, but not the 1+ ones.

We're working on the next PE support; and I hope the next release will come soon :construction_worker_man:
The compilation process will be neater.

The only way you have to use this new PE support for now is to run from source, and compile it with the `setup_leveldb.py` script. You may also need to tweat the startup script `mcedit.sh` if you need to compile `zlib` specifically for the PE support. (Nothing impossible at all here :smile:)

**Comment by tuxutku** [comment]
Thanks for your support, i will wait for the next release :)
