### ISSUE TITLE
1.7.10 forge

### ISSUE THREAD

**Issue by Timmysaur** [Khroki/MCEdit-Unified#812]
I read that MCEdit works with 1.7.10 forge, but whenever I try to open a new version of minecraft, the forge version doesn't show up. I have tried getting a different version of forge 1.7.10, but the same thing happens. I want to know if this application can actually work with 1.7.10 forge or not.

**Comment by LaChal** [comment]
Currently, MCEdit-Unified does not support modded worlds.
It _**may**_ open them, but no guaranty about what happens...

**Comment by Timmysaur** [comment]
Okay, thanks for the quick answer.
