### ISSUE TITLE
Shop Filter Error - Not Working

### ISSUE THREAD

**Issue by Azounstone** [Khroki/MCEdit-Unified#814]
Hi all :)

I am trying to use the shop filter to add over 300 shops to our 3rd adventure map but each time I run the filter it is giving this error:

File "*****path_removed******\mcedit\stock-filters\CreateShops.py", line 123, in perform
    if e["id"].value == "Chest" or MCEDIT_IDS[e["id"].value] == "DEF_TILEENTITIES_CHEST":
KeyError: u'minecraft:chest'

Would anyone be able to fix this for me please?

Thanks :)

**Comment by LaChal** [comment]
Weird. I don't experience this issue.

Please, check if you have the exact same file containing the exact same data as described [here](https://www.reddit.com/r/MCEdit/comments/5ukx18/to_windows_and_mac_users/).

**Comment by Azounstone** [comment]
This fixed it:

https://github.com/Khroki/MCEdit-Unified/issues/771
