### ISSUE TITLE
1.0 buttons missing

### ISSUE THREAD

**Issue by Catlod** [Khroki/MCEdit-Unified#823]
Whenever I download the latest version of 1.0, both the copy and export buttons are missing, and when i try to export a selection with ctrl-e it doesn't work

**Comment by LaChal** [comment]
Which version of MCEdit are you using?
You can see it in the title bar or in the console.

**Comment by Catlod** [comment]
@LaChal I'm using Unified v1.5.6.0

**Comment by LaChal** [comment]
Hmmm...

Weird stuff here.
Before closing MCEdit, please copy the console out put and paste it here. If it is long, just save it to a text file and upload it here.
Also, the log file can be useful. It's named `mcedit.log` and is locate where you installed MCEdit.
You may want to mask some data in the file, like your name, so, just 'Search and replace' that before uploading.

**Comment by Catlod** [comment]
Sorry nevermind. I was in chunk view when i was suppose to be in camera view for the buttons to show.
Sorry for the inconvenience.

**Comment by LaChal** [comment]
Duh...
I also can click the wrong (nuclear warfare) button sometimes...

You're welcome :smile:
