### ISSUE TITLE
PE Data Value Issue When Converting From PC Worlds

### ISSUE THREAD

**Issue by bman92102** [Khroki/MCEdit-Unified#825]
When importing a schematic from PC to PE, the data values of some blocks are lost, these include but are not limited to, Slabs, Double Slabs, Command Blocks, Hoppers, Concrete, Etc. This has already been reported in issue #800, but since then, now I know it occurs to blocks with multiple data values. It mainly occurs with data values 1, and 10-15.  The weird thing is that this doesn't occur when transferring PE schematics to PE, only from PC to PE. This happens on all OSes and has been happening even before the new PE support. I know porting isn't a native feature yet, but this seems like a side effect of a bug as @neonerz said. Thanks! 😄 

Edit: If you want me to close this issue and put it in #800 instead, just tell me.

**Comment by LaChal** [comment]
I think it's a good thing to reopen #800, and use it to track PE/PC DV differences.
This will avoid data/discussion spreading.

You can also rename #800 :smile:
