### ISSUE TITLE
PE 1.2 (beta) world crashes

### ISSUE THREAD

**Issue by neonerz** [Khroki/MCEdit-Unified#834]
Failing with the following error

`AttributeError: Unknown PE chunk version ♠`

Sample world attached.
[flatland_ocean_biome.zip](https://github.com/Khroki/MCEdit-Unified/files/1199338/flatland_ocean_biome.zip)

**Comment by LaChal** [comment]
This is quite attended actually.

Mojang has changed the chunk format and version, IMO...

Will have a look :smile:

**Comment by LaChal** [comment]
@neonerz I made tests with you world, and I was able to change the chunk type from Ocean to Plains for one chunk.
Note that I saw an issue with the signs. Looks like Mojang changed (again) their NBT data...

**Comment by neonerz** [comment]
Looks like more changes. From Tommaso on Twitter:

Tools that read MCPE levels will need a small change, rhis is an example of how to set up a MCPE LevelDB instance:
 https://t.co/t4PhjqbClh

**Comment by neonerz** [comment]
@LaChal, do you want to reopen this issue for the leveldb changes, or do you want me to start a new one?
