### ISSUE TITLE
 Can't open 1.0.0 (MCPE) worlds on windows 10

### ISSUE THREAD

**Issue by babyicewolf** [Khroki/MCEdit-Unified#838]
I'm trying to edit map for mcpe it is a 1.0.0 world on windows 10 but it won't open it just says "looks like this world is empty you will have to creat some chunks "

**Comment by AHUMANTHATISHUMAN** [comment]
1.0.0 worlds do not load unless you are running from source. There are no instruction to run with PE support if you are not using Linux.

**Comment by naor2013** [comment]
Actually, we have pre-releases out with MCPE support so you can test those out! Just a warning, those are not finished releases so you may get some bugs. We recommend to always have backups of your maps before using those pre-releases...
You can find them at:
https://github.com/Podshot/MCEdit-Unified-Preview/releases
