### ISSUE TITLE
Please Update and Error during <function rotate at 0x000000000B0DF198>

### ISSUE THREAD

**Issue by DestructiveBurn** [Khroki/MCEdit-Unified#840]
Someone, please update it with the new blocks and ID's from Minecraft 1.12 
Also, it has a rotation issue.  Not on everything but having to use an older version just to rotate most is annoying. 

Error during <function rotate at 0x000000000B0DF198>:
TypeError("unhashable type: '_nbt.TAG_String'",)

**Screenshot**
[https://s25.postimg.org/cxyo2aotr/2017-08-22_21-43-51.png](https://s25.postimg.org/cxyo2aotr/2017-08-22_21-43-51.png)

**Comment by LaChal** [comment]
Closing this issue, since the bug has already been reported [here](#829) and the PC 1.12 blocks data has been added to our sources.

The rotation bug is also fixed in the sources.

**Comment by DestructiveBurn** [comment]
Well, why don't we have an update yet?  If you know about it don't just update your sources update MC-Edit.

**Comment by LaChal** [comment]
MCEdit is updated with this stuff. It has not yet been released.

If you want to use these features, run it from sources.

**Comment by allamassal** [comment]
I have this exact same problem, see #880
