### ISSUE TITLE
1.7.10 mcedit

### ISSUE THREAD

**Issue by starwarschamp4** [Khroki/MCEdit-Unified#845]
So I just started using mcedit after several months of not using it, and I noticed that it isn't 1.7.10 anymore, it's 1.8 up. Is there a 1.7.10 minecraft version of MCedit that I can download or is it like this now?
SlaAar0513A@gmail.com

**Comment by LaChal** [comment]
After a small test, MCEdit is still able to open 1.7.10 worlds, but you may experience issues when changing stuff.

If you use MCEdit 1.2.x to 1.4.x you may find a better support for old game versions.

**Comment by starwarschamp4** [comment]
Alright, but when I try typing in my 1.7.10 worlds it only shows the newer minecraft version worlds

**Comment by LaChal** [comment]
Just don't use the 'Quick Load' feature but the 'Open' one.
You'll be able to browse your file system for the world you want to open ('level.dat' files).

**Comment by starwarschamp4** [comment]
Omg Thank you!
