### ISSUE TITLE
Loading a second world in a filter

### ISSUE THREAD

**Issue by gentlegiantJGC** [Khroki/MCEdit-Unified#847]
I am trying to load a second world within a filter so that I can write the data from the opened world to it. I have so far managed to open the world and edit it but I can't get MCedit to save the changes to the new world.

```
	if convertTo == 'PE':
		filePath = None
		filePath = mcplatform.askOpenFile(title="Select a Pocket world to write to", schematics=False)
		if filePath is not None:
			if PocketLeveldbWorld._isLevel(filePath):
				if leveldbpocket.leveldb_available:
					levelNew = PocketLeveldbWorld(filePath)
				else:
					raise Exception("Pocket support has failed")
			else:
				raise Exception("Not a Pocket world")
	
	for (chunk, _, _) in level.getChunkSlices(box):
		cx, cz = chunk.chunkPosition
		generateChunk(levelNew, True, cx, cz, 15)
		chunkNew = levelNew.getChunk(cx, cz)
		chunkNew.Blocks[:] = copy.deepcopy(chunk.Blocks)
		chunkNew.Data[:] = copy.deepcopy(chunk.Data)
		chunkNew.TileEntities = copy.deepcopy(chunk.TileEntities)
		chunkNew.Entities = copy.deepcopy(chunk.Entities)
		chunkNew.dirty = True
	levelNew.saveInPlaceGen()
	levelNew.close()
```

And if you can the same but for writing to a PC world. This one may be easy but I haven't tested it yet.
I am probably just calling the wrong function to save it to the database

**Comment by LaChal** [comment]
It is possible to import a whole world like a schematic using the `Import` tool.
Just select this tool, and insteadt of the `.nbt` or `.schematic` file fileter, select the all files one in the file selection dialog.

Moreover, it is not possible to create chunks for PE worlds. We did not implemented this, because Mojang did not share anything about...

**Comment by gentlegiantJGC** [comment]
I am using the code I wrote in the create chunk filter to generate the chunk so that isn't the issue. I should have mentioned `generateChunk(levelNew, True, cx, cz, 15)` is a function I wrote

I have managed to get everything working by importing the data from another world into the loaded world and saving but I want to do it the other way around.

I can't really use the import tool because I am tying to convert a PC world to Bedrock and vice versa

**Comment by naor2013** [comment]
Seems like the correct use for saveInPlaceGen is:
for _ in levelNew.saveInPlaceGen():
    pass

Try that. I'm closing the issue for now but let me know if it worked for you or not
