### ISSUE TITLE
Pocket getAllChunks

### ISSUE THREAD

**Issue by gentlegiantJGC** [Khroki/MCEdit-Unified#851]
getAllChunks in leveldbpocket.py returns the same chunk multiple times. The function checks if the byte after the chunk location is equal to 47 which is the terrain key however there can be multiple terrain keys. Unless there is a reason why this function needs to return the chunk coords multiple times it should be checking for the version key which is 118

**Comment by Podshot** [comment]
We're looking into this now since we now support the new LevelDB format

**Comment by naor2013** [comment]
Well, I'm not sure why we use specifically use 47 either but I fixed the duplicate issue another way. I'll ask the one who wrote the code why he wrote it like that and we'll see if there's a need to change that.
Thanks for the help and the suggestion, hope you love our changes for this next release so far (Even if there are a few bugs :P)
