### ISSUE TITLE
Can't open PE 1.2 worlds after opening world and saving it.

### ISSUE THREAD

**Issue by bman921** [Khroki/MCEdit-Unified#852]
Steps to reproduce: Create a Pocket 1.2 world, add something in MCEdit, save, then open in MCEdit again. I am using the latest MCEdit from source. The strange thing is, when I loaded a superflat built something random, it loaded just fine, but when I built on it, it gave me that error.

> [   ERROR][                   root.py:689]:Failed to load file C:\Users\Admin\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\qI0BABhlAAA=\level.dat: TypeError("object of type 'NoneType' has no len()",)
[   ERROR][                  root.py:1199]:Wasn't able to open a file {file => C:\Users\Admin\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\qI0BABhlAAA=}
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\MCEdit-Unified\leveleditor.py", line 1196, in loadFile
    level = pymclevel.fromFile(filename)
  File "C:\Users\Admin\Desktop\MCEdit-Unified\pymclevel\mclevel.py", line 226, in fromFile
    return PocketLeveldbWorld(filename)
  File "C:\Users\Admin\Desktop\MCEdit-Unified\pymclevel\leveldbpocket.py", line 776, in __init__
    self.worldFile = PocketLeveldbDatabase(filename, self, create=create, world_version=self.world_version)
  File "C:\Users\Admin\Desktop\MCEdit-Unified\pymclevel\leveldbpocket.py", line 265, in __init__
    it.SeekToFirst()
  File "C:\Users\Admin\Desktop\MCEdit-Unified\pymclevel\leveldb.py", line 304, in SeekToFirst
    self._impl.SeekToFirst()
  File "C:\Users\Admin\Desktop\MCEdit-Unified\pymclevel\leveldb.py", line 945, in SeekToFirst
    self._checkError()
  File "C:\Users\Admin\Desktop\MCEdit-Unified\pymclevel\leveldb.py", line 962, in _checkError
    _checkError(error)
  File "C:\Users\Admin\Desktop\MCEdit-Unified\pymclevel\leveldb.py", line 909, in _checkError
    raise Error(message)
Error: Corruption: corrupted compressed block contents

Edit: This also happened when I created a new world (infinite), loaded it up in MCEdit, it loaded, went back into the world, built randomly across the world, and loaded it back in MCEdit.

**Comment by LaChal** [comment]
@bman921 The issue is closed. Is it intentional? Did you find what was wrong?

**Comment by bman921** [comment]
I closed it because I wasn't sure if it's the dll I used for MCEdit. If you could test to make sure, that would be greatly appreciated! :smile:

**Comment by LaChal** [comment]
I tested on Linux and Windows using commit https://github.com/Khroki/MCEdit-Unified/commit/5f36443319f6993e546534655f112699431d2041 and could not reproduce the crash.

The DLL used on windows is the one on the repo.

The addition I made were stone blocks and standing signs.

**Comment by bman921** [comment]
@LaChal What I did was I created a infinite world, built in a line for maybe 100-200 blocks, loaded it, and gave me that error, but it could be the dll I used, I used a different one since I thought the dll wasn't updated yet.

**Comment by LaChal** [comment]
Right, the DLL in the repo is not yet updated.

The fact is PE 1.2 uses a different compression algorithm, and it is not possible to implement is in pure Python, AFAIK.

I could tweak the needed code, but I would prefer Mojang to add few lines to their own code...

Can you try to use the current DLL in the repo?

**Comment by bman921** [comment]
Ok, I tried the dll from the repo, and it still gave the error, but an updated dll by MCCToolchestPE was able to make the problem go away. I think Mojang updated their LevelDB on their Github.

**Comment by zane-myrevio** [comment]
I am also getting this error on macOS (10.13.1 High Sierra).  Not sure if it is a zlib issue or a leveldb issue, but I built leveldb from the latest code off Mojang's repo.

Let me know if there is anything I can do to help resolve this.  I really need it to work for PE 1.2 files.

**Comment by LaChal** [comment]
Mojang's repo lack of some functionalities, and latest MCEdit release (1.5.6.0) simply not implement these functionalities.
The next version will have that implemented.

Technical stuff:
Recent PE versions need several compression algorithms to be set up in the options of the DB, but Mojang did not implemented the API. Even if the code to use this API part was in MCEdit 1.5.6.0, Mojang's code would not be usable 'as is'.

**Comment by zanethorn** [comment]
Thanks @LaChal, are you suggesting that I hit up Mojang for the issue fix?  I would be happy to pester anyone I need to, or even dig into the code myself.
