### ISSUE TITLE
Memory Issues

### ISSUE THREAD

**Issue by gentlegiantJGC** [Khroki/MCEdit-Unified#853]
I am having some memory (RAM) issues with bedrock worlds when modifying a large number of chunks. It fills up between 5 and 10GB modifying 10,000 chunks which is not ideal. The data in memory then persists even after the world is saved to disk.
I want to do some debugging to find where the large variables are but I can't find anything particular large. Are there any easy ways I can find where these large variables are?

**Comment by Podshot** [comment]
It mostly depends on how we are storing the various information. I know for Anvil Worlds we use a numpy array of Chunk objects for chunks and then another numpy array for blocks in that specified Chunk object, not sure how we store if for Bedrock/LevelDB, that'd be a question for @LaChal.

**Comment by LaChal** [comment]
The Bedrock/LevelDB implementation work also like Anvil/Java worls.
Data is stored in numpy arrays (sort of data structures).

The fact is these operations are done in memory, so, bigger the area you want to change is, bigger the amount RAM is.
When you *close* MCEdit, the RAM shall be released.

Yo can use a "hidden" command line parameter to get a huge amount of information about PE support, but be warned it can create a monstrous log file: --debug-pe

**Comment by naor2013** [comment]
I see similar RAM usage between MCPE and PC versions. Is there maybe a specific operation that takes a lot of RAM for PE and less for PC? If that happens, please tell us the specific operation which causes this issue since just opening the map does not show big RAM usage, for me, at least.
