### ISSUE TITLE
Unicode In Commands

### ISSUE THREAD

**Issue by gentlegiantJGC** [Khroki/MCEdit-Unified#854]
If there is unicode in commands (eg the colour symbol), hovering over the command block causes the game to crash because it can't parse unicode. Tested with a bedrock world though would probably work with a PC world as well.
I don't know if you guys would escape the message so that the character is still represented even if it isn't the actual symbol. I added a quick fix to solve the issue here
https://github.com/gentlegiantJGC/MCEdit-Unified/commit/dd271702bfa53769097b11caca327fe164a6b00f

**Comment by LaChal** [comment]
Can be a start point.

But the definitive solution may be to use the right character encoding.
Can be tedious...

**Comment by LaChal** [comment]
Just tried on several PC game versions (1.10.2, 1.12-pre7 and 1.12.2) with the command `/say @a Héhé !`.
The game displayed the string, and MCEdit did not signaled any error on Linux.
Will be tested on Windows also.

The game itself don't want me to use the color character (§).

**Comment by gentlegiantJGC** [comment]
Here is a bedrock world with the colour code. In bedrock you can just paste the colour code into a command block. Hovering over it causes MCedit to crash
[CrashWorld.zip](https://github.com/Khroki/MCEdit-Unified/files/1353851/CrashWorld.zip)
