### ISSUE TITLE
Reloading a world from the nether keeps the red atmosphere

### ISSUE THREAD

**Issue by megaxlr** [Khroki/MCEdit-Unified#857]
MCEdit version: 1.5.6.0
Minecraft version: 1.12.2 (forge)
OS: Ubuntu 17.04 and Windows 10 (1703)

Steps to reproduce:
1. open a world with a nether dimension
2. Ctrl + R to reload
3. observe how you get sent back to the overworld, but the sky is still red.

Example image: (observe the Overworld dimension in the top bar, and the red atmosphere)
![image](https://user-images.githubusercontent.com/8215278/31808611-3ed5c7d4-b574-11e7-8b96-133aec46571b.png)

**Comment by naor2013** [comment]
Will be fixed for next release.
Thanks for reporting the issue :)

**Comment by allamassal** [comment]
I have noticed this bug too. Apparently someone forgot to put in a line of code to check if the dimension has changed when loading a world). The same thing happens with the chunk view in the same world.

**Comment by megaxlr** [comment]
@allamassal Did this happen in the latest version of MCEdit? or did it happen in an older version.

**Comment by allamassal** [comment]
Still happens in the latest version 1.5.6.0 (at least the chunk view thing).
