### ISSUE TITLE
Can't open MCEdit since upgrading Windows

### ISSUE THREAD

**Issue by allamassal** [Khroki/MCEdit-Unified#875]
Everything was working fine until today. Last night I upgraded my computer, and now this morning I can't get MCEdit to open. It always crashes with an error that looks to be about the window position:

Attempt to call an undefined function glWindowPos2d, check for bool(glWindowPos2d) before calling

Can someone please help me? I would now give anything to roll back to the Windows 10 1703 build.

**Comment by allamassal** [comment]
UPDATE: I tried using a newer version of MCEdit and it worked, but it was so laggy it was unusable.

**Comment by LaChal** [comment]
Sending us the log (in MCEdit folder) in something like pastebin and the console output can help.

Also, the issue may come from your video driver, so check if you have the latest version.
If you want to reinstall it, I recomend you to create a snapshot of your system before.

**Comment by allamassal** [comment]
I actually figured out that the issue came from my video drivers, and I just couldn't get my GeForce driver working, so I rolled back to 1703, and it started working properly again.
