### ISSUE TITLE
Error while importing schematics saved by WorldEdit.

### ISSUE THREAD

**Issue by polyzium** [Khroki/MCEdit-Unified#887]
MCedit is so laggy on my system so i saved the schematic in-game using WE using `//schem save`. But then i was disappointed
![image](https://user-images.githubusercontent.com/22579935/34463951-1b49ecbc-ee7e-11e7-8019-3d848754d84c.png)
Steps to Reproduce: should be obvious
MCEdit Version Number: v1.5.6.0
Minecraft Version Number: 1.12.2
Operating System Version: Antergos Linux with kernel 4.14.9-1-lqx
Error log: [here](https://hastebin.com/aridikumip.md)

**Comment by Podshot** [comment]
Can you give us a copy of this schematic?

**Comment by polyzium** [comment]
There you go. Also forgot to mention, i am using mods and spongeforge
[clubnew.schematic.zip](https://github.com/Khroki/MCEdit-Unified/files/1598144/clubnew.schematic.zip)

**Comment by Podshot** [comment]
I think I have fixed the issue, but before I  commit the change, can you send me a similar schematic? I need to make sure the fix works with more than one single schematic file.

**Comment by polyzium** [comment]
You mean another WE schematic?

**Comment by Podshot** [comment]
@polyzium yes

**Comment by polyzium** [comment]
Okay lemme start MC up and i'll cap one

**Comment by polyzium** [comment]
[test.schematic.zip](https://github.com/Khroki/MCEdit-Unified/files/1601378/test.schematic.zip)
@Podshot

**Comment by Podshot** [comment]
Thanks!
