### ISSUE TITLE
page not loading

### ISSUE THREAD

**Issue by GlennTheAlien** [Khroki/MCEdit-Unified#890]
can't load the page

**Comment by Podshot** [comment]
Can you give some more information? Which page? What browser and OS are you using? What have you already tried to try and fix this issue

**Comment by robske110** [comment]
http://khroki.github.io/MCEdit-Unified/
this page was not loading a few days ago for me. now it seems to be loading fine.

**Comment by Podshot** [comment]
Ok, if the issue occurs again, let us know

**Comment by Ghost0312** [comment]
I have exactly the same problem but I use mac and safari
