### ISSUE TITLE
Not an NBT file with a root TAG_Compound (The world is not showing in Minecraft=

### ISSUE THREAD

**Issue by lovrosverko** [Khroki/MCEdit-Unified#891]
Hi there,
my world has disappeared from saved world list. I was trying to open it in MCEdit 2.0.0.0 but I got an error:

```
An error occurred while opening C:\Users\Lovro\AppData\Roaming\.minecraft\saves\kuće
Not an NBT file with a root TAG_Compound (file starts with " ‹" (0x00088b1f)

Traceback (most recent call last):
  File "mcedit2\widgets\layout.py", line 65, in setWidgetError  
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 62: ordinal not in range(128)
```
[here is the link to level.dat](https://drive.google.com/file/d/1eAQLf5x3psNNTtYll4uWkipLuelnxX9D/view?usp=sharing)

someone please help me to restore my world.

**Comment by Podshot** [comment]
This is an issue with MCEdit2, please submit your bug report [here](https://github.com/mcedit/mcedit2/issues)

**Comment by lovrosverko** [comment]
Is it? I think that it's Minecraft problem... But ok.
