### ISSUE TITLE
Find & Replace will not work. "No JSON object could be decoded" error?

### ISSUE THREAD

**Issue by Mirco1502** [Khroki/MCEdit-Unified#892]
Hey there.

Playing on a "designed" (no random) Minecraft map, created in an editor tool.

For some reason, the creator decided to put thousands of little Lava and Water sources underground, which is hell annoying while digging a mine.

So I downloaded McEdit to find and replace alle Water/Lava in a certain Area with stone.

- I mark the the Area with the select tool
- I choose all 24 Water and Lava Blocks? (Dunno why there are so many...)
- I choose "Stone" as replace Block
- I hit "replace"

but nothing happens.

I did save the world and load it in Minecraft, but ye, nothing changed.

The Windows of McEdit running in the Background is showing the Message "No JSON Object can be decoded" .. I thought maybe this is because not running MCEdit as Admin, but this also did not help.

What am I'm doing wrong?

**Comment by Podshot** [comment]
Can you please post a screenshot of the console window?

**Comment by Mirco1502** [comment]
![screenminecraft](https://user-images.githubusercontent.com/35544343/35198184-6b0d03ba-feeb-11e7-95ee-be6a9442436e.png)

Sure

**Comment by Mirco1502** [comment]
Hope thats fine, It's not end of the command windows, but it's just the same error message repeating and repeating again, So i thought: Scroll up a bit so they can see the other stuff, too.

**Comment by Podshot** [comment]
This is a issue with MCEdit2, please post your report [here](https://github.com/mcedit/mcedit2/issues)
