### ISSUE TITLE
is it possible to edit Minecraft PE maps in MCedit

### ISSUE THREAD

**Issue by dimmthewitted** [Khroki/MCEdit-Unified#898]
From what I understand Minecraft Pocket Edition with the better together update or Bedrock update is the same as Windows 10 (universal app) Minecraft.

All of these versions work together.  We can add MCWorlds and MCTemplates.

I can only get MCEdit to work on my Windows (PC) version.
I have not been able to find a way to convert my worlds from Minecraft PC.

There must be a way to convert a PC world into a MCPE world.

Do I need to use MCEdit 2.0 beta or use some 3rd tool?

Does anyone have any good looks where I can read more?

**Comment by TrazLander** [comment]
It is being worked on. Come help test it! https://github.com/Podshot/MCEdit-Unified-Preview/releases

MCC ToolChest is a good tool used for converting in the meantime. It doesnt work well and it breaks tile entities I hear. It's all a work in progress http://mcctoolchest.com/Download

**Comment by TrazLander** [comment]
Also check out the discord for more info https://discordapp.com/invite/BTm6jnf

**Comment by michael-ts** [comment]
@TrazLander From that link I see that the latest is 1.6.0.53, but there is no source code at that link and it appears to be exclusively for Windows (no Linux).  At this URL https://github.com/Podshot/MCEdit-Unified/releases/tag/1.6.0.0 I only see source for 1.6.0.0, and I'm still trying to figure out what to do with it, as I used the MCEdit.v1.5.6.0.Lin.Universal.run installer.  So now I have two questions:

1. Where can I get the 1.6.0.53 source?
2. What do I do with it given that I already have a 1.5.6.0 compile from the installer working?

Update: Ok, so apparently there is nothing to do, I just need to run ./mcedit.sh from the download directory.  1.6.0.0 still won't recognize my world file though: 
`I don't know how to open /home/michael/.minecraft/minecraftWorlds/Test/level.dat:
AttributeError("NoneType" object has no attribute 'Options'".`  So... maybe I still need 1.6.0.53?
